/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/os/gettime.c @ e24c8367
 * Flags:       -g0 -O1 -mips2 -G 0 -non_shared
 * Scores:      true=45  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
OSTime osGetTime(void) {
    u32 tmptime;
    u32 elapseCount;
    OSTime currentCount;
    register u32 saveMask;

#ifdef _DEBUG
    if (!__osViDevMgr.active) {
        __osError(ERR_OSGETTIME, 0);
        return 0;
    }
#endif

    saveMask = __osDisableInt();
    tmptime = osGetCount();
    elapseCount = tmptime - __osBaseCounter;
    currentCount = __osCurrentTime;
    __osRestoreInt(saveMask);
    return currentCount + elapseCount;
}
