/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/gu/ortho.c @ e24c8367
 * Flags:       -g0 -O2 -mips2 -G 0 -non_shared
 * Scores:      true=10  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
void guOrtho(Mtx *m, float l, float r, float b, float t, float n, float f, float scale)
{
	Matrix	mf;

	guOrthoF(mf, l, r, b, t, n, f, scale);

	guMtxF2L(mf, m);
}
