#include "checkpoint.h"
#include "cksum.h"
#include "controls.h"
#include "drivsym.h"
#include "drones.h"
#include "eptyp.h"
#include "fpdef.h"
#include "game.h"
#include "gammatable.h"
#include "io.h"
#include "maxpath.h"
#include "modelcom.h"
#include "modeldat.h"
#include "opcodes.h"
#include "road.h"
#include "slink.h"
#include "smodeldat.h"
#include "sounds.82.h"
#include "sounds.90.h"
#include "sounds.h"
#include "ssounds.h"
#include "stree.h"
#include "typedefs.h"
#include "vecmath.h"
#include "visuals.h"
CAR_DATA x_CAR_DATA;
COLLSIZE x_COLLSIZE;
Car x_Car;
CheckPoint x_CheckPoint;
CmdFunc x_CmdFunc;
EPTYPE x_EPTYPE;
GState x_GState;
InitCheckPoint x_InitCheckPoint;
Init_Track_Data x_Init_Track_Data;
MAT3 x_MAT3;
MAT4 x_MAT4;
MATRIX x_MATRIX;
MATV x_MATV;
MODELDAT x_MODELDAT;
MPATH x_MPATH;
MPCTL x_MPCTL;
MPHEADER x_MPHEADER;
MPWEIGHT x_MPWEIGHT;
NewSkid x_NewSkid;
PATHTYP x_PATHTYP;
POT_TYPES x_POT_TYPES;
RECKON x_RECKON;
S32XYZ x_S32XYZ;
STHEADERTYP x_STHEADERTYP;
STREETYP x_STREETYP;
SURFTYP x_SURFTYP;
SVERTTYP x_SVERTTYP;
Skid x_Skid;
Track x_Track;
Track_Data x_Track_Data;
Visual x_Visual;
fastintyp x_fastintyp;
initintyp x_initintyp;
mainintyp x_mainintyp;
resurrecttyp x_resurrecttyp;
tiredes x_tiredes;
uvect x_uvect;
