/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/io/dpsetnextbuf.c @ e24c8367
 * Flags:       -g0 -O2 -mips2 -G 0 -non_shared
 * Scores:      true=5  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
s32 osDpSetNextBuffer(void* bufPtr, u64 size) {
    register u32 stat;

#ifdef _DEBUG
    if ((u32)bufPtr & 0x7) {
        __osError(ERR_OSDPSETNEXTBUFFER_ADDR, 1, bufPtr);
        return -1;
    }
    if (size & 0x7) {
        __osError(ERR_OSDPSETNEXTBUFFER_SIZE, 1, size);
        return -1;
    }
#endif

    if (__osDpDeviceBusy()) {
        return -1;
    }

    IO_WRITE(DPC_STATUS_REG, DPC_CLR_XBUS_DMEM_DMA);

    while (TRUE) {
        stat = IO_READ(DPC_STATUS_REG);
        if ((stat & DPC_STATUS_XBUS_DMEM_DMA) == 0) {
            break;
        }
    }

    IO_WRITE(DPC_START_REG, osVirtualToPhysical(bufPtr));
    IO_WRITE(DPC_END_REG, osVirtualToPhysical(bufPtr) + size);
    return 0;
}
