"""Receipts omit integration provenance and preserve every real proof field."""
import ast
import copy
import hashlib
import json
from pathlib import Path
import pytest

ROOT = Path(__file__).resolve().parents[2]

PACKETS = [{'generator': 'cloud/work/boot_tail/BT03-sequence-constructor/verify.py',
  'receipt': 'cloud/work/boot_tail/BT03-sequence-constructor/evidence.json',
  'normalizer': 'portable',
  'removed': [{'path': ['manifest_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/boot_tail/BT03-voice-free-donor/verify.py',
  'receipt': 'cloud/work/boot_tail/BT03-voice-free-donor/evidence.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['input_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/cloud/owndata.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/conveyor/seeds/extract_candidates.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/boot_tail_8000f3a4.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/extents.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/conveyor/pipeline/lock.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'matched.lock.json'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001F6EC.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001EE9C.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001F9D0.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_22300/func_80021BC0.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001F954.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_22300/func_80023E9C.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/work/boot_tail/BT03-high-larger/nonmatch/func_8001F6EC.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/work/boot_tail_promotion/sources/func_8001EE9C.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'src/rom/lib_1f5b0.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/work/boot_tail_promotion/voice_lists/sources/func_8001F9D0.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/matches/boot_tail/func_80021BC0.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'src/rom/lib_22300.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 0, 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 1, 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 2, 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 0, 'current_normalized_lock_body_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 1, 'current_normalized_lock_body_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_context', 2, 'current_normalized_lock_body_sha256'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/boot_tail/BT03-voice-unblock-topology/verify.py',
  'receipt': 'cloud/work/boot_tail/BT03-voice-unblock-topology/evidence.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['input_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/cloud/owndata.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/conveyor/seeds/extract_candidates.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'include/boot_tail_audio_record.h'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'include/boot_tail_sample_contract.h'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/boot_tail_8000f3a4.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/extents.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/boot_tail/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/conveyor/pipeline/lock.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'matched.lock.json'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001F954.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_11640/func_80014AF0.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1cf90/func_8001C7F4.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_11640/func_8001467C.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/nonmatchings/rom/lib_1f5b0/func_8001F6EC.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256',
                        'cloud/work/boot_tail_promotion/audio_record_contracts/sources/func_80014AF0.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'src/rom/lib_11640.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/work/boot_tail_promotion/sources/func_8001C7F4.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'src/rom/lib_1cf90.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'cloud/work/boot_tail/BT03-high-init/nonmatch/func_8001F954.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['rows', 1, 'source_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['rows', 2, 'source_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/dot_selector_d9058_20261006/verify.py',
  'receipt': 'cloud/work/dot_selector_d9058_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['protected_target_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['context_origin_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_animation_setter_contract_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_animation_setter_contract_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['target_manifest_provenance'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_cone_start_donor_20261005/verify.py',
  'receipt': 'cloud/work/frontier/dot_cone_start_donor_20261005/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['compiler', 'context_source_sha256'],
               'legacy_shape': {'src/blob/func_80090284.c': 'historical provenance drift',
                                'src/blob/vector_normalize_length.c': 'historical provenance drift',
                                'src/blob/math_utility.c': 'historical provenance drift'}},
              {'path': ['buffer_contract', 'accepted_writer_source_sha256'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_constructor_prepend_20261005/verify.py',
  'receipt': 'cloud/work/frontier/dot_constructor_prepend_20261005/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['protected_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['context_source_sha256'],
               'legacy_shape': {'src/blob/func_800D18D8.c': 'historical provenance drift',
                                'src/blob/func_80091FBC.c': 'historical provenance drift',
                                'src/blob/func_8009211C.c': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/frontier/dot_frame_dispatch_20261005/verify.py',
  'receipt': 'cloud/work/frontier/dot_frame_dispatch_20261005/verification.json',
  'normalizer': 'comparable_receipt',
  'removed': [{'path': ['historical_native_provenance'],
               'legacy_shape': {'asm/us/blob/SHA256SUMS': 'historical provenance drift',
                                'asm/us/blob/symbols.json': 'historical provenance drift',
                                'symbol_addrs.us.txt': 'historical provenance drift'}},
              {'path': ['source_bindings', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_bindings', 'src/blob/Effects_UpdateEmitters.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_bindings', 'cloud/work/game_C31/func_800B7FF8.bits.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_bindings', 'asm/us/nonmatchings/rom/lib_1050/viTickStart.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_bindings', 'asm/us/nonmatchings/rom/lib_1050/viUpdateTime.s'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_material_selector_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_material_selector_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['target_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['tools_sha256'],
               'legacy_shape': {'tools/cloud/score.py': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/conveyor/pipeline/blob_group.py': 'historical provenance drift'}},
              {'path': ['accepted_consumer_source_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_availability_boundary_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_availability_boundary_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_callback_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_callback_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_flags_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_flags_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['input_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'tools/cloud/owndata.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/ovl_a/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/ovl_a/extents.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/ovl_a/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_sha256', 'asm/us/ovl_a/ovl_a_8038a400.s'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_formatted_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_formatted_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['helper_protected_targets'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['owndata_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_menu_loop_20261006/independent/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_menu_loop_20261006/independent/review.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['manifest'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['helper_protected_manifest'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_menu_loop_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_menu_loop_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['helper_protected_targets'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['owndata_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_resource_cache_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_resource_cache_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['game_manifest'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['protected_manifest'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['matched_siblings', 'func_8039156C', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['matched_siblings', 'func_80390D2C', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helper_contracts', 'audio_frame_sync', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helper_contracts', 'func_800BB02C', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_runtime_a_stat_bar_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_runtime_a_stat_bar_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['helper_protected_targets'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_sequence_start_979a0_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_sequence_start_979a0_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['own_data_tool_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['native_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['accepted_group_spec_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_slot_contract_audit_20261006/audit.py',
  'receipt': 'cloud/work/frontier/dot_slot_contract_audit_20261006/evidence.json',
  'normalizer': 'portable',
  'removed': [{'path': ['source_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'cloud/work/s20261004/D/notes.md'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'cloud/work/s20261004/E/notes.md'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'cloud/work/s20261004/E/src/helper.h'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'cloud/work/game_C104/REPORT.md'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'cloud/work/dot_menu_options_root_20261005/slot_state_setup.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'src/blob/groups/credits_scroll_grp/group.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'src/blob/groups/credits_scroll_grp/gr3_c.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['source_sha256', 'src/blob/groups/slot_sound/group.c'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/frontier/dot_slot_setter_boundary_20261006/verify.py',
  'receipt': 'cloud/work/frontier/dot_slot_setter_boundary_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['input_hashes', 'src/blob/func_8008E06C.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_hashes', 'src/blob/func_80092BC8.c'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['input_hashes', 'src/blob/sfx_stop.c'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/ipa-groups/dot_masked_random_b23e0_20261006/verify.py',
  'receipt': 'cloud/work/ipa-groups/dot_masked_random_b23e0_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['target_manifest_historical_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['data_manifest_historical_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['tools_sha256'],
               'legacy_shape': {'tools/cloud/score.py': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/conveyor/pipeline/blob_group.py': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/ipa-groups/dot_nearest_path_context_20261005/verify.py',
  'receipt': 'cloud/work/ipa-groups/dot_nearest_path_context_20261005/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['protected_inputs_sha256'],
               'legacy_shape': {'asm/us/blob/SHA256SUMS': 'historical provenance drift',
                                'asm/us/blob/symbols.json': 'historical provenance drift',
                                'asm/us/blob_data/SHA256SUMS': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/cloud/score.py': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/ipa-groups/dot_random_range_b2e4_20261005/verify.py',
  'receipt': 'cloud/work/ipa-groups/dot_random_range_b2e4_20261005/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['target_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['tools_sha256'],
               'legacy_shape': {'tools/cloud/score.py': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/conveyor/pipeline/blob_group.py': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/ipa-groups/dot_speed_flags_c9210_20261006/verify.py',
  'receipt': 'cloud/work/ipa-groups/dot_speed_flags_c9210_20261006/verification.json',
  'normalizer': 'portable',
  'removed': [{'path': ['accepted_source_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_a_float_product/verify.py',
  'receipt': 'cloud/work/runtime_a_float_product/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['protected_manifest_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_a_settings_bar_20261006/verify.py',
  'receipt': 'cloud/work/runtime_a_settings_bar_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['protected_targets'],
               'legacy_shape': {'extents.json': 'historical provenance drift',
                                'ovl_a_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['helper_protected_targets'],
               'legacy_shape': {'blob_80086a50.s': 'historical provenance drift',
                                'blob_8008d0c0.s': 'historical provenance drift',
                                'blob_800947f0.s': 'historical provenance drift',
                                'blob_800966d8.s': 'historical provenance drift',
                                'blob_8009dd18.s': 'historical provenance drift',
                                'blob_800a4508.s': 'historical provenance drift',
                                'blob_800a7df0.s': 'historical provenance drift',
                                'blob_800aeb54.s': 'historical provenance drift',
                                'blob_800b3b4c.s': 'historical provenance drift',
                                'blob_800b7360.s': 'historical provenance drift',
                                'blob_800bdd90.s': 'historical provenance drift',
                                'blob_800c46d0.s': 'historical provenance drift',
                                'blob_800cbe08.s': 'historical provenance drift',
                                'blob_800d1004.s': 'historical provenance drift',
                                'blob_800d6690.s': 'historical provenance drift',
                                'blob_800de454.s': 'historical provenance drift',
                                'blob_800e7030.s': 'historical provenance drift',
                                'blob_800ef5b0.s': 'historical provenance drift',
                                'blob_800f8d9c.s': 'historical provenance drift',
                                'blob_80100d24.s': 'historical provenance drift',
                                'blob_8010e0fc.s': 'historical provenance drift',
                                'blob_8010fd7c.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift'}},
              {'path': ['scorer_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_e114_parent_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_e114_parent_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['target_manifest_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['tools'],
               'legacy_shape': {'score.py': 'historical provenance drift',
                                'owndata.py': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/runtime_b_event_ring_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_event_ring_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['inputs_sha256'],
               'legacy_shape': {'tools/cloud/score.py': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'asm/us/ovl_b/SHA256SUMS': 'historical provenance drift',
                                'asm/us/ovl_b/ovl_b_8038a400.s': 'historical provenance drift',
                                'asm/us/ovl_b/symbols.json': 'historical provenance drift',
                                'asm/us/ovl_b/extents.json': 'historical provenance drift',
                                'asm/us/blob/SHA256SUMS': 'historical provenance drift'}},
              {'path': ['helpers', 'func_800F7E30', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helpers', 'effect_cleanup', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_initializer_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_initializer_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['inputs_sha256'],
               'legacy_shape': {'asm/us/blob/SHA256SUMS': 'historical provenance drift',
                                'asm/us/ovl_b/SHA256SUMS': 'historical provenance drift',
                                'asm/us/ovl_b/extents.json': 'historical provenance drift',
                                'asm/us/ovl_b/ovl_b_8038a400.s': 'historical provenance drift',
                                'asm/us/ovl_b/symbols.json': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/cloud/score.py': 'historical provenance drift'}},
              {'path': ['helpers', 'func_800B24EC', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helpers', 'func_8038D1A8', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helpers', 'pool_linked_list_init', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helpers', 'string_copy_format', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['helpers', 'struct_fields_init', 'source_sha256'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_lives_text_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_lives_text_20261006/verification.json',
  'normalizer': 'comparable',
  'removed': [{'path': ['input_sha256'],
               'legacy_shape': {'tools/cloud/score.py': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift'}},
              {'path': ['target_sha256'],
               'legacy_shape': {'SHA256SUMS': 'historical provenance drift',
                                'ovl_b_8038a400.s': 'historical provenance drift',
                                'symbols.json': 'historical provenance drift',
                                'extents.json': 'historical provenance drift'}}]},
 {'generator': 'cloud/work/runtime_b_object_phases_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_object_phases_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['inputs_sha256'],
               'legacy_shape': {'asm/us/ovl_b/SHA256SUMS': 'historical provenance drift',
                                'asm/us/ovl_b/extents.json': 'historical provenance drift',
                                'asm/us/ovl_b/ovl_b_8038a400.s': 'historical provenance drift',
                                'asm/us/ovl_b/symbols.json': 'historical provenance drift',
                                'tools/cloud/score.py': 'historical provenance drift'}},
              {'path': ['contexts', 'allocator_sha256'], 'legacy_shape': 'historical provenance drift'},
              {'path': ['contexts', 'list_witness_sha256'], 'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_reset_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_reset_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['inputs_sha256', 'asm/us/blob/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/extents.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/ovl_b_8038a400.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'tools/cloud/owndata.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_teardown_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_teardown_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['inputs_sha256', 'asm/us/blob/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/blob/blob_8008d0c0.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/blob/blob_800aeb54.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/blob/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/SHA256SUMS'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/extents.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/ovl_b_8038a400.s'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'asm/us/ovl_b/symbols.json'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'tools/cloud/owndata.py'],
               'legacy_shape': 'historical provenance drift'},
              {'path': ['inputs_sha256', 'tools/cloud/score.py'],
               'legacy_shape': 'historical provenance drift'}]},
 {'generator': 'cloud/work/runtime_b_texture_ring_20261006/verify.py',
  'receipt': 'cloud/work/runtime_b_texture_ring_20261006/verification.json',
  'normalizer': 'portable_receipt',
  'removed': [{'path': ['inputs_sha256'],
               'legacy_shape': {'asm/us/ovl_b/SHA256SUMS': 'historical provenance drift',
                                'asm/us/ovl_b/extents.json': 'historical provenance drift',
                                'asm/us/ovl_b/ovl_b_8038a400.s': 'historical provenance drift',
                                'asm/us/ovl_b/symbols.json': 'historical provenance drift',
                                'tools/cloud/owndata.py': 'historical provenance drift',
                                'tools/cloud/score.py': 'historical provenance drift'}},
              {'path': ['accepted_helper', 'sha256'], 'legacy_shape': 'historical provenance drift'}]}]


def pure_normalizer(row):
    source = ROOT / row['generator']
    tree = ast.parse(source.read_text())
    definitions = [n for n in tree.body if isinstance(n, ast.FunctionDef)
                   and n.name in (row['normalizer'], 'require')]
    assignments = {target.id: n.value for n in tree.body if isinstance(n, ast.Assign)
                   for target in n.targets if isinstance(target, ast.Name)}
    namespace = {'json': json, 'copy': copy}
    safe = (ast.Constant, ast.Name, ast.List, ast.Tuple, ast.Set, ast.Dict,
            ast.BinOp, ast.Add, ast.Load)
    def bind(name):
        if name in namespace or name not in assignments:
            return
        value = assignments[name]
        assert all(isinstance(n, safe) for n in ast.walk(value)), name
        for node in ast.walk(value):
            if isinstance(node, ast.Name):
                bind(node.id)
        namespace[name] = eval(compile(ast.Expression(value), str(source), 'eval'), namespace)
    for function in definitions:
        for node in ast.walk(function):
            if isinstance(node, ast.Name) and node.id.isupper():
                bind(node.id)
    exec(compile(ast.Module(body=definitions, type_ignores=[]), str(source), 'exec'), namespace)
    return namespace[row['normalizer']]


def contains(value, path):
    try:
        for key in path:
            value = value[key]
        return True
    except (KeyError, IndexError):
        return False


def insert(value, path, replacement):
    result = copy.deepcopy(value)
    node = result
    for key in path[:-1]:
        if isinstance(node, dict):
            node = node.setdefault(key, {})
        else:
            node = node[key]
    node[path[-1]] = replacement
    return result


def leaves(value, path=()):
    if isinstance(value, dict) and value:
        for key, child in value.items():
            yield from leaves(child, path + (key,))
    elif isinstance(value, list) and value:
        for index, child in enumerate(value):
            yield from leaves(child, path + (index,))
    else:
        yield path


@pytest.mark.parametrize('row', PACKETS, ids=lambda r: r['generator'])
def test_receipt_omits_integration_provenance(row):
    receipt = json.loads((ROOT / row['receipt']).read_text())
    for item in row['removed']:
        assert not contains(receipt, item['path']), (row['receipt'], item['path'])


@pytest.mark.parametrize('row', PACKETS, ids=lambda r: r['generator'])
def test_legacy_provenance_is_not_proof(row):
    receipt = json.loads((ROOT / row['receipt']).read_text())
    normalize = pure_normalizer(row)
    expected = normalize(receipt)
    unchanged = copy.deepcopy(receipt)
    for item in row['removed']:
        changed = insert(receipt, item['path'], item['legacy_shape'])
        assert normalize(changed) == expected, item['path']
    assert receipt == unchanged


@pytest.mark.parametrize('row', PACKETS, ids=lambda r: r['generator'])
def test_every_retained_proof_field_rejects_mutation(row):
    receipt = json.loads((ROOT / row['receipt']).read_text())
    normalize = pure_normalizer(row)
    expected = normalize(receipt)
    for path in leaves(expected):
        changed = insert(receipt, path, 'deliberate proof drift')
        try:
            actual = normalize(changed)
        except (AssertionError, KeyError, ValueError, TypeError, AttributeError):
            continue
        assert actual != expected, path
    changed = copy.deepcopy(receipt)
    changed['unknown_proof_field'] = 'must stay bound'
    assert normalize(changed) != expected
