/* Actual C89 source with bounded explicit helper contracts.
 * Binary fixtures are synthetic and generated by test_host.py. */
#include <stdio.h>
#include <string.h>
#include <assert.h>
#if WHICH == 0
#include "nonmatch/func_80019F48.c"
Voice D_8004BEB8[256];
static Layer layers[5];
static u16 *countPointer;
#else
#include "nonmatch/func_8001A270.c"
static Keymap keys[256];
#endif
static u32 trace[256][12];
static u32 events,cursorPort,cursorCreate,cursorRoot;
static u32 portResult[16],createResult[16],rootResult[16];
static u32 portCount,createCount,rootCount,missing,layerCount,countAfter;
static u8 rawLayers[60],rawKeys[2048];
static void emit(u32 address,u32 n,const u32 *args)
{
    u32 i;
    assert(events<256);trace[events][0]=address;
    for(i=0;i<n;i++)trace[events][i+1]=args[i];
    events++;
}
static u32 load(const u8 *p,u32 n)
{
    u32 v,i;
    v=0;for(i=0;i<n;i++)v=(v<<8)|p[i];return v;
}
static int input(u32 *v)
{
    u8 b[4];
    if(fread(b,1,4,stdin)!=4)return 0;
    *v=load(b,4);return 1;
}
static void output(u32 v)
{
    u8 b[4];b[0]=(u8)(v>>24);b[1]=(u8)(v>>16);b[2]=(u8)(v>>8);b[3]=(u8)v;assert(fwrite(b,1,4,stdout)==4);
}
#if WHICH == 0
Layer *func_80016F80(u16 a,u16 *b)
{
    u32 args[2];args[0]=a;args[1]=0;emit(0x80016F80U,2,args);countPointer=b;
    if(missing)return 0;
    *b=(u16)layerCount;return layers;
}
u32 func_8001ECE0(Voice *a)
{
    u32 arg,r;
    arg=0x8004BEB8U+(u32)(a-D_8004BEB8)*416;emit(0x8001ECE0U,1,&arg);
    r=cursorRoot<rootCount?rootResult[cursorRoot]:0x76543210U;cursorRoot++;return r;
}
#else
Keymap *func_80016EE0(u16 a)
{
    u32 arg;arg=a;emit(0x80016EE0U,1,&arg);return missing?0:keys;
}
u32 func_80019F48(u32 a,u16 b,u8 c,u8 d,u8 e,u8 f,u8 g,u16 h,u16 i,u8 j)
{
    u32 args[10];args[0]=a;args[1]=b;args[2]=c;args[3]=d;args[4]=e;args[5]=f;args[6]=g;args[7]=h;args[8]=i;args[9]=j;
    emit(0x80019F48U,10,args);return 0x76543210U;
}
#endif
u32 func_80019ED0(u8 a,u8 b,u8 c)
{
    u32 args[3],r;
    args[0]=a;args[1]=b;args[2]=c;emit(0x80019ED0U,3,args);
#if WHICH == 0
    if(countAfter!=0xFFFFFFFFU)*countPointer=(u16)countAfter;
#endif
    r=cursorPort<portCount?portResult[cursorPort]:0xFFFFFFFFU;cursorPort++;return r;
}
u32 func_80024988(u32 a,u16 b,u8 c,u8 d,u8 e,u8 f,u8 g,u16 h,u16 i,u8 j,u8 k)
{
    u32 args[11],r;
    args[0]=a;args[1]=b;args[2]=c;args[3]=d;args[4]=e;args[5]=f;args[6]=g;args[7]=h;args[8]=i;args[9]=j;args[10]=k;emit(0x80024988U,11,args);
    r=cursorCreate<createCount?createResult[cursorCreate]:(0x12340000U|(cursorCreate+3));cursorCreate++;return r;
}
int main(void)
{
    u32 args[10],r,i,j;
    while(input(&missing)) {
        assert(input(&layerCount)&&input(&countAfter)&&input(&portCount)&&input(&createCount)&&input(&rootCount));
        for(i=0;i<10;i++)assert(input(args+i));
        for(i=0;i<16;i++)assert(input(portResult+i));
        for(i=0;i<16;i++)assert(input(createResult+i));
        for(i=0;i<16;i++)assert(input(rootResult+i));
        assert(fread(rawLayers,1,60,stdin)==60&&fread(rawKeys,1,2048,stdin)==2048);
        events=cursorPort=cursorCreate=cursorRoot=0;memset(trace,0,sizeof(trace));
#if WHICH == 0
        memset(D_8004BEB8,0x5A,sizeof(D_8004BEB8));
        for(i=0;i<5;i++) {
            layers[i].id=(u16)load(rawLayers+12*i,2);layers[i].low=rawLayers[12*i+2];layers[i].high=rawLayers[12*i+3];
            layers[i].transpose=(s8)rawLayers[12*i+4];layers[i].volume=rawLayers[12*i+5];layers[i].priority=(s16)load(rawLayers+12*i+6,2);layers[i].panning=rawLayers[12*i+8];
        }
        r=func_80019F48(args[0],(u16)args[1],(u8)args[2],(u8)args[3],(u8)args[4],(u8)args[5],(u8)args[6],(u16)args[7],(u16)args[8],(u8)args[9]);
        countPointer=0;
#else
        for(i=0;i<256;i++) {
            keys[i].id=(u16)load(rawKeys+8*i,2);keys[i].transpose=(s8)rawKeys[8*i+2];keys[i].panning=rawKeys[8*i+3];keys[i].priority=(s16)load(rawKeys+8*i+4,2);
        }
        r=func_8001A270(args[0],(u8)args[1],(u8)args[2],(u8)args[3],(u8)args[4],(u8)args[5],(u16)args[6],(u16)args[7],(u8)args[8],(s16)args[9]);
#endif
        output(r);output(events);for(i=0;i<events;i++)for(j=0;j<12;j++)output(trace[i][j]);
#if WHICH == 0
        for(i=0;i<256;i++){output(D_8004BEB8[i].child);output(D_8004BEB8[i].parent);}
#endif
    }
    return 0;
}
