/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/os/recvmesg.c @ e24c8367
 * Flags:       -g0 -O1 -mips2 -G 0 -non_shared
 * Scores:      true=40  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
s32 osRecvMesg(OSMesgQueue* mq, OSMesg* msg, s32 flags) {
    register u32 saveMask;

#ifdef _DEBUG
    if ((flags != OS_MESG_NOBLOCK) && (flags != OS_MESG_BLOCK)) {
        __osError(ERR_OSRECVMESG, 1, flags);
        return -1;
    }
#endif

    saveMask = __osDisableInt();

    while (MQ_IS_EMPTY(mq)) {
        if (flags == OS_MESG_NOBLOCK) {
            __osRestoreInt(saveMask);
            return -1;
        } else {
            __osRunningThread->state = OS_STATE_WAITING;
            __osEnqueueAndYield(&mq->mtqueue);
        }
    }

    if (msg != NULL) {
        *msg = mq->msg[mq->first];
    }

    mq->first = (mq->first + 1) % mq->msgCount;
    mq->validCount--;

    if (mq->fullqueue->next != NULL) {
        osStartThread(__osPopThread(&mq->fullqueue));
    }

    __osRestoreInt(saveMask);
    return 0;
}
