/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/gu/lookat.c @ e24c8367
 * Flags:       -g0 -O2 -mips2 -G 0 -non_shared
 * Scores:      true=10  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
void guLookAt (Mtx *m, float xEye, float yEye, float zEye,
	       float xAt,  float yAt,  float zAt,
	       float xUp,  float yUp,  float zUp)
{
	Matrix	mf;

	guLookAtF(mf, xEye, yEye, zEye, xAt, yAt, zAt, xUp, yUp, zUp);

	guMtxF2L(mf, m);
}
