# Generated by pipeline.layout (write_opt_overrides) — DO NOT EDIT.
# Converted ROM TUs use their verified optimization and debug levels;
# different code generation fails the promotion SHA-1 gate.
ifeq ($(COMPILER),ido)
$(BUILD_DIR)/src/rom/lib_1050_sdk.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_21f0.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_2cf0.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_3140.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_3330.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_3390.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_34a0.o: CFLAGS := $(filter-out -g -g0 -g1 -g2 -g3,$(subst -O2,-O1,$(CFLAGS))) -g1
$(BUILD_DIR)/src/rom/lib_7600.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_7a10.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_7b30.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_7c80.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_7fb0.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_81e0.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_8a80.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_8e10.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_a800.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_c990.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_e1c0.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_e240.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_efd0.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
endif
