# Generated by pipeline.layout (write_opt_overrides) — DO NOT EDIT.
# Converted ROM TUs whose match was verified at a non-default opt level
# must compile at that level or the promotion SHA-1 gate fails.
ifeq ($(COMPILER),ido)
$(BUILD_DIR)/src/rom/lib_7600.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_a800.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
$(BUILD_DIR)/src/rom/lib_e240.o: CFLAGS := $(subst -O2,-O1,$(CFLAGS))
endif
