typedef struct AudioState {
    unsigned char active;
    unsigned char held;
    unsigned char unknown02[2];
    unsigned short rate;
    unsigned short unknown06;
    double position;
    unsigned int current;
    unsigned int previous;
    unsigned char unknown18[8];
    unsigned short initial_count;
    unsigned short decay_count;
    float sustain;
    unsigned short release_count;
    unsigned char unknown2A[6];
    unsigned int length;
    unsigned int loop_start;
    unsigned int loop_length;
    unsigned int stop_loop;
    unsigned char unknown40[8];
    unsigned short count;
    unsigned short unknown4A;
    float value;
    unsigned int step;
    float scale;
    float saved_value;
    unsigned char state;
    unsigned char unknown5D[0xB];
} AudioState;
