"""Generate the image's assembly units, linker script, and cloud symbol table.

    python3 -m tools.conveyor.pipeline.blob_tu generate
    python3 -m tools.conveyor.pipeline.blob_tu symbols

One assembly file per region. Every entry gets its own named section so the
linker script can place it at its exact image address and so a single function
can later be replaced by an IDO-compiled object without disturbing its
neighbours:

    .section .text.func_800A7DF0   ->  raw instruction words (passthrough)
    .section .blobdata.op_800AB120 ->  .incbin of the image slice (opaque)

**Contract amendment (recorded 2026-09-24).** The contract as written reused
004's `#pragma GLOBAL_ASM` C translation units. Implementation showed that
pattern is shaped by splat driving the cartridge build: for a standalone
image, a per-entry section plus an explicit linker script is simpler, needs no
asm-processor, and — the deciding point — lets the all-passthrough build run
on the Pi with no IDO at all, so the byte-identity gate can be proven before
the builder is ever involved. Splicing still swaps in an IDO-compiled object
per function; only the container changed.
"""
import argparse
import json
import struct
import sys
from pathlib import Path

from . import blob_layout
from . import targets as targetsmod

REPO = targetsmod.REPO
BLOB_DIR = REPO / "src" / "blob"
ASM_DIR = REPO / "asm" / "us" / "blob"
LINKER_SCRIPT = BLOB_DIR / "blob.ld"

_HEADER = ("/* GENERATED by pipeline.blob_tu — do not hand-edit.\n"
           " * Image {sha} @ 0x{base}; regenerate after any layout change.\n"
           " */\n")


def _words(image, vaddr, size):
    offset = vaddr - blob_layout.BASE
    return [w for (w,) in struct.iter_unpack(">I", image[offset:offset + size])]


def section_name(entry):
    if entry["kind"] == "function":
        return f".text.{entry['target_id']}"
    return f".blobdata.op_{entry['vaddr']:08x}"


def render_region(region, image, image_rel, spliced=()):
    """Assembly source for one region: every entry in image order.

    `spliced` maps target_id -> bytes produced by compiling that function's C
    and linking it at its image address. Those words are emitted in place of
    the image's, so the whole-image gate judges the compiled output. (A set
    of names is also accepted, meaning "omit"; bytes are the normal case.)

    Why bytes rather than linking the IDO object into the image: IDO pads
    .text to 16 bytes, so a 72-byte function occupies 80 in its object and
    the padding overwrites its neighbour. Truncating the section loses its
    relocations. Linking each function alone at its own address resolves the
    relocations first, and then the extent decides exactly how many bytes it
    contributes."""
    lines = [f"/* region {region['name']}: 0x{region['vaddr_start']:08X}"
             f"-0x{region['vaddr_end']:08X} */",
             ".set noreorder", ".set noat", ""]
    for entry in region["entries"]:
        name = section_name(entry)
        lines.append(f'.section {name}, "ax", @progbits')
        if entry["kind"] == "function":
            target_id = entry["target_id"]
            lines.append(f".globl {target_id}")
            lines.append(f"{target_id}:")
            body = spliced.get(target_id) if isinstance(spliced, dict) else None
            if body is not None:
                lines.append(f"    /* compiled from src/blob/{target_id}.c */")
                words = [w for (w,) in struct.iter_unpack(">I", body)]
            else:
                words = _words(image, entry["vaddr"], entry["size"])
            for word in words:
                lines.append(f"    .word 0x{word:08X}")
        else:
            offset = entry["vaddr"] - blob_layout.BASE
            lines.append(f'    .incbin "{image_rel}", {offset}, {entry["size"]}')
        lines.append("")
    return "\n".join(lines) + "\n"


_SYMBOL_ADDRS = REPO / "symbol_addrs.us.txt"
_SYM_LINE = __import__("re").compile(
    r"^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;")


def static_symbols(path=_SYMBOL_ADDRS):
    """{address: name} for the static ROM.

    Game code calls out of the image into libultra and libc — memset,
    osJamMesg, osRecvMesg, viGetTimeToDeadline. Those live in the cartridge,
    not in the image, so the link cannot resolve them from any blob object."""
    out = {}
    try:
        text = Path(path).read_text()
    except OSError:
        return out
    for line in text.splitlines():
        match = _SYM_LINE.match(line)
        if match:
            out.setdefault(int(match.group(2), 16), match.group(1))
    return out


def data_symbols():
    """{address: name} everything spliced C may reference by name.

    Game-code globals (`pad_config`, `D_80152000`) sit inside opaque runs, and
    static-ROM functions sit outside the image entirely; no object defines
    either. The script provides them at their true addresses — a wrong address
    surfaces as an image difference, not as silent corruption. Game-code
    entries win over static ones on collision, since this image is game code."""
    from . import disasm

    merged = static_symbols()
    merged.update(disasm.symbol_table())
    return merged


def render_linker_script(document, symbols=None):
    """Place every entry at its image address, in order, with no padding."""
    symbols = data_symbols() if symbols is None else symbols
    lines = [
        "/* GENERATED by pipeline.blob_tu — do not hand-edit. */",
        "SECTIONS",
        "{",
        f"    . = 0x{document['image']['base']};",
        "    .image : {",
    ]
    for region in document["regions"]:
        lines.append(f"        /* {region['name']} */")
        for entry in region["entries"]:
            lines.append(f"        *({section_name(entry)})")
    lines += [
        "    }",
        "",
        "    /* data symbols referenced by spliced C (addresses are truth:",
        "       a wrong one shows up as an image difference) */",
    ]
    for address in sorted(symbols):
        lines.append(f"    PROVIDE({symbols[address]} = 0x{address:08X});")
    lines += [
        "    /DISCARD/ : { *(.pdr) *(.mdebug*) *(.comment) *(.note*)"
        " *(.reginfo) *(.MIPS.abiflags) }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def write_symbols(document=None, path=ASM_DIR / "symbols.json"):
    """Export exactly the splice resolver's addresses for repo-only scoring.

    This needs the layout and symbol context, but no image bytes, compiled
    objects, or builder. Keep aliases at shared addresses and omit timestamps
    so identical inputs produce byte-identical output.
    """
    from . import blob_splice

    document = blob_layout.load() if document is None else document
    symbols = blob_splice.image_symbols(document)
    payload = {
        "generated_by": "python3 -m tools.conveyor.pipeline.blob_tu symbols",
        "image_sha256": document["image"]["sha256"],
        "symbols": {name: f"0x{address:08X}" for name, address in symbols.items()},
    }
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8")
    return path


def generate(document=None, image_path=blob_layout.IMAGE, asm_dir=ASM_DIR,
             blob_dir=BLOB_DIR, spliced=None):
    document = document or blob_layout.load()
    if spliced is None:
        from . import blob_splice
        spliced = blob_splice.spliced_bodies()
    image = Path(image_path).read_bytes()
    image_rel = Path(image_path)
    try:
        image_rel = image_rel.relative_to(REPO)
    except ValueError:
        pass
    asm_dir = Path(asm_dir)
    asm_dir.mkdir(parents=True, exist_ok=True)
    blob_dir = Path(blob_dir)
    blob_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for region in document["regions"]:
        path = asm_dir / f"{region['name']}.s"
        path.write_text(render_region(region, image, image_rel, spliced))
        written.append(path)
    script = blob_dir / "blob.ld"
    script.write_text(render_linker_script(document))
    write_symbols(document, asm_dir / "symbols.json")
    return written, script


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", default=str(blob_layout.LAYOUT_JSON))
    parser.add_argument("--image", default=str(blob_layout.IMAGE))
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("generate")
    symbols = sub.add_parser("symbols", help="export the cloud symbol table only")
    symbols.add_argument("--output", default=str(ASM_DIR / "symbols.json"))
    args = parser.parse_args()

    document = blob_layout.load(args.layout)
    if args.command == "symbols":
        path = write_symbols(document, args.output)
        print(f"blob_tu: symbol table -> {path}")
        return 0
    written, script = generate(document, args.image)
    functions = document["totals"]["functions"]
    print(f"blob_tu: {len(written)} region files, {functions} function sections, "
          f"linker script -> {script}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
