"""Generate the image's assembly units and linker script (008, stage 1).

    python3 -m tools.conveyor.pipeline.blob_tu generate

One assembly file per region. Every entry gets its own named section so the
linker script can place it at its exact image address and so a single function
can later be replaced by an IDO-compiled object without disturbing its
neighbours:

    .section .text.func_800A7DF0   ->  raw instruction words (passthrough)
    .section .blobdata.op_800AB120 ->  .incbin of the image slice (opaque)

**Contract amendment (recorded 2026-09-24).** The contract as written reused
004's `#pragma GLOBAL_ASM` C translation units. Implementation showed that
pattern is shaped by splat driving the cartridge build: for a standalone
image, a per-entry section plus an explicit linker script is simpler, needs no
asm-processor, and — the deciding point — lets the all-passthrough build run
on the Pi with no IDO at all, so the byte-identity gate can be proven before
the builder is ever involved. Splicing still swaps in an IDO-compiled object
per function; only the container changed.
"""
import argparse
import struct
import sys
from pathlib import Path

from . import blob_layout
from . import targets as targetsmod

REPO = targetsmod.REPO
BLOB_DIR = REPO / "src" / "blob"
ASM_DIR = REPO / "asm" / "us" / "blob"
LINKER_SCRIPT = BLOB_DIR / "blob.ld"

_HEADER = ("/* GENERATED by pipeline.blob_tu — do not hand-edit.\n"
           " * Image {sha} @ 0x{base}; regenerate after any layout change.\n"
           " */\n")


def _words(image, vaddr, size):
    offset = vaddr - blob_layout.BASE
    return [w for (w,) in struct.iter_unpack(">I", image[offset:offset + size])]


def section_name(entry):
    if entry["kind"] == "function":
        return f".text.{entry['target_id']}"
    return f".blobdata.op_{entry['vaddr']:08x}"


def render_region(region, image, image_rel):
    """Assembly source for one region: every entry in image order."""
    lines = [f"/* region {region['name']}: 0x{region['vaddr_start']:08X}"
             f"-0x{region['vaddr_end']:08X} */",
             ".set noreorder", ".set noat", ""]
    for entry in region["entries"]:
        name = section_name(entry)
        lines.append(f'.section {name}, "ax", @progbits')
        if entry["kind"] == "function":
            lines.append(f".globl {entry['target_id']}")
            lines.append(f"{entry['target_id']}:")
            for word in _words(image, entry["vaddr"], entry["size"]):
                lines.append(f"    .word 0x{word:08X}")
        else:
            offset = entry["vaddr"] - blob_layout.BASE
            lines.append(f'    .incbin "{image_rel}", {offset}, {entry["size"]}')
        lines.append("")
    return "\n".join(lines) + "\n"


def render_linker_script(document):
    """Place every entry at its image address, in order, with no padding."""
    lines = [
        "/* GENERATED by pipeline.blob_tu — do not hand-edit. */",
        "SECTIONS",
        "{",
        f"    . = 0x{document['image']['base']};",
        "    .image : {",
    ]
    for region in document["regions"]:
        lines.append(f"        /* {region['name']} */")
        for entry in region["entries"]:
            lines.append(f"        *({section_name(entry)})")
    lines += [
        "    }",
        "    /DISCARD/ : { *(.pdr) *(.mdebug*) *(.comment) *(.note*)"
        " *(.reginfo) *(.MIPS.abiflags) }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def generate(document=None, image_path=blob_layout.IMAGE, asm_dir=ASM_DIR,
             blob_dir=BLOB_DIR):
    document = document or blob_layout.load()
    image = Path(image_path).read_bytes()
    image_rel = Path(image_path)
    try:
        image_rel = image_rel.relative_to(REPO)
    except ValueError:
        pass
    asm_dir = Path(asm_dir)
    asm_dir.mkdir(parents=True, exist_ok=True)
    blob_dir = Path(blob_dir)
    blob_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for region in document["regions"]:
        path = asm_dir / f"{region['name']}.s"
        path.write_text(render_region(region, image, image_rel))
        written.append(path)
    script = blob_dir / "blob.ld"
    script.write_text(render_linker_script(document))
    return written, script


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", default=str(blob_layout.LAYOUT_JSON))
    parser.add_argument("--image", default=str(blob_layout.IMAGE))
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("generate")
    args = parser.parse_args()

    document = blob_layout.load(args.layout)
    written, script = generate(document, args.image)
    functions = document["totals"]["functions"]
    print(f"blob_tu: {len(written)} region files, {functions} function sections, "
          f"linker script -> {script}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
