"""Generate the extracted-population declaration layer for mips_to_c."""
import argparse
import datetime
import hashlib
import json
import re
import tempfile
from pathlib import Path

from ..client import DEFAULT_DATA
from . import autodecomp
from . import disasm


REPO = Path(__file__).resolve().parents[3]
HEADER = REPO / "build" / "m2c_protos.h"
EVIDENCE = REPO / "build" / "m2c_protos.json"
_CALL_RE = re.compile(r"^\s*(?:jal|bal|j)\s+([A-Za-z_]\w*)\s*$", re.M)


def extract_signature(m2c_output, target_id):
    """Return target_id's own cleaned definition header as a declaration."""
    cleaned = autodecomp._clean_m2c(m2c_output)
    match = re.search(
        rf"^([A-Za-z_][\w\s,*]*?\b{re.escape(target_id)}\s*"
        rf"\([^;{{]*\))\s*\{{",
        cleaned,
        re.M,
    )
    if not match:
        return None
    return " ".join(match.group(1).split()) + ";"


def declared_function_names(context_text):
    """Function-declarator names present in preprocessed hand context."""
    return set(re.findall(
        r"\b([A-Za-z_]\w*)\s*\([^;{}]*\)\s*;", context_text, re.S
    ))


def build_layer(candidates, signatures, hand_names, static_names,
                pass_number):
    """Build sorted declaration/omission maps and enforce coverage."""
    declarations = {}
    omitted = {}
    for name in sorted(candidates):
        if name in static_names:
            omitted[name] = "static_target"
        elif name in hand_names:
            omitted[name] = "hand_context"
        else:
            signature = signatures.get(name)
            declarations[name] = {
                "signature": signature or f"s32 {name}();",
                "source": "own_definition" if signature else "fallback",
                "pass": pass_number,
            }
    assert set(declarations) | set(omitted) == set(candidates)
    assert not set(declarations) & set(omitted)
    return {"declarations": declarations, "omitted": omitted}


def render_header(artifact, stamp):
    """Render stable content; volatile timestamp deliberately stays in JSON."""
    stable_stamp = " ".join(
        f"{key}={stamp[key]}" for key in (
            "image_sha", "symbol_table_sha", "context_sha",
            "derivation_version", "passes"
        )
    )
    lines = [
        "/* Generated by tools.conveyor.pipeline.protos; do not edit.",
        f" * {stable_stamp}",
        " */",
        "#ifndef M2C_PROTOS_H",
        "#define M2C_PROTOS_H",
        "",
    ]
    lines.extend(item["signature"]
                 for item in artifact["declarations"].values())
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def write_artifacts(artifact, stamp, header=HEADER, evidence=EVIDENCE):
    header = Path(header)
    evidence = Path(evidence)
    header.parent.mkdir(parents=True, exist_ok=True)
    evidence.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(render_header(artifact, stamp))
    data = {"stamp": stamp, **artifact}
    evidence.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def _rows(conn):
    return conn.execute(
        "SELECT target_id,address,population,gate_reason,target_o_sha"
        " FROM n64_target ORDER BY target_id"
    ).fetchall()


def _run_pass(conn, rows, context):
    """One population-equivalent m2c pass: derive, run, capture own headers."""
    signatures = {}
    referenced = set()
    known = {row["target_id"] for row in rows}
    for row in rows:
        if (row["population"] != "extracted" or not row["target_o_sha"]
                or (row["gate_reason"] or "").startswith("extent_conflict")):
            continue
        try:
            asm_path = disasm.derive(
                conn, row["target_id"],
                context_sha=autodecomp._context_sha(context),
            )
        except Exception:
            continue
        referenced.update(name for name in _CALL_RE.findall(
            asm_path.read_text(errors="replace")) if name in known)
        diagnostics = {}
        try:
            autodecomp.m2c_seed(
                row["target_id"], row["address"], {row["target_id"]: asm_path},
                diagnostics=diagnostics, context=context,
            )
        except Exception:
            continue
        signature = extract_signature(
            diagnostics.get((row["target_id"], "raw"), ""), row["target_id"]
        )
        if signature:
            signatures[row["target_id"]] = signature
    return signatures, referenced


def _stamp(hand_text):
    return {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "image_sha": disasm._sha256(disasm.GAME_CODE_BIN),
        "symbol_table_sha": disasm.symbol_table_sha(),
        "context_sha": hashlib.sha256(hand_text.encode()).hexdigest(),
        "derivation_version": disasm.DERIVATION_VERSION,
        "passes": 2,
    }


def generate(data=DEFAULT_DATA, header=HEADER, evidence=EVIDENCE):
    """Run exactly two signature passes and emit pass 2's declaration layer."""
    conn, _ = autodecomp._conn(data)
    rows = _rows(conn)
    hand_context = autodecomp._context(include_protos=False)
    _, hand_text = hand_context
    hand_names = declared_function_names(hand_text)
    static_names = {
        row["target_id"] for row in rows
        if row["population"] == "static" and row["target_id"] in hand_names
    }

    pass1_signatures, pass1_referenced = _run_pass(conn, rows, hand_context)
    candidates = set(pass1_signatures) | pass1_referenced
    pass1 = build_layer(candidates, pass1_signatures, hand_names, static_names, 1)
    pass1_stamp = _stamp(hand_text)
    with tempfile.TemporaryDirectory(prefix="m2c-protos-") as directory:
        pass1_path = Path(directory) / "m2c_protos.h"
        pass1_path.write_text(render_header(pass1, pass1_stamp))
        pass2_context = autodecomp._context(
            include_protos=True, protos_path=pass1_path
        )
        pass2_signatures, pass2_referenced = _run_pass(
            conn, rows, pass2_context
        )

    # Both passes see the same derived call graph. Unioning is defensive
    # against an isolated per-target failure and preserves the coverage oracle.
    candidates |= set(pass2_signatures) | pass2_referenced
    artifact = build_layer(
        candidates, pass2_signatures, hand_names, static_names, 2
    )
    stamp = _stamp(hand_text)
    write_artifacts(artifact, stamp, header, evidence)
    print(f"declarations={len(artifact['declarations'])} "
          f"omitted={len(artifact['omitted'])}; layer -> {header}")
    return artifact


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default=str(DEFAULT_DATA))
    sub = parser.add_subparsers(dest="command", required=True)
    command = sub.add_parser("generate")
    command.set_defaults(func=lambda args: generate(args.data))
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
