/*
 * CORPUS MATCH (reloc_only_diff) — NOT byte-verified; do not commit as matched.
 * Generated by pipeline.corpus; regenerated on every ingest — do not hand-edit.
 * Origin:      ultralib (https://github.com/decompals/ultralib)
 * Source:      src/io/sptaskyielded.c @ e24c8367
 * Flags:       -g0 -O2 -mips2 -G 0 -non_shared
 * Scores:      true=5  reloc_blind=0
 * Upgrade:     re-scores automatically when relocation-aware targets land
 */
OSYieldResult osSpTaskYielded(OSTask* tp) {
    u32 status;
    OSYieldResult result;

    status = __osSpGetStatus();
    result = (status & SP_STATUS_YIELDED) ? OS_TASK_YIELDED : 0;

    if (status & SP_STATUS_YIELD) {
        tp->t.flags |= result;
        tp->t.flags &= ~(OS_TASK_DP_WAIT);
    }

    return result;
}
