.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osAiDeviceBusy, 0x24

glabel __osAiDeviceBusy
    /* 10760 8000FB60 3C0EA450 */  lui        $t6, %hi(AI_STATUS_REG)
    /* 10764 8000FB64 8DC2000C */  lw         $v0, %lo(AI_STATUS_REG)($t6)
    /* 10768 8000FB68 00027800 */  sll        $t7, $v0, 0
    /* 1076C 8000FB6C 05E10003 */  bgez       $t7, .L8000FB7C
    /* 10770 8000FB70 00001025 */   or        $v0, $zero, $zero
    /* 10774 8000FB74 03E00008 */  jr         $ra
    /* 10778 8000FB78 24020001 */   addiu     $v0, $zero, 0x1
  .L8000FB7C:
    /* 1077C 8000FB7C 03E00008 */  jr         $ra
    /* 10780 8000FB80 00000000 */   nop
endlabel __osAiDeviceBusy
    /* 10784 8000FB84 00000000 */  nop
    /* 10788 8000FB88 00000000 */  nop
    /* 1078C 8000FB8C 00000000 */  nop
