.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching __osSetCompare, 0xC

glabel __osSetCompare
    /* 10790 8000FB90 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 10794 8000FB94 03E00008 */  jr         $ra
    /* 10798 8000FB98 00000000 */   nop
endlabel __osSetCompare
    /* 1079C 8000FB9C 00000000 */  nop
