.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching osDestroyThread, 0x104

glabel osDestroyThread
    /* 107A0 8000FBA0 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 107A4 8000FBA4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 107A8 8000FBA8 AFA40038 */  sw         $a0, 0x38($sp)
    /* 107AC 8000FBAC AFB20020 */  sw         $s2, 0x20($sp)
    /* 107B0 8000FBB0 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 107B4 8000FBB4 0C00312C */  jal        __osDisableInt
    /* 107B8 8000FBB8 AFB00018 */   sw        $s0, 0x18($sp)
    /* 107BC 8000FBBC 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 107C0 8000FBC0 00408025 */  or         $s0, $v0, $zero
    /* 107C4 8000FBC4 15C00005 */  bnez       $t6, .L8000FBDC
    /* 107C8 8000FBC8 00000000 */   nop
    /* 107CC 8000FBCC 3C0F8003 */  lui        $t7, %hi(__osRunningThread)
    /* 107D0 8000FBD0 8DEFC3E0 */  lw         $t7, %lo(__osRunningThread)($t7)
    /* 107D4 8000FBD4 10000009 */  b          .L8000FBFC
    /* 107D8 8000FBD8 AFAF0038 */   sw        $t7, 0x38($sp)
  .L8000FBDC:
    /* 107DC 8000FBDC 8FB80038 */  lw         $t8, 0x38($sp)
    /* 107E0 8000FBE0 24010001 */  addiu      $at, $zero, 0x1
    /* 107E4 8000FBE4 97190010 */  lhu        $t9, 0x10($t8)
    /* 107E8 8000FBE8 13210004 */  beq        $t9, $at, .L8000FBFC
    /* 107EC 8000FBEC 00000000 */   nop
    /* 107F0 8000FBF0 8F040008 */  lw         $a0, 0x8($t8)
    /* 107F4 8000FBF4 0C003014 */  jal        dll_remove
    /* 107F8 8000FBF8 03002825 */   or        $a1, $t8, $zero
  .L8000FBFC:
    /* 107FC 8000FBFC 3C088003 */  lui        $t0, %hi(__osRunQueue)
    /* 10800 8000FC00 8D08C3DC */  lw         $t0, %lo(__osRunQueue)($t0)
    /* 10804 8000FC04 8FA90038 */  lw         $t1, 0x38($sp)
    /* 10808 8000FC08 15090005 */  bne        $t0, $t1, .L8000FC20
    /* 1080C 8000FC0C 00000000 */   nop
    /* 10810 8000FC10 8D0A000C */  lw         $t2, 0xC($t0)
    /* 10814 8000FC14 3C018003 */  lui        $at, %hi(__osRunQueue)
    /* 10818 8000FC18 10000013 */  b          .L8000FC68
    /* 1081C 8000FC1C AC2AC3DC */   sw        $t2, %lo(__osRunQueue)($at)
  .L8000FC20:
    /* 10820 8000FC20 3C118003 */  lui        $s1, %hi(__osRunQueue)
    /* 10824 8000FC24 8E31C3DC */  lw         $s1, %lo(__osRunQueue)($s1)
    /* 10828 8000FC28 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1082C 8000FC2C 8E2B0004 */  lw         $t3, 0x4($s1)
    /* 10830 8000FC30 1161000D */  beq        $t3, $at, .L8000FC68
    /* 10834 8000FC34 00000000 */   nop
  .L8000FC38:
    /* 10838 8000FC38 8E32000C */  lw         $s2, 0xC($s1)
    /* 1083C 8000FC3C 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 10840 8000FC40 164C0004 */  bne        $s2, $t4, .L8000FC54
    /* 10844 8000FC44 00000000 */   nop
    /* 10848 8000FC48 8D8D000C */  lw         $t5, 0xC($t4)
    /* 1084C 8000FC4C 10000006 */  b          .L8000FC68
    /* 10850 8000FC50 AE2D000C */   sw        $t5, 0xC($s1)
  .L8000FC54:
    /* 10854 8000FC54 02408825 */  or         $s1, $s2, $zero
    /* 10858 8000FC58 8E2E0004 */  lw         $t6, 0x4($s1)
    /* 1085C 8000FC5C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 10860 8000FC60 15C1FFF5 */  bne        $t6, $at, .L8000FC38
    /* 10864 8000FC64 00000000 */   nop
  .L8000FC68:
    /* 10868 8000FC68 3C198003 */  lui        $t9, %hi(__osRunningThread)
    /* 1086C 8000FC6C 8F39C3E0 */  lw         $t9, %lo(__osRunningThread)($t9)
    /* 10870 8000FC70 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 10874 8000FC74 15F90003 */  bne        $t7, $t9, .L8000FC84
    /* 10878 8000FC78 00000000 */   nop
    /* 1087C 8000FC7C 0C003447 */  jal        __osDispatchThread
    /* 10880 8000FC80 00000000 */   nop
  .L8000FC84:
    /* 10884 8000FC84 0C003148 */  jal        __osRestoreInt
    /* 10888 8000FC88 02002025 */   or        $a0, $s0, $zero
    /* 1088C 8000FC8C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 10890 8000FC90 8FB00018 */  lw         $s0, 0x18($sp)
    /* 10894 8000FC94 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 10898 8000FC98 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1089C 8000FC9C 03E00008 */  jr         $ra
    /* 108A0 8000FCA0 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel osDestroyThread
    /* 108A4 8000FCA4 00000000 */  nop
    /* 108A8 8000FCA8 00000000 */  nop
    /* 108AC 8000FCAC 00000000 */  nop
