.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching __osProbeTLB, 0xB8

glabel __osProbeTLB
    /* 108B0 8000FCB0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 108B4 8000FCB4 310900FF */  andi       $t1, $t0, 0xFF
    /* 108B8 8000FCB8 2401E000 */  addiu      $at, $zero, -0x2000
    /* 108BC 8000FCBC 00815024 */  and        $t2, $a0, $at
    /* 108C0 8000FCC0 012A4825 */  or         $t1, $t1, $t2
    /* 108C4 8000FCC4 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 108C8 8000FCC8 00000000 */  nop
    /* 108CC 8000FCCC 00000000 */  nop
    /* 108D0 8000FCD0 00000000 */  nop
    /* 108D4 8000FCD4 42000008 */  tlbp /* handwritten instruction */
    /* 108D8 8000FCD8 00000000 */  nop
    /* 108DC 8000FCDC 00000000 */  nop
    /* 108E0 8000FCE0 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 108E4 8000FCE4 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 108E8 8000FCE8 01615824 */  and        $t3, $t3, $at
    /* 108EC 8000FCEC 1560001A */  bnez       $t3, .L8000FD58
    /* 108F0 8000FCF0 00000000 */   nop
    /* 108F4 8000FCF4 42000001 */  tlbr /* handwritten instruction */
    /* 108F8 8000FCF8 00000000 */  nop
    /* 108FC 8000FCFC 00000000 */  nop
    /* 10900 8000FD00 00000000 */  nop
    /* 10904 8000FD04 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 10908 8000FD08 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 1090C 8000FD0C 000B5842 */  srl        $t3, $t3, 1
    /* 10910 8000FD10 01646024 */  and        $t4, $t3, $a0
    /* 10914 8000FD14 15800004 */  bnez       $t4, .L8000FD28
    /* 10918 8000FD18 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 1091C 8000FD1C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 10920 8000FD20 10000002 */  b          .L8000FD2C
    /* 10924 8000FD24 00000000 */   nop
  .L8000FD28:
    /* 10928 8000FD28 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L8000FD2C:
    /* 1092C 8000FD2C 304D0002 */  andi       $t5, $v0, 0x2
    /* 10930 8000FD30 11A00009 */  beqz       $t5, .L8000FD58
    /* 10934 8000FD34 00000000 */   nop
    /* 10938 8000FD38 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 1093C 8000FD3C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 10940 8000FD40 00411024 */  and        $v0, $v0, $at
    /* 10944 8000FD44 00021180 */  sll        $v0, $v0, 6
    /* 10948 8000FD48 008B6824 */  and        $t5, $a0, $t3
    /* 1094C 8000FD4C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 10950 8000FD50 10000002 */  b          .L8000FD5C
    /* 10954 8000FD54 00000000 */   nop
  .L8000FD58:
    /* 10958 8000FD58 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8000FD5C:
    /* 1095C 8000FD5C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 10960 8000FD60 03E00008 */  jr         $ra
    /* 10964 8000FD64 00000000 */   nop
endlabel __osProbeTLB
    /* 10968 8000FD68 00000000 */  nop
    /* 1096C 8000FD6C 00000000 */  nop
