.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osSiDeviceBusy, 0x24

glabel __osSiDeviceBusy
    /* 10970 8000FD70 3C0EA480 */  lui        $t6, %hi(SI_STATUS_REG)
    /* 10974 8000FD74 8DC20018 */  lw         $v0, %lo(SI_STATUS_REG)($t6)
    /* 10978 8000FD78 304F0003 */  andi       $t7, $v0, 0x3
    /* 1097C 8000FD7C 11E00003 */  beqz       $t7, .L8000FD8C
    /* 10980 8000FD80 00001025 */   or        $v0, $zero, $zero
    /* 10984 8000FD84 03E00008 */  jr         $ra
    /* 10988 8000FD88 24020001 */   addiu     $v0, $zero, 0x1
  .L8000FD8C:
    /* 1098C 8000FD8C 03E00008 */  jr         $ra
    /* 10990 8000FD90 00000000 */   nop
endlabel __osSiDeviceBusy
    /* 10994 8000FD94 00000000 */  nop
    /* 10998 8000FD98 00000000 */  nop
    /* 1099C 8000FD9C 00000000 */  nop
