.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osResetGlobalIntMask, 0x58

glabel __osResetGlobalIntMask
    /* 109A0 8000FDA0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 109A4 8000FDA4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 109A8 8000FDA8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 109AC 8000FDAC 0C00312C */  jal        __osDisableInt
    /* 109B0 8000FDB0 AFB00018 */   sw        $s0, 0x18($sp)
    /* 109B4 8000FDB4 8FAF0028 */  lw         $t7, 0x28($sp)
    /* 109B8 8000FDB8 3C0E8003 */  lui        $t6, %hi(__osGlobalIntMask)
    /* 109BC 8000FDBC 8DCEC370 */  lw         $t6, %lo(__osGlobalIntMask)($t6)
    /* 109C0 8000FDC0 2401FBFE */  addiu      $at, $zero, -0x402
    /* 109C4 8000FDC4 01E1C024 */  and        $t8, $t7, $at
    /* 109C8 8000FDC8 0300C827 */  not        $t9, $t8
    /* 109CC 8000FDCC 00408025 */  or         $s0, $v0, $zero
    /* 109D0 8000FDD0 3C018003 */  lui        $at, %hi(__osGlobalIntMask)
    /* 109D4 8000FDD4 01D94024 */  and        $t0, $t6, $t9
    /* 109D8 8000FDD8 AC28C370 */  sw         $t0, %lo(__osGlobalIntMask)($at)
    /* 109DC 8000FDDC 0C003148 */  jal        __osRestoreInt
    /* 109E0 8000FDE0 02002025 */   or        $a0, $s0, $zero
    /* 109E4 8000FDE4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 109E8 8000FDE8 8FB00018 */  lw         $s0, 0x18($sp)
    /* 109EC 8000FDEC 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 109F0 8000FDF0 03E00008 */  jr         $ra
    /* 109F4 8000FDF4 00000000 */   nop
endlabel __osResetGlobalIntMask
    /* 109F8 8000FDF8 00000000 */  nop
    /* 109FC 8000FDFC 00000000 */  nop
