.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osEPiRawWriteIo, 0x158

glabel __osEPiRawWriteIo
    /* 10A00 8000FE00 3C03A460 */  lui        $v1, %hi(PI_STATUS_REG)
    /* 10A04 8000FE04 34630010 */  ori        $v1, $v1, %lo(PI_STATUS_REG)
    /* 10A08 8000FE08 8C620000 */  lw         $v0, 0x0($v1)
    /* 10A0C 8000FE0C 00A03825 */  or         $a3, $a1, $zero
    /* 10A10 8000FE10 304E0003 */  andi       $t6, $v0, 0x3
    /* 10A14 8000FE14 51C00006 */  beql       $t6, $zero, .L8000FE30
    /* 10A18 8000FE18 90820009 */   lbu       $v0, 0x9($a0)
    /* 10A1C 8000FE1C 8C620000 */  lw         $v0, 0x0($v1)
  .L8000FE20:
    /* 10A20 8000FE20 304F0003 */  andi       $t7, $v0, 0x3
    /* 10A24 8000FE24 55E0FFFE */  bnel       $t7, $zero, .L8000FE20
    /* 10A28 8000FE28 8C620000 */   lw        $v0, 0x0($v1)
    /* 10A2C 8000FE2C 90820009 */  lbu        $v0, 0x9($a0)
  .L8000FE30:
    /* 10A30 8000FE30 3C038003 */  lui        $v1, %hi(__osPiDevList)
    /* 10A34 8000FE34 90990004 */  lbu        $t9, 0x4($a0)
    /* 10A38 8000FE38 0002C080 */  sll        $t8, $v0, 2
    /* 10A3C 8000FE3C 00781821 */  addu       $v1, $v1, $t8
    /* 10A40 8000FE40 8C63C3A0 */  lw         $v1, %lo(__osPiDevList)($v1)
    /* 10A44 8000FE44 90680004 */  lbu        $t0, 0x4($v1)
    /* 10A48 8000FE48 5328003D */  beql       $t9, $t0, .L8000FF40
    /* 10A4C 8000FE4C 8C8A000C */   lw        $t2, 0xC($a0)
    /* 10A50 8000FE50 14400019 */  bnez       $v0, .L8000FEB8
    /* 10A54 8000FE54 00602825 */   or        $a1, $v1, $zero
    /* 10A58 8000FE58 90820005 */  lbu        $v0, 0x5($a0)
    /* 10A5C 8000FE5C 90690005 */  lbu        $t1, 0x5($v1)
    /* 10A60 8000FE60 3C0AA460 */  lui        $t2, %hi(PI_BSD_DOM1_LAT_REG)
    /* 10A64 8000FE64 3C0CA460 */  lui        $t4, %hi(PI_BSD_DOM1_PGS_REG)
    /* 10A68 8000FE68 10490002 */  beq        $v0, $t1, .L8000FE74
    /* 10A6C 8000FE6C 3C0EA460 */   lui       $t6, %hi(PI_BSD_DOM1_RLS_REG)
    /* 10A70 8000FE70 AD420014 */  sw         $v0, %lo(PI_BSD_DOM1_LAT_REG)($t2)
  .L8000FE74:
    /* 10A74 8000FE74 90820006 */  lbu        $v0, 0x6($a0)
    /* 10A78 8000FE78 90AB0006 */  lbu        $t3, 0x6($a1)
    /* 10A7C 8000FE7C 3C18A460 */  lui        $t8, %hi(PI_BSD_DOM1_PWD_REG)
    /* 10A80 8000FE80 504B0003 */  beql       $v0, $t3, .L8000FE90
    /* 10A84 8000FE84 90820007 */   lbu       $v0, 0x7($a0)
    /* 10A88 8000FE88 AD82001C */  sw         $v0, %lo(PI_BSD_DOM1_PGS_REG)($t4)
    /* 10A8C 8000FE8C 90820007 */  lbu        $v0, 0x7($a0)
  .L8000FE90:
    /* 10A90 8000FE90 90AD0007 */  lbu        $t5, 0x7($a1)
    /* 10A94 8000FE94 504D0003 */  beql       $v0, $t5, .L8000FEA4
    /* 10A98 8000FE98 90820008 */   lbu       $v0, 0x8($a0)
    /* 10A9C 8000FE9C ADC20020 */  sw         $v0, %lo(PI_BSD_DOM1_RLS_REG)($t6)
    /* 10AA0 8000FEA0 90820008 */  lbu        $v0, 0x8($a0)
  .L8000FEA4:
    /* 10AA4 8000FEA4 90AF0008 */  lbu        $t7, 0x8($a1)
    /* 10AA8 8000FEA8 504F001B */  beql       $v0, $t7, .L8000FF18
    /* 10AAC 8000FEAC 908F0004 */   lbu       $t7, 0x4($a0)
    /* 10AB0 8000FEB0 10000018 */  b          .L8000FF14
    /* 10AB4 8000FEB4 AF020018 */   sw        $v0, %lo(PI_BSD_DOM1_PWD_REG)($t8)
  .L8000FEB8:
    /* 10AB8 8000FEB8 90820005 */  lbu        $v0, 0x5($a0)
    /* 10ABC 8000FEBC 90B90005 */  lbu        $t9, 0x5($a1)
    /* 10AC0 8000FEC0 3C08A460 */  lui        $t0, %hi(PI_BSD_DOM2_LAT_REG)
    /* 10AC4 8000FEC4 3C0AA460 */  lui        $t2, %hi(PI_BSD_DOM2_PGS_REG)
    /* 10AC8 8000FEC8 10590002 */  beq        $v0, $t9, .L8000FED4
    /* 10ACC 8000FECC 3C0CA460 */   lui       $t4, %hi(PI_BSD_DOM2_RLS_REG)
    /* 10AD0 8000FED0 AD020024 */  sw         $v0, %lo(PI_BSD_DOM2_LAT_REG)($t0)
  .L8000FED4:
    /* 10AD4 8000FED4 90820006 */  lbu        $v0, 0x6($a0)
    /* 10AD8 8000FED8 90A90006 */  lbu        $t1, 0x6($a1)
    /* 10ADC 8000FEDC 3C0EA460 */  lui        $t6, %hi(PI_BSD_DOM2_LWD_REG)
    /* 10AE0 8000FEE0 50490003 */  beql       $v0, $t1, .L8000FEF0
    /* 10AE4 8000FEE4 90820007 */   lbu       $v0, 0x7($a0)
    /* 10AE8 8000FEE8 AD42002C */  sw         $v0, %lo(PI_BSD_DOM2_PGS_REG)($t2)
    /* 10AEC 8000FEEC 90820007 */  lbu        $v0, 0x7($a0)
  .L8000FEF0:
    /* 10AF0 8000FEF0 90AB0007 */  lbu        $t3, 0x7($a1)
    /* 10AF4 8000FEF4 504B0003 */  beql       $v0, $t3, .L8000FF04
    /* 10AF8 8000FEF8 90820008 */   lbu       $v0, 0x8($a0)
    /* 10AFC 8000FEFC AD820030 */  sw         $v0, %lo(PI_BSD_DOM2_RLS_REG)($t4)
    /* 10B00 8000FF00 90820008 */  lbu        $v0, 0x8($a0)
  .L8000FF04:
    /* 10B04 8000FF04 90AD0008 */  lbu        $t5, 0x8($a1)
    /* 10B08 8000FF08 504D0003 */  beql       $v0, $t5, .L8000FF18
    /* 10B0C 8000FF0C 908F0004 */   lbu       $t7, 0x4($a0)
    /* 10B10 8000FF10 ADC20028 */  sw         $v0, %lo(PI_BSD_DOM2_LWD_REG)($t6)
  .L8000FF14:
    /* 10B14 8000FF14 908F0004 */  lbu        $t7, 0x4($a0)
  .L8000FF18:
    /* 10B18 8000FF18 A0AF0004 */  sb         $t7, 0x4($a1)
    /* 10B1C 8000FF1C 90980005 */  lbu        $t8, 0x5($a0)
    /* 10B20 8000FF20 A0B80005 */  sb         $t8, 0x5($a1)
    /* 10B24 8000FF24 90990006 */  lbu        $t9, 0x6($a0)
    /* 10B28 8000FF28 A0B90006 */  sb         $t9, 0x6($a1)
    /* 10B2C 8000FF2C 90880007 */  lbu        $t0, 0x7($a0)
    /* 10B30 8000FF30 A0A80007 */  sb         $t0, 0x7($a1)
    /* 10B34 8000FF34 90890008 */  lbu        $t1, 0x8($a0)
    /* 10B38 8000FF38 A0A90008 */  sb         $t1, 0x8($a1)
    /* 10B3C 8000FF3C 8C8A000C */  lw         $t2, 0xC($a0)
  .L8000FF40:
    /* 10B40 8000FF40 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 10B44 8000FF44 00001025 */  or         $v0, $zero, $zero
    /* 10B48 8000FF48 01475825 */  or         $t3, $t2, $a3
    /* 10B4C 8000FF4C 01616025 */  or         $t4, $t3, $at
    /* 10B50 8000FF50 03E00008 */  jr         $ra
    /* 10B54 8000FF54 AD860000 */   sw        $a2, %lo(D_A0000000)($t4)
endlabel __osEPiRawWriteIo
    /* 10B58 8000FF58 00000000 */  nop
    /* 10B5C 8000FF5C 00000000 */  nop
