.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osEPiRawReadIo, 0x15C

glabel __osEPiRawReadIo
    /* 10B60 8000FF60 3C03A460 */  lui        $v1, %hi(PI_STATUS_REG)
    /* 10B64 8000FF64 34630010 */  ori        $v1, $v1, %lo(PI_STATUS_REG)
    /* 10B68 8000FF68 8C620000 */  lw         $v0, 0x0($v1)
    /* 10B6C 8000FF6C 00A03825 */  or         $a3, $a1, $zero
    /* 10B70 8000FF70 304E0003 */  andi       $t6, $v0, 0x3
    /* 10B74 8000FF74 51C00006 */  beql       $t6, $zero, .L8000FF90
    /* 10B78 8000FF78 90820009 */   lbu       $v0, 0x9($a0)
    /* 10B7C 8000FF7C 8C620000 */  lw         $v0, 0x0($v1)
  .L8000FF80:
    /* 10B80 8000FF80 304F0003 */  andi       $t7, $v0, 0x3
    /* 10B84 8000FF84 55E0FFFE */  bnel       $t7, $zero, .L8000FF80
    /* 10B88 8000FF88 8C620000 */   lw        $v0, 0x0($v1)
    /* 10B8C 8000FF8C 90820009 */  lbu        $v0, 0x9($a0)
  .L8000FF90:
    /* 10B90 8000FF90 3C038003 */  lui        $v1, %hi(__osPiDevList)
    /* 10B94 8000FF94 90990004 */  lbu        $t9, 0x4($a0)
    /* 10B98 8000FF98 0002C080 */  sll        $t8, $v0, 2
    /* 10B9C 8000FF9C 00781821 */  addu       $v1, $v1, $t8
    /* 10BA0 8000FFA0 8C63C3A0 */  lw         $v1, %lo(__osPiDevList)($v1)
    /* 10BA4 8000FFA4 90680004 */  lbu        $t0, 0x4($v1)
    /* 10BA8 8000FFA8 5328003D */  beql       $t9, $t0, .L800100A0
    /* 10BAC 8000FFAC 8C8A000C */   lw        $t2, 0xC($a0)
    /* 10BB0 8000FFB0 14400019 */  bnez       $v0, .L80010018
    /* 10BB4 8000FFB4 00602825 */   or        $a1, $v1, $zero
    /* 10BB8 8000FFB8 90820005 */  lbu        $v0, 0x5($a0)
    /* 10BBC 8000FFBC 90690005 */  lbu        $t1, 0x5($v1)
    /* 10BC0 8000FFC0 3C0AA460 */  lui        $t2, %hi(PI_BSD_DOM1_LAT_REG)
    /* 10BC4 8000FFC4 3C0CA460 */  lui        $t4, %hi(PI_BSD_DOM1_PGS_REG)
    /* 10BC8 8000FFC8 10490002 */  beq        $v0, $t1, .L8000FFD4
    /* 10BCC 8000FFCC 3C0EA460 */   lui       $t6, %hi(PI_BSD_DOM1_RLS_REG)
    /* 10BD0 8000FFD0 AD420014 */  sw         $v0, %lo(PI_BSD_DOM1_LAT_REG)($t2)
  .L8000FFD4:
    /* 10BD4 8000FFD4 90820006 */  lbu        $v0, 0x6($a0)
    /* 10BD8 8000FFD8 90AB0006 */  lbu        $t3, 0x6($a1)
    /* 10BDC 8000FFDC 3C18A460 */  lui        $t8, %hi(PI_BSD_DOM1_PWD_REG)
    /* 10BE0 8000FFE0 504B0003 */  beql       $v0, $t3, .L8000FFF0
    /* 10BE4 8000FFE4 90820007 */   lbu       $v0, 0x7($a0)
    /* 10BE8 8000FFE8 AD82001C */  sw         $v0, %lo(PI_BSD_DOM1_PGS_REG)($t4)
    /* 10BEC 8000FFEC 90820007 */  lbu        $v0, 0x7($a0)
  .L8000FFF0:
    /* 10BF0 8000FFF0 90AD0007 */  lbu        $t5, 0x7($a1)
    /* 10BF4 8000FFF4 504D0003 */  beql       $v0, $t5, .L80010004
    /* 10BF8 8000FFF8 90820008 */   lbu       $v0, 0x8($a0)
    /* 10BFC 8000FFFC ADC20020 */  sw         $v0, %lo(PI_BSD_DOM1_RLS_REG)($t6)
    /* 10C00 80010000 90820008 */  lbu        $v0, 0x8($a0)
  .L80010004:
    /* 10C04 80010004 90AF0008 */  lbu        $t7, 0x8($a1)
    /* 10C08 80010008 504F001B */  beql       $v0, $t7, .L80010078
    /* 10C0C 8001000C 908F0004 */   lbu       $t7, 0x4($a0)
    /* 10C10 80010010 10000018 */  b          .L80010074
    /* 10C14 80010014 AF020018 */   sw        $v0, %lo(PI_BSD_DOM1_PWD_REG)($t8)
  .L80010018:
    /* 10C18 80010018 90820005 */  lbu        $v0, 0x5($a0)
    /* 10C1C 8001001C 90B90005 */  lbu        $t9, 0x5($a1)
    /* 10C20 80010020 3C08A460 */  lui        $t0, %hi(PI_BSD_DOM2_LAT_REG)
    /* 10C24 80010024 3C0AA460 */  lui        $t2, %hi(PI_BSD_DOM2_PGS_REG)
    /* 10C28 80010028 10590002 */  beq        $v0, $t9, .L80010034
    /* 10C2C 8001002C 3C0CA460 */   lui       $t4, %hi(PI_BSD_DOM2_RLS_REG)
    /* 10C30 80010030 AD020024 */  sw         $v0, %lo(PI_BSD_DOM2_LAT_REG)($t0)
  .L80010034:
    /* 10C34 80010034 90820006 */  lbu        $v0, 0x6($a0)
    /* 10C38 80010038 90A90006 */  lbu        $t1, 0x6($a1)
    /* 10C3C 8001003C 3C0EA460 */  lui        $t6, %hi(PI_BSD_DOM2_LWD_REG)
    /* 10C40 80010040 50490003 */  beql       $v0, $t1, .L80010050
    /* 10C44 80010044 90820007 */   lbu       $v0, 0x7($a0)
    /* 10C48 80010048 AD42002C */  sw         $v0, %lo(PI_BSD_DOM2_PGS_REG)($t2)
    /* 10C4C 8001004C 90820007 */  lbu        $v0, 0x7($a0)
  .L80010050:
    /* 10C50 80010050 90AB0007 */  lbu        $t3, 0x7($a1)
    /* 10C54 80010054 504B0003 */  beql       $v0, $t3, .L80010064
    /* 10C58 80010058 90820008 */   lbu       $v0, 0x8($a0)
    /* 10C5C 8001005C AD820030 */  sw         $v0, %lo(PI_BSD_DOM2_RLS_REG)($t4)
    /* 10C60 80010060 90820008 */  lbu        $v0, 0x8($a0)
  .L80010064:
    /* 10C64 80010064 90AD0008 */  lbu        $t5, 0x8($a1)
    /* 10C68 80010068 504D0003 */  beql       $v0, $t5, .L80010078
    /* 10C6C 8001006C 908F0004 */   lbu       $t7, 0x4($a0)
    /* 10C70 80010070 ADC20028 */  sw         $v0, %lo(PI_BSD_DOM2_LWD_REG)($t6)
  .L80010074:
    /* 10C74 80010074 908F0004 */  lbu        $t7, 0x4($a0)
  .L80010078:
    /* 10C78 80010078 A0AF0004 */  sb         $t7, 0x4($a1)
    /* 10C7C 8001007C 90980005 */  lbu        $t8, 0x5($a0)
    /* 10C80 80010080 A0B80005 */  sb         $t8, 0x5($a1)
    /* 10C84 80010084 90990006 */  lbu        $t9, 0x6($a0)
    /* 10C88 80010088 A0B90006 */  sb         $t9, 0x6($a1)
    /* 10C8C 8001008C 90880007 */  lbu        $t0, 0x7($a0)
    /* 10C90 80010090 A0A80007 */  sb         $t0, 0x7($a1)
    /* 10C94 80010094 90890008 */  lbu        $t1, 0x8($a0)
    /* 10C98 80010098 A0A90008 */  sb         $t1, 0x8($a1)
    /* 10C9C 8001009C 8C8A000C */  lw         $t2, 0xC($a0)
  .L800100A0:
    /* 10CA0 800100A0 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 10CA4 800100A4 00001025 */  or         $v0, $zero, $zero
    /* 10CA8 800100A8 01475825 */  or         $t3, $t2, $a3
    /* 10CAC 800100AC 01616025 */  or         $t4, $t3, $at
    /* 10CB0 800100B0 8D8D0000 */  lw         $t5, %lo(D_A0000000)($t4)
    /* 10CB4 800100B4 03E00008 */  jr         $ra
    /* 10CB8 800100B8 ACCD0000 */   sw        $t5, 0x0($a2)
endlabel __osEPiRawReadIo
    /* 10CBC 800100BC 00000000 */  nop
