.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __osSetGlobalIntMask, 0x4C

glabel __osSetGlobalIntMask
    /* 10CC0 800100C0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 10CC4 800100C4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 10CC8 800100C8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 10CCC 800100CC 0C00312C */  jal        __osDisableInt
    /* 10CD0 800100D0 AFB00018 */   sw        $s0, 0x18($sp)
    /* 10CD4 800100D4 3C0E8003 */  lui        $t6, %hi(__osGlobalIntMask)
    /* 10CD8 800100D8 8DCEC370 */  lw         $t6, %lo(__osGlobalIntMask)($t6)
    /* 10CDC 800100DC 8FAF0028 */  lw         $t7, 0x28($sp)
    /* 10CE0 800100E0 00408025 */  or         $s0, $v0, $zero
    /* 10CE4 800100E4 3C018003 */  lui        $at, %hi(__osGlobalIntMask)
    /* 10CE8 800100E8 01CFC025 */  or         $t8, $t6, $t7
    /* 10CEC 800100EC AC38C370 */  sw         $t8, %lo(__osGlobalIntMask)($at)
    /* 10CF0 800100F0 0C003148 */  jal        __osRestoreInt
    /* 10CF4 800100F4 02002025 */   or        $a0, $s0, $zero
    /* 10CF8 800100F8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 10CFC 800100FC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 10D00 80010100 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 10D04 80010104 03E00008 */  jr         $ra
    /* 10D08 80010108 00000000 */   nop
endlabel __osSetGlobalIntMask
    /* 10D0C 8001010C 00000000 */  nop
