.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching osPfsIsPlug, 0x18C

glabel osPfsIsPlug
    /* 10D60 80010160 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* 10D64 80010164 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 10D68 80010168 AFB5002C */  sw         $s5, 0x2C($sp)
    /* 10D6C 8001016C AFB20020 */  sw         $s2, 0x20($sp)
    /* 10D70 80010170 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 10D74 80010174 00809025 */  or         $s2, $a0, $zero
    /* 10D78 80010178 AFBE0038 */  sw         $fp, 0x38($sp)
    /* 10D7C 8001017C AFB70034 */  sw         $s7, 0x34($sp)
    /* 10D80 80010180 AFB60030 */  sw         $s6, 0x30($sp)
    /* 10D84 80010184 AFB40028 */  sw         $s4, 0x28($sp)
    /* 10D88 80010188 AFB30024 */  sw         $s3, 0x24($sp)
    /* 10D8C 8001018C AFB00018 */  sw         $s0, 0x18($sp)
    /* 10D90 80010190 AFA50074 */  sw         $a1, 0x74($sp)
    /* 10D94 80010194 0000A825 */  or         $s5, $zero, $zero
    /* 10D98 80010198 0C00396C */  jal        __osSiGetAccess
    /* 10D9C 8001019C 24110003 */   addiu     $s1, $zero, 0x3
    /* 10DA0 800101A0 3C1E8003 */  lui        $fp, %hi(__osPfsRequestType2)
    /* 10DA4 800101A4 3C138003 */  lui        $s3, %hi(__osPfsBuffer)
    /* 10DA8 800101A8 26737F60 */  addiu      $s3, $s3, %lo(__osPfsBuffer)
    /* 10DAC 800101AC 27DE7AE1 */  addiu      $fp, $fp, %lo(__osPfsRequestType2)
    /* 10DB0 800101B0 00008025 */  or         $s0, $zero, $zero
    /* 10DB4 800101B4 27B70054 */  addiu      $s7, $sp, 0x54
    /* 10DB8 800101B8 27B60067 */  addiu      $s6, $sp, 0x67
    /* 10DBC 800101BC 27B40068 */  addiu      $s4, $sp, 0x68
  .L800101C0:
    /* 10DC0 800101C0 0C0040BB */  jal        __osPfsRequestData
    /* 10DC4 800101C4 00002025 */   or        $a0, $zero, $zero
    /* 10DC8 800101C8 24040001 */  addiu      $a0, $zero, 0x1
    /* 10DCC 800101CC 0C00392C */  jal        __osSiRawStartDma
    /* 10DD0 800101D0 02602825 */   or        $a1, $s3, $zero
    /* 10DD4 800101D4 02402025 */  or         $a0, $s2, $zero
    /* 10DD8 800101D8 02802825 */  or         $a1, $s4, $zero
    /* 10DDC 800101DC 0C001C9C */  jal        osRecvMesg
    /* 10DE0 800101E0 24060001 */   addiu     $a2, $zero, 0x1
    /* 10DE4 800101E4 00002025 */  or         $a0, $zero, $zero
    /* 10DE8 800101E8 0C00392C */  jal        __osSiRawStartDma
    /* 10DEC 800101EC 02602825 */   or        $a1, $s3, $zero
    /* 10DF0 800101F0 AFA2006C */  sw         $v0, 0x6C($sp)
    /* 10DF4 800101F4 02402025 */  or         $a0, $s2, $zero
    /* 10DF8 800101F8 02802825 */  or         $a1, $s4, $zero
    /* 10DFC 800101FC 0C001C9C */  jal        osRecvMesg
    /* 10E00 80010200 24060001 */   addiu     $a2, $zero, 0x1
    /* 10E04 80010204 02C02025 */  or         $a0, $s6, $zero
    /* 10E08 80010208 0C0040E8 */  jal        func_800103A0
    /* 10E0C 8001020C 02E02825 */   or        $a1, $s7, $zero
    /* 10E10 80010210 93C30000 */  lbu        $v1, 0x0($fp)
    /* 10E14 80010214 27A20054 */  addiu      $v0, $sp, 0x54
    /* 10E18 80010218 5860000C */  blezl      $v1, .L8001024C
    /* 10E1C 8001021C 02031026 */   xor       $v0, $s0, $v1
  .L80010220:
    /* 10E20 80010220 904E0002 */  lbu        $t6, 0x2($v0)
    /* 10E24 80010224 31CF0004 */  andi       $t7, $t6, 0x4
    /* 10E28 80010228 55E00004 */  bnel       $t7, $zero, .L8001023C
    /* 10E2C 8001022C 26100001 */   addiu     $s0, $s0, 0x1
    /* 10E30 80010230 10000005 */  b          .L80010248
    /* 10E34 80010234 2631FFFF */   addiu     $s1, $s1, -0x1
    /* 10E38 80010238 26100001 */  addiu      $s0, $s0, 0x1
  .L8001023C:
    /* 10E3C 8001023C 0203082A */  slt        $at, $s0, $v1
    /* 10E40 80010240 1420FFF7 */  bnez       $at, .L80010220
    /* 10E44 80010244 24420004 */   addiu     $v0, $v0, 0x4
  .L80010248:
    /* 10E48 80010248 02031026 */  xor        $v0, $s0, $v1
  .L8001024C:
    /* 10E4C 8001024C 14400002 */  bnez       $v0, .L80010258
    /* 10E50 80010250 00008025 */   or        $s0, $zero, $zero
    /* 10E54 80010254 00008825 */  or         $s1, $zero, $zero
  .L80010258:
    /* 10E58 80010258 1E20FFD9 */  bgtz       $s1, .L800101C0
    /* 10E5C 8001025C 00000000 */   nop
    /* 10E60 80010260 18600011 */  blez       $v1, .L800102A8
    /* 10E64 80010264 27A20054 */   addiu     $v0, $sp, 0x54
  .L80010268:
    /* 10E68 80010268 90580003 */  lbu        $t8, 0x3($v0)
    /* 10E6C 8001026C 5700000B */  bnel       $t8, $zero, .L8001029C
    /* 10E70 80010270 26100001 */   addiu     $s0, $s0, 0x1
    /* 10E74 80010274 90590002 */  lbu        $t9, 0x2($v0)
    /* 10E78 80010278 24090001 */  addiu      $t1, $zero, 0x1
    /* 10E7C 8001027C 02095004 */  sllv       $t2, $t1, $s0
    /* 10E80 80010280 33280001 */  andi       $t0, $t9, 0x1
    /* 10E84 80010284 51000005 */  beql       $t0, $zero, .L8001029C
    /* 10E88 80010288 26100001 */   addiu     $s0, $s0, 0x1
    /* 10E8C 8001028C 02AAA825 */  or         $s5, $s5, $t2
    /* 10E90 80010290 32AB00FF */  andi       $t3, $s5, 0xFF
    /* 10E94 80010294 0160A825 */  or         $s5, $t3, $zero
    /* 10E98 80010298 26100001 */  addiu      $s0, $s0, 0x1
  .L8001029C:
    /* 10E9C 8001029C 0203082A */  slt        $at, $s0, $v1
    /* 10EA0 800102A0 1420FFF1 */  bnez       $at, .L80010268
    /* 10EA4 800102A4 24420004 */   addiu     $v0, $v0, 0x4
  .L800102A8:
    /* 10EA8 800102A8 0C00397D */  jal        __osSiRelAccess
    /* 10EAC 800102AC 00000000 */   nop
    /* 10EB0 800102B0 8FAC0074 */  lw         $t4, 0x74($sp)
    /* 10EB4 800102B4 A1950000 */  sb         $s5, 0x0($t4)
    /* 10EB8 800102B8 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 10EBC 800102BC 8FBE0038 */  lw         $fp, 0x38($sp)
    /* 10EC0 800102C0 8FB70034 */  lw         $s7, 0x34($sp)
    /* 10EC4 800102C4 8FB60030 */  lw         $s6, 0x30($sp)
    /* 10EC8 800102C8 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 10ECC 800102CC 8FB40028 */  lw         $s4, 0x28($sp)
    /* 10ED0 800102D0 8FB30024 */  lw         $s3, 0x24($sp)
    /* 10ED4 800102D4 8FB20020 */  lw         $s2, 0x20($sp)
    /* 10ED8 800102D8 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 10EDC 800102DC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 10EE0 800102E0 8FA2006C */  lw         $v0, 0x6C($sp)
    /* 10EE4 800102E4 03E00008 */  jr         $ra
    /* 10EE8 800102E8 27BD0070 */   addiu     $sp, $sp, 0x70
endlabel osPfsIsPlug

nonmatching __osPfsRequestData, 0xB4

glabel __osPfsRequestData
    /* 10EEC 800102EC 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 10EF0 800102F0 3C058003 */  lui        $a1, %hi(__osPfsBuffer)
    /* 10EF4 800102F4 3C018003 */  lui        $at, %hi(__osPfsRequestType)
    /* 10EF8 800102F8 24A27F60 */  addiu      $v0, $a1, %lo(__osPfsBuffer)
    /* 10EFC 800102FC AFA40010 */  sw         $a0, 0x10($sp)
    /* 10F00 80010300 A0247AE0 */  sb         $a0, %lo(__osPfsRequestType)($at)
    /* 10F04 80010304 240F0001 */  addiu      $t7, $zero, 0x1
    /* 10F08 80010308 AC4F003C */  sw         $t7, 0x3C($v0)
    /* 10F0C 8001030C 3C068003 */  lui        $a2, %hi(__osPfsRequestType2)
    /* 10F10 80010310 24C67AE1 */  addiu      $a2, $a2, %lo(__osPfsRequestType2)
    /* 10F14 80010314 90CD0000 */  lbu        $t5, 0x0($a2)
    /* 10F18 80010318 241800FF */  addiu      $t8, $zero, 0xFF
    /* 10F1C 8001031C 24190001 */  addiu      $t9, $zero, 0x1
    /* 10F20 80010320 24080003 */  addiu      $t0, $zero, 0x3
    /* 10F24 80010324 240900FF */  addiu      $t1, $zero, 0xFF
    /* 10F28 80010328 240A00FF */  addiu      $t2, $zero, 0xFF
    /* 10F2C 8001032C 240B00FF */  addiu      $t3, $zero, 0xFF
    /* 10F30 80010330 240C00FF */  addiu      $t4, $zero, 0xFF
    /* 10F34 80010334 A3B80004 */  sb         $t8, 0x4($sp)
    /* 10F38 80010338 A3B90005 */  sb         $t9, 0x5($sp)
    /* 10F3C 8001033C A3A80006 */  sb         $t0, 0x6($sp)
    /* 10F40 80010340 A3A40007 */  sb         $a0, 0x7($sp)
    /* 10F44 80010344 A3A90008 */  sb         $t1, 0x8($sp)
    /* 10F48 80010348 A3AA0009 */  sb         $t2, 0x9($sp)
    /* 10F4C 8001034C A3AB000A */  sb         $t3, 0xA($sp)
    /* 10F50 80010350 A3AC000B */  sb         $t4, 0xB($sp)
    /* 10F54 80010354 19A0000E */  blez       $t5, .L80010390
    /* 10F58 80010358 00001825 */   or        $v1, $zero, $zero
    /* 10F5C 8001035C 27A40004 */  addiu      $a0, $sp, 0x4
    /* 10F60 80010360 8C810000 */  lw         $at, 0x0($a0)
  .L80010364:
    /* 10F64 80010364 24630001 */  addiu      $v1, $v1, 0x1
    /* 10F68 80010368 24420008 */  addiu      $v0, $v0, 0x8
    /* 10F6C 8001036C A841FFF8 */  swl        $at, -0x8($v0)
    /* 10F70 80010370 B841FFFB */  swr        $at, -0x5($v0)
    /* 10F74 80010374 8C8F0004 */  lw         $t7, 0x4($a0)
    /* 10F78 80010378 A84FFFFC */  swl        $t7, -0x4($v0)
    /* 10F7C 8001037C B84FFFFF */  swr        $t7, -0x1($v0)
    /* 10F80 80010380 90D80000 */  lbu        $t8, 0x0($a2)
    /* 10F84 80010384 0078082A */  slt        $at, $v1, $t8
    /* 10F88 80010388 5420FFF6 */  bnel       $at, $zero, .L80010364
    /* 10F8C 8001038C 8C810000 */   lw        $at, 0x0($a0)
  .L80010390:
    /* 10F90 80010390 241900FE */  addiu      $t9, $zero, 0xFE
    /* 10F94 80010394 A0590000 */  sb         $t9, 0x0($v0)
    /* 10F98 80010398 03E00008 */  jr         $ra
    /* 10F9C 8001039C 27BD0010 */   addiu     $sp, $sp, 0x10
endlabel __osPfsRequestData

nonmatching func_800103A0, 0xAC

glabel func_800103A0
    /* 10FA0 800103A0 3C078003 */  lui        $a3, %hi(__osPfsRequestType2)
    /* 10FA4 800103A4 24E77AE1 */  addiu      $a3, $a3, %lo(__osPfsRequestType2)
    /* 10FA8 800103A8 90EE0000 */  lbu        $t6, 0x0($a3)
    /* 10FAC 800103AC 3C038003 */  lui        $v1, %hi(__osPfsBuffer)
    /* 10FB0 800103B0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10FB4 800103B4 00001025 */  or         $v0, $zero, $zero
    /* 10FB8 800103B8 24637F60 */  addiu      $v1, $v1, %lo(__osPfsBuffer)
    /* 10FBC 800103BC 19C00020 */  blez       $t6, .L80010440
    /* 10FC0 800103C0 00003025 */   or        $a2, $zero, $zero
    /* 10FC4 800103C4 27A8000C */  addiu      $t0, $sp, 0xC
  .L800103C8:
    /* 10FC8 800103C8 88610000 */  lwl        $at, 0x0($v1)
    /* 10FCC 800103CC 98610003 */  lwr        $at, 0x3($v1)
    /* 10FD0 800103D0 AD010000 */  sw         $at, 0x0($t0)
    /* 10FD4 800103D4 88780004 */  lwl        $t8, 0x4($v1)
    /* 10FD8 800103D8 98780007 */  lwr        $t8, 0x7($v1)
    /* 10FDC 800103DC AD180004 */  sw         $t8, 0x4($t0)
    /* 10FE0 800103E0 93B9000E */  lbu        $t9, 0xE($sp)
    /* 10FE4 800103E4 332900C0 */  andi       $t1, $t9, 0xC0
    /* 10FE8 800103E8 00095103 */  sra        $t2, $t1, 4
    /* 10FEC 800103EC 314B00FF */  andi       $t3, $t2, 0xFF
    /* 10FF0 800103F0 1560000D */  bnez       $t3, .L80010428
    /* 10FF4 800103F4 A0AA0003 */   sb        $t2, 0x3($a1)
    /* 10FF8 800103F8 93AC0011 */  lbu        $t4, 0x11($sp)
    /* 10FFC 800103FC 93AE0010 */  lbu        $t6, 0x10($sp)
    /* 11000 80010400 24190001 */  addiu      $t9, $zero, 0x1
    /* 11004 80010404 000C6A00 */  sll        $t5, $t4, 8
    /* 11008 80010408 01AE7825 */  or         $t7, $t5, $t6
    /* 1100C 8001040C A4AF0000 */  sh         $t7, 0x0($a1)
    /* 11010 80010410 93B80012 */  lbu        $t8, 0x12($sp)
    /* 11014 80010414 00D94804 */  sllv       $t1, $t9, $a2
    /* 11018 80010418 00491025 */  or         $v0, $v0, $t1
    /* 1101C 8001041C 304A00FF */  andi       $t2, $v0, 0xFF
    /* 11020 80010420 01401025 */  or         $v0, $t2, $zero
    /* 11024 80010424 A0B80002 */  sb         $t8, 0x2($a1)
  .L80010428:
    /* 11028 80010428 90EB0000 */  lbu        $t3, 0x0($a3)
    /* 1102C 8001042C 24C60001 */  addiu      $a2, $a2, 0x1
    /* 11030 80010430 24630008 */  addiu      $v1, $v1, 0x8
    /* 11034 80010434 00CB082A */  slt        $at, $a2, $t3
    /* 11038 80010438 1420FFE3 */  bnez       $at, .L800103C8
    /* 1103C 8001043C 24A50004 */   addiu     $a1, $a1, 0x4
  .L80010440:
    /* 11040 80010440 A0820000 */  sb         $v0, 0x0($a0)
    /* 11044 80010444 03E00008 */  jr         $ra
    /* 11048 80010448 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800103A0
    /* 1104C 8001044C 00000000 */  nop
