.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8001E0E0, 0x360

glabel func_8001E0E0
    /* 1ECE0 8001E0E0 3C08007F */  lui        $t0, (0x7F0001 >> 16)
    /* 1ECE4 8001E0E4 35080001 */  ori        $t0, $t0, (0x7F0001 & 0xFFFF)
    /* 1ECE8 8001E0E8 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 1ECEC 8001E0EC 00C8082B */  sltu       $at, $a2, $t0
    /* 1ECF0 8001E0F0 F7B40008 */  sdc1       $fs0, 0x8($sp)
    /* 1ECF4 8001E0F4 14200002 */  bnez       $at, .L8001E100
    /* 1ECF8 8001E0F8 AFA40010 */   sw        $a0, 0x10($sp)
    /* 1ECFC 8001E0FC 3C06007F */  lui        $a2, (0x7F0000 >> 16)
  .L8001E100:
    /* 1ED00 8001E100 3C013780 */  lui        $at, (0x37800000 >> 16)
    /* 1ED04 8001E104 44818000 */  mtc1       $at, $ft4
    /* 1ED08 8001E108 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 1ED0C 8001E10C 30D8FFFF */  andi       $t8, $a2, 0xFFFF
    /* 1ED10 8001E110 44982000 */  mtc1       $t8, $ft0
    /* 1ED14 8001E114 44819000 */  mtc1       $at, $ft5
    /* 1ED18 8001E118 3C0A8003 */  lui        $t2, %hi(D_8002CA40)
    /* 1ED1C 8001E11C 00067402 */  srl        $t6, $a2, 16
    /* 1ED20 8001E120 254ACA40 */  addiu      $t2, $t2, %lo(D_8002CA40)
    /* 1ED24 8001E124 3C018003 */  lui        $at, %hi(D_8002D910)
    /* 1ED28 8001E128 3C0B8003 */  lui        $t3, %hi(D_8002CC44)
    /* 1ED2C 8001E12C 3C0C003F */  lui        $t4, (0x3FFFFF >> 16)
    /* 1ED30 8001E130 000E7880 */  sll        $t7, $t6, 2
    /* 1ED34 8001E134 358CFFFF */  ori        $t4, $t4, (0x3FFFFF & 0xFFFF)
    /* 1ED38 8001E138 256BCC44 */  addiu      $t3, $t3, %lo(D_8002CC44)
    /* 1ED3C 8001E13C C434D910 */  lwc1       $fs0, %lo(D_8002D910)($at)
    /* 1ED40 8001E140 8FA30020 */  lw         $v1, 0x20($sp)
    /* 1ED44 8001E144 3C09007F */  lui        $t1, (0x7F0000 >> 16)
    /* 1ED48 8001E148 3C0D0080 */  lui        $t5, (0x800000 >> 16)
    /* 1ED4C 8001E14C 014F1021 */  addu       $v0, $t2, $t7
    /* 1ED50 8001E150 07010005 */  bgez       $t8, .L8001E168
    /* 1ED54 8001E154 468021A0 */   cvt.s.w   $ft1, $ft0
    /* 1ED58 8001E158 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1ED5C 8001E15C 44814000 */  mtc1       $at, $ft2
    /* 1ED60 8001E160 00000000 */  nop
    /* 1ED64 8001E164 46083180 */  add.s      $ft1, $ft1, $ft2
  .L8001E168:
    /* 1ED68 8001E168 46103082 */  mul.s      $fv1, $ft1, $ft4
    /* 1ED6C 8001E16C C4440000 */  lwc1       $ft0, 0x0($v0)
    /* 1ED70 8001E170 C4460004 */  lwc1       $ft1, 0x4($v0)
    /* 1ED74 8001E174 006C7824 */  and        $t7, $v1, $t4
    /* 1ED78 8001E178 0003CD82 */  srl        $t9, $v1, 22
    /* 1ED7C 8001E17C 00197080 */  sll        $t6, $t9, 2
    /* 1ED80 8001E180 016E2021 */  addu       $a0, $t3, $t6
    /* 1ED84 8001E184 46029281 */  sub.s      $ft3, $ft5, $fv1
    /* 1ED88 8001E188 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1ED8C 8001E18C 46045202 */  mul.s      $ft2, $ft3, $ft0
    /* 1ED90 8001E190 448F2000 */  mtc1       $t7, $ft0
    /* 1ED94 8001E194 46023282 */  mul.s      $ft3, $ft1, $fv1
    /* 1ED98 8001E198 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 1ED9C 8001E19C 05E10004 */  bgez       $t7, .L8001E1B0
    /* 1EDA0 8001E1A0 46085000 */   add.s     $fv0, $ft3, $ft2
    /* 1EDA4 8001E1A4 44815000 */  mtc1       $at, $ft3
    /* 1EDA8 8001E1A8 00000000 */  nop
    /* 1EDAC 8001E1AC 460A3180 */  add.s      $ft1, $ft1, $ft3
  .L8001E1B0:
    /* 1EDB0 8001E1B0 3C013480 */  lui        $at, (0x34800000 >> 16)
    /* 1EDB4 8001E1B4 44814000 */  mtc1       $at, $ft2
    /* 1EDB8 8001E1B8 C48A0000 */  lwc1       $ft3, 0x0($a0)
    /* 1EDBC 8001E1BC 3C018003 */  lui        $at, %hi(D_8002D914)
    /* 1EDC0 8001E1C0 46083302 */  mul.s      $fa0, $ft1, $ft2
    /* 1EDC4 8001E1C4 C4880004 */  lwc1       $ft2, 0x4($a0)
    /* 1EDC8 8001E1C8 8FAE0024 */  lw         $t6, 0x24($sp)
    /* 1EDCC 8001E1CC 01A31823 */  subu       $v1, $t5, $v1
    /* 1EDD0 8001E1D0 460C9101 */  sub.s      $ft0, $ft5, $fa0
    /* 1EDD4 8001E1D4 460A2182 */  mul.s      $ft1, $ft0, $ft3
    /* 1EDD8 8001E1D8 00000000 */  nop
    /* 1EDDC 8001E1DC 460C4102 */  mul.s      $ft0, $ft2, $fa0
    /* 1EDE0 8001E1E0 C428D914 */  lwc1       $ft2, %lo(D_8002D914)($at)
    /* 1EDE4 8001E1E4 006D082B */  sltu       $at, $v1, $t5
    /* 1EDE8 8001E1E8 46062380 */  add.s      $fa1, $ft0, $ft1
    /* 1EDEC 8001E1EC 460E0282 */  mul.s      $ft3, $fv0, $fa1
    /* 1EDF0 8001E1F0 00000000 */  nop
    /* 1EDF4 8001E1F4 46085102 */  mul.s      $ft0, $ft3, $ft2
    /* 1EDF8 8001E1F8 00000000 */  nop
    /* 1EDFC 8001E1FC 46142182 */  mul.s      $ft1, $ft0, $fs0
    /* 1EE00 8001E200 4600328D */  trunc.w.s  $ft3, $ft1
    /* 1EE04 8001E204 44195000 */  mfc1       $t9, $ft3
    /* 1EE08 8001E208 14200002 */  bnez       $at, .L8001E214
    /* 1EE0C 8001E20C A5D90000 */   sh        $t9, 0x0($t6)
    /* 1EE10 8001E210 01201825 */  or         $v1, $t1, $zero
  .L8001E214:
    /* 1EE14 8001E214 006CC824 */  and        $t9, $v1, $t4
    /* 1EE18 8001E218 44994000 */  mtc1       $t9, $ft2
    /* 1EE1C 8001E21C 00037D82 */  srl        $t7, $v1, 22
    /* 1EE20 8001E220 000FC080 */  sll        $t8, $t7, 2
    /* 1EE24 8001E224 01782021 */  addu       $a0, $t3, $t8
    /* 1EE28 8001E228 07210005 */  bgez       $t9, .L8001E240
    /* 1EE2C 8001E22C 46804120 */   cvt.s.w   $ft0, $ft2
    /* 1EE30 8001E230 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1EE34 8001E234 44813000 */  mtc1       $at, $ft1
    /* 1EE38 8001E238 00000000 */  nop
    /* 1EE3C 8001E23C 46062100 */  add.s      $ft0, $ft0, $ft1
  .L8001E240:
    /* 1EE40 8001E240 3C013480 */  lui        $at, (0x34800000 >> 16)
    /* 1EE44 8001E244 44815000 */  mtc1       $at, $ft3
    /* 1EE48 8001E248 C4860000 */  lwc1       $ft1, 0x0($a0)
    /* 1EE4C 8001E24C 00077D82 */  srl        $t7, $a3, 22
    /* 1EE50 8001E250 460A2302 */  mul.s      $fa0, $ft0, $ft3
    /* 1EE54 8001E254 C48A0004 */  lwc1       $ft3, 0x4($a0)
    /* 1EE58 8001E258 3C018003 */  lui        $at, %hi(D_8002D918)
    /* 1EE5C 8001E25C 000FC080 */  sll        $t8, $t7, 2
    /* 1EE60 8001E260 00ECC824 */  and        $t9, $a3, $t4
    /* 1EE64 8001E264 460C9201 */  sub.s      $ft2, $ft5, $fa0
    /* 1EE68 8001E268 46064102 */  mul.s      $ft0, $ft2, $ft1
    /* 1EE6C 8001E26C 00000000 */  nop
    /* 1EE70 8001E270 460C5202 */  mul.s      $ft2, $ft3, $fa0
    /* 1EE74 8001E274 46044380 */  add.s      $fa1, $ft2, $ft0
    /* 1EE78 8001E278 460E0002 */  mul.s      $fv0, $fv0, $fa1
    /* 1EE7C 8001E27C 14ED0013 */  bne        $a3, $t5, .L8001E2CC
    /* 1EE80 8001E280 00000000 */   nop
    /* 1EE84 8001E284 C426D918 */  lwc1       $ft1, %lo(D_8002D918)($at)
    /* 1EE88 8001E288 8FB80010 */  lw         $t8, 0x10($sp)
    /* 1EE8C 8001E28C 3C018003 */  lui        $at, %hi(D_8002D91C)
    /* 1EE90 8001E290 46060282 */  mul.s      $ft3, $fv0, $ft1
    /* 1EE94 8001E294 00000000 */  nop
    /* 1EE98 8001E298 46145202 */  mul.s      $ft2, $ft3, $fs0
    /* 1EE9C 8001E29C 4600410D */  trunc.w.s  $ft0, $ft2
    /* 1EEA0 8001E2A0 440F2000 */  mfc1       $t7, $ft0
    /* 1EEA4 8001E2A4 00000000 */  nop
    /* 1EEA8 8001E2A8 A70F0000 */  sh         $t7, 0x0($t8)
    /* 1EEAC 8001E2AC C426D91C */  lwc1       $ft1, %lo(D_8002D91C)($at)
    /* 1EEB0 8001E2B0 46060282 */  mul.s      $ft3, $fv0, $ft1
    /* 1EEB4 8001E2B4 00000000 */  nop
    /* 1EEB8 8001E2B8 46145202 */  mul.s      $ft2, $ft3, $fs0
    /* 1EEBC 8001E2BC 4600410D */  trunc.w.s  $ft0, $ft2
    /* 1EEC0 8001E2C0 440E2000 */  mfc1       $t6, $ft0
    /* 1EEC4 8001E2C4 1000003A */  b          .L8001E3B0
    /* 1EEC8 8001E2C8 A4AE0000 */   sh        $t6, 0x0($a1)
  .L8001E2CC:
    /* 1EECC 8001E2CC 44993000 */  mtc1       $t9, $ft1
    /* 1EED0 8001E2D0 01781021 */  addu       $v0, $t3, $t8
    /* 1EED4 8001E2D4 07210005 */  bgez       $t9, .L8001E2EC
    /* 1EED8 8001E2D8 468032A0 */   cvt.s.w   $ft3, $ft1
    /* 1EEDC 8001E2DC 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1EEE0 8001E2E0 44814000 */  mtc1       $at, $ft2
    /* 1EEE4 8001E2E4 00000000 */  nop
    /* 1EEE8 8001E2E8 46085280 */  add.s      $ft3, $ft3, $ft2
  .L8001E2EC:
    /* 1EEEC 8001E2EC 3C013480 */  lui        $at, (0x34800000 >> 16)
    /* 1EEF0 8001E2F0 44812000 */  mtc1       $at, $ft0
    /* 1EEF4 8001E2F4 C4480000 */  lwc1       $ft2, 0x0($v0)
    /* 1EEF8 8001E2F8 8FB80010 */  lw         $t8, 0x10($sp)
    /* 1EEFC 8001E2FC 46045082 */  mul.s      $fv1, $ft3, $ft0
    /* 1EF00 8001E300 C4440004 */  lwc1       $ft0, 0x4($v0)
    /* 1EF04 8001E304 01A73823 */  subu       $a3, $t5, $a3
    /* 1EF08 8001E308 00ED082B */  sltu       $at, $a3, $t5
    /* 1EF0C 8001E30C 46029181 */  sub.s      $ft1, $ft5, $fv1
    /* 1EF10 8001E310 46083282 */  mul.s      $ft3, $ft1, $ft2
    /* 1EF14 8001E314 00000000 */  nop
    /* 1EF18 8001E318 46022182 */  mul.s      $ft1, $ft0, $fv1
    /* 1EF1C 8001E31C 460A3380 */  add.s      $fa1, $ft1, $ft3
    /* 1EF20 8001E320 460E0202 */  mul.s      $ft2, $fv0, $fa1
    /* 1EF24 8001E324 00000000 */  nop
    /* 1EF28 8001E328 46144102 */  mul.s      $ft0, $ft2, $fs0
    /* 1EF2C 8001E32C 4600218D */  trunc.w.s  $ft1, $ft0
    /* 1EF30 8001E330 440F3000 */  mfc1       $t7, $ft1
    /* 1EF34 8001E334 14200002 */  bnez       $at, .L8001E340
    /* 1EF38 8001E338 A70F0000 */   sh        $t7, 0x0($t8)
    /* 1EF3C 8001E33C 01203825 */  or         $a3, $t1, $zero
  .L8001E340:
    /* 1EF40 8001E340 00EC7824 */  and        $t7, $a3, $t4
    /* 1EF44 8001E344 448F5000 */  mtc1       $t7, $ft3
    /* 1EF48 8001E348 0007CD82 */  srl        $t9, $a3, 22
    /* 1EF4C 8001E34C 00197080 */  sll        $t6, $t9, 2
    /* 1EF50 8001E350 016E1021 */  addu       $v0, $t3, $t6
    /* 1EF54 8001E354 05E10005 */  bgez       $t7, .L8001E36C
    /* 1EF58 8001E358 46805220 */   cvt.s.w   $ft2, $ft3
    /* 1EF5C 8001E35C 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1EF60 8001E360 44812000 */  mtc1       $at, $ft0
    /* 1EF64 8001E364 00000000 */  nop
    /* 1EF68 8001E368 46044200 */  add.s      $ft2, $ft2, $ft0
  .L8001E36C:
    /* 1EF6C 8001E36C 3C013480 */  lui        $at, (0x34800000 >> 16)
    /* 1EF70 8001E370 44813000 */  mtc1       $at, $ft1
    /* 1EF74 8001E374 C4440000 */  lwc1       $ft0, 0x0($v0)
    /* 1EF78 8001E378 46064082 */  mul.s      $fv1, $ft2, $ft1
    /* 1EF7C 8001E37C C4460004 */  lwc1       $ft1, 0x4($v0)
    /* 1EF80 8001E380 46029281 */  sub.s      $ft3, $ft5, $fv1
    /* 1EF84 8001E384 46045202 */  mul.s      $ft2, $ft3, $ft0
    /* 1EF88 8001E388 00000000 */  nop
    /* 1EF8C 8001E38C 46023282 */  mul.s      $ft3, $ft1, $fv1
    /* 1EF90 8001E390 46085380 */  add.s      $fa1, $ft3, $ft2
    /* 1EF94 8001E394 460E0102 */  mul.s      $ft0, $fv0, $fa1
    /* 1EF98 8001E398 00000000 */  nop
    /* 1EF9C 8001E39C 46142182 */  mul.s      $ft1, $ft0, $fs0
    /* 1EFA0 8001E3A0 4600328D */  trunc.w.s  $ft3, $ft1
    /* 1EFA4 8001E3A4 44195000 */  mfc1       $t9, $ft3
    /* 1EFA8 8001E3A8 00000000 */  nop
    /* 1EFAC 8001E3AC A4B90000 */  sh         $t9, 0x0($a1)
  .L8001E3B0:
    /* 1EFB0 8001E3B0 8FA20028 */  lw         $v0, 0x28($sp)
    /* 1EFB4 8001E3B4 0048082B */  sltu       $at, $v0, $t0
    /* 1EFB8 8001E3B8 54200003 */  bnel       $at, $zero, .L8001E3C8
    /* 1EFBC 8001E3BC 3058FFFF */   andi      $t8, $v0, 0xFFFF
    /* 1EFC0 8001E3C0 01201025 */  or         $v0, $t1, $zero
    /* 1EFC4 8001E3C4 3058FFFF */  andi       $t8, $v0, 0xFFFF
  .L8001E3C8:
    /* 1EFC8 8001E3C8 44984000 */  mtc1       $t8, $ft2
    /* 1EFCC 8001E3CC 00027402 */  srl        $t6, $v0, 16
    /* 1EFD0 8001E3D0 000E7880 */  sll        $t7, $t6, 2
    /* 1EFD4 8001E3D4 014F1821 */  addu       $v1, $t2, $t7
    /* 1EFD8 8001E3D8 07010005 */  bgez       $t8, .L8001E3F0
    /* 1EFDC 8001E3DC 46804120 */   cvt.s.w   $ft0, $ft2
    /* 1EFE0 8001E3E0 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1EFE4 8001E3E4 44813000 */  mtc1       $at, $ft1
    /* 1EFE8 8001E3E8 00000000 */  nop
    /* 1EFEC 8001E3EC 46062100 */  add.s      $ft0, $ft0, $ft1
  .L8001E3F0:
    /* 1EFF0 8001E3F0 46102082 */  mul.s      $fv1, $ft0, $ft4
    /* 1EFF4 8001E3F4 C4680000 */  lwc1       $ft2, 0x0($v1)
    /* 1EFF8 8001E3F8 C4640004 */  lwc1       $ft0, 0x4($v1)
    /* 1EFFC 8001E3FC 3C018003 */  lui        $at, %hi(D_8002D920)
    /* 1F000 8001E400 8FAF002C */  lw         $t7, 0x2C($sp)
    /* 1F004 8001E404 46029281 */  sub.s      $ft3, $ft5, $fv1
    /* 1F008 8001E408 46085182 */  mul.s      $ft1, $ft3, $ft2
    /* 1F00C 8001E40C C428D920 */  lwc1       $ft2, %lo(D_8002D920)($at)
    /* 1F010 8001E410 46022282 */  mul.s      $ft3, $ft0, $fv1
    /* 1F014 8001E414 46065000 */  add.s      $fv0, $ft3, $ft1
    /* 1F018 8001E418 46080102 */  mul.s      $ft0, $fv0, $ft2
    /* 1F01C 8001E41C 00000000 */  nop
    /* 1F020 8001E420 46142282 */  mul.s      $ft3, $ft0, $fs0
    /* 1F024 8001E424 4600518D */  trunc.w.s  $ft1, $ft3
    /* 1F028 8001E428 440E3000 */  mfc1       $t6, $ft1
    /* 1F02C 8001E42C 00000000 */  nop
    /* 1F030 8001E430 A5EE0000 */  sh         $t6, 0x0($t7)
    /* 1F034 8001E434 D7B40008 */  ldc1       $fs0, 0x8($sp)
    /* 1F038 8001E438 03E00008 */  jr         $ra
    /* 1F03C 8001E43C 27BD0010 */   addiu     $sp, $sp, 0x10
endlabel func_8001E0E0

nonmatching func_8001E440, 0xCC

glabel func_8001E440
    /* 1F040 8001E440 AFA40000 */  sw         $a0, 0x0($sp)
    /* 1F044 8001E444 3084FFFF */  andi       $a0, $a0, 0xFFFF
    /* 1F048 8001E448 44842000 */  mtc1       $a0, $ft0
    /* 1F04C 8001E44C 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1F050 8001E450 04810004 */  bgez       $a0, .L8001E464
    /* 1F054 8001E454 468021A0 */   cvt.s.w   $ft1, $ft0
    /* 1F058 8001E458 44814000 */  mtc1       $at, $ft2
    /* 1F05C 8001E45C 00000000 */  nop
    /* 1F060 8001E460 46083180 */  add.s      $ft1, $ft1, $ft2
  .L8001E464:
    /* 1F064 8001E464 3C018003 */  lui        $at, %hi(D_8002D924)
    /* 1F068 8001E468 C42AD924 */  lwc1       $ft3, %lo(D_8002D924)($at)
    /* 1F06C 8001E46C 24020001 */  addiu      $v0, $zero, 0x1
    /* 1F070 8001E470 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* 1F074 8001E474 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 1F078 8001E478 444EF800 */  cfc1       $t6, $31
    /* 1F07C 8001E47C 44C2F800 */  ctc1       $v0, $31
    /* 1F080 8001E480 00000000 */  nop
    /* 1F084 8001E484 460084A4 */  cvt.w.s    $ft5, $ft4
    /* 1F088 8001E488 4442F800 */  cfc1       $v0, $31
    /* 1F08C 8001E48C 00000000 */  nop
    /* 1F090 8001E490 30420078 */  andi       $v0, $v0, 0x78
    /* 1F094 8001E494 50400017 */  beql       $v0, $zero, .L8001E4F4
    /* 1F098 8001E498 44029000 */   mfc1      $v0, $ft5
    /* 1F09C 8001E49C 44819000 */  mtc1       $at, $ft5
    /* 1F0A0 8001E4A0 24020001 */  addiu      $v0, $zero, 0x1
    /* 1F0A4 8001E4A4 46128481 */  sub.s      $ft5, $ft4, $ft5
    /* 1F0A8 8001E4A8 44C2F800 */  ctc1       $v0, $31
    /* 1F0AC 8001E4AC 00000000 */  nop
    /* 1F0B0 8001E4B0 460094A4 */  cvt.w.s    $ft5, $ft5
    /* 1F0B4 8001E4B4 4442F800 */  cfc1       $v0, $31
    /* 1F0B8 8001E4B8 00000000 */  nop
    /* 1F0BC 8001E4BC 30420078 */  andi       $v0, $v0, 0x78
    /* 1F0C0 8001E4C0 54400008 */  bnel       $v0, $zero, .L8001E4E4
    /* 1F0C4 8001E4C4 2402FFFF */   addiu     $v0, $zero, -0x1
    /* 1F0C8 8001E4C8 44029000 */  mfc1       $v0, $ft5
    /* 1F0CC 8001E4CC 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1F0D0 8001E4D0 44CEF800 */  ctc1       $t6, $31
    /* 1F0D4 8001E4D4 00411025 */  or         $v0, $v0, $at
    /* 1F0D8 8001E4D8 03E00008 */  jr         $ra
    /* 1F0DC 8001E4DC 3042FFFF */   andi      $v0, $v0, 0xFFFF
    /* 1F0E0 8001E4E0 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8001E4E4:
    /* 1F0E4 8001E4E4 44CEF800 */  ctc1       $t6, $31
    /* 1F0E8 8001E4E8 03E00008 */  jr         $ra
    /* 1F0EC 8001E4EC 3042FFFF */   andi      $v0, $v0, 0xFFFF
    /* 1F0F0 8001E4F0 44029000 */  mfc1       $v0, $ft5
  .L8001E4F4:
    /* 1F0F4 8001E4F4 00000000 */  nop
    /* 1F0F8 8001E4F8 0442FFFA */  bltzl      $v0, .L8001E4E4
    /* 1F0FC 8001E4FC 2402FFFF */   addiu     $v0, $zero, -0x1
    /* 1F100 8001E500 44CEF800 */  ctc1       $t6, $31
    /* 1F104 8001E504 03E00008 */  jr         $ra
    /* 1F108 8001E508 3042FFFF */   andi      $v0, $v0, 0xFFFF
endlabel func_8001E440

nonmatching func_8001E50C, 0x17C

glabel func_8001E50C
    /* 1F10C 8001E50C AFA40000 */  sw         $a0, 0x0($sp)
    /* 1F110 8001E510 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1F114 8001E514 14A10003 */  bne        $a1, $at, .L8001E524
    /* 1F118 8001E518 308400FF */   andi      $a0, $a0, 0xFF
    /* 1F11C 8001E51C 3C054000 */  lui        $a1, (0x40005622 >> 16)
    /* 1F120 8001E520 34A55622 */  ori        $a1, $a1, (0x40005622 & 0xFFFF)
  .L8001E524:
    /* 1F124 8001E524 00051602 */  srl        $v0, $a1, 24
    /* 1F128 8001E528 304200FF */  andi       $v0, $v0, 0xFF
    /* 1F12C 8001E52C 1044001F */  beq        $v0, $a0, .L8001E5AC
    /* 1F130 8001E530 00801825 */   or        $v1, $a0, $zero
    /* 1F134 8001E534 0044082A */  slt        $at, $v0, $a0
    /* 1F138 8001E538 10200009 */  beqz       $at, .L8001E560
    /* 1F13C 8001E53C 00024080 */   sll       $t0, $v0, 2
    /* 1F140 8001E540 00027880 */  sll        $t7, $v0, 2
    /* 1F144 8001E544 000FC023 */  negu       $t8, $t7
    /* 1F148 8001E548 00047080 */  sll        $t6, $a0, 2
    /* 1F14C 8001E54C 01D8C821 */  addu       $t9, $t6, $t8
    /* 1F150 8001E550 3C018003 */  lui        $at, %hi(D_8002C640)
    /* 1F154 8001E554 00390821 */  addu       $at, $at, $t9
    /* 1F158 8001E558 10000007 */  b          .L8001E578
    /* 1F15C 8001E55C C420C640 */   lwc1      $fv0, %lo(D_8002C640)($at)
  .L8001E560:
    /* 1F160 8001E560 00034880 */  sll        $t1, $v1, 2
    /* 1F164 8001E564 00095023 */  negu       $t2, $t1
    /* 1F168 8001E568 010A5821 */  addu       $t3, $t0, $t2
    /* 1F16C 8001E56C 3C018003 */  lui        $at, %hi(D_8002C840)
    /* 1F170 8001E570 002B0821 */  addu       $at, $at, $t3
    /* 1F174 8001E574 C420C840 */  lwc1       $fv0, %lo(D_8002C840)($at)
  .L8001E578:
    /* 1F178 8001E578 3C0100FF */  lui        $at, (0xFFFFFF >> 16)
    /* 1F17C 8001E57C 3421FFFF */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 1F180 8001E580 00A16024 */  and        $t4, $a1, $at
    /* 1F184 8001E584 448C2000 */  mtc1       $t4, $ft0
    /* 1F188 8001E588 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1F18C 8001E58C 05810004 */  bgez       $t4, .L8001E5A0
    /* 1F190 8001E590 468021A0 */   cvt.s.w   $ft1, $ft0
    /* 1F194 8001E594 44814000 */  mtc1       $at, $ft2
    /* 1F198 8001E598 00000000 */  nop
    /* 1F19C 8001E59C 46083180 */  add.s      $ft1, $ft1, $ft2
  .L8001E5A0:
    /* 1F1A0 8001E5A0 46060082 */  mul.s      $fv1, $fv0, $ft1
    /* 1F1A4 8001E5A4 1000000B */  b          .L8001E5D4
    /* 1F1A8 8001E5A8 00000000 */   nop
  .L8001E5AC:
    /* 1F1AC 8001E5AC 3C0100FF */  lui        $at, (0xFFFFFF >> 16)
    /* 1F1B0 8001E5B0 3421FFFF */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
    /* 1F1B4 8001E5B4 00A16824 */  and        $t5, $a1, $at
    /* 1F1B8 8001E5B8 448D5000 */  mtc1       $t5, $ft3
    /* 1F1BC 8001E5BC 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1F1C0 8001E5C0 05A10004 */  bgez       $t5, .L8001E5D4
    /* 1F1C4 8001E5C4 468050A0 */   cvt.s.w   $fv1, $ft3
    /* 1F1C8 8001E5C8 44818000 */  mtc1       $at, $ft4
    /* 1F1CC 8001E5CC 00000000 */  nop
    /* 1F1D0 8001E5D0 46101080 */  add.s      $fv1, $fv1, $ft4
  .L8001E5D4:
    /* 1F1D4 8001E5D4 3C0F8005 */  lui        $t7, %hi(D_8004F800)
    /* 1F1D8 8001E5D8 8DEFF800 */  lw         $t7, %lo(D_8004F800)($t7)
    /* 1F1DC 8001E5DC 3C014580 */  lui        $at, (0x45800000 >> 16)
    /* 1F1E0 8001E5E0 44819000 */  mtc1       $at, $ft5
    /* 1F1E4 8001E5E4 448F4000 */  mtc1       $t7, $ft2
    /* 1F1E8 8001E5E8 24020001 */  addiu      $v0, $zero, 0x1
    /* 1F1EC 8001E5EC 46121102 */  mul.s      $ft0, $fv1, $ft5
    /* 1F1F0 8001E5F0 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* 1F1F4 8001E5F4 468041A0 */  cvt.s.w    $ft1, $ft2
    /* 1F1F8 8001E5F8 46062283 */  div.s      $ft3, $ft0, $ft1
    /* 1F1FC 8001E5FC 444EF800 */  cfc1       $t6, $31
    /* 1F200 8001E600 44C2F800 */  ctc1       $v0, $31
    /* 1F204 8001E604 00000000 */  nop
    /* 1F208 8001E608 46005424 */  cvt.w.s    $ft4, $ft3
    /* 1F20C 8001E60C 4442F800 */  cfc1       $v0, $31
    /* 1F210 8001E610 00000000 */  nop
    /* 1F214 8001E614 30420078 */  andi       $v0, $v0, 0x78
    /* 1F218 8001E618 50400015 */  beql       $v0, $zero, .L8001E670
    /* 1F21C 8001E61C 44028000 */   mfc1      $v0, $ft4
    /* 1F220 8001E620 44818000 */  mtc1       $at, $ft4
    /* 1F224 8001E624 24020001 */  addiu      $v0, $zero, 0x1
    /* 1F228 8001E628 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1F22C 8001E62C 46105401 */  sub.s      $ft4, $ft3, $ft4
    /* 1F230 8001E630 44C2F800 */  ctc1       $v0, $31
    /* 1F234 8001E634 00000000 */  nop
    /* 1F238 8001E638 46008424 */  cvt.w.s    $ft4, $ft4
    /* 1F23C 8001E63C 4442F800 */  cfc1       $v0, $31
    /* 1F240 8001E640 00000000 */  nop
    /* 1F244 8001E644 30420078 */  andi       $v0, $v0, 0x78
    /* 1F248 8001E648 54400006 */  bnel       $v0, $zero, .L8001E664
    /* 1F24C 8001E64C 44CEF800 */   ctc1      $t6, $31
    /* 1F250 8001E650 44028000 */  mfc1       $v0, $ft4
    /* 1F254 8001E654 44CEF800 */  ctc1       $t6, $31
    /* 1F258 8001E658 03E00008 */  jr         $ra
    /* 1F25C 8001E65C 00411025 */   or        $v0, $v0, $at
    /* 1F260 8001E660 44CEF800 */  ctc1       $t6, $31
  .L8001E664:
    /* 1F264 8001E664 03E00008 */  jr         $ra
    /* 1F268 8001E668 2402FFFF */   addiu     $v0, $zero, -0x1
    /* 1F26C 8001E66C 44028000 */  mfc1       $v0, $ft4
  .L8001E670:
    /* 1F270 8001E670 00000000 */  nop
    /* 1F274 8001E674 0442FFFB */  bltzl      $v0, .L8001E664
    /* 1F278 8001E678 44CEF800 */   ctc1      $t6, $31
    /* 1F27C 8001E67C 44CEF800 */  ctc1       $t6, $31
    /* 1F280 8001E680 03E00008 */  jr         $ra
    /* 1F284 8001E684 00000000 */   nop
endlabel func_8001E50C

nonmatching func_8001E688, 0xAC

glabel func_8001E688
    /* 1F288 8001E688 444EF800 */  cfc1       $t6, $31
    /* 1F28C 8001E68C 240F0001 */  addiu      $t7, $zero, 0x1
    /* 1F290 8001E690 44CFF800 */  ctc1       $t7, $31
    /* 1F294 8001E694 3C0141E0 */  lui        $at, (0x41E00000 >> 16)
    /* 1F298 8001E698 46206124 */  cvt.w.d    $ft0, $fa0
    /* 1F29C 8001E69C 444FF800 */  cfc1       $t7, $31
    /* 1F2A0 8001E6A0 00000000 */  nop
    /* 1F2A4 8001E6A4 31EF0078 */  andi       $t7, $t7, 0x78
    /* 1F2A8 8001E6A8 51E00014 */  beql       $t7, $zero, .L8001E6FC
    /* 1F2AC 8001E6AC 440F2000 */   mfc1      $t7, $ft0
    /* 1F2B0 8001E6B0 44812800 */  mtc1       $at, $ft0f
    /* 1F2B4 8001E6B4 44802000 */  mtc1       $zero, $ft0
    /* 1F2B8 8001E6B8 240F0001 */  addiu      $t7, $zero, 0x1
    /* 1F2BC 8001E6BC 46246101 */  sub.d      $ft0, $fa0, $ft0
    /* 1F2C0 8001E6C0 44CFF800 */  ctc1       $t7, $31
    /* 1F2C4 8001E6C4 00000000 */  nop
    /* 1F2C8 8001E6C8 46202124 */  cvt.w.d    $ft0, $ft0
    /* 1F2CC 8001E6CC 444FF800 */  cfc1       $t7, $31
    /* 1F2D0 8001E6D0 00000000 */  nop
    /* 1F2D4 8001E6D4 31EF0078 */  andi       $t7, $t7, 0x78
    /* 1F2D8 8001E6D8 15E00005 */  bnez       $t7, .L8001E6F0
    /* 1F2DC 8001E6DC 00000000 */   nop
    /* 1F2E0 8001E6E0 440F2000 */  mfc1       $t7, $ft0
    /* 1F2E4 8001E6E4 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1F2E8 8001E6E8 10000007 */  b          .L8001E708
    /* 1F2EC 8001E6EC 01E17825 */   or        $t7, $t7, $at
  .L8001E6F0:
    /* 1F2F0 8001E6F0 10000005 */  b          .L8001E708
    /* 1F2F4 8001E6F4 240FFFFF */   addiu     $t7, $zero, -0x1
    /* 1F2F8 8001E6F8 440F2000 */  mfc1       $t7, $ft0
  .L8001E6FC:
    /* 1F2FC 8001E6FC 00000000 */  nop
    /* 1F300 8001E700 05E0FFFB */  bltz       $t7, .L8001E6F0
    /* 1F304 8001E704 00000000 */   nop
  .L8001E708:
    /* 1F308 8001E708 44CEF800 */  ctc1       $t6, $31
    /* 1F30C 8001E70C 448F3000 */  mtc1       $t7, $ft1
    /* 1F310 8001E710 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 1F314 8001E714 05E10005 */  bgez       $t7, .L8001E72C
    /* 1F318 8001E718 46803021 */   cvt.d.w   $fv0, $ft1
    /* 1F31C 8001E71C 44814800 */  mtc1       $at, $ft2f
    /* 1F320 8001E720 44804000 */  mtc1       $zero, $ft2
    /* 1F324 8001E724 00000000 */  nop
    /* 1F328 8001E728 46280000 */  add.d      $fv0, $fv0, $ft2
  .L8001E72C:
    /* 1F32C 8001E72C 03E00008 */  jr         $ra
    /* 1F330 8001E730 00000000 */   nop
endlabel func_8001E688
    /* 1F334 8001E734 00000000 */  nop
    /* 1F338 8001E738 00000000 */  nop
    /* 1F33C 8001E73C 00000000 */  nop
