.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8001E9B0, 0xF0

glabel func_8001E9B0
    /* 1F5B0 8001E9B0 3C018005 */  lui        $at, %hi(D_80050A4C)
    /* 1F5B4 8001E9B4 AC200A4C */  sw         $zero, %lo(D_80050A4C)($at)
    /* 1F5B8 8001E9B8 3C018005 */  lui        $at, %hi(D_80050C50)
    /* 1F5BC 8001E9BC 3C088005 */  lui        $t0, %hi(D_80050A50)
    /* 1F5C0 8001E9C0 AC200C50 */  sw         $zero, %lo(D_80050C50)($at)
    /* 1F5C4 8001E9C4 25080A50 */  addiu      $t0, $t0, %lo(D_80050A50)
    /* 1F5C8 8001E9C8 3C018005 */  lui        $at, %hi(D_80050C54)
    /* 1F5CC 8001E9CC 3C048005 */  lui        $a0, %hi(D_80050A50)
    /* 1F5D0 8001E9D0 3C058005 */  lui        $a1, %hi(D_80050A60)
    /* 1F5D4 8001E9D4 3C068005 */  lui        $a2, %hi(D_80050A70)
    /* 1F5D8 8001E9D8 3C078005 */  lui        $a3, %hi(D_80050A80)
    /* 1F5DC 8001E9DC AC280C54 */  sw         $t0, %lo(D_80050C54)($at)
    /* 1F5E0 8001E9E0 00001025 */  or         $v0, $zero, $zero
    /* 1F5E4 8001E9E4 24E70A80 */  addiu      $a3, $a3, %lo(D_80050A80)
    /* 1F5E8 8001E9E8 24C60A70 */  addiu      $a2, $a2, %lo(D_80050A70)
    /* 1F5EC 8001E9EC 24A50A60 */  addiu      $a1, $a1, %lo(D_80050A60)
    /* 1F5F0 8001E9F0 24840A50 */  addiu      $a0, $a0, %lo(D_80050A50)
    /* 1F5F4 8001E9F4 00001825 */  or         $v1, $zero, $zero
    /* 1F5F8 8001E9F8 24090020 */  addiu      $t1, $zero, 0x20
  .L8001E9FC:
    /* 1F5FC 8001E9FC A8820004 */  swl        $v0, 0x4($a0)
    /* 1F600 8001EA00 10400005 */  beqz       $v0, .L8001EA18
    /* 1F604 8001EA04 B8820007 */   swr       $v0, 0x7($a0)
    /* 1F608 8001EA08 00037100 */  sll        $t6, $v1, 4
    /* 1F60C 8001EA0C 010E7821 */  addu       $t7, $t0, $t6
    /* 1F610 8001EA10 A84F0000 */  swl        $t7, 0x0($v0)
    /* 1F614 8001EA14 B84F0003 */  swr        $t7, 0x3($v0)
  .L8001EA18:
    /* 1F618 8001EA18 A8840014 */  swl        $a0, 0x14($a0)
    /* 1F61C 8001EA1C 10800006 */  beqz       $a0, .L8001EA38
    /* 1F620 8001EA20 B8840017 */   swr       $a0, 0x17($a0)
    /* 1F624 8001EA24 0003C100 */  sll        $t8, $v1, 4
    /* 1F628 8001EA28 0118C821 */  addu       $t9, $t0, $t8
    /* 1F62C 8001EA2C 272A0010 */  addiu      $t2, $t9, 0x10
    /* 1F630 8001EA30 A88A0000 */  swl        $t2, 0x0($a0)
    /* 1F634 8001EA34 B88A0003 */  swr        $t2, 0x3($a0)
  .L8001EA38:
    /* 1F638 8001EA38 A8850024 */  swl        $a1, 0x24($a0)
    /* 1F63C 8001EA3C 10A00006 */  beqz       $a1, .L8001EA58
    /* 1F640 8001EA40 B8850027 */   swr       $a1, 0x27($a0)
    /* 1F644 8001EA44 00035900 */  sll        $t3, $v1, 4
    /* 1F648 8001EA48 010B6021 */  addu       $t4, $t0, $t3
    /* 1F64C 8001EA4C 258D0020 */  addiu      $t5, $t4, 0x20
    /* 1F650 8001EA50 A8AD0000 */  swl        $t5, 0x0($a1)
    /* 1F654 8001EA54 B8AD0003 */  swr        $t5, 0x3($a1)
  .L8001EA58:
    /* 1F658 8001EA58 A8860034 */  swl        $a2, 0x34($a0)
    /* 1F65C 8001EA5C 10C00006 */  beqz       $a2, .L8001EA78
    /* 1F660 8001EA60 B8860037 */   swr       $a2, 0x37($a0)
    /* 1F664 8001EA64 00037100 */  sll        $t6, $v1, 4
    /* 1F668 8001EA68 010E7821 */  addu       $t7, $t0, $t6
    /* 1F66C 8001EA6C 25F80030 */  addiu      $t8, $t7, 0x30
    /* 1F670 8001EA70 A8D80000 */  swl        $t8, 0x0($a2)
    /* 1F674 8001EA74 B8D80003 */  swr        $t8, 0x3($a2)
  .L8001EA78:
    /* 1F678 8001EA78 00E01025 */  or         $v0, $a3, $zero
    /* 1F67C 8001EA7C 24630004 */  addiu      $v1, $v1, 0x4
    /* 1F680 8001EA80 24E70040 */  addiu      $a3, $a3, 0x40
    /* 1F684 8001EA84 24840040 */  addiu      $a0, $a0, 0x40
    /* 1F688 8001EA88 24A50040 */  addiu      $a1, $a1, 0x40
    /* 1F68C 8001EA8C 1469FFDB */  bne        $v1, $t1, .L8001E9FC
    /* 1F690 8001EA90 24C60040 */   addiu     $a2, $a2, 0x40
    /* 1F694 8001EA94 A8400000 */  swl        $zero, 0x0($v0)
    /* 1F698 8001EA98 03E00008 */  jr         $ra
    /* 1F69C 8001EA9C B8400003 */   swr       $zero, 0x3($v0)
endlabel func_8001E9B0

nonmatching func_8001EAA0, 0x4C

glabel func_8001EAA0
    /* 1F6A0 8001EAA0 3C038005 */  lui        $v1, %hi(D_80050C50)
    /* 1F6A4 8001EAA4 8C630C50 */  lw         $v1, %lo(D_80050C50)($v1)
    /* 1F6A8 8001EAA8 5060000E */  beql       $v1, $zero, .L8001EAE4
    /* 1F6AC 8001EAAC 00001025 */   or        $v0, $zero, $zero
    /* 1F6B0 8001EAB0 88620008 */  lwl        $v0, 0x8($v1)
  .L8001EAB4:
    /* 1F6B4 8001EAB4 9862000B */  lwr        $v0, 0xB($v1)
    /* 1F6B8 8001EAB8 14820003 */  bne        $a0, $v0, .L8001EAC8
    /* 1F6BC 8001EABC 0082082B */   sltu      $at, $a0, $v0
    /* 1F6C0 8001EAC0 03E00008 */  jr         $ra
    /* 1F6C4 8001EAC4 00601025 */   or        $v0, $v1, $zero
  .L8001EAC8:
    /* 1F6C8 8001EAC8 14200005 */  bnez       $at, .L8001EAE0
    /* 1F6CC 8001EACC 00600821 */   addu      $at, $v1, $zero
    /* 1F6D0 8001EAD0 88630000 */  lwl        $v1, 0x0($v1)
    /* 1F6D4 8001EAD4 98230003 */  lwr        $v1, 0x3($at)
    /* 1F6D8 8001EAD8 5460FFF6 */  bnel       $v1, $zero, .L8001EAB4
    /* 1F6DC 8001EADC 88620008 */   lwl       $v0, 0x8($v1)
  .L8001EAE0:
    /* 1F6E0 8001EAE0 00001025 */  or         $v0, $zero, $zero
  .L8001EAE4:
    /* 1F6E4 8001EAE4 03E00008 */  jr         $ra
    /* 1F6E8 8001EAE8 00000000 */   nop
endlabel func_8001EAA0

nonmatching func_8001EAEC, 0x24

glabel func_8001EAEC
    /* 1F6EC 8001EAEC 3C048005 */  lui        $a0, %hi(D_80050A4C)
    /* 1F6F0 8001EAF0 24840A4C */  addiu      $a0, $a0, %lo(D_80050A4C)
    /* 1F6F4 8001EAF4 2405FFFF */  addiu      $a1, $zero, -0x1
  .L8001EAF8:
    /* 1F6F8 8001EAF8 8C820000 */  lw         $v0, 0x0($a0)
    /* 1F6FC 8001EAFC 244E0001 */  addiu      $t6, $v0, 0x1
    /* 1F700 8001EB00 1045FFFD */  beq        $v0, $a1, .L8001EAF8
    /* 1F704 8001EB04 AC8E0000 */   sw        $t6, 0x0($a0)
    /* 1F708 8001EB08 03E00008 */  jr         $ra
    /* 1F70C 8001EB0C 00000000 */   nop
endlabel func_8001EAEC

nonmatching func_8001EB10, 0x1D0

glabel func_8001EB10
    /* 1F710 8001EB10 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1F714 8001EB14 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1F718 8001EB18 0C008611 */  jal        func_80021844
    /* 1F71C 8001EB1C AFA40018 */   sw        $a0, 0x18($sp)
    /* 1F720 8001EB20 8FA40018 */  lw         $a0, 0x18($sp)
    /* 1F724 8001EB24 2403FFFF */  addiu      $v1, $zero, -0x1
    /* 1F728 8001EB28 888E0060 */  lwl        $t6, 0x60($a0)
    /* 1F72C 8001EB2C 988E0063 */  lwr        $t6, 0x63($a0)
    /* 1F730 8001EB30 506E0068 */  beql       $v1, $t6, .L8001ECD4
    /* 1F734 8001EB34 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 1F738 8001EB38 88850014 */  lwl        $a1, 0x14($a0)
    /* 1F73C 8001EB3C 98850017 */  lwr        $a1, 0x17($a0)
    /* 1F740 8001EB40 240701A0 */  addiu      $a3, $zero, 0x1A0
    /* 1F744 8001EB44 10650016 */  beq        $v1, $a1, .L8001EBA0
    /* 1F748 8001EB48 30B800FF */   andi      $t8, $a1, 0xFF
    /* 1F74C 8001EB4C 03070019 */  multu      $t8, $a3
    /* 1F750 8001EB50 888F0010 */  lwl        $t7, 0x10($a0)
    /* 1F754 8001EB54 988F0013 */  lwr        $t7, 0x13($a0)
    /* 1F758 8001EB58 3C068005 */  lui        $a2, %hi(D_8004BEB8)
    /* 1F75C 8001EB5C 24C6BEB8 */  addiu      $a2, $a2, %lo(D_8004BEB8)
    /* 1F760 8001EB60 0000C812 */  mflo       $t9
    /* 1F764 8001EB64 00D94021 */  addu       $t0, $a2, $t9
    /* 1F768 8001EB68 A90F0010 */  swl        $t7, 0x10($t0)
    /* 1F76C 8001EB6C B90F0013 */  swr        $t7, 0x13($t0)
    /* 1F770 8001EB70 88820010 */  lwl        $v0, 0x10($a0)
    /* 1F774 8001EB74 98820013 */  lwr        $v0, 0x13($a0)
    /* 1F778 8001EB78 10620055 */  beq        $v1, $v0, .L8001ECD0
    /* 1F77C 8001EB7C 304A00FF */   andi      $t2, $v0, 0xFF
    /* 1F780 8001EB80 01470019 */  multu      $t2, $a3
    /* 1F784 8001EB84 88890014 */  lwl        $t1, 0x14($a0)
    /* 1F788 8001EB88 98890017 */  lwr        $t1, 0x17($a0)
    /* 1F78C 8001EB8C 00005812 */  mflo       $t3
    /* 1F790 8001EB90 00CB6021 */  addu       $t4, $a2, $t3
    /* 1F794 8001EB94 A9890014 */  swl        $t1, 0x14($t4)
    /* 1F798 8001EB98 1000004D */  b          .L8001ECD0
    /* 1F79C 8001EB9C B9890017 */   swr       $t1, 0x17($t4)
  .L8001EBA0:
    /* 1F7A0 8001EBA0 88820010 */  lwl        $v0, 0x10($a0)
    /* 1F7A4 8001EBA4 98820013 */  lwr        $v0, 0x13($a0)
    /* 1F7A8 8001EBA8 5062001C */  beql       $v1, $v0, .L8001EC1C
    /* 1F7AC 8001EBAC 88820018 */   lwl       $v0, 0x18($a0)
    /* 1F7B0 8001EBB0 888D0018 */  lwl        $t5, 0x18($a0)
    /* 1F7B4 8001EBB4 988D001B */  lwr        $t5, 0x1B($a0)
    /* 1F7B8 8001EBB8 240701A0 */  addiu      $a3, $zero, 0x1A0
    /* 1F7BC 8001EBBC 3C068005 */  lui        $a2, %hi(D_8004BEB8)
    /* 1F7C0 8001EBC0 A9A2000C */  swl        $v0, 0xC($t5)
    /* 1F7C4 8001EBC4 B9A2000F */  swr        $v0, 0xF($t5)
    /* 1F7C8 8001EBC8 888E0010 */  lwl        $t6, 0x10($a0)
    /* 1F7CC 8001EBCC 988E0013 */  lwr        $t6, 0x13($a0)
    /* 1F7D0 8001EBD0 24C6BEB8 */  addiu      $a2, $a2, %lo(D_8004BEB8)
    /* 1F7D4 8001EBD4 31D800FF */  andi       $t8, $t6, 0xFF
    /* 1F7D8 8001EBD8 03070019 */  multu      $t8, $a3
    /* 1F7DC 8001EBDC 0000C812 */  mflo       $t9
    /* 1F7E0 8001EBE0 00D97821 */  addu       $t7, $a2, $t9
    /* 1F7E4 8001EBE4 A9E30014 */  swl        $v1, 0x14($t7)
    /* 1F7E8 8001EBE8 B9E30017 */  swr        $v1, 0x17($t7)
    /* 1F7EC 8001EBEC 888A0010 */  lwl        $t2, 0x10($a0)
    /* 1F7F0 8001EBF0 988A0013 */  lwr        $t2, 0x13($a0)
    /* 1F7F4 8001EBF4 88880018 */  lwl        $t0, 0x18($a0)
    /* 1F7F8 8001EBF8 9888001B */  lwr        $t0, 0x1B($a0)
    /* 1F7FC 8001EBFC 314B00FF */  andi       $t3, $t2, 0xFF
    /* 1F800 8001EC00 01670019 */  multu      $t3, $a3
    /* 1F804 8001EC04 00004812 */  mflo       $t1
    /* 1F808 8001EC08 00C96021 */  addu       $t4, $a2, $t1
    /* 1F80C 8001EC0C A9880018 */  swl        $t0, 0x18($t4)
    /* 1F810 8001EC10 1000002F */  b          .L8001ECD0
    /* 1F814 8001EC14 B988001B */   swr       $t0, 0x1B($t4)
    /* 1F818 8001EC18 88820018 */  lwl        $v0, 0x18($a0)
  .L8001EC1C:
    /* 1F81C 8001EC1C 9882001B */  lwr        $v0, 0x1B($a0)
    /* 1F820 8001EC20 3C058005 */  lui        $a1, %hi(D_80050C54)
    /* 1F824 8001EC24 24A50C54 */  addiu      $a1, $a1, %lo(D_80050C54)
    /* 1F828 8001EC28 88430004 */  lwl        $v1, 0x4($v0)
    /* 1F82C 8001EC2C 98430007 */  lwr        $v1, 0x7($v0)
    /* 1F830 8001EC30 50600007 */  beql       $v1, $zero, .L8001EC50
    /* 1F834 8001EC34 884E0000 */   lwl       $t6, 0x0($v0)
    /* 1F838 8001EC38 884D0000 */  lwl        $t5, 0x0($v0)
    /* 1F83C 8001EC3C 984D0003 */  lwr        $t5, 0x3($v0)
    /* 1F840 8001EC40 A86D0000 */  swl        $t5, 0x0($v1)
    /* 1F844 8001EC44 10000005 */  b          .L8001EC5C
    /* 1F848 8001EC48 B86D0003 */   swr       $t5, 0x3($v1)
    /* 1F84C 8001EC4C 884E0000 */  lwl        $t6, 0x0($v0)
  .L8001EC50:
    /* 1F850 8001EC50 984E0003 */  lwr        $t6, 0x3($v0)
    /* 1F854 8001EC54 3C018005 */  lui        $at, %hi(D_80050C50)
    /* 1F858 8001EC58 AC2E0C50 */  sw         $t6, %lo(D_80050C50)($at)
  .L8001EC5C:
    /* 1F85C 8001EC5C 88820018 */  lwl        $v0, 0x18($a0)
    /* 1F860 8001EC60 9882001B */  lwr        $v0, 0x1B($a0)
    /* 1F864 8001EC64 88430000 */  lwl        $v1, 0x0($v0)
    /* 1F868 8001EC68 98430003 */  lwr        $v1, 0x3($v0)
    /* 1F86C 8001EC6C 50600008 */  beql       $v1, $zero, .L8001EC90
    /* 1F870 8001EC70 8CB90000 */   lw        $t9, 0x0($a1)
    /* 1F874 8001EC74 88580004 */  lwl        $t8, 0x4($v0)
    /* 1F878 8001EC78 98580007 */  lwr        $t8, 0x7($v0)
    /* 1F87C 8001EC7C A8780004 */  swl        $t8, 0x4($v1)
    /* 1F880 8001EC80 B8780007 */  swr        $t8, 0x7($v1)
    /* 1F884 8001EC84 88820018 */  lwl        $v0, 0x18($a0)
    /* 1F888 8001EC88 9882001B */  lwr        $v0, 0x1B($a0)
    /* 1F88C 8001EC8C 8CB90000 */  lw         $t9, 0x0($a1)
  .L8001EC90:
    /* 1F890 8001EC90 A8590000 */  swl        $t9, 0x0($v0)
    /* 1F894 8001EC94 B8590003 */  swr        $t9, 0x3($v0)
    /* 1F898 8001EC98 8CA30000 */  lw         $v1, 0x0($a1)
    /* 1F89C 8001EC9C 50600006 */  beql       $v1, $zero, .L8001ECB8
    /* 1F8A0 8001ECA0 888A0018 */   lwl       $t2, 0x18($a0)
    /* 1F8A4 8001ECA4 888F0018 */  lwl        $t7, 0x18($a0)
    /* 1F8A8 8001ECA8 988F001B */  lwr        $t7, 0x1B($a0)
    /* 1F8AC 8001ECAC A86F0004 */  swl        $t7, 0x4($v1)
    /* 1F8B0 8001ECB0 B86F0007 */  swr        $t7, 0x7($v1)
    /* 1F8B4 8001ECB4 888A0018 */  lwl        $t2, 0x18($a0)
  .L8001ECB8:
    /* 1F8B8 8001ECB8 988A001B */  lwr        $t2, 0x1B($a0)
    /* 1F8BC 8001ECBC A9400004 */  swl        $zero, 0x4($t2)
    /* 1F8C0 8001ECC0 B9400007 */  swr        $zero, 0x7($t2)
    /* 1F8C4 8001ECC4 888B0018 */  lwl        $t3, 0x18($a0)
    /* 1F8C8 8001ECC8 988B001B */  lwr        $t3, 0x1B($a0)
    /* 1F8CC 8001ECCC ACAB0000 */  sw         $t3, 0x0($a1)
  .L8001ECD0:
    /* 1F8D0 8001ECD0 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8001ECD4:
    /* 1F8D4 8001ECD4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1F8D8 8001ECD8 03E00008 */  jr         $ra
    /* 1F8DC 8001ECDC 00000000 */   nop
endlabel func_8001EB10

nonmatching func_8001ECE0, 0x114

glabel func_8001ECE0
    /* 1F8E0 8001ECE0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 1F8E4 8001ECE4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1F8E8 8001ECE8 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1F8EC 8001ECEC 0C007ABB */  jal        func_8001EAEC
    /* 1F8F0 8001ECF0 AFA40020 */   sw        $a0, 0x20($sp)
    /* 1F8F4 8001ECF4 3C108005 */  lui        $s0, %hi(D_80050C50)
    /* 1F8F8 8001ECF8 8E100C50 */  lw         $s0, %lo(D_80050C50)($s0)
    /* 1F8FC 8001ECFC 00402825 */  or         $a1, $v0, $zero
    /* 1F900 8001ED00 00002025 */  or         $a0, $zero, $zero
    /* 1F904 8001ED04 12000011 */  beqz       $s0, .L8001ED4C
    /* 1F908 8001ED08 00000000 */   nop
    /* 1F90C 8001ED0C 8A030008 */  lwl        $v1, 0x8($s0)
  .L8001ED10:
    /* 1F910 8001ED10 9A03000B */  lwr        $v1, 0xB($s0)
    /* 1F914 8001ED14 0043082B */  sltu       $at, $v0, $v1
    /* 1F918 8001ED18 1420000C */  bnez       $at, .L8001ED4C
    /* 1F91C 8001ED1C 00000000 */   nop
    /* 1F920 8001ED20 54430005 */  bnel       $v0, $v1, .L8001ED38
    /* 1F924 8001ED24 02000821 */   addu      $at, $s0, $zero
    /* 1F928 8001ED28 0C007ABB */  jal        func_8001EAEC
    /* 1F92C 8001ED2C 00000000 */   nop
    /* 1F930 8001ED30 00402825 */  or         $a1, $v0, $zero
    /* 1F934 8001ED34 02000821 */  addu       $at, $s0, $zero
  .L8001ED38:
    /* 1F938 8001ED38 02002025 */  or         $a0, $s0, $zero
    /* 1F93C 8001ED3C 8A100000 */  lwl        $s0, 0x0($s0)
    /* 1F940 8001ED40 98300003 */  lwr        $s0, 0x3($at)
    /* 1F944 8001ED44 5600FFF2 */  bnel       $s0, $zero, .L8001ED10
    /* 1F948 8001ED48 8A030008 */   lwl       $v1, 0x8($s0)
  .L8001ED4C:
    /* 1F94C 8001ED4C 3C068005 */  lui        $a2, %hi(D_80050C54)
    /* 1F950 8001ED50 24C60C54 */  addiu      $a2, $a2, %lo(D_80050C54)
    /* 1F954 8001ED54 8CC20000 */  lw         $v0, 0x0($a2)
    /* 1F958 8001ED58 14400003 */  bnez       $v0, .L8001ED68
    /* 1F95C 8001ED5C 00401825 */   or        $v1, $v0, $zero
    /* 1F960 8001ED60 1000001F */  b          .L8001EDE0
    /* 1F964 8001ED64 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001ED68:
    /* 1F968 8001ED68 884E0000 */  lwl        $t6, 0x0($v0)
    /* 1F96C 8001ED6C 984E0003 */  lwr        $t6, 0x3($v0)
    /* 1F970 8001ED70 3C018005 */  lui        $at, %hi(D_80050C50)
    /* 1F974 8001ED74 11C00003 */  beqz       $t6, .L8001ED84
    /* 1F978 8001ED78 ACCE0000 */   sw        $t6, 0x0($a2)
    /* 1F97C 8001ED7C A9C00004 */  swl        $zero, 0x4($t6)
    /* 1F980 8001ED80 B9C00007 */  swr        $zero, 0x7($t6)
  .L8001ED84:
    /* 1F984 8001ED84 54800004 */  bnel       $a0, $zero, .L8001ED98
    /* 1F988 8001ED88 A8830000 */   swl       $v1, 0x0($a0)
    /* 1F98C 8001ED8C 10000003 */  b          .L8001ED9C
    /* 1F990 8001ED90 AC230C50 */   sw        $v1, %lo(D_80050C50)($at)
    /* 1F994 8001ED94 A8830000 */  swl        $v1, 0x0($a0)
  .L8001ED98:
    /* 1F998 8001ED98 B8830003 */  swr        $v1, 0x3($a0)
  .L8001ED9C:
    /* 1F99C 8001ED9C A8640004 */  swl        $a0, 0x4($v1)
    /* 1F9A0 8001EDA0 A8700000 */  swl        $s0, 0x0($v1)
    /* 1F9A4 8001EDA4 B8640007 */  swr        $a0, 0x7($v1)
    /* 1F9A8 8001EDA8 12000003 */  beqz       $s0, .L8001EDB8
    /* 1F9AC 8001EDAC B8700003 */   swr       $s0, 0x3($v1)
    /* 1F9B0 8001EDB0 AA030004 */  swl        $v1, 0x4($s0)
    /* 1F9B4 8001EDB4 BA030007 */  swr        $v1, 0x7($s0)
  .L8001EDB8:
    /* 1F9B8 8001EDB8 8FA40020 */  lw         $a0, 0x20($sp)
    /* 1F9BC 8001EDBC A8650008 */  swl        $a1, 0x8($v1)
    /* 1F9C0 8001EDC0 B865000B */  swr        $a1, 0xB($v1)
    /* 1F9C4 8001EDC4 888F0060 */  lwl        $t7, 0x60($a0)
    /* 1F9C8 8001EDC8 988F0063 */  lwr        $t7, 0x63($a0)
    /* 1F9CC 8001EDCC 00A01025 */  or         $v0, $a1, $zero
    /* 1F9D0 8001EDD0 A86F000C */  swl        $t7, 0xC($v1)
    /* 1F9D4 8001EDD4 B86F000F */  swr        $t7, 0xF($v1)
    /* 1F9D8 8001EDD8 A8830018 */  swl        $v1, 0x18($a0)
    /* 1F9DC 8001EDDC B883001B */  swr        $v1, 0x1B($a0)
  .L8001EDE0:
    /* 1F9E0 8001EDE0 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1F9E4 8001EDE4 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1F9E8 8001EDE8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 1F9EC 8001EDEC 03E00008 */  jr         $ra
    /* 1F9F0 8001EDF0 00000000 */   nop
endlabel func_8001ECE0

nonmatching func_8001EDF4, 0x40

glabel func_8001EDF4
    /* 1F9F4 8001EDF4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1F9F8 8001EDF8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1F9FC 8001EDFC 10810008 */  beq        $a0, $at, .L8001EE20
    /* 1FA00 8001EE00 AFBF0014 */   sw        $ra, 0x14($sp)
    /* 1FA04 8001EE04 0C007AA8 */  jal        func_8001EAA0
    /* 1FA08 8001EE08 00000000 */   nop
    /* 1FA0C 8001EE0C 10400004 */  beqz       $v0, .L8001EE20
    /* 1FA10 8001EE10 00401825 */   or        $v1, $v0, $zero
    /* 1FA14 8001EE14 8842000C */  lwl        $v0, 0xC($v0)
    /* 1FA18 8001EE18 10000002 */  b          .L8001EE24
    /* 1FA1C 8001EE1C 9862000F */   lwr       $v0, 0xF($v1)
  .L8001EE20:
    /* 1FA20 8001EE20 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8001EE24:
    /* 1FA24 8001EE24 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1FA28 8001EE28 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1FA2C 8001EE2C 03E00008 */  jr         $ra
    /* 1FA30 8001EE30 00000000 */   nop
endlabel func_8001EDF4

nonmatching func_8001EE34, 0x68

glabel func_8001EE34
    /* 1FA34 8001EE34 3C038005 */  lui        $v1, %hi(D_8004FA18)
    /* 1FA38 8001EE38 9063FA18 */  lbu        $v1, %lo(D_8004FA18)($v1)
    /* 1FA3C 8001EE3C 00001025 */  or         $v0, $zero, $zero
    /* 1FA40 8001EE40 3C048005 */  lui        $a0, %hi(D_800504C8)
    /* 1FA44 8001EE44 10600007 */  beqz       $v1, .L8001EE64
    /* 1FA48 8001EE48 340EFFFF */   ori       $t6, $zero, 0xFFFF
    /* 1FA4C 8001EE4C 248404C8 */  addiu      $a0, $a0, %lo(D_800504C8)
  .L8001EE50:
    /* 1FA50 8001EE50 24420001 */  addiu      $v0, $v0, 0x1
    /* 1FA54 8001EE54 0043082B */  sltu       $at, $v0, $v1
    /* 1FA58 8001EE58 24840004 */  addiu      $a0, $a0, 0x4
    /* 1FA5C 8001EE5C 1420FFFC */  bnez       $at, .L8001EE50
    /* 1FA60 8001EE60 A480FFFE */   sh        $zero, -0x2($a0)
  .L8001EE64:
    /* 1FA64 8001EE64 3C028005 */  lui        $v0, %hi(D_80050548)
    /* 1FA68 8001EE68 3C048005 */  lui        $a0, %hi(D_80050648)
    /* 1FA6C 8001EE6C 24840648 */  addiu      $a0, $a0, %lo(D_80050648)
    /* 1FA70 8001EE70 24420548 */  addiu      $v0, $v0, %lo(D_80050548)
    /* 1FA74 8001EE74 240300FF */  addiu      $v1, $zero, 0xFF
  .L8001EE78:
    /* 1FA78 8001EE78 24420004 */  addiu      $v0, $v0, 0x4
    /* 1FA7C 8001EE7C A043FFFD */  sb         $v1, -0x3($v0)
    /* 1FA80 8001EE80 A043FFFE */  sb         $v1, -0x2($v0)
    /* 1FA84 8001EE84 A043FFFF */  sb         $v1, -0x1($v0)
    /* 1FA88 8001EE88 1444FFFB */  bne        $v0, $a0, .L8001EE78
    /* 1FA8C 8001EE8C A043FFFC */   sb        $v1, -0x4($v0)
    /* 1FA90 8001EE90 3C018005 */  lui        $at, %hi(D_80050A48)
    /* 1FA94 8001EE94 03E00008 */  jr         $ra
    /* 1FA98 8001EE98 A42E0A48 */   sh        $t6, %lo(D_80050A48)($at)
endlabel func_8001EE34

nonmatching func_8001EE9C, 0xF0

glabel func_8001EE9C
    /* 1FA9C 8001EE9C 888E0060 */  lwl        $t6, 0x60($a0)
    /* 1FAA0 8001EEA0 988E0063 */  lwr        $t6, 0x63($a0)
    /* 1FAA4 8001EEA4 3C058005 */  lui        $a1, %hi(D_800504C8)
    /* 1FAA8 8001EEA8 24A504C8 */  addiu      $a1, $a1, %lo(D_800504C8)
    /* 1FAAC 8001EEAC 31CF00FF */  andi       $t7, $t6, 0xFF
    /* 1FAB0 8001EEB0 000FC080 */  sll        $t8, $t7, 2
    /* 1FAB4 8001EEB4 00B81021 */  addu       $v0, $a1, $t8
    /* 1FAB8 8001EEB8 94590002 */  lhu        $t9, 0x2($v0)
    /* 1FABC 8001EEBC 24010001 */  addiu      $at, $zero, 0x1
    /* 1FAC0 8001EEC0 17210030 */  bne        $t9, $at, .L8001EF84
    /* 1FAC4 8001EEC4 00000000 */   nop
    /* 1FAC8 8001EEC8 90430000 */  lbu        $v1, 0x0($v0)
    /* 1FACC 8001EECC 240600FF */  addiu      $a2, $zero, 0xFF
    /* 1FAD0 8001EED0 10C30005 */  beq        $a2, $v1, .L8001EEE8
    /* 1FAD4 8001EED4 00034880 */   sll       $t1, $v1, 2
    /* 1FAD8 8001EED8 90480001 */  lbu        $t0, 0x1($v0)
    /* 1FADC 8001EEDC 00A95021 */  addu       $t2, $a1, $t1
    /* 1FAE0 8001EEE0 10000006 */  b          .L8001EEFC
    /* 1FAE4 8001EEE4 A1480001 */   sb        $t0, 0x1($t2)
  .L8001EEE8:
    /* 1FAE8 8001EEE8 908C002E */  lbu        $t4, 0x2E($a0)
    /* 1FAEC 8001EEEC 904B0001 */  lbu        $t3, 0x1($v0)
    /* 1FAF0 8001EEF0 3C018005 */  lui        $at, %hi(D_80050548)
    /* 1FAF4 8001EEF4 002C0821 */  addu       $at, $at, $t4
    /* 1FAF8 8001EEF8 A02B0548 */  sb         $t3, %lo(D_80050548)($at)
  .L8001EEFC:
    /* 1FAFC 8001EEFC 90430001 */  lbu        $v1, 0x1($v0)
    /* 1FB00 8001EF00 10C30005 */  beq        $a2, $v1, .L8001EF18
    /* 1FB04 8001EF04 00037080 */   sll       $t6, $v1, 2
    /* 1FB08 8001EF08 904D0000 */  lbu        $t5, 0x0($v0)
    /* 1FB0C 8001EF0C 00AE7821 */  addu       $t7, $a1, $t6
    /* 1FB10 8001EF10 1000001B */  b          .L8001EF80
    /* 1FB14 8001EF14 A1ED0000 */   sb        $t5, 0x0($t7)
  .L8001EF18:
    /* 1FB18 8001EF18 90580000 */  lbu        $t8, 0x0($v0)
    /* 1FB1C 8001EF1C 54D80019 */  bnel       $a2, $t8, .L8001EF84
    /* 1FB20 8001EF20 A4400002 */   sh        $zero, 0x2($v0)
    /* 1FB24 8001EF24 9099002E */  lbu        $t9, 0x2E($a0)
    /* 1FB28 8001EF28 3C068005 */  lui        $a2, %hi(D_80050648)
    /* 1FB2C 8001EF2C 24C60648 */  addiu      $a2, $a2, %lo(D_80050648)
    /* 1FB30 8001EF30 00194880 */  sll        $t1, $t9, 2
    /* 1FB34 8001EF34 00C91821 */  addu       $v1, $a2, $t1
    /* 1FB38 8001EF38 94650002 */  lhu        $a1, 0x2($v1)
    /* 1FB3C 8001EF3C 3407FFFF */  ori        $a3, $zero, 0xFFFF
    /* 1FB40 8001EF40 10E50005 */  beq        $a3, $a1, .L8001EF58
    /* 1FB44 8001EF44 00055080 */   sll       $t2, $a1, 2
    /* 1FB48 8001EF48 94680000 */  lhu        $t0, 0x0($v1)
    /* 1FB4C 8001EF4C 00CA5821 */  addu       $t3, $a2, $t2
    /* 1FB50 8001EF50 10000004 */  b          .L8001EF64
    /* 1FB54 8001EF54 A5680000 */   sh        $t0, 0x0($t3)
  .L8001EF58:
    /* 1FB58 8001EF58 946C0000 */  lhu        $t4, 0x0($v1)
    /* 1FB5C 8001EF5C 3C018005 */  lui        $at, %hi(D_80050A48)
    /* 1FB60 8001EF60 A42C0A48 */  sh         $t4, %lo(D_80050A48)($at)
  .L8001EF64:
    /* 1FB64 8001EF64 94640000 */  lhu        $a0, 0x0($v1)
    /* 1FB68 8001EF68 50E40006 */  beql       $a3, $a0, .L8001EF84
    /* 1FB6C 8001EF6C A4400002 */   sh        $zero, 0x2($v0)
    /* 1FB70 8001EF70 946E0002 */  lhu        $t6, 0x2($v1)
    /* 1FB74 8001EF74 00046880 */  sll        $t5, $a0, 2
    /* 1FB78 8001EF78 00CD7821 */  addu       $t7, $a2, $t5
    /* 1FB7C 8001EF7C A5EE0002 */  sh         $t6, 0x2($t7)
  .L8001EF80:
    /* 1FB80 8001EF80 A4400002 */  sh         $zero, 0x2($v0)
  .L8001EF84:
    /* 1FB84 8001EF84 03E00008 */  jr         $ra
    /* 1FB88 8001EF88 00000000 */   nop
endlabel func_8001EE9C

nonmatching func_8001EF8C, 0x1B0

glabel func_8001EF8C
    /* 1FB8C 8001EF8C 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 1FB90 8001EF90 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1FB94 8001EF94 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1FB98 8001EF98 AFA40030 */  sw         $a0, 0x30($sp)
    /* 1FB9C 8001EF9C AFA50034 */  sw         $a1, 0x34($sp)
    /* 1FBA0 8001EFA0 88890060 */  lwl        $t1, 0x60($a0)
    /* 1FBA4 8001EFA4 98890063 */  lwr        $t1, 0x63($a0)
    /* 1FBA8 8001EFA8 3C188005 */  lui        $t8, %hi(D_800504C8)
    /* 1FBAC 8001EFAC 271804C8 */  addiu      $t8, $t8, %lo(D_800504C8)
    /* 1FBB0 8001EFB0 312900FF */  andi       $t1, $t1, 0xFF
    /* 1FBB4 8001EFB4 00097880 */  sll        $t7, $t1, 2
    /* 1FBB8 8001EFB8 01F81821 */  addu       $v1, $t7, $t8
    /* 1FBBC 8001EFBC 94790002 */  lhu        $t9, 0x2($v1)
    /* 1FBC0 8001EFC0 24010001 */  addiu      $at, $zero, 0x1
    /* 1FBC4 8001EFC4 30B000FF */  andi       $s0, $a1, 0xFF
    /* 1FBC8 8001EFC8 17210009 */  bne        $t9, $at, .L8001EFF0
    /* 1FBCC 8001EFCC 00000000 */   nop
    /* 1FBD0 8001EFD0 908A002E */  lbu        $t2, 0x2E($a0)
    /* 1FBD4 8001EFD4 520A0055 */  beql       $s0, $t2, .L8001F12C
    /* 1FBD8 8001EFD8 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1FBDC 8001EFDC AFA30020 */  sw         $v1, 0x20($sp)
    /* 1FBE0 8001EFE0 0C007BA7 */  jal        func_8001EE9C
    /* 1FBE4 8001EFE4 A3A90027 */   sb        $t1, 0x27($sp)
    /* 1FBE8 8001EFE8 8FA30020 */  lw         $v1, 0x20($sp)
    /* 1FBEC 8001EFEC 93A90027 */  lbu        $t1, 0x27($sp)
  .L8001EFF0:
    /* 1FBF0 8001EFF0 3C0D8005 */  lui        $t5, %hi(D_80050548)
    /* 1FBF4 8001EFF4 240B0001 */  addiu      $t3, $zero, 0x1
    /* 1FBF8 8001EFF8 240C00FF */  addiu      $t4, $zero, 0xFF
    /* 1FBFC 8001EFFC 25AD0548 */  addiu      $t5, $t5, %lo(D_80050548)
    /* 1FC00 8001F000 A46B0002 */  sh         $t3, 0x2($v1)
    /* 1FC04 8001F004 A06C0000 */  sb         $t4, 0x0($v1)
    /* 1FC08 8001F008 020D4021 */  addu       $t0, $s0, $t5
    /* 1FC0C 8001F00C 91020000 */  lbu        $v0, 0x0($t0)
    /* 1FC10 8001F010 240100FF */  addiu      $at, $zero, 0xFF
    /* 1FC14 8001F014 10410007 */  beq        $v0, $at, .L8001F034
    /* 1FC18 8001F018 A0620001 */   sb        $v0, 0x1($v1)
    /* 1FC1C 8001F01C 910F0000 */  lbu        $t7, 0x0($t0)
    /* 1FC20 8001F020 3C018005 */  lui        $at, %hi(D_800504C8)
    /* 1FC24 8001F024 000FC080 */  sll        $t8, $t7, 2
    /* 1FC28 8001F028 00380821 */  addu       $at, $at, $t8
    /* 1FC2C 8001F02C 1000003B */  b          .L8001F11C
    /* 1FC30 8001F030 A02904C8 */   sb        $t1, %lo(D_800504C8)($at)
  .L8001F034:
    /* 1FC34 8001F034 3C038005 */  lui        $v1, %hi(D_80050A48)
    /* 1FC38 8001F038 24630A48 */  addiu      $v1, $v1, %lo(D_80050A48)
    /* 1FC3C 8001F03C 94670000 */  lhu        $a3, 0x0($v1)
    /* 1FC40 8001F040 3406FFFF */  ori        $a2, $zero, 0xFFFF
    /* 1FC44 8001F044 3404FFFF */  ori        $a0, $zero, 0xFFFF
    /* 1FC48 8001F048 10C7002E */  beq        $a2, $a3, .L8001F104
    /* 1FC4C 8001F04C 3C058005 */   lui       $a1, %hi(D_80050648)
    /* 1FC50 8001F050 0207082A */  slt        $at, $s0, $a3
    /* 1FC54 8001F054 1420001F */  bnez       $at, .L8001F0D4
    /* 1FC58 8001F058 02002025 */   or        $a0, $s0, $zero
    /* 1FC5C 8001F05C 30E3FFFF */  andi       $v1, $a3, 0xFFFF
    /* 1FC60 8001F060 10C3000B */  beq        $a2, $v1, .L8001F090
    /* 1FC64 8001F064 00601025 */   or        $v0, $v1, $zero
    /* 1FC68 8001F068 3C058005 */  lui        $a1, %hi(D_80050648)
    /* 1FC6C 8001F06C 24A50648 */  addiu      $a1, $a1, %lo(D_80050648)
  .L8001F070:
    /* 1FC70 8001F070 0082082A */  slt        $at, $a0, $v0
    /* 1FC74 8001F074 14200006 */  bnez       $at, .L8001F090
    /* 1FC78 8001F078 0003C880 */   sll       $t9, $v1, 2
    /* 1FC7C 8001F07C 00B97021 */  addu       $t6, $a1, $t9
    /* 1FC80 8001F080 A7A3002C */  sh         $v1, 0x2C($sp)
    /* 1FC84 8001F084 95C30000 */  lhu        $v1, 0x0($t6)
    /* 1FC88 8001F088 14C3FFF9 */  bne        $a2, $v1, .L8001F070
    /* 1FC8C 8001F08C 00601025 */   or        $v0, $v1, $zero
  .L8001F090:
    /* 1FC90 8001F090 97AA002C */  lhu        $t2, 0x2C($sp)
    /* 1FC94 8001F094 3C058005 */  lui        $a1, %hi(D_80050648)
    /* 1FC98 8001F098 24A50648 */  addiu      $a1, $a1, %lo(D_80050648)
    /* 1FC9C 8001F09C 000A5880 */  sll        $t3, $t2, 2
    /* 1FCA0 8001F0A0 00AB6021 */  addu       $t4, $a1, $t3
    /* 1FCA4 8001F0A4 A5900000 */  sh         $s0, 0x0($t4)
    /* 1FCA8 8001F0A8 97AF002C */  lhu        $t7, 0x2C($sp)
    /* 1FCAC 8001F0AC 00106880 */  sll        $t5, $s0, 2
    /* 1FCB0 8001F0B0 00AD1021 */  addu       $v0, $a1, $t5
    /* 1FCB4 8001F0B4 3078FFFF */  andi       $t8, $v1, 0xFFFF
    /* 1FCB8 8001F0B8 A4430000 */  sh         $v1, 0x0($v0)
    /* 1FCBC 8001F0BC 10D80017 */  beq        $a2, $t8, .L8001F11C
    /* 1FCC0 8001F0C0 A44F0002 */   sh        $t7, 0x2($v0)
    /* 1FCC4 8001F0C4 0003C880 */  sll        $t9, $v1, 2
    /* 1FCC8 8001F0C8 00B97021 */  addu       $t6, $a1, $t9
    /* 1FCCC 8001F0CC 10000013 */  b          .L8001F11C
    /* 1FCD0 8001F0D0 A5D00002 */   sh        $s0, 0x2($t6)
  .L8001F0D4:
    /* 1FCD4 8001F0D4 3C058005 */  lui        $a1, %hi(D_80050648)
    /* 1FCD8 8001F0D8 24A50648 */  addiu      $a1, $a1, %lo(D_80050648)
    /* 1FCDC 8001F0DC 00105080 */  sll        $t2, $s0, 2
    /* 1FCE0 8001F0E0 00AA1021 */  addu       $v0, $a1, $t2
    /* 1FCE4 8001F0E4 3404FFFF */  ori        $a0, $zero, 0xFFFF
    /* 1FCE8 8001F0E8 00075880 */  sll        $t3, $a3, 2
    /* 1FCEC 8001F0EC A4470000 */  sh         $a3, 0x0($v0)
    /* 1FCF0 8001F0F0 A4440002 */  sh         $a0, 0x2($v0)
    /* 1FCF4 8001F0F4 00AB6021 */  addu       $t4, $a1, $t3
    /* 1FCF8 8001F0F8 A5900002 */  sh         $s0, 0x2($t4)
    /* 1FCFC 8001F0FC 10000007 */  b          .L8001F11C
    /* 1FD00 8001F100 A4700000 */   sh        $s0, 0x0($v1)
  .L8001F104:
    /* 1FD04 8001F104 24A50648 */  addiu      $a1, $a1, %lo(D_80050648)
    /* 1FD08 8001F108 00106880 */  sll        $t5, $s0, 2
    /* 1FD0C 8001F10C 00AD1021 */  addu       $v0, $a1, $t5
    /* 1FD10 8001F110 A4440000 */  sh         $a0, 0x0($v0)
    /* 1FD14 8001F114 A4440002 */  sh         $a0, 0x2($v0)
    /* 1FD18 8001F118 A4700000 */  sh         $s0, 0x0($v1)
  .L8001F11C:
    /* 1FD1C 8001F11C 8FAF0030 */  lw         $t7, 0x30($sp)
    /* 1FD20 8001F120 A1090000 */  sb         $t1, 0x0($t0)
    /* 1FD24 8001F124 A1F0002E */  sb         $s0, 0x2E($t7)
    /* 1FD28 8001F128 8FBF001C */  lw         $ra, 0x1C($sp)
  .L8001F12C:
    /* 1FD2C 8001F12C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1FD30 8001F130 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 1FD34 8001F134 03E00008 */  jr         $ra
    /* 1FD38 8001F138 00000000 */   nop
endlabel func_8001EF8C

nonmatching func_8001F13C, 0x5B0

glabel func_8001F13C
    /* 1FD3C 8001F13C 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1FD40 8001F140 3C0E8005 */  lui        $t6, %hi(D_8004BE94)
    /* 1FD44 8001F144 AFB40014 */  sw         $s4, 0x14($sp)
    /* 1FD48 8001F148 AFB30010 */  sw         $s3, 0x10($sp)
    /* 1FD4C 8001F14C AFB2000C */  sw         $s2, 0xC($sp)
    /* 1FD50 8001F150 AFB10008 */  sw         $s1, 0x8($sp)
    /* 1FD54 8001F154 AFB00004 */  sw         $s0, 0x4($sp)
    /* 1FD58 8001F158 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1FD5C 8001F15C AFA5003C */  sw         $a1, 0x3C($sp)
    /* 1FD60 8001F160 AFA60040 */  sw         $a2, 0x40($sp)
    /* 1FD64 8001F164 AFA70044 */  sw         $a3, 0x44($sp)
    /* 1FD68 8001F168 25CEBE94 */  addiu      $t6, $t6, %lo(D_8004BE94)
    /* 1FD6C 8001F16C 91CF0000 */  lbu        $t7, 0x0($t6)
    /* 1FD70 8001F170 30A500FF */  andi       $a1, $a1, 0xFF
    /* 1FD74 8001F174 30D0FFFF */  andi       $s0, $a2, 0xFFFF
    /* 1FD78 8001F178 15E00154 */  bnez       $t7, .L8001F6CC
    /* 1FD7C 8001F17C 30F100FF */   andi      $s1, $a3, 0xFF
    /* 1FD80 8001F180 12200021 */  beqz       $s1, .L8001F208
    /* 1FD84 8001F184 3C028005 */   lui       $v0, %hi(D_8004FA19)
    /* 1FD88 8001F188 3C028005 */  lui        $v0, %hi(D_8004FA1A)
    /* 1FD8C 8001F18C 3C188005 */  lui        $t8, %hi(D_800504C2)
    /* 1FD90 8001F190 931804C2 */  lbu        $t8, %lo(D_800504C2)($t8)
    /* 1FD94 8001F194 9042FA1A */  lbu        $v0, %lo(D_8004FA1A)($v0)
    /* 1FD98 8001F198 3C198005 */  lui        $t9, %hi(D_8004FA18)
    /* 1FD9C 8001F19C 00005025 */  or         $t2, $zero, $zero
    /* 1FDA0 8001F1A0 0302082A */  slt        $at, $t8, $v0
    /* 1FDA4 8001F1A4 14200007 */  bnez       $at, .L8001F1C4
    /* 1FDA8 8001F1A8 2404FFFF */   addiu     $a0, $zero, -0x1
    /* 1FDAC 8001F1AC 9339FA18 */  lbu        $t9, %lo(D_8004FA18)($t9)
    /* 1FDB0 8001F1B0 0059082A */  slt        $at, $v0, $t9
    /* 1FDB4 8001F1B4 10200003 */  beqz       $at, .L8001F1C4
    /* 1FDB8 8001F1B8 00000000 */   nop
    /* 1FDBC 8001F1BC 10000001 */  b          .L8001F1C4
    /* 1FDC0 8001F1C0 240A0001 */   addiu     $t2, $zero, 0x1
  .L8001F1C4:
    /* 1FDC4 8001F1C4 00A2082A */  slt        $at, $a1, $v0
    /* 1FDC8 8001F1C8 1420002E */  bnez       $at, .L8001F284
    /* 1FDCC 8001F1CC AFA5001C */   sw        $a1, 0x1C($sp)
    /* 1FDD0 8001F1D0 3C138005 */  lui        $s3, %hi(D_80050648)
    /* 1FDD4 8001F1D4 3C128005 */  lui        $s2, %hi(D_80050548)
    /* 1FDD8 8001F1D8 3C078005 */  lui        $a3, %hi(D_800504C8)
    /* 1FDDC 8001F1DC 3C058005 */  lui        $a1, %hi(D_8004BEB8)
    /* 1FDE0 8001F1E0 24A5BEB8 */  addiu      $a1, $a1, %lo(D_8004BEB8)
    /* 1FDE4 8001F1E4 24E704C8 */  addiu      $a3, $a3, %lo(D_800504C8)
    /* 1FDE8 8001F1E8 26520548 */  addiu      $s2, $s2, %lo(D_80050548)
    /* 1FDEC 8001F1EC 26730648 */  addiu      $s3, $s3, %lo(D_80050648)
    /* 1FDF0 8001F1F0 93AC003B */  lbu        $t4, 0x3B($sp)
    /* 1FDF4 8001F1F4 340DFFFF */  ori        $t5, $zero, 0xFFFF
    /* 1FDF8 8001F1F8 2409FFFF */  addiu      $t1, $zero, -0x1
    /* 1FDFC 8001F1FC 240800FF */  addiu      $t0, $zero, 0xFF
    /* 1FE00 8001F200 100000A2 */  b          .L8001F48C
    /* 1FE04 8001F204 240601A0 */   addiu     $a2, $zero, 0x1A0
  .L8001F208:
    /* 1FE08 8001F208 3C0F8005 */  lui        $t7, %hi(D_800504C3)
    /* 1FE0C 8001F20C 91EF04C3 */  lbu        $t7, %lo(D_800504C3)($t7)
    /* 1FE10 8001F210 9042FA19 */  lbu        $v0, %lo(D_8004FA19)($v0)
    /* 1FE14 8001F214 3C188005 */  lui        $t8, %hi(D_8004FA18)
    /* 1FE18 8001F218 00005025 */  or         $t2, $zero, $zero
    /* 1FE1C 8001F21C 01E2082A */  slt        $at, $t7, $v0
    /* 1FE20 8001F220 14200007 */  bnez       $at, .L8001F240
    /* 1FE24 8001F224 2404FFFF */   addiu     $a0, $zero, -0x1
    /* 1FE28 8001F228 9318FA18 */  lbu        $t8, %lo(D_8004FA18)($t8)
    /* 1FE2C 8001F22C 0058082A */  slt        $at, $v0, $t8
    /* 1FE30 8001F230 10200003 */  beqz       $at, .L8001F240
    /* 1FE34 8001F234 00000000 */   nop
    /* 1FE38 8001F238 10000001 */  b          .L8001F240
    /* 1FE3C 8001F23C 240A0001 */   addiu     $t2, $zero, 0x1
  .L8001F240:
    /* 1FE40 8001F240 00A2082A */  slt        $at, $a1, $v0
    /* 1FE44 8001F244 1420000F */  bnez       $at, .L8001F284
    /* 1FE48 8001F248 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 1FE4C 8001F24C 3C138005 */  lui        $s3, %hi(D_80050648)
    /* 1FE50 8001F250 3C128005 */  lui        $s2, %hi(D_80050548)
    /* 1FE54 8001F254 3C078005 */  lui        $a3, %hi(D_800504C8)
    /* 1FE58 8001F258 3C058005 */  lui        $a1, %hi(D_8004BEB8)
    /* 1FE5C 8001F25C 24A5BEB8 */  addiu      $a1, $a1, %lo(D_8004BEB8)
    /* 1FE60 8001F260 24E704C8 */  addiu      $a3, $a3, %lo(D_800504C8)
    /* 1FE64 8001F264 26520548 */  addiu      $s2, $s2, %lo(D_80050548)
    /* 1FE68 8001F268 26730648 */  addiu      $s3, $s3, %lo(D_80050648)
    /* 1FE6C 8001F26C 93AC003B */  lbu        $t4, 0x3B($sp)
    /* 1FE70 8001F270 340DFFFF */  ori        $t5, $zero, 0xFFFF
    /* 1FE74 8001F274 2409FFFF */  addiu      $t1, $zero, -0x1
    /* 1FE78 8001F278 240800FF */  addiu      $t0, $zero, 0xFF
    /* 1FE7C 8001F27C 10000083 */  b          .L8001F48C
    /* 1FE80 8001F280 240601A0 */   addiu     $a2, $zero, 0x1A0
  .L8001F284:
    /* 1FE84 8001F284 3C0B8005 */  lui        $t3, %hi(D_80050A48)
    /* 1FE88 8001F288 956B0A48 */  lhu        $t3, %lo(D_80050A48)($t3)
    /* 1FE8C 8001F28C 340DFFFF */  ori        $t5, $zero, 0xFFFF
    /* 1FE90 8001F290 00001825 */  or         $v1, $zero, $zero
    /* 1FE94 8001F294 2404FFFF */  addiu      $a0, $zero, -0x1
    /* 1FE98 8001F298 11AB0047 */  beq        $t5, $t3, .L8001F3B8
    /* 1FE9C 8001F29C 01601025 */   or        $v0, $t3, $zero
    /* 1FEA0 8001F2A0 93AC003B */  lbu        $t4, 0x3B($sp)
    /* 1FEA4 8001F2A4 3C138005 */  lui        $s3, %hi(D_80050648)
    /* 1FEA8 8001F2A8 26730648 */  addiu      $s3, $s3, %lo(D_80050648)
    /* 1FEAC 8001F2AC 0182082A */  slt        $at, $t4, $v0
    /* 1FEB0 8001F2B0 14200041 */  bnez       $at, .L8001F3B8
    /* 1FEB4 8001F2B4 3C128005 */   lui       $s2, %hi(D_80050548)
    /* 1FEB8 8001F2B8 3C078005 */  lui        $a3, %hi(D_800504C8)
    /* 1FEBC 8001F2BC 3C058005 */  lui        $a1, %hi(D_8004BEB8)
    /* 1FEC0 8001F2C0 24A5BEB8 */  addiu      $a1, $a1, %lo(D_8004BEB8)
    /* 1FEC4 8001F2C4 24E704C8 */  addiu      $a3, $a3, %lo(D_800504C8)
    /* 1FEC8 8001F2C8 26520548 */  addiu      $s2, $s2, %lo(D_80050548)
    /* 1FECC 8001F2CC 2409FFFF */  addiu      $t1, $zero, -0x1
    /* 1FED0 8001F2D0 240800FF */  addiu      $t0, $zero, 0xFF
    /* 1FED4 8001F2D4 240601A0 */  addiu      $a2, $zero, 0x1A0
    /* 1FED8 8001F2D8 024B7021 */  addu       $t6, $s2, $t3
  .L8001F2DC:
    /* 1FEDC 8001F2DC 91C20000 */  lbu        $v0, 0x0($t6)
    /* 1FEE0 8001F2E0 5048002C */  beql       $v0, $t0, .L8001F394
    /* 1FEE4 8001F2E4 000BC880 */   sll       $t9, $t3, 2
  .L8001F2E8:
    /* 1FEE8 8001F2E8 00460019 */  multu      $v0, $a2
    /* 1FEEC 8001F2EC 00007812 */  mflo       $t7
    /* 1FEF0 8001F2F0 00AFA021 */  addu       $s4, $a1, $t7
    /* 1FEF4 8001F2F4 929800BD */  lbu        $t8, 0xBD($s4)
    /* 1FEF8 8001F2F8 57000021 */  bnel       $t8, $zero, .L8001F380
    /* 1FEFC 8001F2FC 00027080 */   sll       $t6, $v0, 2
    /* 1FF00 8001F300 928100BA */  lbu        $at, 0xBA($s4)
    /* 1FF04 8001F304 929900BB */  lbu        $t9, 0xBB($s4)
    /* 1FF08 8001F308 00010A00 */  sll        $at, $at, 8
    /* 1FF0C 8001F30C 0321C825 */  or         $t9, $t9, $at
    /* 1FF10 8001F310 5619001B */  bnel       $s0, $t9, .L8001F380
    /* 1FF14 8001F314 00027080 */   sll       $t6, $v0, 2
    /* 1FF18 8001F318 11400004 */  beqz       $t2, .L8001F32C
    /* 1FF1C 8001F31C 24630001 */   addiu     $v1, $v1, 0x1
    /* 1FF20 8001F320 928E004C */  lbu        $t6, 0x4C($s4)
    /* 1FF24 8001F324 562E0016 */  bnel       $s1, $t6, .L8001F380
    /* 1FF28 8001F328 00027080 */   sll       $t6, $v0, 2
  .L8001F32C:
    /* 1FF2C 8001F32C 8A8F0024 */  lwl        $t7, 0x24($s4)
    /* 1FF30 8001F330 9A8F0027 */  lwr        $t7, 0x27($s4)
    /* 1FF34 8001F334 31F80002 */  andi       $t8, $t7, 0x2
    /* 1FF38 8001F338 57000011 */  bnel       $t8, $zero, .L8001F380
    /* 1FF3C 8001F33C 00027080 */   sll       $t6, $v0, 2
    /* 1FF40 8001F340 5089000E */  beql       $a0, $t1, .L8001F37C
    /* 1FF44 8001F344 00402025 */   or        $a0, $v0, $zero
    /* 1FF48 8001F348 00860019 */  multu      $a0, $a2
    /* 1FF4C 8001F34C 8A990028 */  lwl        $t9, 0x28($s4)
    /* 1FF50 8001F350 9A99002B */  lwr        $t9, 0x2B($s4)
    /* 1FF54 8001F354 00007012 */  mflo       $t6
    /* 1FF58 8001F358 00AE7821 */  addu       $t7, $a1, $t6
    /* 1FF5C 8001F35C 89F80028 */  lwl        $t8, 0x28($t7)
    /* 1FF60 8001F360 99F8002B */  lwr        $t8, 0x2B($t7)
    /* 1FF64 8001F364 0338082B */  sltu       $at, $t9, $t8
    /* 1FF68 8001F368 50200005 */  beql       $at, $zero, .L8001F380
    /* 1FF6C 8001F36C 00027080 */   sll       $t6, $v0, 2
    /* 1FF70 8001F370 10000002 */  b          .L8001F37C
    /* 1FF74 8001F374 00402025 */   or        $a0, $v0, $zero
    /* 1FF78 8001F378 00402025 */  or         $a0, $v0, $zero
  .L8001F37C:
    /* 1FF7C 8001F37C 00027080 */  sll        $t6, $v0, 2
  .L8001F380:
    /* 1FF80 8001F380 00EE7821 */  addu       $t7, $a3, $t6
    /* 1FF84 8001F384 91E20001 */  lbu        $v0, 0x1($t7)
    /* 1FF88 8001F388 1448FFD7 */  bne        $v0, $t0, .L8001F2E8
    /* 1FF8C 8001F38C 00000000 */   nop
    /* 1FF90 8001F390 000BC880 */  sll        $t9, $t3, 2
  .L8001F394:
    /* 1FF94 8001F394 0279C021 */  addu       $t8, $s3, $t9
    /* 1FF98 8001F398 970B0000 */  lhu        $t3, 0x0($t8)
    /* 1FF9C 8001F39C 11AB0006 */  beq        $t5, $t3, .L8001F3B8
    /* 1FFA0 8001F3A0 01601025 */   or        $v0, $t3, $zero
    /* 1FFA4 8001F3A4 0182082A */  slt        $at, $t4, $v0
    /* 1FFA8 8001F3A8 54200004 */  bnel       $at, $zero, .L8001F3BC
    /* 1FFAC 8001F3AC 8FAE001C */   lw        $t6, 0x1C($sp)
    /* 1FFB0 8001F3B0 5089FFCA */  beql       $a0, $t1, .L8001F2DC
    /* 1FFB4 8001F3B4 024B7021 */   addu      $t6, $s2, $t3
  .L8001F3B8:
    /* 1FFB8 8001F3B8 8FAE001C */  lw         $t6, 0x1C($sp)
  .L8001F3BC:
    /* 1FFBC 8001F3BC 3C058005 */  lui        $a1, %hi(D_8004BEB8)
    /* 1FFC0 8001F3C0 3C078005 */  lui        $a3, %hi(D_800504C8)
    /* 1FFC4 8001F3C4 3C128005 */  lui        $s2, %hi(D_80050548)
    /* 1FFC8 8001F3C8 3C138005 */  lui        $s3, %hi(D_80050648)
    /* 1FFCC 8001F3CC 006E082A */  slt        $at, $v1, $t6
    /* 1FFD0 8001F3D0 26730648 */  addiu      $s3, $s3, %lo(D_80050648)
    /* 1FFD4 8001F3D4 26520548 */  addiu      $s2, $s2, %lo(D_80050548)
    /* 1FFD8 8001F3D8 24E704C8 */  addiu      $a3, $a3, %lo(D_800504C8)
    /* 1FFDC 8001F3DC 24A5BEB8 */  addiu      $a1, $a1, %lo(D_8004BEB8)
    /* 1FFE0 8001F3E0 240601A0 */  addiu      $a2, $zero, 0x1A0
    /* 1FFE4 8001F3E4 240800FF */  addiu      $t0, $zero, 0xFF
    /* 1FFE8 8001F3E8 10200076 */  beqz       $at, .L8001F5C4
    /* 1FFEC 8001F3EC 2409FFFF */   addiu     $t1, $zero, -0x1
    /* 1FFF0 8001F3F0 11A20020 */  beq        $t5, $v0, .L8001F474
    /* 1FFF4 8001F3F4 006E082A */   slt       $at, $v1, $t6
    /* 1FFF8 8001F3F8 1020001E */  beqz       $at, .L8001F474
    /* 1FFFC 8001F3FC 024BC821 */   addu      $t9, $s2, $t3
  .L8001F400:
    /* 20000 8001F400 93220000 */  lbu        $v0, 0x0($t9)
    /* 20004 8001F404 50480014 */  beql       $v0, $t0, .L8001F458
    /* 20008 8001F408 000B7080 */   sll       $t6, $t3, 2
  .L8001F40C:
    /* 2000C 8001F40C 00460019 */  multu      $v0, $a2
    /* 20010 8001F410 0002C880 */  sll        $t9, $v0, 2
    /* 20014 8001F414 0000C012 */  mflo       $t8
    /* 20018 8001F418 00B8A021 */  addu       $s4, $a1, $t8
    /* 2001C 8001F41C 928E00BD */  lbu        $t6, 0xBD($s4)
    /* 20020 8001F420 00F9C021 */  addu       $t8, $a3, $t9
    /* 20024 8001F424 55C00009 */  bnel       $t6, $zero, .L8001F44C
    /* 20028 8001F428 93020001 */   lbu       $v0, 0x1($t8)
    /* 2002C 8001F42C 928100BA */  lbu        $at, 0xBA($s4)
    /* 20030 8001F430 928F00BB */  lbu        $t7, 0xBB($s4)
    /* 20034 8001F434 00010A00 */  sll        $at, $at, 8
    /* 20038 8001F438 01E17825 */  or         $t7, $t7, $at
    /* 2003C 8001F43C 560F0003 */  bnel       $s0, $t7, .L8001F44C
    /* 20040 8001F440 93020001 */   lbu       $v0, 0x1($t8)
    /* 20044 8001F444 24630001 */  addiu      $v1, $v1, 0x1
    /* 20048 8001F448 93020001 */  lbu        $v0, 0x1($t8)
  .L8001F44C:
    /* 2004C 8001F44C 1448FFEF */  bne        $v0, $t0, .L8001F40C
    /* 20050 8001F450 00000000 */   nop
    /* 20054 8001F454 000B7080 */  sll        $t6, $t3, 2
  .L8001F458:
    /* 20058 8001F458 026E7821 */  addu       $t7, $s3, $t6
    /* 2005C 8001F45C 95EB0000 */  lhu        $t3, 0x0($t7)
    /* 20060 8001F460 8FB9001C */  lw         $t9, 0x1C($sp)
    /* 20064 8001F464 11AB0003 */  beq        $t5, $t3, .L8001F474
    /* 20068 8001F468 0079082A */   slt       $at, $v1, $t9
    /* 2006C 8001F46C 5420FFE4 */  bnel       $at, $zero, .L8001F400
    /* 20070 8001F470 024BC821 */   addu      $t9, $s2, $t3
  .L8001F474:
    /* 20074 8001F474 8FB8001C */  lw         $t8, 0x1C($sp)
    /* 20078 8001F478 93AC003B */  lbu        $t4, 0x3B($sp)
    /* 2007C 8001F47C 0078082A */  slt        $at, $v1, $t8
    /* 20080 8001F480 10200050 */  beqz       $at, .L8001F5C4
    /* 20084 8001F484 00000000 */   nop
    /* 20088 8001F488 2404FFFF */  addiu      $a0, $zero, -0x1
  .L8001F48C:
    /* 2008C 8001F48C 3C028005 */  lui        $v0, %hi(D_800504C0)
    /* 20090 8001F490 904204C0 */  lbu        $v0, %lo(D_800504C0)($v0)
    /* 20094 8001F494 3C038005 */  lui        $v1, %hi(D_80050A48)
    /* 20098 8001F498 11020005 */  beq        $t0, $v0, .L8001F4B0
    /* 2009C 8001F49C 00000000 */   nop
    /* 200A0 8001F4A0 15400003 */  bnez       $t2, .L8001F4B0
    /* 200A4 8001F4A4 00000000 */   nop
    /* 200A8 8001F4A8 1000003F */  b          .L8001F5A8
    /* 200AC 8001F4AC 00402025 */   or        $a0, $v0, $zero
  .L8001F4B0:
    /* 200B0 8001F4B0 94630A48 */  lhu        $v1, %lo(D_80050A48)($v1)
    /* 200B4 8001F4B4 0183082A */  slt        $at, $t4, $v1
    /* 200B8 8001F4B8 10200003 */  beqz       $at, .L8001F4C8
    /* 200BC 8001F4BC 306BFFFF */   andi      $t3, $v1, 0xFFFF
    /* 200C0 8001F4C0 10000083 */  b          .L8001F6D0
    /* 200C4 8001F4C4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001F4C8:
    /* 200C8 8001F4C8 11AB0033 */  beq        $t5, $t3, .L8001F598
    /* 200CC 8001F4CC 018B082A */   slt       $at, $t4, $t3
    /* 200D0 8001F4D0 14200031 */  bnez       $at, .L8001F598
    /* 200D4 8001F4D4 024B7021 */   addu      $t6, $s2, $t3
  .L8001F4D8:
    /* 200D8 8001F4D8 91C20000 */  lbu        $v0, 0x0($t6)
    /* 200DC 8001F4DC 50480026 */  beql       $v0, $t0, .L8001F578
    /* 200E0 8001F4E0 000BC880 */   sll       $t9, $t3, 2
  .L8001F4E4:
    /* 200E4 8001F4E4 00460019 */  multu      $v0, $a2
    /* 200E8 8001F4E8 00007812 */  mflo       $t7
    /* 200EC 8001F4EC 00AFA021 */  addu       $s4, $a1, $t7
    /* 200F0 8001F4F0 929900BD */  lbu        $t9, 0xBD($s4)
    /* 200F4 8001F4F4 5720001B */  bnel       $t9, $zero, .L8001F564
    /* 200F8 8001F4F8 0002C080 */   sll       $t8, $v0, 2
    /* 200FC 8001F4FC 51400005 */  beql       $t2, $zero, .L8001F514
    /* 20100 8001F500 8A8E0024 */   lwl       $t6, 0x24($s4)
    /* 20104 8001F504 9298004C */  lbu        $t8, 0x4C($s4)
    /* 20108 8001F508 56380016 */  bnel       $s1, $t8, .L8001F564
    /* 2010C 8001F50C 0002C080 */   sll       $t8, $v0, 2
    /* 20110 8001F510 8A8E0024 */  lwl        $t6, 0x24($s4)
  .L8001F514:
    /* 20114 8001F514 9A8E0027 */  lwr        $t6, 0x27($s4)
    /* 20118 8001F518 31CF0002 */  andi       $t7, $t6, 0x2
    /* 2011C 8001F51C 55E00011 */  bnel       $t7, $zero, .L8001F564
    /* 20120 8001F520 0002C080 */   sll       $t8, $v0, 2
    /* 20124 8001F524 5089000E */  beql       $a0, $t1, .L8001F560
    /* 20128 8001F528 00402025 */   or        $a0, $v0, $zero
    /* 2012C 8001F52C 00860019 */  multu      $a0, $a2
    /* 20130 8001F530 8A990028 */  lwl        $t9, 0x28($s4)
    /* 20134 8001F534 9A99002B */  lwr        $t9, 0x2B($s4)
    /* 20138 8001F538 0000C012 */  mflo       $t8
    /* 2013C 8001F53C 00B87021 */  addu       $t6, $a1, $t8
    /* 20140 8001F540 89CF0028 */  lwl        $t7, 0x28($t6)
    /* 20144 8001F544 99CF002B */  lwr        $t7, 0x2B($t6)
    /* 20148 8001F548 032F082B */  sltu       $at, $t9, $t7
    /* 2014C 8001F54C 50200005 */  beql       $at, $zero, .L8001F564
    /* 20150 8001F550 0002C080 */   sll       $t8, $v0, 2
    /* 20154 8001F554 10000002 */  b          .L8001F560
    /* 20158 8001F558 00402025 */   or        $a0, $v0, $zero
    /* 2015C 8001F55C 00402025 */  or         $a0, $v0, $zero
  .L8001F560:
    /* 20160 8001F560 0002C080 */  sll        $t8, $v0, 2
  .L8001F564:
    /* 20164 8001F564 00F87021 */  addu       $t6, $a3, $t8
    /* 20168 8001F568 91C20001 */  lbu        $v0, 0x1($t6)
    /* 2016C 8001F56C 1448FFDD */  bne        $v0, $t0, .L8001F4E4
    /* 20170 8001F570 00000000 */   nop
    /* 20174 8001F574 000BC880 */  sll        $t9, $t3, 2
  .L8001F578:
    /* 20178 8001F578 02797821 */  addu       $t7, $s3, $t9
    /* 2017C 8001F57C 95EB0000 */  lhu        $t3, 0x0($t7)
    /* 20180 8001F580 11AB0005 */  beq        $t5, $t3, .L8001F598
    /* 20184 8001F584 018B082A */   slt       $at, $t4, $t3
    /* 20188 8001F588 14200003 */  bnez       $at, .L8001F598
    /* 2018C 8001F58C 00000000 */   nop
    /* 20190 8001F590 5089FFD1 */  beql       $a0, $t1, .L8001F4D8
    /* 20194 8001F594 024B7021 */   addu      $t6, $s2, $t3
  .L8001F598:
    /* 20198 8001F598 14890003 */  bne        $a0, $t1, .L8001F5A8
    /* 2019C 8001F59C 00000000 */   nop
    /* 201A0 8001F5A0 1000004B */  b          .L8001F6D0
    /* 201A4 8001F5A4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001F5A8:
    /* 201A8 8001F5A8 00860019 */  multu      $a0, $a2
    /* 201AC 8001F5AC 0000C012 */  mflo       $t8
    /* 201B0 8001F5B0 00B87021 */  addu       $t6, $a1, $t8
    /* 201B4 8001F5B4 91D9002E */  lbu        $t9, 0x2E($t6)
    /* 201B8 8001F5B8 0199082A */  slt        $at, $t4, $t9
    /* 201BC 8001F5BC 54200044 */  bnel       $at, $zero, .L8001F6D0
    /* 201C0 8001F5C0 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001F5C4:
    /* 201C4 8001F5C4 10890041 */  beq        $a0, $t1, .L8001F6CC
    /* 201C8 8001F5C8 3C078005 */   lui       $a3, %hi(D_80050440)
    /* 201CC 8001F5CC 24E70440 */  addiu      $a3, $a3, %lo(D_80050440)
    /* 201D0 8001F5D0 00047880 */  sll        $t7, $a0, 2
    /* 201D4 8001F5D4 00EF1821 */  addu       $v1, $a3, $t7
    /* 201D8 8001F5D8 94780002 */  lhu        $t8, 0x2($v1)
    /* 201DC 8001F5DC 24010001 */  addiu      $at, $zero, 0x1
    /* 201E0 8001F5E0 1701001B */  bne        $t8, $at, .L8001F650
    /* 201E4 8001F5E4 00000000 */   nop
    /* 201E8 8001F5E8 90620000 */  lbu        $v0, 0x0($v1)
    /* 201EC 8001F5EC 10480005 */  beq        $v0, $t0, .L8001F604
    /* 201F0 8001F5F0 0002C880 */   sll       $t9, $v0, 2
    /* 201F4 8001F5F4 906E0001 */  lbu        $t6, 0x1($v1)
    /* 201F8 8001F5F8 00F97821 */  addu       $t7, $a3, $t9
    /* 201FC 8001F5FC 10000004 */  b          .L8001F610
    /* 20200 8001F600 A1EE0001 */   sb        $t6, 0x1($t7)
  .L8001F604:
    /* 20204 8001F604 90780001 */  lbu        $t8, 0x1($v1)
    /* 20208 8001F608 3C018005 */  lui        $at, %hi(D_800504C0)
    /* 2020C 8001F60C A03804C0 */  sb         $t8, %lo(D_800504C0)($at)
  .L8001F610:
    /* 20210 8001F610 90620001 */  lbu        $v0, 0x1($v1)
    /* 20214 8001F614 3C188005 */  lui        $t8, %hi(D_800504C1)
    /* 20218 8001F618 10480005 */  beq        $v0, $t0, .L8001F630
    /* 2021C 8001F61C 00000000 */   nop
    /* 20220 8001F620 90790000 */  lbu        $t9, 0x0($v1)
    /* 20224 8001F624 00027080 */  sll        $t6, $v0, 2
    /* 20228 8001F628 00EE7821 */  addu       $t7, $a3, $t6
    /* 2022C 8001F62C A1F90000 */  sb         $t9, 0x0($t7)
  .L8001F630:
    /* 20230 8001F630 931804C1 */  lbu        $t8, %lo(D_800504C1)($t8)
    /* 20234 8001F634 14980004 */  bne        $a0, $t8, .L8001F648
    /* 20238 8001F638 00000000 */   nop
    /* 2023C 8001F63C 906E0000 */  lbu        $t6, 0x0($v1)
    /* 20240 8001F640 3C018005 */  lui        $at, %hi(D_800504C1)
    /* 20244 8001F644 A02E04C1 */  sb         $t6, %lo(D_800504C1)($at)
  .L8001F648:
    /* 20248 8001F648 10000011 */  b          .L8001F690
    /* 2024C 8001F64C A4600002 */   sh        $zero, 0x2($v1)
  .L8001F650:
    /* 20250 8001F650 00860019 */  multu      $a0, $a2
    /* 20254 8001F654 0000C812 */  mflo       $t9
    /* 20258 8001F658 00B97821 */  addu       $t7, $a1, $t9
    /* 2025C 8001F65C 91F8004C */  lbu        $t8, 0x4C($t7)
    /* 20260 8001F660 13000006 */  beqz       $t8, .L8001F67C
    /* 20264 8001F664 3C0E8005 */   lui       $t6, %hi(D_800504C2)
    /* 20268 8001F668 91CE04C2 */  lbu        $t6, %lo(D_800504C2)($t6)
    /* 2026C 8001F66C 3C018005 */  lui        $at, %hi(D_800504C2)
    /* 20270 8001F670 25D9FFFF */  addiu      $t9, $t6, -0x1
    /* 20274 8001F674 10000006 */  b          .L8001F690
    /* 20278 8001F678 A03904C2 */   sb        $t9, %lo(D_800504C2)($at)
  .L8001F67C:
    /* 2027C 8001F67C 3C0F8005 */  lui        $t7, %hi(D_800504C3)
    /* 20280 8001F680 91EF04C3 */  lbu        $t7, %lo(D_800504C3)($t7)
    /* 20284 8001F684 3C018005 */  lui        $at, %hi(D_800504C3)
    /* 20288 8001F688 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 2028C 8001F68C A03804C3 */  sb         $t8, %lo(D_800504C3)($at)
  .L8001F690:
    /* 20290 8001F690 12200007 */  beqz       $s1, .L8001F6B0
    /* 20294 8001F694 3C028005 */   lui       $v0, %hi(D_800504C2)
    /* 20298 8001F698 244204C2 */  addiu      $v0, $v0, %lo(D_800504C2)
    /* 2029C 8001F69C 904E0000 */  lbu        $t6, 0x0($v0)
    /* 202A0 8001F6A0 25D90001 */  addiu      $t9, $t6, 0x1
    /* 202A4 8001F6A4 A0590000 */  sb         $t9, 0x0($v0)
    /* 202A8 8001F6A8 10000009 */  b          .L8001F6D0
    /* 202AC 8001F6AC 00801025 */   or        $v0, $a0, $zero
  .L8001F6B0:
    /* 202B0 8001F6B0 3C028005 */  lui        $v0, %hi(D_800504C3)
    /* 202B4 8001F6B4 244204C3 */  addiu      $v0, $v0, %lo(D_800504C3)
    /* 202B8 8001F6B8 904F0000 */  lbu        $t7, 0x0($v0)
    /* 202BC 8001F6BC 25F80001 */  addiu      $t8, $t7, 0x1
    /* 202C0 8001F6C0 A0580000 */  sb         $t8, 0x0($v0)
    /* 202C4 8001F6C4 10000002 */  b          .L8001F6D0
    /* 202C8 8001F6C8 00801025 */   or        $v0, $a0, $zero
  .L8001F6CC:
    /* 202CC 8001F6CC 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8001F6D0:
    /* 202D0 8001F6D0 8FB00004 */  lw         $s0, 0x4($sp)
    /* 202D4 8001F6D4 8FB10008 */  lw         $s1, 0x8($sp)
    /* 202D8 8001F6D8 8FB2000C */  lw         $s2, 0xC($sp)
    /* 202DC 8001F6DC 8FB30010 */  lw         $s3, 0x10($sp)
    /* 202E0 8001F6E0 8FB40014 */  lw         $s4, 0x14($sp)
    /* 202E4 8001F6E4 03E00008 */  jr         $ra
    /* 202E8 8001F6E8 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_8001F13C

nonmatching func_8001F6EC, 0x100

glabel func_8001F6EC
    /* 202EC 8001F6EC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 202F0 8001F6F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 202F4 8001F6F4 0C007BA7 */  jal        func_8001EE9C
    /* 202F8 8001F6F8 AFA40018 */   sw        $a0, 0x18($sp)
    /* 202FC 8001F6FC 8FA40018 */  lw         $a0, 0x18($sp)
    /* 20300 8001F700 3C058005 */  lui        $a1, %hi(D_80050440)
    /* 20304 8001F704 24A50440 */  addiu      $a1, $a1, %lo(D_80050440)
    /* 20308 8001F708 88830060 */  lwl        $v1, 0x60($a0)
    /* 2030C 8001F70C 98830063 */  lwr        $v1, 0x63($a0)
    /* 20310 8001F710 A8800000 */  swl        $zero, 0x0($a0)
    /* 20314 8001F714 B8800003 */  swr        $zero, 0x3($a0)
    /* 20318 8001F718 306300FF */  andi       $v1, $v1, 0xFF
    /* 2031C 8001F71C 00037080 */  sll        $t6, $v1, 2
    /* 20320 8001F720 00AE1021 */  addu       $v0, $a1, $t6
    /* 20324 8001F724 A080002E */  sb         $zero, 0x2E($a0)
    /* 20328 8001F728 944F0002 */  lhu        $t7, 0x2($v0)
    /* 2032C 8001F72C 3C068005 */  lui        $a2, %hi(D_800504C0)
    /* 20330 8001F730 24C604C0 */  addiu      $a2, $a2, %lo(D_800504C0)
    /* 20334 8001F734 55E00027 */  bnel       $t7, $zero, .L8001F7D4
    /* 20338 8001F738 2419FFFF */   addiu     $t9, $zero, -0x1
    /* 2033C 8001F73C 90D90000 */  lbu        $t9, 0x0($a2)
    /* 20340 8001F740 24180001 */  addiu      $t8, $zero, 0x1
    /* 20344 8001F744 240100FF */  addiu      $at, $zero, 0xFF
    /* 20348 8001F748 1321000C */  beq        $t9, $at, .L8001F77C
    /* 2034C 8001F74C A4580002 */   sh        $t8, 0x2($v0)
    /* 20350 8001F750 3C068005 */  lui        $a2, %hi(D_800504C1)
    /* 20354 8001F754 24C604C1 */  addiu      $a2, $a2, %lo(D_800504C1)
    /* 20358 8001F758 90C90000 */  lbu        $t1, 0x0($a2)
    /* 2035C 8001F75C 90C80000 */  lbu        $t0, 0x0($a2)
    /* 20360 8001F760 240700FF */  addiu      $a3, $zero, 0xFF
    /* 20364 8001F764 00095080 */  sll        $t2, $t1, 2
    /* 20368 8001F768 A0470001 */  sb         $a3, 0x1($v0)
    /* 2036C 8001F76C 00AA5821 */  addu       $t3, $a1, $t2
    /* 20370 8001F770 A0480000 */  sb         $t0, 0x0($v0)
    /* 20374 8001F774 10000007 */  b          .L8001F794
    /* 20378 8001F778 A1630001 */   sb        $v1, 0x1($t3)
  .L8001F77C:
    /* 2037C 8001F77C 240700FF */  addiu      $a3, $zero, 0xFF
    /* 20380 8001F780 A0C30000 */  sb         $v1, 0x0($a2)
    /* 20384 8001F784 3C068005 */  lui        $a2, %hi(D_800504C1)
    /* 20388 8001F788 A0470001 */  sb         $a3, 0x1($v0)
    /* 2038C 8001F78C A0470000 */  sb         $a3, 0x0($v0)
    /* 20390 8001F790 24C604C1 */  addiu      $a2, $a2, %lo(D_800504C1)
  .L8001F794:
    /* 20394 8001F794 A0C30000 */  sb         $v1, 0x0($a2)
    /* 20398 8001F798 908C004C */  lbu        $t4, 0x4C($a0)
    /* 2039C 8001F79C 3C028005 */  lui        $v0, %hi(D_800504C2)
    /* 203A0 8001F7A0 244204C2 */  addiu      $v0, $v0, %lo(D_800504C2)
    /* 203A4 8001F7A4 11800005 */  beqz       $t4, .L8001F7BC
    /* 203A8 8001F7A8 00000000 */   nop
    /* 203AC 8001F7AC 904D0000 */  lbu        $t5, 0x0($v0)
    /* 203B0 8001F7B0 25AEFFFF */  addiu      $t6, $t5, -0x1
    /* 203B4 8001F7B4 10000006 */  b          .L8001F7D0
    /* 203B8 8001F7B8 A04E0000 */   sb        $t6, 0x0($v0)
  .L8001F7BC:
    /* 203BC 8001F7BC 3C028005 */  lui        $v0, %hi(D_800504C3)
    /* 203C0 8001F7C0 244204C3 */  addiu      $v0, $v0, %lo(D_800504C3)
    /* 203C4 8001F7C4 904F0000 */  lbu        $t7, 0x0($v0)
    /* 203C8 8001F7C8 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 203CC 8001F7CC A0580000 */  sb         $t8, 0x0($v0)
  .L8001F7D0:
    /* 203D0 8001F7D0 2419FFFF */  addiu      $t9, $zero, -0x1
  .L8001F7D4:
    /* 203D4 8001F7D4 A8990060 */  swl        $t9, 0x60($a0)
    /* 203D8 8001F7D8 B8990063 */  swr        $t9, 0x63($a0)
    /* 203DC 8001F7DC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 203E0 8001F7E0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 203E4 8001F7E4 03E00008 */  jr         $ra
    /* 203E8 8001F7E8 00000000 */   nop
endlabel func_8001F6EC

nonmatching func_8001F7EC, 0x78

glabel func_8001F7EC
    /* 203EC 8001F7EC 3C038005 */  lui        $v1, %hi(D_8004FA18)
    /* 203F0 8001F7F0 9063FA18 */  lbu        $v1, %lo(D_8004FA18)($v1)
    /* 203F4 8001F7F4 00001025 */  or         $v0, $zero, $zero
    /* 203F8 8001F7F8 3C058005 */  lui        $a1, %hi(D_80050440)
    /* 203FC 8001F7FC 1060000C */  beqz       $v1, .L8001F830
    /* 20400 8001F800 00602025 */   or        $a0, $v1, $zero
    /* 20404 8001F804 24A50440 */  addiu      $a1, $a1, %lo(D_80050440)
    /* 20408 8001F808 24070001 */  addiu      $a3, $zero, 0x1
  .L8001F80C:
    /* 2040C 8001F80C 24460001 */  addiu      $a2, $v0, 0x1
    /* 20410 8001F810 00C4082B */  sltu       $at, $a2, $a0
    /* 20414 8001F814 244EFFFF */  addiu      $t6, $v0, -0x1
    /* 20418 8001F818 00C01025 */  or         $v0, $a2, $zero
    /* 2041C 8001F81C 24A50004 */  addiu      $a1, $a1, 0x4
    /* 20420 8001F820 A0AEFFFC */  sb         $t6, -0x4($a1)
    /* 20424 8001F824 A0A6FFFD */  sb         $a2, -0x3($a1)
    /* 20428 8001F828 1420FFF8 */  bnez       $at, .L8001F80C
    /* 2042C 8001F82C A4A7FFFE */   sh        $a3, -0x2($a1)
  .L8001F830:
    /* 20430 8001F830 3C028005 */  lui        $v0, %hi(D_80050440)
    /* 20434 8001F834 24420440 */  addiu      $v0, $v0, %lo(D_80050440)
    /* 20438 8001F838 240400FF */  addiu      $a0, $zero, 0xFF
    /* 2043C 8001F83C 00037880 */  sll        $t7, $v1, 2
    /* 20440 8001F840 A0440000 */  sb         $a0, 0x0($v0)
    /* 20444 8001F844 004FC021 */  addu       $t8, $v0, $t7
    /* 20448 8001F848 A304FFFD */  sb         $a0, -0x3($t8)
    /* 2044C 8001F84C 3C018005 */  lui        $at, %hi(D_800504C0)
    /* 20450 8001F850 A02004C0 */  sb         $zero, %lo(D_800504C0)($at)
    /* 20454 8001F854 3C018005 */  lui        $at, %hi(D_800504C1)
    /* 20458 8001F858 2479FFFF */  addiu      $t9, $v1, -0x1
    /* 2045C 8001F85C 03E00008 */  jr         $ra
    /* 20460 8001F860 A03904C1 */   sb        $t9, %lo(D_800504C1)($at)
endlabel func_8001F7EC

nonmatching func_8001F864, 0x34

glabel func_8001F864
    /* 20464 8001F864 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 20468 8001F868 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2046C 8001F86C 0C007DFB */  jal        func_8001F7EC
    /* 20470 8001F870 00000000 */   nop
    /* 20474 8001F874 0C007B8D */  jal        func_8001EE34
    /* 20478 8001F878 00000000 */   nop
    /* 2047C 8001F87C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20480 8001F880 3C018005 */  lui        $at, %hi(D_800504C2)
    /* 20484 8001F884 A02004C2 */  sb         $zero, %lo(D_800504C2)($at)
    /* 20488 8001F888 3C018005 */  lui        $at, %hi(D_800504C3)
    /* 2048C 8001F88C A02004C3 */  sb         $zero, %lo(D_800504C3)($at)
    /* 20490 8001F890 03E00008 */  jr         $ra
    /* 20494 8001F894 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8001F864

nonmatching func_8001F898, 0xBC

glabel func_8001F898
    /* 20498 8001F898 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2049C 8001F89C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 204A0 8001F8A0 AFA40020 */  sw         $a0, 0x20($sp)
    /* 204A4 8001F8A4 AFB10018 */  sw         $s1, 0x18($sp)
    /* 204A8 8001F8A8 AFB00014 */  sw         $s0, 0x14($sp)
    /* 204AC 8001F8AC 93A40023 */  lbu        $a0, 0x23($sp)
    /* 204B0 8001F8B0 240500FF */  addiu      $a1, $zero, 0xFF
    /* 204B4 8001F8B4 3406FFFF */  ori        $a2, $zero, 0xFFFF
    /* 204B8 8001F8B8 0C007C4F */  jal        func_8001F13C
    /* 204BC 8001F8BC 24070001 */   addiu     $a3, $zero, 0x1
    /* 204C0 8001F8C0 2401FFFF */  addiu      $at, $zero, -0x1
    /* 204C4 8001F8C4 1041001D */  beq        $v0, $at, .L8001F93C
    /* 204C8 8001F8C8 00408825 */   or        $s1, $v0, $zero
    /* 204CC 8001F8CC 00117080 */  sll        $t6, $s1, 2
    /* 204D0 8001F8D0 01D17023 */  subu       $t6, $t6, $s1
    /* 204D4 8001F8D4 000E7080 */  sll        $t6, $t6, 2
    /* 204D8 8001F8D8 01D17021 */  addu       $t6, $t6, $s1
    /* 204DC 8001F8DC 3C0F8005 */  lui        $t7, %hi(D_8004BEB8)
    /* 204E0 8001F8E0 25EFBEB8 */  addiu      $t7, $t7, %lo(D_8004BEB8)
    /* 204E4 8001F8E4 000E7140 */  sll        $t6, $t6, 5
    /* 204E8 8001F8E8 01CF8021 */  addu       $s0, $t6, $t7
    /* 204EC 8001F8EC 24020001 */  addiu      $v0, $zero, 0x1
    /* 204F0 8001F8F0 A20200BD */  sb         $v0, 0xBD($s0)
    /* 204F4 8001F8F4 A202004C */  sb         $v0, 0x4C($s0)
    /* 204F8 8001F8F8 0C007AC4 */  jal        func_8001EB10
    /* 204FC 8001F8FC 02002025 */   or        $a0, $s0, $zero
    /* 20500 8001F900 2401FF00 */  addiu      $at, $zero, -0x100
    /* 20504 8001F904 0221C025 */  or         $t8, $s1, $at
    /* 20508 8001F908 AA180060 */  swl        $t8, 0x60($s0)
    /* 2050C 8001F90C BA180063 */  swr        $t8, 0x63($s0)
    /* 20510 8001F910 0C00519F */  jal        func_8001467C
    /* 20514 8001F914 02202025 */   or        $a0, $s1, $zero
    /* 20518 8001F918 50400004 */  beql       $v0, $zero, .L8001F92C
    /* 2051C 8001F91C AA000000 */   swl       $zero, 0x0($s0)
    /* 20520 8001F920 0C0052BC */  jal        func_80014AF0
    /* 20524 8001F924 02202025 */   or        $a0, $s1, $zero
    /* 20528 8001F928 AA000000 */  swl        $zero, 0x0($s0)
  .L8001F92C:
    /* 2052C 8001F92C BA000003 */  swr        $zero, 0x3($s0)
    /* 20530 8001F930 02002025 */  or         $a0, $s0, $zero
    /* 20534 8001F934 0C007BE3 */  jal        func_8001EF8C
    /* 20538 8001F938 93A50023 */   lbu       $a1, 0x23($sp)
  .L8001F93C:
    /* 2053C 8001F93C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 20540 8001F940 02201025 */  or         $v0, $s1, $zero
    /* 20544 8001F944 8FB10018 */  lw         $s1, 0x18($sp)
    /* 20548 8001F948 8FB00014 */  lw         $s0, 0x14($sp)
    /* 2054C 8001F94C 03E00008 */  jr         $ra
    /* 20550 8001F950 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_8001F898

nonmatching func_8001F954, 0x7C

glabel func_8001F954
    /* 20554 8001F954 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20558 8001F958 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2055C 8001F95C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20560 8001F960 10810017 */  beq        $a0, $at, .L8001F9C0
    /* 20564 8001F964 00802825 */   or        $a1, $a0, $zero
    /* 20568 8001F968 0C00519F */  jal        func_8001467C
    /* 2056C 8001F96C AFA50020 */   sw        $a1, 0x20($sp)
    /* 20570 8001F970 10400005 */  beqz       $v0, .L8001F988
    /* 20574 8001F974 8FA50020 */   lw        $a1, 0x20($sp)
    /* 20578 8001F978 00A02025 */  or         $a0, $a1, $zero
    /* 2057C 8001F97C 0C0052BC */  jal        func_80014AF0
    /* 20580 8001F980 AFA50020 */   sw        $a1, 0x20($sp)
    /* 20584 8001F984 8FA50020 */  lw         $a1, 0x20($sp)
  .L8001F988:
    /* 20588 8001F988 00057080 */  sll        $t6, $a1, 2
    /* 2058C 8001F98C 01C57023 */  subu       $t6, $t6, $a1
    /* 20590 8001F990 000E7080 */  sll        $t6, $t6, 2
    /* 20594 8001F994 01C57021 */  addu       $t6, $t6, $a1
    /* 20598 8001F998 3C0F8005 */  lui        $t7, %hi(D_8004BEB8)
    /* 2059C 8001F99C 25EFBEB8 */  addiu      $t7, $t7, %lo(D_8004BEB8)
    /* 205A0 8001F9A0 000E7140 */  sll        $t6, $t6, 5
    /* 205A4 8001F9A4 01CF2021 */  addu       $a0, $t6, $t7
    /* 205A8 8001F9A8 A8850060 */  swl        $a1, 0x60($a0)
    /* 205AC 8001F9AC B8850063 */  swr        $a1, 0x63($a0)
    /* 205B0 8001F9B0 0C007DBB */  jal        func_8001F6EC
    /* 205B4 8001F9B4 AFA4001C */   sw        $a0, 0x1C($sp)
    /* 205B8 8001F9B8 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 205BC 8001F9BC A08000BD */  sb         $zero, 0xBD($a0)
  .L8001F9C0:
    /* 205C0 8001F9C0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 205C4 8001F9C4 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 205C8 8001F9C8 03E00008 */  jr         $ra
    /* 205CC 8001F9CC 00000000 */   nop
endlabel func_8001F954

nonmatching func_8001F9D0, 0x48

glabel func_8001F9D0
    /* 205D0 8001F9D0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 205D4 8001F9D4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 205D8 8001F9D8 0C007AC4 */  jal        func_8001EB10
    /* 205DC 8001F9DC AFA40018 */   sw        $a0, 0x18($sp)
    /* 205E0 8001F9E0 8FA40018 */  lw         $a0, 0x18($sp)
    /* 205E4 8001F9E4 2401FFFC */  addiu      $at, $zero, -0x4
    /* 205E8 8001F9E8 888E0024 */  lwl        $t6, 0x24($a0)
    /* 205EC 8001F9EC 988E0027 */  lwr        $t6, 0x27($a0)
    /* 205F0 8001F9F0 A8800028 */  swl        $zero, 0x28($a0)
    /* 205F4 8001F9F4 B880002B */  swr        $zero, 0x2B($a0)
    /* 205F8 8001F9F8 01C17824 */  and        $t7, $t6, $at
    /* 205FC 8001F9FC A88F0024 */  swl        $t7, 0x24($a0)
    /* 20600 8001FA00 0C007DBB */  jal        func_8001F6EC
    /* 20604 8001FA04 B88F0027 */   swr       $t7, 0x27($a0)
    /* 20608 8001FA08 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2060C 8001FA0C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 20610 8001FA10 03E00008 */  jr         $ra
    /* 20614 8001FA14 00000000 */   nop
endlabel func_8001F9D0

nonmatching func_8001FA18, 0xCC

glabel func_8001FA18
    /* 20618 8001FA18 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 2061C 8001FA1C 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20620 8001FA20 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20624 8001FA24 AFB50028 */  sw         $s5, 0x28($sp)
    /* 20628 8001FA28 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 2062C 8001FA2C AFB40024 */  sw         $s4, 0x24($sp)
    /* 20630 8001FA30 AFB30020 */  sw         $s3, 0x20($sp)
    /* 20634 8001FA34 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 20638 8001FA38 AFB10018 */  sw         $s1, 0x18($sp)
    /* 2063C 8001FA3C AFB00014 */  sw         $s0, 0x14($sp)
    /* 20640 8001FA40 11C0001E */  beqz       $t6, .L8001FABC
    /* 20644 8001FA44 2415FFFF */   addiu     $s5, $zero, -0x1
    /* 20648 8001FA48 0C007B7D */  jal        func_8001EDF4
    /* 2064C 8001FA4C 00000000 */   nop
    /* 20650 8001FA50 2412FFFF */  addiu      $s2, $zero, -0x1
    /* 20654 8001FA54 10520019 */  beq        $v0, $s2, .L8001FABC
    /* 20658 8001FA58 00402825 */   or        $a1, $v0, $zero
    /* 2065C 8001FA5C 3C138005 */  lui        $s3, %hi(D_8004BEB8)
    /* 20660 8001FA60 2673BEB8 */  addiu      $s3, $s3, %lo(D_8004BEB8)
    /* 20664 8001FA64 241401A0 */  addiu      $s4, $zero, 0x1A0
  .L8001FA68:
    /* 20668 8001FA68 30B000FF */  andi       $s0, $a1, 0xFF
    /* 2066C 8001FA6C 02140019 */  multu      $s0, $s4
    /* 20670 8001FA70 00007812 */  mflo       $t7
    /* 20674 8001FA74 026F2021 */  addu       $a0, $s3, $t7
    /* 20678 8001FA78 88980060 */  lwl        $t8, 0x60($a0)
    /* 2067C 8001FA7C 98980063 */  lwr        $t8, 0x63($a0)
    /* 20680 8001FA80 88910010 */  lwl        $s1, 0x10($a0)
    /* 20684 8001FA84 98910013 */  lwr        $s1, 0x13($a0)
    /* 20688 8001FA88 14B8000A */  bne        $a1, $t8, .L8001FAB4
    /* 2068C 8001FA8C 00000000 */   nop
    /* 20690 8001FA90 88990000 */  lwl        $t9, 0x0($a0)
    /* 20694 8001FA94 98990003 */  lwr        $t9, 0x3($a0)
    /* 20698 8001FA98 0000A825 */  or         $s5, $zero, $zero
    /* 2069C 8001FA9C 13200003 */  beqz       $t9, .L8001FAAC
    /* 206A0 8001FAA0 00000000 */   nop
    /* 206A4 8001FAA4 0C007E74 */  jal        func_8001F9D0
    /* 206A8 8001FAA8 00000000 */   nop
  .L8001FAAC:
    /* 206AC 8001FAAC 0C0052CF */  jal        func_80014B3C
    /* 206B0 8001FAB0 02002025 */   or        $a0, $s0, $zero
  .L8001FAB4:
    /* 206B4 8001FAB4 1632FFEC */  bne        $s1, $s2, .L8001FA68
    /* 206B8 8001FAB8 02202825 */   or        $a1, $s1, $zero
  .L8001FABC:
    /* 206BC 8001FABC 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 206C0 8001FAC0 02A01025 */  or         $v0, $s5, $zero
    /* 206C4 8001FAC4 8FB50028 */  lw         $s5, 0x28($sp)
    /* 206C8 8001FAC8 8FB00014 */  lw         $s0, 0x14($sp)
    /* 206CC 8001FACC 8FB10018 */  lw         $s1, 0x18($sp)
    /* 206D0 8001FAD0 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 206D4 8001FAD4 8FB30020 */  lw         $s3, 0x20($sp)
    /* 206D8 8001FAD8 8FB40024 */  lw         $s4, 0x24($sp)
    /* 206DC 8001FADC 03E00008 */  jr         $ra
    /* 206E0 8001FAE0 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_8001FA18

nonmatching func_8001FAE4, 0xC8

glabel func_8001FAE4
    /* 206E4 8001FAE4 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 206E8 8001FAE8 3C028005 */  lui        $v0, %hi(D_8004FA18)
    /* 206EC 8001FAEC 9042FA18 */  lbu        $v0, %lo(D_8004FA18)($v0)
    /* 206F0 8001FAF0 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 206F4 8001FAF4 AFB10018 */  sw         $s1, 0x18($sp)
    /* 206F8 8001FAF8 309200FF */  andi       $s2, $a0, 0xFF
    /* 206FC 8001FAFC AFBF0024 */  sw         $ra, 0x24($sp)
    /* 20700 8001FB00 AFB30020 */  sw         $s3, 0x20($sp)
    /* 20704 8001FB04 AFB00014 */  sw         $s0, 0x14($sp)
    /* 20708 8001FB08 AFA40028 */  sw         $a0, 0x28($sp)
    /* 2070C 8001FB0C 18400020 */  blez       $v0, .L8001FB90
    /* 20710 8001FB10 00008825 */   or        $s1, $zero, $zero
    /* 20714 8001FB14 3C108005 */  lui        $s0, %hi(D_8004BEB8)
    /* 20718 8001FB18 2610BEB8 */  addiu      $s0, $s0, %lo(D_8004BEB8)
    /* 2071C 8001FB1C 2413FFFC */  addiu      $s3, $zero, -0x4
  .L8001FB20:
    /* 20720 8001FB20 8A0E0000 */  lwl        $t6, 0x0($s0)
    /* 20724 8001FB24 9A0E0003 */  lwr        $t6, 0x3($s0)
    /* 20728 8001FB28 11C00011 */  beqz       $t6, .L8001FB70
    /* 2072C 8001FB2C 00000000 */   nop
    /* 20730 8001FB30 12400006 */  beqz       $s2, .L8001FB4C
    /* 20734 8001FB34 00000000 */   nop
    /* 20738 8001FB38 52400012 */  beql       $s2, $zero, .L8001FB84
    /* 2073C 8001FB3C 26310001 */   addiu     $s1, $s1, 0x1
    /* 20740 8001FB40 920F004C */  lbu        $t7, 0x4C($s0)
    /* 20744 8001FB44 55E0000F */  bnel       $t7, $zero, .L8001FB84
    /* 20748 8001FB48 26310001 */   addiu     $s1, $s1, 0x1
  .L8001FB4C:
    /* 2074C 8001FB4C 0C007E74 */  jal        func_8001F9D0
    /* 20750 8001FB50 02002025 */   or        $a0, $s0, $zero
    /* 20754 8001FB54 8A180024 */  lwl        $t8, 0x24($s0)
    /* 20758 8001FB58 9A180027 */  lwr        $t8, 0x27($s0)
    /* 2075C 8001FB5C AA000000 */  swl        $zero, 0x0($s0)
    /* 20760 8001FB60 BA000003 */  swr        $zero, 0x3($s0)
    /* 20764 8001FB64 0313C824 */  and        $t9, $t8, $s3
    /* 20768 8001FB68 AA190024 */  swl        $t9, 0x24($s0)
    /* 2076C 8001FB6C BA190027 */  swr        $t9, 0x27($s0)
  .L8001FB70:
    /* 20770 8001FB70 0C0052CF */  jal        func_80014B3C
    /* 20774 8001FB74 02202025 */   or        $a0, $s1, $zero
    /* 20778 8001FB78 3C028005 */  lui        $v0, %hi(D_8004FA18)
    /* 2077C 8001FB7C 9042FA18 */  lbu        $v0, %lo(D_8004FA18)($v0)
    /* 20780 8001FB80 26310001 */  addiu      $s1, $s1, 0x1
  .L8001FB84:
    /* 20784 8001FB84 0222082A */  slt        $at, $s1, $v0
    /* 20788 8001FB88 1420FFE5 */  bnez       $at, .L8001FB20
    /* 2078C 8001FB8C 261001A0 */   addiu     $s0, $s0, 0x1A0
  .L8001FB90:
    /* 20790 8001FB90 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 20794 8001FB94 8FB00014 */  lw         $s0, 0x14($sp)
    /* 20798 8001FB98 8FB10018 */  lw         $s1, 0x18($sp)
    /* 2079C 8001FB9C 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 207A0 8001FBA0 8FB30020 */  lw         $s3, 0x20($sp)
    /* 207A4 8001FBA4 03E00008 */  jr         $ra
    /* 207A8 8001FBA8 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_8001FAE4
    /* 207AC 8001FBAC 00000000 */  nop
