.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8001FBB0, 0x17C

glabel func_8001FBB0
    /* 207B0 8001FBB0 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 207B4 8001FBB4 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 207B8 8001FBB8 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 207BC 8001FBBC AFBE0038 */  sw         $fp, 0x38($sp)
    /* 207C0 8001FBC0 AFB60030 */  sw         $s6, 0x30($sp)
    /* 207C4 8001FBC4 AFB00018 */  sw         $s0, 0x18($sp)
    /* 207C8 8001FBC8 00808025 */  or         $s0, $a0, $zero
    /* 207CC 8001FBCC 30B6FFFF */  andi       $s6, $a1, 0xFFFF
    /* 207D0 8001FBD0 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 207D4 8001FBD4 AFB70034 */  sw         $s7, 0x34($sp)
    /* 207D8 8001FBD8 AFB5002C */  sw         $s5, 0x2C($sp)
    /* 207DC 8001FBDC AFB40028 */  sw         $s4, 0x28($sp)
    /* 207E0 8001FBE0 AFB30024 */  sw         $s3, 0x24($sp)
    /* 207E4 8001FBE4 AFB20020 */  sw         $s2, 0x20($sp)
    /* 207E8 8001FBE8 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 207EC 8001FBEC AFA50044 */  sw         $a1, 0x44($sp)
    /* 207F0 8001FBF0 11C00041 */  beqz       $t6, .L8001FCF8
    /* 207F4 8001FBF4 241EFFFF */   addiu     $fp, $zero, -0x1
    /* 207F8 8001FBF8 0C005165 */  jal        func_80014594
    /* 207FC 8001FBFC 00000000 */   nop
    /* 20800 8001FC00 0C007B7D */  jal        func_8001EDF4
    /* 20804 8001FC04 02002025 */   or        $a0, $s0, $zero
    /* 20808 8001FC08 2417FFFF */  addiu      $s7, $zero, -0x1
    /* 2080C 8001FC0C 10570038 */  beq        $v0, $s7, .L8001FCF0
    /* 20810 8001FC10 00408025 */   or        $s0, $v0, $zero
    /* 20814 8001FC14 3C148005 */  lui        $s4, %hi(D_8004BEB8)
    /* 20818 8001FC18 2694BEB8 */  addiu      $s4, $s4, %lo(D_8004BEB8)
    /* 2081C 8001FC1C 241501A0 */  addiu      $s5, $zero, 0x1A0
    /* 20820 8001FC20 320200FF */  andi       $v0, $s0, 0xFF
  .L8001FC24:
    /* 20824 8001FC24 00550019 */  multu      $v0, $s5
    /* 20828 8001FC28 001639C3 */  sra        $a3, $s6, 7
    /* 2082C 8001FC2C 00409825 */  or         $s3, $v0, $zero
    /* 20830 8001FC30 30E700FF */  andi       $a3, $a3, 0xFF
    /* 20834 8001FC34 24040001 */  addiu      $a0, $zero, 0x1
    /* 20838 8001FC38 00007812 */  mflo       $t7
    /* 2083C 8001FC3C 028F8821 */  addu       $s1, $s4, $t7
    /* 20840 8001FC40 8A380060 */  lwl        $t8, 0x60($s1)
    /* 20844 8001FC44 9A380063 */  lwr        $t8, 0x63($s1)
    /* 20848 8001FC48 16180023 */  bne        $s0, $t8, .L8001FCD8
    /* 2084C 8001FC4C 00000000 */   nop
    /* 20850 8001FC50 8A390024 */  lwl        $t9, 0x24($s1)
    /* 20854 8001FC54 9A390027 */  lwr        $t9, 0x27($s1)
    /* 20858 8001FC58 02C09025 */  or         $s2, $s6, $zero
    /* 2085C 8001FC5C 3252007F */  andi       $s2, $s2, 0x7F
    /* 20860 8001FC60 33280002 */  andi       $t0, $t9, 0x2
    /* 20864 8001FC64 1100000D */  beqz       $t0, .L8001FC9C
    /* 20868 8001FC68 0000F025 */   or        $fp, $zero, $zero
    /* 2086C 8001FC6C 305000FF */  andi       $s0, $v0, 0xFF
    /* 20870 8001FC70 320500FF */  andi       $a1, $s0, 0xFF
    /* 20874 8001FC74 24040001 */  addiu      $a0, $zero, 0x1
    /* 20878 8001FC78 0C008184 */  jal        func_80020610
    /* 2087C 8001FC7C 92260055 */   lbu       $a2, 0x55($s1)
    /* 20880 8001FC80 24040021 */  addiu      $a0, $zero, 0x21
    /* 20884 8001FC84 320500FF */  andi       $a1, $s0, 0xFF
    /* 20888 8001FC88 92260055 */  lbu        $a2, 0x55($s1)
    /* 2088C 8001FC8C 0C008184 */  jal        func_80020610
    /* 20890 8001FC90 324700FF */   andi      $a3, $s2, 0xFF
    /* 20894 8001FC94 1000000A */  b          .L8001FCC0
    /* 20898 8001FC98 00000000 */   nop
  .L8001FC9C:
    /* 2089C 8001FC9C 305000FF */  andi       $s0, $v0, 0xFF
    /* 208A0 8001FCA0 320500FF */  andi       $a1, $s0, 0xFF
    /* 208A4 8001FCA4 0C008184 */  jal        func_80020610
    /* 208A8 8001FCA8 9226004B */   lbu       $a2, 0x4B($s1)
    /* 208AC 8001FCAC 24040021 */  addiu      $a0, $zero, 0x21
    /* 208B0 8001FCB0 320500FF */  andi       $a1, $s0, 0xFF
    /* 208B4 8001FCB4 9226004B */  lbu        $a2, 0x4B($s1)
    /* 208B8 8001FCB8 0C008184 */  jal        func_80020610
    /* 208BC 8001FCBC 324700FF */   andi      $a3, $s2, 0xFF
  .L8001FCC0:
    /* 208C0 8001FCC0 02750019 */  multu      $s3, $s5
    /* 208C4 8001FCC4 00004812 */  mflo       $t1
    /* 208C8 8001FCC8 02895021 */  addu       $t2, $s4, $t1
    /* 208CC 8001FCCC 89500010 */  lwl        $s0, 0x10($t2)
    /* 208D0 8001FCD0 10000005 */  b          .L8001FCE8
    /* 208D4 8001FCD4 99500013 */   lwr       $s0, 0x13($t2)
  .L8001FCD8:
    /* 208D8 8001FCD8 0C005177 */  jal        func_800145DC
    /* 208DC 8001FCDC 00000000 */   nop
    /* 208E0 8001FCE0 10000006 */  b          .L8001FCFC
    /* 208E4 8001FCE4 03C01025 */   or        $v0, $fp, $zero
  .L8001FCE8:
    /* 208E8 8001FCE8 5617FFCE */  bnel       $s0, $s7, .L8001FC24
    /* 208EC 8001FCEC 320200FF */   andi      $v0, $s0, 0xFF
  .L8001FCF0:
    /* 208F0 8001FCF0 0C005177 */  jal        func_800145DC
    /* 208F4 8001FCF4 00000000 */   nop
  .L8001FCF8:
    /* 208F8 8001FCF8 03C01025 */  or         $v0, $fp, $zero
  .L8001FCFC:
    /* 208FC 8001FCFC 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 20900 8001FD00 8FB00018 */  lw         $s0, 0x18($sp)
    /* 20904 8001FD04 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 20908 8001FD08 8FB20020 */  lw         $s2, 0x20($sp)
    /* 2090C 8001FD0C 8FB30024 */  lw         $s3, 0x24($sp)
    /* 20910 8001FD10 8FB40028 */  lw         $s4, 0x28($sp)
    /* 20914 8001FD14 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 20918 8001FD18 8FB60030 */  lw         $s6, 0x30($sp)
    /* 2091C 8001FD1C 8FB70034 */  lw         $s7, 0x34($sp)
    /* 20920 8001FD20 8FBE0038 */  lw         $fp, 0x38($sp)
    /* 20924 8001FD24 03E00008 */  jr         $ra
    /* 20928 8001FD28 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_8001FBB0

nonmatching func_8001FD2C, 0x12C

glabel func_8001FD2C
    /* 2092C 8001FD2C 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 20930 8001FD30 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20934 8001FD34 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20938 8001FD38 AFB50028 */  sw         $s5, 0x28($sp)
    /* 2093C 8001FD3C AFB30020 */  sw         $s3, 0x20($sp)
    /* 20940 8001FD40 30B300FF */  andi       $s3, $a1, 0xFF
    /* 20944 8001FD44 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 20948 8001FD48 AFB40024 */  sw         $s4, 0x24($sp)
    /* 2094C 8001FD4C AFB2001C */  sw         $s2, 0x1C($sp)
    /* 20950 8001FD50 AFB10018 */  sw         $s1, 0x18($sp)
    /* 20954 8001FD54 AFB00014 */  sw         $s0, 0x14($sp)
    /* 20958 8001FD58 AFA50034 */  sw         $a1, 0x34($sp)
    /* 2095C 8001FD5C 11C00034 */  beqz       $t6, .L8001FE30
    /* 20960 8001FD60 2415FFFF */   addiu     $s5, $zero, -0x1
    /* 20964 8001FD64 0C005165 */  jal        func_80014594
    /* 20968 8001FD68 AFA40030 */   sw        $a0, 0x30($sp)
    /* 2096C 8001FD6C 0C007B7D */  jal        func_8001EDF4
    /* 20970 8001FD70 8FA40030 */   lw        $a0, 0x30($sp)
    /* 20974 8001FD74 2414FFFF */  addiu      $s4, $zero, -0x1
    /* 20978 8001FD78 1054002B */  beq        $v0, $s4, .L8001FE28
    /* 2097C 8001FD7C 00402025 */   or        $a0, $v0, $zero
    /* 20980 8001FD80 3C118005 */  lui        $s1, %hi(D_8004BEB8)
    /* 20984 8001FD84 2631BEB8 */  addiu      $s1, $s1, %lo(D_8004BEB8)
    /* 20988 8001FD88 241201A0 */  addiu      $s2, $zero, 0x1A0
    /* 2098C 8001FD8C 308200FF */  andi       $v0, $a0, 0xFF
  .L8001FD90:
    /* 20990 8001FD90 00520019 */  multu      $v0, $s2
    /* 20994 8001FD94 00408025 */  or         $s0, $v0, $zero
    /* 20998 8001FD98 304500FF */  andi       $a1, $v0, 0xFF
    /* 2099C 8001FD9C 326700FF */  andi       $a3, $s3, 0xFF
    /* 209A0 8001FDA0 00007812 */  mflo       $t7
    /* 209A4 8001FDA4 022F1821 */  addu       $v1, $s1, $t7
    /* 209A8 8001FDA8 88780060 */  lwl        $t8, 0x60($v1)
    /* 209AC 8001FDAC 98780063 */  lwr        $t8, 0x63($v1)
    /* 209B0 8001FDB0 14980017 */  bne        $a0, $t8, .L8001FE10
    /* 209B4 8001FDB4 00000000 */   nop
    /* 209B8 8001FDB8 88790024 */  lwl        $t9, 0x24($v1)
    /* 209BC 8001FDBC 98790027 */  lwr        $t9, 0x27($v1)
    /* 209C0 8001FDC0 0000A825 */  or         $s5, $zero, $zero
    /* 209C4 8001FDC4 2404005B */  addiu      $a0, $zero, 0x5B
    /* 209C8 8001FDC8 33280002 */  andi       $t0, $t9, 0x2
    /* 209CC 8001FDCC 11000008 */  beqz       $t0, .L8001FDF0
    /* 209D0 8001FDD0 00000000 */   nop
    /* 209D4 8001FDD4 2404005B */  addiu      $a0, $zero, 0x5B
    /* 209D8 8001FDD8 304500FF */  andi       $a1, $v0, 0xFF
    /* 209DC 8001FDDC 90660055 */  lbu        $a2, 0x55($v1)
    /* 209E0 8001FDE0 0C008184 */  jal        func_80020610
    /* 209E4 8001FDE4 326700FF */   andi      $a3, $s3, 0xFF
    /* 209E8 8001FDE8 10000003 */  b          .L8001FDF8
    /* 209EC 8001FDEC 00000000 */   nop
  .L8001FDF0:
    /* 209F0 8001FDF0 0C008184 */  jal        func_80020610
    /* 209F4 8001FDF4 9066004B */   lbu       $a2, 0x4B($v1)
  .L8001FDF8:
    /* 209F8 8001FDF8 02120019 */  multu      $s0, $s2
    /* 209FC 8001FDFC 00004812 */  mflo       $t1
    /* 20A00 8001FE00 02295021 */  addu       $t2, $s1, $t1
    /* 20A04 8001FE04 89440010 */  lwl        $a0, 0x10($t2)
    /* 20A08 8001FE08 10000005 */  b          .L8001FE20
    /* 20A0C 8001FE0C 99440013 */   lwr       $a0, 0x13($t2)
  .L8001FE10:
    /* 20A10 8001FE10 0C005177 */  jal        func_800145DC
    /* 20A14 8001FE14 00000000 */   nop
    /* 20A18 8001FE18 10000006 */  b          .L8001FE34
    /* 20A1C 8001FE1C 02A01025 */   or        $v0, $s5, $zero
  .L8001FE20:
    /* 20A20 8001FE20 5494FFDB */  bnel       $a0, $s4, .L8001FD90
    /* 20A24 8001FE24 308200FF */   andi      $v0, $a0, 0xFF
  .L8001FE28:
    /* 20A28 8001FE28 0C005177 */  jal        func_800145DC
    /* 20A2C 8001FE2C 00000000 */   nop
  .L8001FE30:
    /* 20A30 8001FE30 02A01025 */  or         $v0, $s5, $zero
  .L8001FE34:
    /* 20A34 8001FE34 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 20A38 8001FE38 8FB00014 */  lw         $s0, 0x14($sp)
    /* 20A3C 8001FE3C 8FB10018 */  lw         $s1, 0x18($sp)
    /* 20A40 8001FE40 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 20A44 8001FE44 8FB30020 */  lw         $s3, 0x20($sp)
    /* 20A48 8001FE48 8FB40024 */  lw         $s4, 0x24($sp)
    /* 20A4C 8001FE4C 8FB50028 */  lw         $s5, 0x28($sp)
    /* 20A50 8001FE50 03E00008 */  jr         $ra
    /* 20A54 8001FE54 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_8001FD2C

nonmatching func_8001FE58, 0x4C

glabel func_8001FE58
    /* 20A58 8001FE58 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20A5C 8001FE5C 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20A60 8001FE60 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20A64 8001FE64 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20A68 8001FE68 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20A6C 8001FE6C 11C00008 */  beqz       $t6, .L8001FE90
    /* 20A70 8001FE70 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20A74 8001FE74 0C005165 */  jal        func_80014594
    /* 20A78 8001FE78 00000000 */   nop
    /* 20A7C 8001FE7C 0C006E31 */  jal        func_8001B8C4
    /* 20A80 8001FE80 8FA40020 */   lw        $a0, 0x20($sp)
    /* 20A84 8001FE84 0C005177 */  jal        func_800145DC
    /* 20A88 8001FE88 AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20A8C 8001FE8C 8FA3001C */  lw         $v1, 0x1C($sp)
  .L8001FE90:
    /* 20A90 8001FE90 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20A94 8001FE94 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20A98 8001FE98 00601025 */  or         $v0, $v1, $zero
    /* 20A9C 8001FE9C 03E00008 */  jr         $ra
    /* 20AA0 8001FEA0 00000000 */   nop
endlabel func_8001FE58

nonmatching func_8001FEA4, 0x54

glabel func_8001FEA4
    /* 20AA4 8001FEA4 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20AA8 8001FEA8 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20AAC 8001FEAC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20AB0 8001FEB0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20AB4 8001FEB4 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20AB8 8001FEB8 AFA50024 */  sw         $a1, 0x24($sp)
    /* 20ABC 8001FEBC 11C00009 */  beqz       $t6, .L8001FEE4
    /* 20AC0 8001FEC0 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20AC4 8001FEC4 0C005165 */  jal        func_80014594
    /* 20AC8 8001FEC8 00000000 */   nop
    /* 20ACC 8001FECC 8FA40020 */  lw         $a0, 0x20($sp)
    /* 20AD0 8001FED0 0C006DF0 */  jal        func_8001B7C0
    /* 20AD4 8001FED4 93A50027 */   lbu       $a1, 0x27($sp)
    /* 20AD8 8001FED8 0C005177 */  jal        func_800145DC
    /* 20ADC 8001FEDC AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20AE0 8001FEE0 8FA3001C */  lw         $v1, 0x1C($sp)
  .L8001FEE4:
    /* 20AE4 8001FEE4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20AE8 8001FEE8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20AEC 8001FEEC 00601025 */  or         $v0, $v1, $zero
    /* 20AF0 8001FEF0 03E00008 */  jr         $ra
    /* 20AF4 8001FEF4 00000000 */   nop
endlabel func_8001FEA4

nonmatching func_8001FEF8, 0x54

glabel func_8001FEF8
    /* 20AF8 8001FEF8 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20AFC 8001FEFC 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20B00 8001FF00 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20B04 8001FF04 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20B08 8001FF08 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20B0C 8001FF0C AFA50024 */  sw         $a1, 0x24($sp)
    /* 20B10 8001FF10 11C00009 */  beqz       $t6, .L8001FF38
    /* 20B14 8001FF14 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20B18 8001FF18 0C005165 */  jal        func_80014594
    /* 20B1C 8001FF1C 00000000 */   nop
    /* 20B20 8001FF20 8FA40020 */  lw         $a0, 0x20($sp)
    /* 20B24 8001FF24 0C006D7D */  jal        func_8001B5F4
    /* 20B28 8001FF28 97A50026 */   lhu       $a1, 0x26($sp)
    /* 20B2C 8001FF2C 0C005177 */  jal        func_800145DC
    /* 20B30 8001FF30 AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20B34 8001FF34 8FA3001C */  lw         $v1, 0x1C($sp)
  .L8001FF38:
    /* 20B38 8001FF38 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20B3C 8001FF3C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20B40 8001FF40 00601025 */  or         $v0, $v1, $zero
    /* 20B44 8001FF44 03E00008 */  jr         $ra
    /* 20B48 8001FF48 00000000 */   nop
endlabel func_8001FEF8

nonmatching func_8001FF4C, 0x54

glabel func_8001FF4C
    /* 20B4C 8001FF4C 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20B50 8001FF50 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20B54 8001FF54 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20B58 8001FF58 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20B5C 8001FF5C AFA40020 */  sw         $a0, 0x20($sp)
    /* 20B60 8001FF60 AFA50024 */  sw         $a1, 0x24($sp)
    /* 20B64 8001FF64 11C00009 */  beqz       $t6, .L8001FF8C
    /* 20B68 8001FF68 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20B6C 8001FF6C 0C005165 */  jal        func_80014594
    /* 20B70 8001FF70 00000000 */   nop
    /* 20B74 8001FF74 8FA40020 */  lw         $a0, 0x20($sp)
    /* 20B78 8001FF78 0C006CE8 */  jal        func_8001B3A0
    /* 20B7C 8001FF7C 93A50027 */   lbu       $a1, 0x27($sp)
    /* 20B80 8001FF80 0C005177 */  jal        func_800145DC
    /* 20B84 8001FF84 AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20B88 8001FF88 8FA3001C */  lw         $v1, 0x1C($sp)
  .L8001FF8C:
    /* 20B8C 8001FF8C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20B90 8001FF90 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20B94 8001FF94 00601025 */  or         $v0, $v1, $zero
    /* 20B98 8001FF98 03E00008 */  jr         $ra
    /* 20B9C 8001FF9C 00000000 */   nop
endlabel func_8001FF4C

nonmatching func_8001FFA0, 0x54

glabel func_8001FFA0
    /* 20BA0 8001FFA0 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20BA4 8001FFA4 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20BA8 8001FFA8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20BAC 8001FFAC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20BB0 8001FFB0 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20BB4 8001FFB4 AFA50024 */  sw         $a1, 0x24($sp)
    /* 20BB8 8001FFB8 11C00009 */  beqz       $t6, .L8001FFE0
    /* 20BBC 8001FFBC 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20BC0 8001FFC0 0C005165 */  jal        func_80014594
    /* 20BC4 8001FFC4 00000000 */   nop
    /* 20BC8 8001FFC8 8FA40020 */  lw         $a0, 0x20($sp)
    /* 20BCC 8001FFCC 0C006D29 */  jal        func_8001B4A4
    /* 20BD0 8001FFD0 97A50026 */   lhu       $a1, 0x26($sp)
    /* 20BD4 8001FFD4 0C005177 */  jal        func_800145DC
    /* 20BD8 8001FFD8 AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20BDC 8001FFDC 8FA3001C */  lw         $v1, 0x1C($sp)
  .L8001FFE0:
    /* 20BE0 8001FFE0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20BE4 8001FFE4 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20BE8 8001FFE8 00601025 */  or         $v0, $v1, $zero
    /* 20BEC 8001FFEC 03E00008 */  jr         $ra
    /* 20BF0 8001FFF0 00000000 */   nop
endlabel func_8001FFA0

nonmatching func_8001FFF4, 0x54

glabel func_8001FFF4
    /* 20BF4 8001FFF4 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20BF8 8001FFF8 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20BFC 8001FFFC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20C00 80020000 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20C04 80020004 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20C08 80020008 AFA50024 */  sw         $a1, 0x24($sp)
    /* 20C0C 8002000C 11C00009 */  beqz       $t6, .L80020034
    /* 20C10 80020010 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20C14 80020014 0C005165 */  jal        func_80014594
    /* 20C18 80020018 00000000 */   nop
    /* 20C1C 8002001C 8FA40020 */  lw         $a0, 0x20($sp)
    /* 20C20 80020020 0C006CA7 */  jal        func_8001B29C
    /* 20C24 80020024 93A50027 */   lbu       $a1, 0x27($sp)
    /* 20C28 80020028 0C005177 */  jal        func_800145DC
    /* 20C2C 8002002C AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20C30 80020030 8FA3001C */  lw         $v1, 0x1C($sp)
  .L80020034:
    /* 20C34 80020034 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20C38 80020038 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20C3C 8002003C 00601025 */  or         $v0, $v1, $zero
    /* 20C40 80020040 03E00008 */  jr         $ra
    /* 20C44 80020044 00000000 */   nop
endlabel func_8001FFF4

nonmatching func_80020048, 0x12C

glabel func_80020048
    /* 20C48 80020048 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 20C4C 8002004C 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20C50 80020050 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20C54 80020054 AFB50028 */  sw         $s5, 0x28($sp)
    /* 20C58 80020058 AFB30020 */  sw         $s3, 0x20($sp)
    /* 20C5C 8002005C 30B300FF */  andi       $s3, $a1, 0xFF
    /* 20C60 80020060 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 20C64 80020064 AFB40024 */  sw         $s4, 0x24($sp)
    /* 20C68 80020068 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 20C6C 8002006C AFB10018 */  sw         $s1, 0x18($sp)
    /* 20C70 80020070 AFB00014 */  sw         $s0, 0x14($sp)
    /* 20C74 80020074 AFA50034 */  sw         $a1, 0x34($sp)
    /* 20C78 80020078 11C00034 */  beqz       $t6, .L8002014C
    /* 20C7C 8002007C 2415FFFF */   addiu     $s5, $zero, -0x1
    /* 20C80 80020080 0C005165 */  jal        func_80014594
    /* 20C84 80020084 AFA40030 */   sw        $a0, 0x30($sp)
    /* 20C88 80020088 0C007B7D */  jal        func_8001EDF4
    /* 20C8C 8002008C 8FA40030 */   lw        $a0, 0x30($sp)
    /* 20C90 80020090 2414FFFF */  addiu      $s4, $zero, -0x1
    /* 20C94 80020094 1054002B */  beq        $v0, $s4, .L80020144
    /* 20C98 80020098 00402025 */   or        $a0, $v0, $zero
    /* 20C9C 8002009C 3C118005 */  lui        $s1, %hi(D_8004BEB8)
    /* 20CA0 800200A0 2631BEB8 */  addiu      $s1, $s1, %lo(D_8004BEB8)
    /* 20CA4 800200A4 241201A0 */  addiu      $s2, $zero, 0x1A0
    /* 20CA8 800200A8 308200FF */  andi       $v0, $a0, 0xFF
  .L800200AC:
    /* 20CAC 800200AC 00520019 */  multu      $v0, $s2
    /* 20CB0 800200B0 00408025 */  or         $s0, $v0, $zero
    /* 20CB4 800200B4 304500FF */  andi       $a1, $v0, 0xFF
    /* 20CB8 800200B8 326700FF */  andi       $a3, $s3, 0xFF
    /* 20CBC 800200BC 00007812 */  mflo       $t7
    /* 20CC0 800200C0 022F1821 */  addu       $v1, $s1, $t7
    /* 20CC4 800200C4 88780060 */  lwl        $t8, 0x60($v1)
    /* 20CC8 800200C8 98780063 */  lwr        $t8, 0x63($v1)
    /* 20CCC 800200CC 14980017 */  bne        $a0, $t8, .L8002012C
    /* 20CD0 800200D0 00000000 */   nop
    /* 20CD4 800200D4 88790024 */  lwl        $t9, 0x24($v1)
    /* 20CD8 800200D8 98790027 */  lwr        $t9, 0x27($v1)
    /* 20CDC 800200DC 0000A825 */  or         $s5, $zero, $zero
    /* 20CE0 800200E0 24040040 */  addiu      $a0, $zero, 0x40
    /* 20CE4 800200E4 33280002 */  andi       $t0, $t9, 0x2
    /* 20CE8 800200E8 11000008 */  beqz       $t0, .L8002010C
    /* 20CEC 800200EC 00000000 */   nop
    /* 20CF0 800200F0 24040040 */  addiu      $a0, $zero, 0x40
    /* 20CF4 800200F4 304500FF */  andi       $a1, $v0, 0xFF
    /* 20CF8 800200F8 90660055 */  lbu        $a2, 0x55($v1)
    /* 20CFC 800200FC 0C008184 */  jal        func_80020610
    /* 20D00 80020100 326700FF */   andi      $a3, $s3, 0xFF
    /* 20D04 80020104 10000003 */  b          .L80020114
    /* 20D08 80020108 00000000 */   nop
  .L8002010C:
    /* 20D0C 8002010C 0C008184 */  jal        func_80020610
    /* 20D10 80020110 9066004B */   lbu       $a2, 0x4B($v1)
  .L80020114:
    /* 20D14 80020114 02120019 */  multu      $s0, $s2
    /* 20D18 80020118 00004812 */  mflo       $t1
    /* 20D1C 8002011C 02295021 */  addu       $t2, $s1, $t1
    /* 20D20 80020120 89440010 */  lwl        $a0, 0x10($t2)
    /* 20D24 80020124 10000005 */  b          .L8002013C
    /* 20D28 80020128 99440013 */   lwr       $a0, 0x13($t2)
  .L8002012C:
    /* 20D2C 8002012C 0C005177 */  jal        func_800145DC
    /* 20D30 80020130 00000000 */   nop
    /* 20D34 80020134 10000006 */  b          .L80020150
    /* 20D38 80020138 02A01025 */   or        $v0, $s5, $zero
  .L8002013C:
    /* 20D3C 8002013C 5494FFDB */  bnel       $a0, $s4, .L800200AC
    /* 20D40 80020140 308200FF */   andi      $v0, $a0, 0xFF
  .L80020144:
    /* 20D44 80020144 0C005177 */  jal        func_800145DC
    /* 20D48 80020148 00000000 */   nop
  .L8002014C:
    /* 20D4C 8002014C 02A01025 */  or         $v0, $s5, $zero
  .L80020150:
    /* 20D50 80020150 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 20D54 80020154 8FB00014 */  lw         $s0, 0x14($sp)
    /* 20D58 80020158 8FB10018 */  lw         $s1, 0x18($sp)
    /* 20D5C 8002015C 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 20D60 80020160 8FB30020 */  lw         $s3, 0x20($sp)
    /* 20D64 80020164 8FB40024 */  lw         $s4, 0x24($sp)
    /* 20D68 80020168 8FB50028 */  lw         $s5, 0x28($sp)
    /* 20D6C 8002016C 03E00008 */  jr         $ra
    /* 20D70 80020170 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_80020048

nonmatching func_80020174, 0x5C

glabel func_80020174
    /* 20D74 80020174 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20D78 80020178 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20D7C 8002017C 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20D80 80020180 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20D84 80020184 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20D88 80020188 AFA50024 */  sw         $a1, 0x24($sp)
    /* 20D8C 8002018C AFA60028 */  sw         $a2, 0x28($sp)
    /* 20D90 80020190 11C0000A */  beqz       $t6, .L800201BC
    /* 20D94 80020194 2403FFFF */   addiu     $v1, $zero, -0x1
    /* 20D98 80020198 0C005165 */  jal        func_80014594
    /* 20D9C 8002019C 00000000 */   nop
    /* 20DA0 800201A0 97A40022 */  lhu        $a0, 0x22($sp)
    /* 20DA4 800201A4 93A50027 */  lbu        $a1, 0x27($sp)
    /* 20DA8 800201A8 0C006C74 */  jal        func_8001B1D0
    /* 20DAC 800201AC 93A6002B */   lbu       $a2, 0x2B($sp)
    /* 20DB0 800201B0 0C005177 */  jal        func_800145DC
    /* 20DB4 800201B4 AFA2001C */   sw        $v0, 0x1C($sp)
    /* 20DB8 800201B8 8FA3001C */  lw         $v1, 0x1C($sp)
  .L800201BC:
    /* 20DBC 800201BC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20DC0 800201C0 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20DC4 800201C4 00601025 */  or         $v0, $v1, $zero
    /* 20DC8 800201C8 03E00008 */  jr         $ra
    /* 20DCC 800201CC 00000000 */   nop
endlabel func_80020174

nonmatching func_800201D0, 0x30

glabel func_800201D0
    /* 20DD0 800201D0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 20DD4 800201D4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20DD8 800201D8 0C007B7D */  jal        func_8001EDF4
    /* 20DDC 800201DC AFA40018 */   sw        $a0, 0x18($sp)
    /* 20DE0 800201E0 2401FFFF */  addiu      $at, $zero, -0x1
    /* 20DE4 800201E4 10410003 */  beq        $v0, $at, .L800201F4
    /* 20DE8 800201E8 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 20DEC 800201EC 10000002 */  b          .L800201F8
    /* 20DF0 800201F0 8FA20018 */   lw        $v0, 0x18($sp)
  .L800201F4:
    /* 20DF4 800201F4 2402FFFF */  addiu      $v0, $zero, -0x1
  .L800201F8:
    /* 20DF8 800201F8 03E00008 */  jr         $ra
    /* 20DFC 800201FC 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800201D0

nonmatching func_80020200, 0x1C

glabel func_80020200
    /* 20E00 80020200 308E000F */  andi       $t6, $a0, 0xF
    /* 20E04 80020204 000E7840 */  sll        $t7, $t6, 1
    /* 20E08 80020208 3C028005 */  lui        $v0, %hi(D_8004BE98)
    /* 20E0C 8002020C 004F1021 */  addu       $v0, $v0, $t7
    /* 20E10 80020210 AFA40000 */  sw         $a0, 0x0($sp)
    /* 20E14 80020214 03E00008 */  jr         $ra
    /* 20E18 80020218 8442BE98 */   lh        $v0, %lo(D_8004BE98)($v0)
endlabel func_80020200

nonmatching func_8002021C, 0x58

glabel func_8002021C
    /* 20E1C 8002021C 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 20E20 80020220 AFA40020 */  sw         $a0, 0x20($sp)
    /* 20E24 80020224 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20E28 80020228 3084000F */  andi       $a0, $a0, 0xF
    /* 20E2C 8002022C AFA50024 */  sw         $a1, 0x24($sp)
    /* 20E30 80020230 0C005165 */  jal        func_80014594
    /* 20E34 80020234 A3A40023 */   sb        $a0, 0x23($sp)
    /* 20E38 80020238 93A40023 */  lbu        $a0, 0x23($sp)
    /* 20E3C 8002023C 3C0F8005 */  lui        $t7, %hi(D_8004BE98)
    /* 20E40 80020240 25EFBE98 */  addiu      $t7, $t7, %lo(D_8004BE98)
    /* 20E44 80020244 00047040 */  sll        $t6, $a0, 1
    /* 20E48 80020248 01CF1021 */  addu       $v0, $t6, $t7
    /* 20E4C 8002024C 84580000 */  lh         $t8, 0x0($v0)
    /* 20E50 80020250 87B90026 */  lh         $t9, 0x26($sp)
    /* 20E54 80020254 A7B8001E */  sh         $t8, 0x1E($sp)
    /* 20E58 80020258 0C005177 */  jal        func_800145DC
    /* 20E5C 8002025C A4590000 */   sh        $t9, 0x0($v0)
    /* 20E60 80020260 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20E64 80020264 87A2001E */  lh         $v0, 0x1E($sp)
    /* 20E68 80020268 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 20E6C 8002026C 03E00008 */  jr         $ra
    /* 20E70 80020270 00000000 */   nop
endlabel func_8002021C

nonmatching func_80020274, 0x50

glabel func_80020274
    /* 20E74 80020274 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20E78 80020278 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20E7C 8002027C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 20E80 80020280 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20E84 80020284 51C0000C */  beql       $t6, $zero, .L800202B8
    /* 20E88 80020288 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 20E8C 8002028C 0C005165 */  jal        func_80014594
    /* 20E90 80020290 00000000 */   nop
    /* 20E94 80020294 0C00639B */  jal        func_80018E6C
    /* 20E98 80020298 00000000 */   nop
    /* 20E9C 8002029C 0C00755E */  jal        func_8001D578
    /* 20EA0 800202A0 00000000 */   nop
    /* 20EA4 800202A4 0C007EB9 */  jal        func_8001FAE4
    /* 20EA8 800202A8 00002025 */   or        $a0, $zero, $zero
    /* 20EAC 800202AC 0C005177 */  jal        func_800145DC
    /* 20EB0 800202B0 00000000 */   nop
    /* 20EB4 800202B4 8FBF0014 */  lw         $ra, 0x14($sp)
  .L800202B8:
    /* 20EB8 800202B8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 20EBC 800202BC 03E00008 */  jr         $ra
    /* 20EC0 800202C0 00000000 */   nop
endlabel func_80020274

nonmatching func_800202C4, 0xAC

glabel func_800202C4
    /* 20EC4 800202C4 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20EC8 800202C8 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20ECC 800202CC 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 20ED0 800202D0 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 20ED4 800202D4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 20ED8 800202D8 AFB20020 */  sw         $s2, 0x20($sp)
    /* 20EDC 800202DC AFB00018 */  sw         $s0, 0x18($sp)
    /* 20EE0 800202E0 11C0001B */  beqz       $t6, .L80020350
    /* 20EE4 800202E4 00008825 */   or        $s1, $zero, $zero
    /* 20EE8 800202E8 3C188005 */  lui        $t8, %hi(D_8004BE94)
    /* 20EEC 800202EC 2718BE94 */  addiu      $t8, $t8, %lo(D_8004BE94)
    /* 20EF0 800202F0 240F0001 */  addiu      $t7, $zero, 0x1
    /* 20EF4 800202F4 0C0051AB */  jal        func_800146AC
    /* 20EF8 800202F8 A30F0000 */   sb        $t7, 0x0($t8)
    /* 20EFC 800202FC 14400010 */  bnez       $v0, .L80020340
    /* 20F00 80020300 3C128005 */   lui       $s2, %hi(D_8004FA18)
    /* 20F04 80020304 2652FA18 */  addiu      $s2, $s2, %lo(D_8004FA18)
    /* 20F08 80020308 92590000 */  lbu        $t9, 0x0($s2)
    /* 20F0C 8002030C 00008025 */  or         $s0, $zero, $zero
    /* 20F10 80020310 1B20000C */  blez       $t9, .L80020344
    /* 20F14 80020314 00000000 */   nop
  .L80020318:
    /* 20F18 80020318 0C00519F */  jal        func_8001467C
    /* 20F1C 8002031C 02002025 */   or        $a0, $s0, $zero
    /* 20F20 80020320 92480000 */  lbu        $t0, 0x0($s2)
    /* 20F24 80020324 26100001 */  addiu      $s0, $s0, 0x1
    /* 20F28 80020328 02228825 */  or         $s1, $s1, $v0
    /* 20F2C 8002032C 0208082A */  slt        $at, $s0, $t0
    /* 20F30 80020330 1420FFF9 */  bnez       $at, .L80020318
    /* 20F34 80020334 323100FF */   andi      $s1, $s1, 0xFF
    /* 20F38 80020338 10000002 */  b          .L80020344
    /* 20F3C 8002033C 00000000 */   nop
  .L80020340:
    /* 20F40 80020340 24110001 */  addiu      $s1, $zero, 0x1
  .L80020344:
    /* 20F44 80020344 3C098005 */  lui        $t1, %hi(D_8004BE94)
    /* 20F48 80020348 2529BE94 */  addiu      $t1, $t1, %lo(D_8004BE94)
    /* 20F4C 8002034C A1200000 */  sb         $zero, 0x0($t1)
  .L80020350:
    /* 20F50 80020350 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 20F54 80020354 2E220001 */  sltiu      $v0, $s1, 0x1
    /* 20F58 80020358 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 20F5C 8002035C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 20F60 80020360 8FB20020 */  lw         $s2, 0x20($sp)
    /* 20F64 80020364 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 20F68 80020368 03E00008 */  jr         $ra
    /* 20F6C 8002036C 304200FF */   andi      $v0, $v0, 0xFF
endlabel func_800202C4

nonmatching func_80020370, 0x7C

glabel func_80020370
    /* 20F70 80020370 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20F74 80020374 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20F78 80020378 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 20F7C 8002037C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20F80 80020380 AFA40018 */  sw         $a0, 0x18($sp)
    /* 20F84 80020384 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 20F88 80020388 11C00014 */  beqz       $t6, .L800203DC
    /* 20F8C 8002038C 30A600FF */   andi      $a2, $a1, 0xFF
    /* 20F90 80020390 0C005165 */  jal        func_80014594
    /* 20F94 80020394 A3A6001F */   sb        $a2, 0x1F($sp)
    /* 20F98 80020398 0C005C10 */  jal        func_80017040
    /* 20F9C 8002039C 97A4001A */   lhu       $a0, 0x1A($sp)
    /* 20FA0 800203A0 93A6001F */  lbu        $a2, 0x1F($sp)
    /* 20FA4 800203A4 1040000B */  beqz       $v0, .L800203D4
    /* 20FA8 800203A8 00401825 */   or        $v1, $v0, $zero
    /* 20FAC 800203AC 240100FE */  addiu      $at, $zero, 0xFE
    /* 20FB0 800203B0 10C10007 */  beq        $a2, $at, .L800203D0
    /* 20FB4 800203B4 240F001F */   addiu     $t7, $zero, 0x1F
    /* 20FB8 800203B8 A0660009 */  sb         $a2, 0x9($v1)
    /* 20FBC 800203BC 30C400FF */  andi       $a0, $a2, 0xFF
    /* 20FC0 800203C0 0C007067 */  jal        func_8001C19C
    /* 20FC4 800203C4 24050003 */   addiu     $a1, $zero, 0x3
    /* 20FC8 800203C8 10000002 */  b          .L800203D4
    /* 20FCC 800203CC 00000000 */   nop
  .L800203D0:
    /* 20FD0 800203D0 A04F0009 */  sb         $t7, 0x9($v0)
  .L800203D4:
    /* 20FD4 800203D4 0C005177 */  jal        func_800145DC
    /* 20FD8 800203D8 00000000 */   nop
  .L800203DC:
    /* 20FDC 800203DC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 20FE0 800203E0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 20FE4 800203E4 03E00008 */  jr         $ra
    /* 20FE8 800203E8 00000000 */   nop
endlabel func_80020370

nonmatching func_800203EC, 0x50

glabel func_800203EC
    /* 20FEC 800203EC 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 20FF0 800203F0 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 20FF4 800203F4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 20FF8 800203F8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 20FFC 800203FC AFA40018 */  sw         $a0, 0x18($sp)
    /* 21000 80020400 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 21004 80020404 11C00009 */  beqz       $t6, .L8002042C
    /* 21008 80020408 AFA60020 */   sw        $a2, 0x20($sp)
    /* 2100C 8002040C 0C005165 */  jal        func_80014594
    /* 21010 80020410 00000000 */   nop
    /* 21014 80020414 93A4001B */  lbu        $a0, 0x1B($sp)
    /* 21018 80020418 97A5001E */  lhu        $a1, 0x1E($sp)
    /* 2101C 8002041C 0C006F85 */  jal        func_8001BE14
    /* 21020 80020420 93A60023 */   lbu       $a2, 0x23($sp)
    /* 21024 80020424 0C005177 */  jal        func_800145DC
    /* 21028 80020428 00000000 */   nop
  .L8002042C:
    /* 2102C 8002042C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 21030 80020430 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 21034 80020434 03E00008 */  jr         $ra
    /* 21038 80020438 00000000 */   nop
endlabel func_800203EC

nonmatching func_8002043C, 0x58

glabel func_8002043C
    /* 2103C 8002043C 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 21040 80020440 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 21044 80020444 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 21048 80020448 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2104C 8002044C AFA40020 */  sw         $a0, 0x20($sp)
    /* 21050 80020450 AFA50024 */  sw         $a1, 0x24($sp)
    /* 21054 80020454 11C0000B */  beqz       $t6, .L80020484
    /* 21058 80020458 AFA60028 */   sw        $a2, 0x28($sp)
    /* 2105C 8002045C 0C005165 */  jal        func_80014594
    /* 21060 80020460 00000000 */   nop
    /* 21064 80020464 93A40023 */  lbu        $a0, 0x23($sp)
    /* 21068 80020468 97A50026 */  lhu        $a1, 0x26($sp)
    /* 2106C 8002046C 93A6002B */  lbu        $a2, 0x2B($sp)
    /* 21070 80020470 00003825 */  or         $a3, $zero, $zero
    /* 21074 80020474 0C006E7E */  jal        func_8001B9F8
    /* 21078 80020478 AFA00010 */   sw        $zero, 0x10($sp)
    /* 2107C 8002047C 0C005177 */  jal        func_800145DC
    /* 21080 80020480 00000000 */   nop
  .L80020484:
    /* 21084 80020484 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 21088 80020488 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 2108C 8002048C 03E00008 */  jr         $ra
    /* 21090 80020490 00000000 */   nop
endlabel func_8002043C

nonmatching func_80020494, 0x84

glabel func_80020494
    /* 21094 80020494 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 21098 80020498 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 2109C 8002049C 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 210A0 800204A0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 210A4 800204A4 AFA40020 */  sw         $a0, 0x20($sp)
    /* 210A8 800204A8 AFA50024 */  sw         $a1, 0x24($sp)
    /* 210AC 800204AC AFA60028 */  sw         $a2, 0x28($sp)
    /* 210B0 800204B0 11C00015 */  beqz       $t6, .L80020508
    /* 210B4 800204B4 AFA7002C */   sw        $a3, 0x2C($sp)
    /* 210B8 800204B8 0C005165 */  jal        func_80014594
    /* 210BC 800204BC 00000000 */   nop
    /* 210C0 800204C0 93AF002B */  lbu        $t7, 0x2B($sp)
    /* 210C4 800204C4 93A40023 */  lbu        $a0, 0x23($sp)
    /* 210C8 800204C8 97A50026 */  lhu        $a1, 0x26($sp)
    /* 210CC 800204CC 11E00004 */  beqz       $t7, .L800204E0
    /* 210D0 800204D0 24060015 */   addiu     $a2, $zero, 0x15
    /* 210D4 800204D4 00003825 */  or         $a3, $zero, $zero
    /* 210D8 800204D8 0C006E7E */  jal        func_8001B9F8
    /* 210DC 800204DC AFA00010 */   sw        $zero, 0x10($sp)
  .L800204E0:
    /* 210E0 800204E0 93B8002F */  lbu        $t8, 0x2F($sp)
    /* 210E4 800204E4 93A40023 */  lbu        $a0, 0x23($sp)
    /* 210E8 800204E8 97A50026 */  lhu        $a1, 0x26($sp)
    /* 210EC 800204EC 13000004 */  beqz       $t8, .L80020500
    /* 210F0 800204F0 24060016 */   addiu     $a2, $zero, 0x16
    /* 210F4 800204F4 00003825 */  or         $a3, $zero, $zero
    /* 210F8 800204F8 0C006E7E */  jal        func_8001B9F8
    /* 210FC 800204FC AFA00010 */   sw        $zero, 0x10($sp)
  .L80020500:
    /* 21100 80020500 0C005177 */  jal        func_800145DC
    /* 21104 80020504 00000000 */   nop
  .L80020508:
    /* 21108 80020508 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2110C 8002050C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 21110 80020510 03E00008 */  jr         $ra
    /* 21114 80020514 00000000 */   nop
endlabel func_80020494

nonmatching func_80020518, 0x10

glabel func_80020518
    /* 21118 80020518 3C018005 */  lui        $at, %hi(D_8004F2F8)
    /* 2111C 8002051C AFA40000 */  sw         $a0, 0x0($sp)
    /* 21120 80020520 03E00008 */  jr         $ra
    /* 21124 80020524 A024F2F8 */   sb        $a0, %lo(D_8004F2F8)($at)
endlabel func_80020518

nonmatching func_80020528, 0x30

glabel func_80020528
    /* 21128 80020528 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 2112C 8002052C 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 21130 80020530 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 21134 80020534 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 21138 80020538 51C00004 */  beql       $t6, $zero, .L8002054C
    /* 2113C 8002053C 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 21140 80020540 0C0052F6 */  jal        func_80014BD8
    /* 21144 80020544 00000000 */   nop
    /* 21148 80020548 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002054C:
    /* 2114C 8002054C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 21150 80020550 03E00008 */  jr         $ra
    /* 21154 80020554 00000000 */   nop
endlabel func_80020528

nonmatching func_80020558, 0x40

glabel func_80020558
    /* 21158 80020558 3C0E8003 */  lui        $t6, %hi(D_8002C630)
    /* 2115C 8002055C 91CEC630 */  lbu        $t6, %lo(D_8002C630)($t6)
    /* 21160 80020560 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 21164 80020564 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 21168 80020568 51C00008 */  beql       $t6, $zero, .L8002058C
    /* 2116C 8002056C 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 21170 80020570 0C005165 */  jal        func_80014594
    /* 21174 80020574 00000000 */   nop
    /* 21178 80020578 0C0052FE */  jal        func_80014BF8
    /* 2117C 8002057C 00000000 */   nop
    /* 21180 80020580 0C005177 */  jal        func_800145DC
    /* 21184 80020584 00000000 */   nop
    /* 21188 80020588 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002058C:
    /* 2118C 8002058C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 21190 80020590 03E00008 */  jr         $ra
    /* 21194 80020594 00000000 */   nop
endlabel func_80020558

nonmatching func_80020598, 0x4C

glabel func_80020598
    /* 21198 80020598 8C980000 */  lw         $t8, 0x0($a0)
    /* 2119C 8002059C 3C0E8004 */  lui        $t6, %hi(D_80038000)
    /* 211A0 800205A0 25CE8000 */  addiu      $t6, $t6, %lo(D_80038000)
    /* 211A4 800205A4 ADD80000 */  sw         $t8, 0x0($t6)
    /* 211A8 800205A8 8C8F0004 */  lw         $t7, 0x4($a0)
    /* 211AC 800205AC ADCF0004 */  sw         $t7, 0x4($t6)
    /* 211B0 800205B0 8C980008 */  lw         $t8, 0x8($a0)
    /* 211B4 800205B4 ADD80008 */  sw         $t8, 0x8($t6)
    /* 211B8 800205B8 8C8F000C */  lw         $t7, 0xC($a0)
    /* 211BC 800205BC ADCF000C */  sw         $t7, 0xC($t6)
    /* 211C0 800205C0 8C980010 */  lw         $t8, 0x10($a0)
    /* 211C4 800205C4 ADD80010 */  sw         $t8, 0x10($t6)
    /* 211C8 800205C8 8C8F0014 */  lw         $t7, 0x14($a0)
    /* 211CC 800205CC ADCF0014 */  sw         $t7, 0x14($t6)
    /* 211D0 800205D0 8C980018 */  lw         $t8, 0x18($a0)
    /* 211D4 800205D4 ADD80018 */  sw         $t8, 0x18($t6)
    /* 211D8 800205D8 8C8F001C */  lw         $t7, 0x1C($a0)
    /* 211DC 800205DC 03E00008 */  jr         $ra
    /* 211E0 800205E0 ADCF001C */   sw        $t7, 0x1C($t6)
endlabel func_80020598

nonmatching func_800205E4, 0x20

glabel func_800205E4
    /* 211E4 800205E4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 211E8 800205E8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 211EC 800205EC 0C005347 */  jal        func_80014D1C
    /* 211F0 800205F0 00000000 */   nop
    /* 211F4 800205F4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 211F8 800205F8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 211FC 800205FC 03E00008 */  jr         $ra
    /* 21200 80020600 00000000 */   nop
endlabel func_800205E4
    /* 21204 80020604 00000000 */  nop
    /* 21208 80020608 00000000 */  nop
    /* 2120C 8002060C 00000000 */  nop
