.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching __setfpcsr, 0x14

glabel __setfpcsr
    /* 55F0 800049F0 44C4F800 */  ctc1       $a0, $31
    /* 55F4 800049F4 00000000 */  nop
    /* 55F8 800049F8 00000000 */  nop
    /* 55FC 800049FC 03E00008 */  jr         $ra
    /* 5600 80004A00 00000000 */   nop
endlabel __setfpcsr
    /* 5604 80004A04 00000000 */  nop
    /* 5608 80004A08 00000000 */  nop
    /* 560C 80004A0C 00000000 */  nop
