.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80006A00, 0x2C

glabel func_80006A00
    /* 7600 80006A00 3C0E8003 */  lui        $t6, %hi(D_8002C3D0)
    /* 7604 80006A04 3C0F8003 */  lui        $t7, %hi(D_8002C3D0)
    /* 7608 80006A08 25CEC3D0 */  addiu      $t6, $t6, %lo(D_8002C3D0)
    /* 760C 80006A0C 25EFC3D0 */  addiu      $t7, $t7, %lo(D_8002C3D0)
    /* 7610 80006A10 AC8E0000 */  sw         $t6, 0x0($a0)
    /* 7614 80006A14 AC8F0004 */  sw         $t7, 0x4($a0)
    /* 7618 80006A18 AC800008 */  sw         $zero, 0x8($a0)
    /* 761C 80006A1C AC80000C */  sw         $zero, 0xC($a0)
    /* 7620 80006A20 AC860010 */  sw         $a2, 0x10($a0)
    /* 7624 80006A24 03E00008 */  jr         $ra
    /* 7628 80006A28 AC850014 */   sw        $a1, 0x14($a0)
endlabel func_80006A00
    /* 762C 80006A2C 00000000 */  nop
