.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80006D40, 0x58

glabel func_80006D40
    /* 7940 80006D40 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 7944 80006D44 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 7948 80006D48 0C00312C */  jal        func_8000C4B0
    /* 794C 80006D4C AFA40018 */   sw        $a0, 0x18($sp)
    /* 7950 80006D50 3C058003 */  lui        $a1, %hi(D_8002C464)
    /* 7954 80006D54 24A5C464 */  addiu      $a1, $a1, %lo(D_8002C464)
    /* 7958 80006D58 8CAF0000 */  lw         $t7, 0x0($a1)
    /* 795C 80006D5C 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 7960 80006D60 24180001 */  addiu      $t8, $zero, 0x1
    /* 7964 80006D64 00402025 */  or         $a0, $v0, $zero
    /* 7968 80006D68 ADEE0008 */  sw         $t6, 0x8($t7)
    /* 796C 80006D6C 8CB90000 */  lw         $t9, 0x0($a1)
    /* 7970 80006D70 A7380000 */  sh         $t8, 0x0($t9)
    /* 7974 80006D74 8CA30000 */  lw         $v1, 0x0($a1)
    /* 7978 80006D78 8C680008 */  lw         $t0, 0x8($v1)
    /* 797C 80006D7C 8D090004 */  lw         $t1, 0x4($t0)
    /* 7980 80006D80 0C003148 */  jal        func_8000C520
    /* 7984 80006D84 AC69000C */   sw        $t1, 0xC($v1)
    /* 7988 80006D88 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 798C 80006D8C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 7990 80006D90 03E00008 */  jr         $ra
    /* 7994 80006D94 00000000 */   nop
endlabel func_80006D40
    /* 7998 80006D98 00000000 */  nop
    /* 799C 80006D9C 00000000 */  nop
