.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80007730, 0x60

glabel func_80007730
    /* 8330 80007730 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 8334 80007734 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8338 80007738 0C0034A8 */  jal        func_8000D2A0
    /* 833C 8000773C AFA40018 */   sw        $a0, 0x18($sp)
    /* 8340 80007740 304E0100 */  andi       $t6, $v0, 0x100
    /* 8344 80007744 11C00003 */  beqz       $t6, .L80007754
    /* 8348 80007748 8FA40018 */   lw        $a0, 0x18($sp)
    /* 834C 8000774C 10000002 */  b          .L80007758
    /* 8350 80007750 24030001 */   addiu     $v1, $zero, 0x1
  .L80007754:
    /* 8354 80007754 00001825 */  or         $v1, $zero, $zero
  .L80007758:
    /* 8358 80007758 304F0080 */  andi       $t7, $v0, 0x80
    /* 835C 8000775C 51E00008 */  beql       $t7, $zero, .L80007780
    /* 8360 80007760 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 8364 80007764 8C980004 */  lw         $t8, 0x4($a0)
    /* 8368 80007768 2401FFFD */  addiu      $at, $zero, -0x3
    /* 836C 8000776C 0303C825 */  or         $t9, $t8, $v1
    /* 8370 80007770 AC990004 */  sw         $t9, 0x4($a0)
    /* 8374 80007774 03214824 */  and        $t1, $t9, $at
    /* 8378 80007778 AC890004 */  sw         $t1, 0x4($a0)
    /* 837C 8000777C 8FBF0014 */  lw         $ra, 0x14($sp)
  .L80007780:
    /* 8380 80007780 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 8384 80007784 00601025 */  or         $v0, $v1, $zero
    /* 8388 80007788 03E00008 */  jr         $ra
    /* 838C 8000778C 00000000 */   nop
endlabel func_80007730

nonmatching func_80007790, 0x3C

glabel func_80007790
    /* 8390 80007790 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 8394 80007794 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8398 80007798 0C00312C */  jal        func_8000C4B0
    /* 839C 8000779C 00000000 */   nop
    /* 83A0 800077A0 3C0E8003 */  lui        $t6, %hi(D_8002C460)
    /* 83A4 800077A4 8DCEC460 */  lw         $t6, %lo(D_8002C460)($t6)
    /* 83A8 800077A8 00402025 */  or         $a0, $v0, $zero
    /* 83AC 800077AC 8DCF0004 */  lw         $t7, 0x4($t6)
    /* 83B0 800077B0 0C003148 */  jal        func_8000C520
    /* 83B4 800077B4 AFAF0018 */   sw        $t7, 0x18($sp)
    /* 83B8 800077B8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 83BC 800077BC 8FA20018 */  lw         $v0, 0x18($sp)
    /* 83C0 800077C0 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 83C4 800077C4 03E00008 */  jr         $ra
    /* 83C8 800077C8 00000000 */   nop
endlabel func_80007790
    /* 83CC 800077CC 00000000 */  nop
