.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80007C00, 0x40

glabel func_80007C00
    /* 8800 80007C00 90830000 */  lbu        $v1, 0x0($a0)
    /* 8804 80007C04 30AE00FF */  andi       $t6, $a1, 0xFF
    /* 8808 80007C08 30A200FF */  andi       $v0, $a1, 0xFF
    /* 880C 80007C0C 51C3000A */  beql       $t6, $v1, .L80007C38
    /* 8810 80007C10 00801025 */   or        $v0, $a0, $zero
  .L80007C14:
    /* 8814 80007C14 54600004 */  bnel       $v1, $zero, .L80007C28
    /* 8818 80007C18 90830001 */   lbu       $v1, 0x1($a0)
    /* 881C 80007C1C 03E00008 */  jr         $ra
    /* 8820 80007C20 00001025 */   or        $v0, $zero, $zero
    /* 8824 80007C24 90830001 */  lbu        $v1, 0x1($a0)
  .L80007C28:
    /* 8828 80007C28 24840001 */  addiu      $a0, $a0, 0x1
    /* 882C 80007C2C 1443FFF9 */  bne        $v0, $v1, .L80007C14
    /* 8830 80007C30 00000000 */   nop
    /* 8834 80007C34 00801025 */  or         $v0, $a0, $zero
  .L80007C38:
    /* 8838 80007C38 03E00008 */  jr         $ra
    /* 883C 80007C3C 00000000 */   nop
endlabel func_80007C00

nonmatching func_80007C40, 0x28

glabel func_80007C40
    /* 8840 80007C40 908E0000 */  lbu        $t6, 0x0($a0)
    /* 8844 80007C44 00801825 */  or         $v1, $a0, $zero
    /* 8848 80007C48 11C00005 */  beqz       $t6, .L80007C60
    /* 884C 80007C4C 00000000 */   nop
    /* 8850 80007C50 906F0001 */  lbu        $t7, 0x1($v1)
  .L80007C54:
    /* 8854 80007C54 24630001 */  addiu      $v1, $v1, 0x1
    /* 8858 80007C58 55E0FFFE */  bnel       $t7, $zero, .L80007C54
    /* 885C 80007C5C 906F0001 */   lbu       $t7, 0x1($v1)
  .L80007C60:
    /* 8860 80007C60 03E00008 */  jr         $ra
    /* 8864 80007C64 00641023 */   subu      $v0, $v1, $a0
endlabel func_80007C40

nonmatching func_80007C68, 0x2C

glabel func_80007C68
    /* 8868 80007C68 00801025 */  or         $v0, $a0, $zero
    /* 886C 80007C6C 10C00007 */  beqz       $a2, .L80007C8C
    /* 8870 80007C70 00A01825 */   or        $v1, $a1, $zero
  .L80007C74:
    /* 8874 80007C74 906E0000 */  lbu        $t6, 0x0($v1)
    /* 8878 80007C78 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 887C 80007C7C 24420001 */  addiu      $v0, $v0, 0x1
    /* 8880 80007C80 24630001 */  addiu      $v1, $v1, 0x1
    /* 8884 80007C84 14C0FFFB */  bnez       $a2, .L80007C74
    /* 8888 80007C88 A04EFFFF */   sb        $t6, -0x1($v0)
  .L80007C8C:
    /* 888C 80007C8C 03E00008 */  jr         $ra
    /* 8890 80007C90 00801025 */   or        $v0, $a0, $zero
endlabel func_80007C68
    /* 8894 80007C94 00000000 */  nop
    /* 8898 80007C98 00000000 */  nop
    /* 889C 80007C9C 00000000 */  nop
