.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80009450, 0x15C

glabel func_80009450
    /* A050 80009450 3C028003 */  lui        $v0, %hi(D_8002C3B0)
    /* A054 80009454 2442C3B0 */  addiu      $v0, $v0, %lo(D_8002C3B0)
    /* A058 80009458 8C4E0000 */  lw         $t6, 0x0($v0)
    /* A05C 8000945C 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* A060 80009460 AFBF0024 */  sw         $ra, 0x24($sp)
    /* A064 80009464 AFA40070 */  sw         $a0, 0x70($sp)
    /* A068 80009468 AFA50074 */  sw         $a1, 0x74($sp)
    /* A06C 8000946C 11C00003 */  beqz       $t6, .L8000947C
    /* A070 80009470 AFA60078 */   sw        $a2, 0x78($sp)
    /* A074 80009474 10000049 */  b          .L8000959C
    /* A078 80009478 00001025 */   or        $v0, $zero, $zero
  .L8000947C:
    /* A07C 8000947C 240F0001 */  addiu      $t7, $zero, 0x1
    /* A080 80009480 0C001CEC */  jal        func_800073B0
    /* A084 80009484 AC4F0000 */   sw        $t7, 0x0($v0)
    /* A088 80009488 AFA20060 */  sw         $v0, 0x60($sp)
    /* A08C 8000948C 14400020 */  bnez       $v0, .L80009510
    /* A090 80009490 AFA30064 */   sw        $v1, 0x64($sp)
    /* A094 80009494 3C010165 */  lui        $at, (0x165A0BC >> 16)
    /* A098 80009498 3421A0BC */  ori        $at, $at, (0x165A0BC & 0xFFFF)
    /* A09C 8000949C 0061082B */  sltu       $at, $v1, $at
    /* A0A0 800094A0 1020001B */  beqz       $at, .L80009510
    /* A0A4 800094A4 27A40028 */   addiu     $a0, $sp, 0x28
    /* A0A8 800094A8 27A5006C */  addiu      $a1, $sp, 0x6C
    /* A0AC 800094AC 0C001A80 */  jal        func_80006A00
    /* A0B0 800094B0 24060001 */   addiu     $a2, $zero, 0x1
    /* A0B4 800094B4 8FB80060 */  lw         $t8, 0x60($sp)
    /* A0B8 800094B8 8FB90064 */  lw         $t9, 0x64($sp)
    /* A0BC 800094BC 3C090165 */  lui        $t1, (0x165A0BC >> 16)
    /* A0C0 800094C0 3529A0BC */  ori        $t1, $t1, (0x165A0BC & 0xFFFF)
    /* A0C4 800094C4 24080000 */  addiu      $t0, $zero, 0x0
    /* A0C8 800094C8 240A0000 */  addiu      $t2, $zero, 0x0
    /* A0CC 800094CC 240B0000 */  addiu      $t3, $zero, 0x0
    /* A0D0 800094D0 27AC0028 */  addiu      $t4, $sp, 0x28
    /* A0D4 800094D4 27AD006C */  addiu      $t5, $sp, 0x6C
    /* A0D8 800094D8 01183023 */  subu       $a2, $t0, $t8
    /* A0DC 800094DC 0139082B */  sltu       $at, $t1, $t9
    /* A0E0 800094E0 00C13023 */  subu       $a2, $a2, $at
    /* A0E4 800094E4 AFAD001C */  sw         $t5, 0x1C($sp)
    /* A0E8 800094E8 AFAC0018 */  sw         $t4, 0x18($sp)
    /* A0EC 800094EC AFAB0014 */  sw         $t3, 0x14($sp)
    /* A0F0 800094F0 AFAA0010 */  sw         $t2, 0x10($sp)
    /* A0F4 800094F4 27A40040 */  addiu      $a0, $sp, 0x40
    /* A0F8 800094F8 0C0038F4 */  jal        func_8000E3D0
    /* A0FC 800094FC 01393823 */   subu      $a3, $t1, $t9
    /* A100 80009500 27A40028 */  addiu      $a0, $sp, 0x28
    /* A104 80009504 27A5006C */  addiu      $a1, $sp, 0x6C
    /* A108 80009508 0C001C9C */  jal        func_80007270
    /* A10C 8000950C 24060001 */   addiu     $a2, $zero, 0x1
  .L80009510:
    /* A110 80009510 240E0004 */  addiu      $t6, $zero, 0x4
    /* A114 80009514 3C018003 */  lui        $at, %hi(D_80037AE1)
    /* A118 80009518 A02E7AE1 */  sb         $t6, %lo(D_80037AE1)($at)
    /* A11C 8000951C 0C002596 */  jal        func_80009658
    /* A120 80009520 00002025 */   or        $a0, $zero, $zero
    /* A124 80009524 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A128 80009528 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A12C 8000952C 0C00392C */  jal        func_8000E4B0
    /* A130 80009530 24040001 */   addiu     $a0, $zero, 0x1
    /* A134 80009534 8FA40070 */  lw         $a0, 0x70($sp)
    /* A138 80009538 27A5006C */  addiu      $a1, $sp, 0x6C
    /* A13C 8000953C 0C001C9C */  jal        func_80007270
    /* A140 80009540 24060001 */   addiu     $a2, $zero, 0x1
    /* A144 80009544 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A148 80009548 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A14C 8000954C 0C00392C */  jal        func_8000E4B0
    /* A150 80009550 00002025 */   or        $a0, $zero, $zero
    /* A154 80009554 AFA20068 */  sw         $v0, 0x68($sp)
    /* A158 80009558 8FA40070 */  lw         $a0, 0x70($sp)
    /* A15C 8000955C 27A5006C */  addiu      $a1, $sp, 0x6C
    /* A160 80009560 0C001C9C */  jal        func_80007270
    /* A164 80009564 24060001 */   addiu     $a2, $zero, 0x1
    /* A168 80009568 8FA40074 */  lw         $a0, 0x74($sp)
    /* A16C 8000956C 0C00256B */  jal        func_800095AC
    /* A170 80009570 8FA50078 */   lw        $a1, 0x78($sp)
    /* A174 80009574 3C018003 */  lui        $at, %hi(D_80037AE0)
    /* A178 80009578 0C003958 */  jal        func_8000E560
    /* A17C 8000957C A0207AE0 */   sb        $zero, %lo(D_80037AE0)($at)
    /* A180 80009580 3C048003 */  lui        $a0, %hi(D_80037B08)
    /* A184 80009584 3C058003 */  lui        $a1, %hi(D_80037B20)
    /* A188 80009588 24A57B20 */  addiu      $a1, $a1, %lo(D_80037B20)
    /* A18C 8000958C 24847B08 */  addiu      $a0, $a0, %lo(D_80037B08)
    /* A190 80009590 0C001A80 */  jal        func_80006A00
    /* A194 80009594 24060001 */   addiu     $a2, $zero, 0x1
    /* A198 80009598 8FA20068 */  lw         $v0, 0x68($sp)
  .L8000959C:
    /* A19C 8000959C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* A1A0 800095A0 27BD0070 */  addiu      $sp, $sp, 0x70
    /* A1A4 800095A4 03E00008 */  jr         $ra
    /* A1A8 800095A8 00000000 */   nop
endlabel func_80009450

nonmatching func_800095AC, 0xAC

glabel func_800095AC
    /* A1AC 800095AC 3C078003 */  lui        $a3, %hi(D_80037AE1)
    /* A1B0 800095B0 24E77AE1 */  addiu      $a3, $a3, %lo(D_80037AE1)
    /* A1B4 800095B4 90EE0000 */  lbu        $t6, 0x0($a3)
    /* A1B8 800095B8 3C038003 */  lui        $v1, %hi(D_80037AA0)
    /* A1BC 800095BC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* A1C0 800095C0 00001025 */  or         $v0, $zero, $zero
    /* A1C4 800095C4 24637AA0 */  addiu      $v1, $v1, %lo(D_80037AA0)
    /* A1C8 800095C8 19C00020 */  blez       $t6, .L8000964C
    /* A1CC 800095CC 00003025 */   or        $a2, $zero, $zero
    /* A1D0 800095D0 27A8000C */  addiu      $t0, $sp, 0xC
  .L800095D4:
    /* A1D4 800095D4 88610000 */  lwl        $at, 0x0($v1)
    /* A1D8 800095D8 98610003 */  lwr        $at, 0x3($v1)
    /* A1DC 800095DC AD010000 */  sw         $at, 0x0($t0)
    /* A1E0 800095E0 88780004 */  lwl        $t8, 0x4($v1)
    /* A1E4 800095E4 98780007 */  lwr        $t8, 0x7($v1)
    /* A1E8 800095E8 AD180004 */  sw         $t8, 0x4($t0)
    /* A1EC 800095EC 93B9000E */  lbu        $t9, 0xE($sp)
    /* A1F0 800095F0 332900C0 */  andi       $t1, $t9, 0xC0
    /* A1F4 800095F4 00095103 */  sra        $t2, $t1, 4
    /* A1F8 800095F8 314B00FF */  andi       $t3, $t2, 0xFF
    /* A1FC 800095FC 1560000D */  bnez       $t3, .L80009634
    /* A200 80009600 A0AA0003 */   sb        $t2, 0x3($a1)
    /* A204 80009604 93AC0011 */  lbu        $t4, 0x11($sp)
    /* A208 80009608 93AE0010 */  lbu        $t6, 0x10($sp)
    /* A20C 8000960C 24190001 */  addiu      $t9, $zero, 0x1
    /* A210 80009610 000C6A00 */  sll        $t5, $t4, 8
    /* A214 80009614 01AE7825 */  or         $t7, $t5, $t6
    /* A218 80009618 A4AF0000 */  sh         $t7, 0x0($a1)
    /* A21C 8000961C 93B80012 */  lbu        $t8, 0x12($sp)
    /* A220 80009620 00D94804 */  sllv       $t1, $t9, $a2
    /* A224 80009624 00491025 */  or         $v0, $v0, $t1
    /* A228 80009628 304A00FF */  andi       $t2, $v0, 0xFF
    /* A22C 8000962C 01401025 */  or         $v0, $t2, $zero
    /* A230 80009630 A0B80002 */  sb         $t8, 0x2($a1)
  .L80009634:
    /* A234 80009634 90EB0000 */  lbu        $t3, 0x0($a3)
    /* A238 80009638 24C60001 */  addiu      $a2, $a2, 0x1
    /* A23C 8000963C 24630008 */  addiu      $v1, $v1, 0x8
    /* A240 80009640 00CB082A */  slt        $at, $a2, $t3
    /* A244 80009644 1420FFE3 */  bnez       $at, .L800095D4
    /* A248 80009648 24A50004 */   addiu     $a1, $a1, 0x4
  .L8000964C:
    /* A24C 8000964C A0820000 */  sb         $v0, 0x0($a0)
    /* A250 80009650 03E00008 */  jr         $ra
    /* A254 80009654 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800095AC

nonmatching func_80009658, 0xD4

glabel func_80009658
    /* A258 80009658 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* A25C 8000965C AFA40018 */  sw         $a0, 0x18($sp)
    /* A260 80009660 308E00FF */  andi       $t6, $a0, 0xFF
    /* A264 80009664 3C038003 */  lui        $v1, %hi(D_80037AA0)
    /* A268 80009668 3C028003 */  lui        $v0, %hi(D_80037ADC)
    /* A26C 8000966C 01C02025 */  or         $a0, $t6, $zero
    /* A270 80009670 24427ADC */  addiu      $v0, $v0, %lo(D_80037ADC)
    /* A274 80009674 24637AA0 */  addiu      $v1, $v1, %lo(D_80037AA0)
  .L80009678:
    /* A278 80009678 24630004 */  addiu      $v1, $v1, 0x4
    /* A27C 8000967C 0062082B */  sltu       $at, $v1, $v0
    /* A280 80009680 1420FFFD */  bnez       $at, .L80009678
    /* A284 80009684 AC60FFFC */   sw        $zero, -0x4($v1)
    /* A288 80009688 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A28C 8000968C 24A37AA0 */  addiu      $v1, $a1, %lo(D_80037AA0)
    /* A290 80009690 240F0001 */  addiu      $t7, $zero, 0x1
    /* A294 80009694 AC6F003C */  sw         $t7, 0x3C($v1)
    /* A298 80009698 3C068003 */  lui        $a2, %hi(D_80037AE1)
    /* A29C 8000969C 24C67AE1 */  addiu      $a2, $a2, %lo(D_80037AE1)
    /* A2A0 800096A0 90CD0000 */  lbu        $t5, 0x0($a2)
    /* A2A4 800096A4 241800FF */  addiu      $t8, $zero, 0xFF
    /* A2A8 800096A8 24190001 */  addiu      $t9, $zero, 0x1
    /* A2AC 800096AC 24080003 */  addiu      $t0, $zero, 0x3
    /* A2B0 800096B0 240900FF */  addiu      $t1, $zero, 0xFF
    /* A2B4 800096B4 240A00FF */  addiu      $t2, $zero, 0xFF
    /* A2B8 800096B8 240B00FF */  addiu      $t3, $zero, 0xFF
    /* A2BC 800096BC 240C00FF */  addiu      $t4, $zero, 0xFF
    /* A2C0 800096C0 A3B8000C */  sb         $t8, 0xC($sp)
    /* A2C4 800096C4 A3B9000D */  sb         $t9, 0xD($sp)
    /* A2C8 800096C8 A3A8000E */  sb         $t0, 0xE($sp)
    /* A2CC 800096CC A3A4000F */  sb         $a0, 0xF($sp)
    /* A2D0 800096D0 A3A90010 */  sb         $t1, 0x10($sp)
    /* A2D4 800096D4 A3AA0011 */  sb         $t2, 0x11($sp)
    /* A2D8 800096D8 A3AB0012 */  sb         $t3, 0x12($sp)
    /* A2DC 800096DC A3AC0013 */  sb         $t4, 0x13($sp)
    /* A2E0 800096E0 19A0000E */  blez       $t5, .L8000971C
    /* A2E4 800096E4 00001025 */   or        $v0, $zero, $zero
    /* A2E8 800096E8 27A4000C */  addiu      $a0, $sp, 0xC
    /* A2EC 800096EC 8C810000 */  lw         $at, 0x0($a0)
  .L800096F0:
    /* A2F0 800096F0 24420001 */  addiu      $v0, $v0, 0x1
    /* A2F4 800096F4 24630008 */  addiu      $v1, $v1, 0x8
    /* A2F8 800096F8 A861FFF8 */  swl        $at, -0x8($v1)
    /* A2FC 800096FC B861FFFB */  swr        $at, -0x5($v1)
    /* A300 80009700 8C8F0004 */  lw         $t7, 0x4($a0)
    /* A304 80009704 A86FFFFC */  swl        $t7, -0x4($v1)
    /* A308 80009708 B86FFFFF */  swr        $t7, -0x1($v1)
    /* A30C 8000970C 90D80000 */  lbu        $t8, 0x0($a2)
    /* A310 80009710 0058082A */  slt        $at, $v0, $t8
    /* A314 80009714 5420FFF6 */  bnel       $at, $zero, .L800096F0
    /* A318 80009718 8C810000 */   lw        $at, 0x0($a0)
  .L8000971C:
    /* A31C 8000971C 241900FE */  addiu      $t9, $zero, 0xFE
    /* A320 80009720 A0790000 */  sb         $t9, 0x0($v1)
    /* A324 80009724 03E00008 */  jr         $ra
    /* A328 80009728 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80009658
    /* A32C 8000972C 00000000 */  nop
