.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80009730, 0x7C

glabel func_80009730
    /* A330 80009730 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* A334 80009734 AFBF0014 */  sw         $ra, 0x14($sp)
    /* A338 80009738 0C00396C */  jal        func_8000E5B0
    /* A33C 8000973C AFA40020 */   sw        $a0, 0x20($sp)
    /* A340 80009740 3C0E8003 */  lui        $t6, %hi(D_80037AE0)
    /* A344 80009744 91CE7AE0 */  lbu        $t6, %lo(D_80037AE0)($t6)
    /* A348 80009748 11C0000B */  beqz       $t6, .L80009778
    /* A34C 8000974C 00000000 */   nop
    /* A350 80009750 0C002596 */  jal        func_80009658
    /* A354 80009754 00002025 */   or        $a0, $zero, $zero
    /* A358 80009758 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A35C 8000975C 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A360 80009760 0C00392C */  jal        func_8000E4B0
    /* A364 80009764 24040001 */   addiu     $a0, $zero, 0x1
    /* A368 80009768 8FA40020 */  lw         $a0, 0x20($sp)
    /* A36C 8000976C 00002825 */  or         $a1, $zero, $zero
    /* A370 80009770 0C001C9C */  jal        func_80007270
    /* A374 80009774 24060001 */   addiu     $a2, $zero, 0x1
  .L80009778:
    /* A378 80009778 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A37C 8000977C 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A380 80009780 0C00392C */  jal        func_8000E4B0
    /* A384 80009784 00002025 */   or        $a0, $zero, $zero
    /* A388 80009788 3C018003 */  lui        $at, %hi(D_80037AE0)
    /* A38C 8000978C AFA2001C */  sw         $v0, 0x1C($sp)
    /* A390 80009790 0C00397D */  jal        func_8000E5F4
    /* A394 80009794 A0207AE0 */   sb        $zero, %lo(D_80037AE0)($at)
    /* A398 80009798 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A39C 8000979C 8FA2001C */  lw         $v0, 0x1C($sp)
    /* A3A0 800097A0 27BD0020 */  addiu      $sp, $sp, 0x20
    /* A3A4 800097A4 03E00008 */  jr         $ra
    /* A3A8 800097A8 00000000 */   nop
endlabel func_80009730

nonmatching func_800097AC, 0x24

glabel func_800097AC
    /* A3AC 800097AC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* A3B0 800097B0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* A3B4 800097B4 00802825 */  or         $a1, $a0, $zero
    /* A3B8 800097B8 0C00256B */  jal        func_800095AC
    /* A3BC 800097BC 27A4001F */   addiu     $a0, $sp, 0x1F
    /* A3C0 800097C0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A3C4 800097C4 27BD0020 */  addiu      $sp, $sp, 0x20
    /* A3C8 800097C8 03E00008 */  jr         $ra
    /* A3CC 800097CC 00000000 */   nop
endlabel func_800097AC

nonmatching func_800097D0, 0x84

glabel func_800097D0
    /* A3D0 800097D0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* A3D4 800097D4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* A3D8 800097D8 0C00396C */  jal        func_8000E5B0
    /* A3DC 800097DC AFA40020 */   sw        $a0, 0x20($sp)
    /* A3E0 800097E0 3C0E8003 */  lui        $t6, %hi(D_80037AE0)
    /* A3E4 800097E4 91CE7AE0 */  lbu        $t6, %lo(D_80037AE0)($t6)
    /* A3E8 800097E8 24010001 */  addiu      $at, $zero, 0x1
    /* A3EC 800097EC 11C1000B */  beq        $t6, $at, .L8000981C
    /* A3F0 800097F0 00000000 */   nop
    /* A3F4 800097F4 0C002638 */  jal        func_800098E0
    /* A3F8 800097F8 00000000 */   nop
    /* A3FC 800097FC 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A400 80009800 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A404 80009804 0C00392C */  jal        func_8000E4B0
    /* A408 80009808 24040001 */   addiu     $a0, $zero, 0x1
    /* A40C 8000980C 8FA40020 */  lw         $a0, 0x20($sp)
    /* A410 80009810 00002825 */  or         $a1, $zero, $zero
    /* A414 80009814 0C001C9C */  jal        func_80007270
    /* A418 80009818 24060001 */   addiu     $a2, $zero, 0x1
  .L8000981C:
    /* A41C 8000981C 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A420 80009820 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A424 80009824 0C00392C */  jal        func_8000E4B0
    /* A428 80009828 00002025 */   or        $a0, $zero, $zero
    /* A42C 8000982C 240F0001 */  addiu      $t7, $zero, 0x1
    /* A430 80009830 3C018003 */  lui        $at, %hi(D_80037AE0)
    /* A434 80009834 AFA2001C */  sw         $v0, 0x1C($sp)
    /* A438 80009838 0C00397D */  jal        func_8000E5F4
    /* A43C 8000983C A02F7AE0 */   sb        $t7, %lo(D_80037AE0)($at)
    /* A440 80009840 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A444 80009844 8FA2001C */  lw         $v0, 0x1C($sp)
    /* A448 80009848 27BD0020 */  addiu      $sp, $sp, 0x20
    /* A44C 8000984C 03E00008 */  jr         $ra
    /* A450 80009850 00000000 */   nop
endlabel func_800097D0

nonmatching func_80009854, 0x8C

glabel func_80009854
    /* A454 80009854 3C058003 */  lui        $a1, %hi(D_80037AE1)
    /* A458 80009858 24A57AE1 */  addiu      $a1, $a1, %lo(D_80037AE1)
    /* A45C 8000985C 90AE0000 */  lbu        $t6, 0x0($a1)
    /* A460 80009860 3C028003 */  lui        $v0, %hi(D_80037AA0)
    /* A464 80009864 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* A468 80009868 24427AA0 */  addiu      $v0, $v0, %lo(D_80037AA0)
    /* A46C 8000986C 19C0001A */  blez       $t6, .L800098D8
    /* A470 80009870 00001825 */   or        $v1, $zero, $zero
    /* A474 80009874 27A60004 */  addiu      $a2, $sp, 0x4
  .L80009878:
    /* A478 80009878 88410000 */  lwl        $at, 0x0($v0)
    /* A47C 8000987C 98410003 */  lwr        $at, 0x3($v0)
    /* A480 80009880 ACC10000 */  sw         $at, 0x0($a2)
    /* A484 80009884 88580004 */  lwl        $t8, 0x4($v0)
    /* A488 80009888 98580007 */  lwr        $t8, 0x7($v0)
    /* A48C 8000988C ACD80004 */  sw         $t8, 0x4($a2)
    /* A490 80009890 93B90006 */  lbu        $t9, 0x6($sp)
    /* A494 80009894 332800C0 */  andi       $t0, $t9, 0xC0
    /* A498 80009898 00084903 */  sra        $t1, $t0, 4
    /* A49C 8000989C 312A00FF */  andi       $t2, $t1, 0xFF
    /* A4A0 800098A0 15400007 */  bnez       $t2, .L800098C0
    /* A4A4 800098A4 A0890004 */   sb        $t1, 0x4($a0)
    /* A4A8 800098A8 97AB0008 */  lhu        $t3, 0x8($sp)
    /* A4AC 800098AC A48B0000 */  sh         $t3, 0x0($a0)
    /* A4B0 800098B0 83AC000A */  lb         $t4, 0xA($sp)
    /* A4B4 800098B4 A08C0002 */  sb         $t4, 0x2($a0)
    /* A4B8 800098B8 83AD000B */  lb         $t5, 0xB($sp)
    /* A4BC 800098BC A08D0003 */  sb         $t5, 0x3($a0)
  .L800098C0:
    /* A4C0 800098C0 90AE0000 */  lbu        $t6, 0x0($a1)
    /* A4C4 800098C4 24630001 */  addiu      $v1, $v1, 0x1
    /* A4C8 800098C8 24420008 */  addiu      $v0, $v0, 0x8
    /* A4CC 800098CC 006E082A */  slt        $at, $v1, $t6
    /* A4D0 800098D0 1420FFE9 */  bnez       $at, .L80009878
    /* A4D4 800098D4 24840006 */   addiu     $a0, $a0, 0x6
  .L800098D8:
    /* A4D8 800098D8 03E00008 */  jr         $ra
    /* A4DC 800098DC 27BD0010 */   addiu     $sp, $sp, 0x10
endlabel func_80009854

nonmatching func_800098E0, 0xC8

glabel func_800098E0
    /* A4E0 800098E0 3C058003 */  lui        $a1, %hi(D_80037AA0)
    /* A4E4 800098E4 24A57AA0 */  addiu      $a1, $a1, %lo(D_80037AA0)
    /* A4E8 800098E8 3C048003 */  lui        $a0, %hi(D_80037AA0)
    /* A4EC 800098EC 3C038003 */  lui        $v1, %hi(D_80037ADC)
    /* A4F0 800098F0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* A4F4 800098F4 00A01025 */  or         $v0, $a1, $zero
    /* A4F8 800098F8 24637ADC */  addiu      $v1, $v1, %lo(D_80037ADC)
    /* A4FC 800098FC 24847AA0 */  addiu      $a0, $a0, %lo(D_80037AA0)
  .L80009900:
    /* A500 80009900 24840004 */  addiu      $a0, $a0, 0x4
    /* A504 80009904 0083082B */  sltu       $at, $a0, $v1
    /* A508 80009908 1420FFFD */  bnez       $at, .L80009900
    /* A50C 8000990C AC80FFFC */   sw        $zero, -0x4($a0)
    /* A510 80009910 3C048003 */  lui        $a0, %hi(D_80037AE1)
    /* A514 80009914 24847AE1 */  addiu      $a0, $a0, %lo(D_80037AE1)
    /* A518 80009918 908C0000 */  lbu        $t4, 0x0($a0)
    /* A51C 8000991C 240E0001 */  addiu      $t6, $zero, 0x1
    /* A520 80009920 240F00FF */  addiu      $t7, $zero, 0xFF
    /* A524 80009924 24180001 */  addiu      $t8, $zero, 0x1
    /* A528 80009928 24190004 */  addiu      $t9, $zero, 0x4
    /* A52C 8000992C 24080001 */  addiu      $t0, $zero, 0x1
    /* A530 80009930 3409FFFF */  ori        $t1, $zero, 0xFFFF
    /* A534 80009934 240AFFFF */  addiu      $t2, $zero, -0x1
    /* A538 80009938 240BFFFF */  addiu      $t3, $zero, -0x1
    /* A53C 8000993C ACAE003C */  sw         $t6, 0x3C($a1)
    /* A540 80009940 A3AF000C */  sb         $t7, 0xC($sp)
    /* A544 80009944 A3B8000D */  sb         $t8, 0xD($sp)
    /* A548 80009948 A3B9000E */  sb         $t9, 0xE($sp)
    /* A54C 8000994C A3A8000F */  sb         $t0, 0xF($sp)
    /* A550 80009950 A7A90010 */  sh         $t1, 0x10($sp)
    /* A554 80009954 A3AA0012 */  sb         $t2, 0x12($sp)
    /* A558 80009958 A3AB0013 */  sb         $t3, 0x13($sp)
    /* A55C 8000995C 1980000E */  blez       $t4, .L80009998
    /* A560 80009960 00001825 */   or        $v1, $zero, $zero
    /* A564 80009964 27A5000C */  addiu      $a1, $sp, 0xC
    /* A568 80009968 8CA10000 */  lw         $at, 0x0($a1)
  .L8000996C:
    /* A56C 8000996C 24630001 */  addiu      $v1, $v1, 0x1
    /* A570 80009970 24420008 */  addiu      $v0, $v0, 0x8
    /* A574 80009974 A841FFF8 */  swl        $at, -0x8($v0)
    /* A578 80009978 B841FFFB */  swr        $at, -0x5($v0)
    /* A57C 8000997C 8CAE0004 */  lw         $t6, 0x4($a1)
    /* A580 80009980 A84EFFFC */  swl        $t6, -0x4($v0)
    /* A584 80009984 B84EFFFF */  swr        $t6, -0x1($v0)
    /* A588 80009988 908F0000 */  lbu        $t7, 0x0($a0)
    /* A58C 8000998C 006F082A */  slt        $at, $v1, $t7
    /* A590 80009990 5420FFF6 */  bnel       $at, $zero, .L8000996C
    /* A594 80009994 8CA10000 */   lw        $at, 0x0($a1)
  .L80009998:
    /* A598 80009998 241800FE */  addiu      $t8, $zero, 0xFE
    /* A59C 8000999C A0580000 */  sb         $t8, 0x0($v0)
    /* A5A0 800099A0 03E00008 */  jr         $ra
    /* A5A4 800099A4 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800098E0
    /* A5A8 800099A8 00000000 */  nop
    /* A5AC 800099AC 00000000 */  nop
