.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_800099B0, 0x38

glabel func_800099B0
    /* A5B0 800099B0 3C0EA410 */  lui        $t6, %hi(DPC_CLOCK_REG)
    /* A5B4 800099B4 8DCF0010 */  lw         $t7, %lo(DPC_CLOCK_REG)($t6)
    /* A5B8 800099B8 3C18A410 */  lui        $t8, %hi(DPC_BUFBUSY_REG)
    /* A5BC 800099BC 3C08A410 */  lui        $t0, %hi(DPC_PIPEBUSY_REG)
    /* A5C0 800099C0 AC8F0000 */  sw         $t7, 0x0($a0)
    /* A5C4 800099C4 8F190014 */  lw         $t9, %lo(DPC_BUFBUSY_REG)($t8)
    /* A5C8 800099C8 3C0AA410 */  lui        $t2, %hi(DPC_TMEM_REG)
    /* A5CC 800099CC 2484000C */  addiu      $a0, $a0, 0xC
    /* A5D0 800099D0 AC99FFF8 */  sw         $t9, -0x8($a0)
    /* A5D4 800099D4 8D090018 */  lw         $t1, %lo(DPC_PIPEBUSY_REG)($t0)
    /* A5D8 800099D8 AC89FFFC */  sw         $t1, -0x4($a0)
    /* A5DC 800099DC 8D4B001C */  lw         $t3, %lo(DPC_TMEM_REG)($t2)
    /* A5E0 800099E0 03E00008 */  jr         $ra
    /* A5E4 800099E4 AC8B0000 */   sw        $t3, 0x0($a0)
endlabel func_800099B0
    /* A5E8 800099E8 00000000 */  nop
    /* A5EC 800099EC 00000000 */  nop
