.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_80009F20, 0x168

glabel func_80009F20
    /* AB20 80009F20 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* AB24 80009F24 AFBF001C */  sw         $ra, 0x1C($sp)
    /* AB28 80009F28 AFB00018 */  sw         $s0, 0x18($sp)
    /* AB2C 80009F2C 8C8E0008 */  lw         $t6, 0x8($a0)
    /* AB30 80009F30 8C990000 */  lw         $t9, 0x0($a0)
    /* AB34 80009F34 3C188003 */  lui        $t8, %hi(D_80037B30)
    /* AB38 80009F38 27187B30 */  addiu      $t8, $t8, %lo(D_80037B30)
    /* AB3C 80009F3C 000E7980 */  sll        $t7, $t6, 6
    /* AB40 80009F40 33290008 */  andi       $t1, $t9, 0x8
    /* AB44 80009F44 00808025 */  or         $s0, $a0, $zero
    /* AB48 80009F48 00A03825 */  or         $a3, $a1, $zero
    /* AB4C 80009F4C 15200003 */  bnez       $t1, .L80009F5C
    /* AB50 80009F50 01F84021 */   addu      $t0, $t7, $t8
    /* AB54 80009F54 10000047 */  b          .L8000A074
    /* AB58 80009F58 24020005 */   addiu     $v0, $zero, 0x5
  .L80009F5C:
    /* AB5C 80009F5C AFA70034 */  sw         $a3, 0x34($sp)
    /* AB60 80009F60 0C00396C */  jal        func_8000E5B0
    /* AB64 80009F64 AFA80024 */   sw        $t0, 0x24($sp)
    /* AB68 80009F68 8E0B0008 */  lw         $t3, 0x8($s0)
    /* AB6C 80009F6C 3C068003 */  lui        $a2, %hi(D_80037B30)
    /* AB70 80009F70 24C67B30 */  addiu      $a2, $a2, %lo(D_80037B30)
    /* AB74 80009F74 000B6180 */  sll        $t4, $t3, 6
    /* AB78 80009F78 00CC6821 */  addu       $t5, $a2, $t4
    /* AB7C 80009F7C 240A0001 */  addiu      $t2, $zero, 0x1
    /* AB80 80009F80 ADAA003C */  sw         $t2, 0x3C($t5)
    /* AB84 80009F84 8FA80024 */  lw         $t0, 0x24($sp)
    /* AB88 80009F88 8E0E0008 */  lw         $t6, 0x8($s0)
    /* AB8C 80009F8C 8FA70034 */  lw         $a3, 0x34($sp)
    /* AB90 80009F90 00001825 */  or         $v1, $zero, $zero
    /* AB94 80009F94 010E4021 */  addu       $t0, $t0, $t6
    /* AB98 80009F98 01001025 */  or         $v0, $t0, $zero
    /* AB9C 80009F9C 24040020 */  addiu      $a0, $zero, 0x20
  .L80009FA0:
    /* ABA0 80009FA0 24630004 */  addiu      $v1, $v1, 0x4
    /* ABA4 80009FA4 A0470007 */  sb         $a3, 0x7($v0)
    /* ABA8 80009FA8 A0470008 */  sb         $a3, 0x8($v0)
    /* ABAC 80009FAC A0470009 */  sb         $a3, 0x9($v0)
    /* ABB0 80009FB0 24420004 */  addiu      $v0, $v0, 0x4
    /* ABB4 80009FB4 1464FFFA */  bne        $v1, $a0, .L80009FA0
    /* ABB8 80009FB8 A0470002 */   sb        $a3, 0x2($v0)
    /* ABBC 80009FBC 240F00FE */  addiu      $t7, $zero, 0xFE
    /* ABC0 80009FC0 3C018003 */  lui        $at, %hi(D_80037AE0)
    /* ABC4 80009FC4 A02F7AE0 */  sb         $t7, %lo(D_80037AE0)($at)
    /* ABC8 80009FC8 8E180008 */  lw         $t8, 0x8($s0)
    /* ABCC 80009FCC AFA80024 */  sw         $t0, 0x24($sp)
    /* ABD0 80009FD0 AFA70034 */  sw         $a3, 0x34($sp)
    /* ABD4 80009FD4 0018C980 */  sll        $t9, $t8, 6
    /* ABD8 80009FD8 00D92821 */  addu       $a1, $a2, $t9
    /* ABDC 80009FDC 0C00392C */  jal        func_8000E4B0
    /* ABE0 80009FE0 24040001 */   addiu     $a0, $zero, 0x1
    /* ABE4 80009FE4 8E040004 */  lw         $a0, 0x4($s0)
    /* ABE8 80009FE8 00002825 */  or         $a1, $zero, $zero
    /* ABEC 80009FEC 0C001C9C */  jal        func_80007270
    /* ABF0 80009FF0 24060001 */   addiu     $a2, $zero, 0x1
    /* ABF4 80009FF4 8E090008 */  lw         $t1, 0x8($s0)
    /* ABF8 80009FF8 3C0C8003 */  lui        $t4, %hi(D_80037B30)
    /* ABFC 80009FFC 258C7B30 */  addiu      $t4, $t4, %lo(D_80037B30)
    /* AC00 8000A000 00095980 */  sll        $t3, $t1, 6
    /* AC04 8000A004 016C2821 */  addu       $a1, $t3, $t4
    /* AC08 8000A008 0C00392C */  jal        func_8000E4B0
    /* AC0C 8000A00C 00002025 */   or        $a0, $zero, $zero
    /* AC10 8000A010 8E040004 */  lw         $a0, 0x4($s0)
    /* AC14 8000A014 00002825 */  or         $a1, $zero, $zero
    /* AC18 8000A018 0C001C9C */  jal        func_80007270
    /* AC1C 8000A01C 24060001 */   addiu     $a2, $zero, 0x1
    /* AC20 8000A020 8FA80024 */  lw         $t0, 0x24($sp)
    /* AC24 8000A024 8FA70034 */  lw         $a3, 0x34($sp)
    /* AC28 8000A028 91100002 */  lbu        $s0, 0x2($t0)
    /* AC2C 8000A02C 320A00C0 */  andi       $t2, $s0, 0xC0
    /* AC30 8000A030 1540000D */  bnez       $t2, .L8000A068
    /* AC34 8000A034 01408025 */   or        $s0, $t2, $zero
    /* AC38 8000A038 54E00007 */  bnel       $a3, $zero, .L8000A058
    /* AC3C 8000A03C 910E0026 */   lbu       $t6, 0x26($t0)
    /* AC40 8000A040 910D0026 */  lbu        $t5, 0x26($t0)
    /* AC44 8000A044 11A00008 */  beqz       $t5, .L8000A068
    /* AC48 8000A048 00000000 */   nop
    /* AC4C 8000A04C 10000006 */  b          .L8000A068
    /* AC50 8000A050 24100004 */   addiu     $s0, $zero, 0x4
    /* AC54 8000A054 910E0026 */  lbu        $t6, 0x26($t0)
  .L8000A058:
    /* AC58 8000A058 240100EB */  addiu      $at, $zero, 0xEB
    /* AC5C 8000A05C 11C10002 */  beq        $t6, $at, .L8000A068
    /* AC60 8000A060 00000000 */   nop
    /* AC64 8000A064 24100004 */  addiu      $s0, $zero, 0x4
  .L8000A068:
    /* AC68 8000A068 0C00397D */  jal        func_8000E5F4
    /* AC6C 8000A06C 00000000 */   nop
    /* AC70 8000A070 02001025 */  or         $v0, $s0, $zero
  .L8000A074:
    /* AC74 8000A074 8FBF001C */  lw         $ra, 0x1C($sp)
    /* AC78 8000A078 8FB00018 */  lw         $s0, 0x18($sp)
    /* AC7C 8000A07C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* AC80 8000A080 03E00008 */  jr         $ra
    /* AC84 8000A084 00000000 */   nop
endlabel func_80009F20

nonmatching func_8000A088, 0x10C

glabel func_8000A088
    /* AC88 8000A088 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* AC8C 8000A08C AFBF0014 */  sw         $ra, 0x14($sp)
    /* AC90 8000A090 00803025 */  or         $a2, $a0, $zero
    /* AC94 8000A094 240E00FF */  addiu      $t6, $zero, 0xFF
    /* AC98 8000A098 240F0023 */  addiu      $t7, $zero, 0x23
    /* AC9C 8000A09C 24180001 */  addiu      $t8, $zero, 0x1
    /* ACA0 8000A0A0 24190003 */  addiu      $t9, $zero, 0x3
    /* ACA4 8000A0A4 240800C0 */  addiu      $t0, $zero, 0xC0
    /* ACA8 8000A0A8 A3AE0024 */  sb         $t6, 0x24($sp)
    /* ACAC 8000A0AC A3AF0025 */  sb         $t7, 0x25($sp)
    /* ACB0 8000A0B0 A3B80026 */  sb         $t8, 0x26($sp)
    /* ACB4 8000A0B4 A3B90027 */  sb         $t9, 0x27($sp)
    /* ACB8 8000A0B8 A3A80028 */  sb         $t0, 0x28($sp)
    /* ACBC 8000A0BC AFA60050 */  sw         $a2, 0x50($sp)
    /* ACC0 8000A0C0 24040600 */  addiu      $a0, $zero, 0x600
    /* ACC4 8000A0C4 0C003E7C */  jal        func_8000F9F0
    /* ACC8 8000A0C8 AFA5004C */   sw        $a1, 0x4C($sp)
    /* ACCC 8000A0CC 8FA60050 */  lw         $a2, 0x50($sp)
    /* ACD0 8000A0D0 3449C000 */  ori        $t1, $v0, 0xC000
    /* ACD4 8000A0D4 A3A90029 */  sb         $t1, 0x29($sp)
    /* ACD8 8000A0D8 10C00012 */  beqz       $a2, .L8000A124
    /* ACDC 8000A0DC 8FA3004C */   lw        $v1, 0x4C($sp)
    /* ACE0 8000A0E0 18C00010 */  blez       $a2, .L8000A124
    /* ACE4 8000A0E4 00001025 */   or        $v0, $zero, $zero
    /* ACE8 8000A0E8 30C50003 */  andi       $a1, $a2, 0x3
    /* ACEC 8000A0EC 10A00006 */  beqz       $a1, .L8000A108
    /* ACF0 8000A0F0 00A02025 */   or        $a0, $a1, $zero
  .L8000A0F4:
    /* ACF4 8000A0F4 24420001 */  addiu      $v0, $v0, 0x1
    /* ACF8 8000A0F8 A0600000 */  sb         $zero, 0x0($v1)
    /* ACFC 8000A0FC 1482FFFD */  bne        $a0, $v0, .L8000A0F4
    /* AD00 8000A100 24630001 */   addiu     $v1, $v1, 0x1
    /* AD04 8000A104 10460007 */  beq        $v0, $a2, .L8000A124
  .L8000A108:
    /* AD08 8000A108 24420004 */   addiu     $v0, $v0, 0x4
    /* AD0C 8000A10C A0600001 */  sb         $zero, 0x1($v1)
    /* AD10 8000A110 A0600002 */  sb         $zero, 0x2($v1)
    /* AD14 8000A114 A0600003 */  sb         $zero, 0x3($v1)
    /* AD18 8000A118 24630004 */  addiu      $v1, $v1, 0x4
    /* AD1C 8000A11C 1446FFFA */  bne        $v0, $a2, .L8000A108
    /* AD20 8000A120 A060FFFC */   sb        $zero, -0x4($v1)
  .L8000A124:
    /* AD24 8000A124 27AA0024 */  addiu      $t2, $sp, 0x24
    /* AD28 8000A128 254C0024 */  addiu      $t4, $t2, 0x24
    /* AD2C 8000A12C 00606825 */  or         $t5, $v1, $zero
  .L8000A130:
    /* AD30 8000A130 8D410000 */  lw         $at, 0x0($t2)
    /* AD34 8000A134 254A000C */  addiu      $t2, $t2, 0xC
    /* AD38 8000A138 25AD000C */  addiu      $t5, $t5, 0xC
    /* AD3C 8000A13C A9A1FFF4 */  swl        $at, -0xC($t5)
    /* AD40 8000A140 B9A1FFF7 */  swr        $at, -0x9($t5)
    /* AD44 8000A144 8D41FFF8 */  lw         $at, -0x8($t2)
    /* AD48 8000A148 A9A1FFF8 */  swl        $at, -0x8($t5)
    /* AD4C 8000A14C B9A1FFFB */  swr        $at, -0x5($t5)
    /* AD50 8000A150 8D41FFFC */  lw         $at, -0x4($t2)
    /* AD54 8000A154 A9A1FFFC */  swl        $at, -0x4($t5)
    /* AD58 8000A158 154CFFF5 */  bne        $t2, $t4, .L8000A130
    /* AD5C 8000A15C B9A1FFFF */   swr       $at, -0x1($t5)
    /* AD60 8000A160 91410000 */  lbu        $at, 0x0($t2)
    /* AD64 8000A164 240E00FE */  addiu      $t6, $zero, 0xFE
    /* AD68 8000A168 24630027 */  addiu      $v1, $v1, 0x27
    /* AD6C 8000A16C A1A10000 */  sb         $at, 0x0($t5)
    /* AD70 8000A170 914C0001 */  lbu        $t4, 0x1($t2)
    /* AD74 8000A174 A1AC0001 */  sb         $t4, 0x1($t5)
    /* AD78 8000A178 91410002 */  lbu        $at, 0x2($t2)
    /* AD7C 8000A17C A1A10002 */  sb         $at, 0x2($t5)
    /* AD80 8000A180 A06E0000 */  sb         $t6, 0x0($v1)
    /* AD84 8000A184 8FBF0014 */  lw         $ra, 0x14($sp)
    /* AD88 8000A188 27BD0050 */  addiu      $sp, $sp, 0x50
    /* AD8C 8000A18C 03E00008 */  jr         $ra
    /* AD90 8000A190 00000000 */   nop
endlabel func_8000A088

nonmatching func_8000A194, 0x15C

glabel func_8000A194
    /* AD94 8000A194 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* AD98 8000A198 AFBF001C */  sw         $ra, 0x1C($sp)
    /* AD9C 8000A19C AFB00018 */  sw         $s0, 0x18($sp)
    /* ADA0 8000A1A0 AFA40048 */  sw         $a0, 0x48($sp)
    /* ADA4 8000A1A4 AFA60050 */  sw         $a2, 0x50($sp)
    /* ADA8 8000A1A8 ACA40004 */  sw         $a0, 0x4($a1)
    /* ADAC 8000A1AC 8FAF0050 */  lw         $t7, 0x50($sp)
    /* ADB0 8000A1B0 241800FF */  addiu      $t8, $zero, 0xFF
    /* ADB4 8000A1B4 00A08025 */  or         $s0, $a1, $zero
    /* ADB8 8000A1B8 A0B80065 */  sb         $t8, 0x65($a1)
    /* ADBC 8000A1BC ACA00000 */  sw         $zero, 0x0($a1)
    /* ADC0 8000A1C0 00A02025 */  or         $a0, $a1, $zero
    /* ADC4 8000A1C4 ACAF0008 */  sw         $t7, 0x8($a1)
    /* ADC8 8000A1C8 0C003A14 */  jal        func_8000E850
    /* ADCC 8000A1CC 240500FE */   addiu     $a1, $zero, 0xFE
    /* ADD0 8000A1D0 24010002 */  addiu      $at, $zero, 0x2
    /* ADD4 8000A1D4 14410005 */  bne        $v0, $at, .L8000A1EC
    /* ADD8 8000A1D8 00401825 */   or        $v1, $v0, $zero
    /* ADDC 8000A1DC 02002025 */  or         $a0, $s0, $zero
    /* ADE0 8000A1E0 0C003A14 */  jal        func_8000E850
    /* ADE4 8000A1E4 24050080 */   addiu     $a1, $zero, 0x80
    /* ADE8 8000A1E8 00401825 */  or         $v1, $v0, $zero
  .L8000A1EC:
    /* ADEC 8000A1EC 10400003 */  beqz       $v0, .L8000A1FC
    /* ADF0 8000A1F0 8FA40048 */   lw        $a0, 0x48($sp)
    /* ADF4 8000A1F4 10000039 */  b          .L8000A2DC
    /* ADF8 8000A1F8 00601025 */   or        $v0, $v1, $zero
  .L8000A1FC:
    /* ADFC 8000A1FC 8FA50050 */  lw         $a1, 0x50($sp)
    /* AE00 8000A200 24060400 */  addiu      $a2, $zero, 0x400
    /* AE04 8000A204 0C003A34 */  jal        func_8000E8D0
    /* AE08 8000A208 27A70024 */   addiu     $a3, $sp, 0x24
    /* AE0C 8000A20C 24010002 */  addiu      $at, $zero, 0x2
    /* AE10 8000A210 14410002 */  bne        $v0, $at, .L8000A21C
    /* AE14 8000A214 00401825 */   or        $v1, $v0, $zero
    /* AE18 8000A218 24030004 */  addiu      $v1, $zero, 0x4
  .L8000A21C:
    /* AE1C 8000A21C 10600003 */  beqz       $v1, .L8000A22C
    /* AE20 8000A220 93B90043 */   lbu       $t9, 0x43($sp)
    /* AE24 8000A224 1000002D */  b          .L8000A2DC
    /* AE28 8000A228 00601025 */   or        $v0, $v1, $zero
  .L8000A22C:
    /* AE2C 8000A22C 240100FE */  addiu      $at, $zero, 0xFE
    /* AE30 8000A230 17210003 */  bne        $t9, $at, .L8000A240
    /* AE34 8000A234 02002025 */   or        $a0, $s0, $zero
    /* AE38 8000A238 10000028 */  b          .L8000A2DC
    /* AE3C 8000A23C 2402000B */   addiu     $v0, $zero, 0xB
  .L8000A240:
    /* AE40 8000A240 0C003A14 */  jal        func_8000E850
    /* AE44 8000A244 24050080 */   addiu     $a1, $zero, 0x80
    /* AE48 8000A248 24010002 */  addiu      $at, $zero, 0x2
    /* AE4C 8000A24C 14410002 */  bne        $v0, $at, .L8000A258
    /* AE50 8000A250 00401825 */   or        $v1, $v0, $zero
    /* AE54 8000A254 24030004 */  addiu      $v1, $zero, 0x4
  .L8000A258:
    /* AE58 8000A258 10600003 */  beqz       $v1, .L8000A268
    /* AE5C 8000A25C 8FA40048 */   lw        $a0, 0x48($sp)
    /* AE60 8000A260 1000001E */  b          .L8000A2DC
    /* AE64 8000A264 00601025 */   or        $v0, $v1, $zero
  .L8000A268:
    /* AE68 8000A268 8FA50050 */  lw         $a1, 0x50($sp)
    /* AE6C 8000A26C 24060400 */  addiu      $a2, $zero, 0x400
    /* AE70 8000A270 0C003A34 */  jal        func_8000E8D0
    /* AE74 8000A274 27A70024 */   addiu     $a3, $sp, 0x24
    /* AE78 8000A278 24010002 */  addiu      $at, $zero, 0x2
    /* AE7C 8000A27C 14410002 */  bne        $v0, $at, .L8000A288
    /* AE80 8000A280 00401825 */   or        $v1, $v0, $zero
    /* AE84 8000A284 24030004 */  addiu      $v1, $zero, 0x4
  .L8000A288:
    /* AE88 8000A288 10600003 */  beqz       $v1, .L8000A298
    /* AE8C 8000A28C 93A80043 */   lbu       $t0, 0x43($sp)
    /* AE90 8000A290 10000012 */  b          .L8000A2DC
    /* AE94 8000A294 00601025 */   or        $v0, $v1, $zero
  .L8000A298:
    /* AE98 8000A298 24010080 */  addiu      $at, $zero, 0x80
    /* AE9C 8000A29C 51010004 */  beql       $t0, $at, .L8000A2B0
    /* AEA0 8000A2A0 8E090000 */   lw        $t1, 0x0($s0)
    /* AEA4 8000A2A4 1000000D */  b          .L8000A2DC
    /* AEA8 8000A2A8 2402000B */   addiu     $v0, $zero, 0xB
    /* AEAC 8000A2AC 8E090000 */  lw         $t1, 0x0($s0)
  .L8000A2B0:
    /* AEB0 8000A2B0 8FA40050 */  lw         $a0, 0x50($sp)
    /* AEB4 8000A2B4 3C0D8003 */  lui        $t5, %hi(D_80037B30)
    /* AEB8 8000A2B8 312A0008 */  andi       $t2, $t1, 0x8
    /* AEBC 8000A2BC 15400004 */  bnez       $t2, .L8000A2D0
    /* AEC0 8000A2C0 00046180 */   sll       $t4, $a0, 6
    /* AEC4 8000A2C4 25AD7B30 */  addiu      $t5, $t5, %lo(D_80037B30)
    /* AEC8 8000A2C8 0C002822 */  jal        func_8000A088
    /* AECC 8000A2CC 018D2821 */   addu      $a1, $t4, $t5
  .L8000A2D0:
    /* AED0 8000A2D0 240E0008 */  addiu      $t6, $zero, 0x8
    /* AED4 8000A2D4 AE0E0000 */  sw         $t6, 0x0($s0)
    /* AED8 8000A2D8 00001025 */  or         $v0, $zero, $zero
  .L8000A2DC:
    /* AEDC 8000A2DC 8FBF001C */  lw         $ra, 0x1C($sp)
    /* AEE0 8000A2E0 8FB00018 */  lw         $s0, 0x18($sp)
    /* AEE4 8000A2E4 27BD0048 */  addiu      $sp, $sp, 0x48
    /* AEE8 8000A2E8 03E00008 */  jr         $ra
    /* AEEC 8000A2EC 00000000 */   nop
endlabel func_8000A194

nonmatching func_8000A2F0, 0x58

glabel func_8000A2F0
    /* AEF0 8000A2F0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* AEF4 8000A2F4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* AEF8 8000A2F8 8C8E0000 */  lw         $t6, 0x0($a0)
    /* AEFC 8000A2FC 24030005 */  addiu      $v1, $zero, 0x5
    /* AF00 8000A300 31CF0005 */  andi       $t7, $t6, 0x5
    /* AF04 8000A304 11E0000B */  beqz       $t7, .L8000A334
    /* AF08 8000A308 00000000 */   nop
    /* AF0C 8000A30C 0C003C49 */  jal        func_8000F124
    /* AF10 8000A310 AFA40018 */   sw        $a0, 0x18($sp)
    /* AF14 8000A314 8FA40018 */  lw         $a0, 0x18($sp)
    /* AF18 8000A318 14400006 */  bnez       $v0, .L8000A334
    /* AF1C 8000A31C 00401825 */   or        $v1, $v0, $zero
    /* AF20 8000A320 8C980000 */  lw         $t8, 0x0($a0)
    /* AF24 8000A324 2401FFFB */  addiu      $at, $zero, -0x5
    /* AF28 8000A328 0301C824 */  and        $t9, $t8, $at
    /* AF2C 8000A32C 10000001 */  b          .L8000A334
    /* AF30 8000A330 AC990000 */   sw        $t9, 0x0($a0)
  .L8000A334:
    /* AF34 8000A334 8FBF0014 */  lw         $ra, 0x14($sp)
    /* AF38 8000A338 27BD0018 */  addiu      $sp, $sp, 0x18
    /* AF3C 8000A33C 00601025 */  or         $v0, $v1, $zero
    /* AF40 8000A340 03E00008 */  jr         $ra
    /* AF44 8000A344 00000000 */   nop
endlabel func_8000A2F0
    /* AF48 8000A348 00000000 */  nop
    /* AF4C 8000A34C 00000000 */  nop
