.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000C050, 0x40

glabel func_8000C050
    /* CC50 8000C050 00803025 */  or         $a2, $a0, $zero
    /* CC54 8000C054 8CC70000 */  lw         $a3, 0x0($a2)
    /* CC58 8000C058 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* CC5C 8000C05C 10E0000A */  beqz       $a3, .L8000C088
    /* CC60 8000C060 00000000 */   nop
  .L8000C064:
    /* CC64 8000C064 14E50004 */  bne        $a3, $a1, .L8000C078
    /* CC68 8000C068 00000000 */   nop
    /* CC6C 8000C06C 8CAE0000 */  lw         $t6, 0x0($a1)
    /* CC70 8000C070 10000005 */  b          .L8000C088
    /* CC74 8000C074 ACCE0000 */   sw        $t6, 0x0($a2)
  .L8000C078:
    /* CC78 8000C078 00E03025 */  or         $a2, $a3, $zero
    /* CC7C 8000C07C 8CC70000 */  lw         $a3, 0x0($a2)
    /* CC80 8000C080 14E0FFF8 */  bnez       $a3, .L8000C064
    /* CC84 8000C084 00000000 */   nop
  .L8000C088:
    /* CC88 8000C088 03E00008 */  jr         $ra
    /* CC8C 8000C08C 27BD0008 */   addiu     $sp, $sp, 0x8
endlabel func_8000C050

nonmatching func_8000C090, 0x8C

glabel func_8000C090
    /* CC90 8000C090 3C018003 */  lui        $at, %hi(D_80037C54)
    /* CC94 8000C094 240E0000 */  addiu      $t6, $zero, 0x0
    /* CC98 8000C098 240F0000 */  addiu      $t7, $zero, 0x0
    /* CC9C 8000C09C AC2F7C54 */  sw         $t7, %lo(D_80037C54)($at)
    /* CCA0 8000C0A0 AC2E7C50 */  sw         $t6, %lo(D_80037C50)($at)
    /* CCA4 8000C0A4 3C018003 */  lui        $at, %hi(D_80037C58)
    /* CCA8 8000C0A8 3C188003 */  lui        $t8, %hi(D_8002C3F0)
    /* CCAC 8000C0AC 8F18C3F0 */  lw         $t8, %lo(D_8002C3F0)($t8)
    /* CCB0 8000C0B0 AC207C58 */  sw         $zero, %lo(D_80037C58)($at)
    /* CCB4 8000C0B4 3C018003 */  lui        $at, %hi(D_80037C5C)
    /* CCB8 8000C0B8 AC207C5C */  sw         $zero, %lo(D_80037C5C)($at)
    /* CCBC 8000C0BC 3C198003 */  lui        $t9, %hi(D_8002C3F0)
    /* CCC0 8000C0C0 AF180004 */  sw         $t8, 0x4($t8)
    /* CCC4 8000C0C4 8F39C3F0 */  lw         $t9, %lo(D_8002C3F0)($t9)
    /* CCC8 8000C0C8 3C098003 */  lui        $t1, %hi(D_8002C3F0)
    /* CCCC 8000C0CC 240A0000 */  addiu      $t2, $zero, 0x0
    /* CCD0 8000C0D0 8F280004 */  lw         $t0, 0x4($t9)
    /* CCD4 8000C0D4 240B0000 */  addiu      $t3, $zero, 0x0
    /* CCD8 8000C0D8 3C0C8003 */  lui        $t4, %hi(D_8002C3F0)
    /* CCDC 8000C0DC AF280000 */  sw         $t0, 0x0($t9)
    /* CCE0 8000C0E0 8D29C3F0 */  lw         $t1, %lo(D_8002C3F0)($t1)
    /* CCE4 8000C0E4 3C0D8003 */  lui        $t5, %hi(D_8002C3F0)
    /* CCE8 8000C0E8 3C188003 */  lui        $t8, %hi(D_8002C3F0)
    /* CCEC 8000C0EC AD2A0010 */  sw         $t2, 0x10($t1)
    /* CCF0 8000C0F0 AD2B0014 */  sw         $t3, 0x14($t1)
    /* CCF4 8000C0F4 8D8CC3F0 */  lw         $t4, %lo(D_8002C3F0)($t4)
    /* CCF8 8000C0F8 8D8E0010 */  lw         $t6, 0x10($t4)
    /* CCFC 8000C0FC 8D8F0014 */  lw         $t7, 0x14($t4)
    /* CD00 8000C100 AD8E0008 */  sw         $t6, 0x8($t4)
    /* CD04 8000C104 AD8F000C */  sw         $t7, 0xC($t4)
    /* CD08 8000C108 8DADC3F0 */  lw         $t5, %lo(D_8002C3F0)($t5)
    /* CD0C 8000C10C ADA00018 */  sw         $zero, 0x18($t5)
    /* CD10 8000C110 8F18C3F0 */  lw         $t8, %lo(D_8002C3F0)($t8)
    /* CD14 8000C114 03E00008 */  jr         $ra
    /* CD18 8000C118 AF00001C */   sw        $zero, 0x1C($t8)
endlabel func_8000C090

nonmatching func_8000C11C, 0x178

glabel func_8000C11C
    /* CD1C 8000C11C 3C0E8003 */  lui        $t6, %hi(D_8002C3F0)
    /* CD20 8000C120 8DCEC3F0 */  lw         $t6, %lo(D_8002C3F0)($t6)
    /* CD24 8000C124 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* CD28 8000C128 AFBF0014 */  sw         $ra, 0x14($sp)
    /* CD2C 8000C12C 8DCF0000 */  lw         $t7, 0x0($t6)
    /* CD30 8000C130 11EE0054 */  beq        $t7, $t6, .L8000C284
    /* CD34 8000C134 00000000 */   nop
  .L8000C138:
    /* CD38 8000C138 3C188003 */  lui        $t8, %hi(D_8002C3F0)
    /* CD3C 8000C13C 8F18C3F0 */  lw         $t8, %lo(D_8002C3F0)($t8)
    /* CD40 8000C140 8F190000 */  lw         $t9, 0x0($t8)
    /* CD44 8000C144 17380006 */  bne        $t9, $t8, .L8000C160
    /* CD48 8000C148 AFB90024 */   sw        $t9, 0x24($sp)
    /* CD4C 8000C14C 0C003EE4 */  jal        func_8000FB90
    /* CD50 8000C150 00002025 */   or        $a0, $zero, $zero
    /* CD54 8000C154 3C018003 */  lui        $at, %hi(D_80037C60)
    /* CD58 8000C158 1000004A */  b          .L8000C284
    /* CD5C 8000C15C AC207C60 */   sw        $zero, %lo(D_80037C60)($at)
  .L8000C160:
    /* CD60 8000C160 0C00325C */  jal        func_8000C970
    /* CD64 8000C164 00000000 */   nop
    /* CD68 8000C168 AFA20020 */  sw         $v0, 0x20($sp)
    /* CD6C 8000C16C 3C098003 */  lui        $t1, %hi(D_80037C60)
    /* CD70 8000C170 8D297C60 */  lw         $t1, %lo(D_80037C60)($t1)
    /* CD74 8000C174 8FA80020 */  lw         $t0, 0x20($sp)
    /* CD78 8000C178 8FAF0024 */  lw         $t7, 0x24($sp)
    /* CD7C 8000C17C 3C018003 */  lui        $at, %hi(D_80037C60)
    /* CD80 8000C180 01095023 */  subu       $t2, $t0, $t1
    /* CD84 8000C184 AFAA001C */  sw         $t2, 0x1C($sp)
    /* CD88 8000C188 AC287C60 */  sw         $t0, %lo(D_80037C60)($at)
    /* CD8C 8000C18C 8DEE0010 */  lw         $t6, 0x10($t7)
    /* CD90 8000C190 8FAB001C */  lw         $t3, 0x1C($sp)
    /* CD94 8000C194 240C0000 */  addiu      $t4, $zero, 0x0
    /* CD98 8000C198 01E0C825 */  or         $t9, $t7, $zero
    /* CD9C 8000C19C 01CC082B */  sltu       $at, $t6, $t4
    /* CDA0 8000C1A0 8DEF0014 */  lw         $t7, 0x14($t7)
    /* CDA4 8000C1A4 14200016 */  bnez       $at, .L8000C200
    /* CDA8 8000C1A8 01606825 */   or        $t5, $t3, $zero
    /* CDAC 8000C1AC 018E082B */  sltu       $at, $t4, $t6
    /* CDB0 8000C1B0 14200003 */  bnez       $at, .L8000C1C0
    /* CDB4 8000C1B4 01AF082B */   sltu      $at, $t5, $t7
    /* CDB8 8000C1B8 10200011 */  beqz       $at, .L8000C200
    /* CDBC 8000C1BC 00000000 */   nop
  .L8000C1C0:
    /* CDC0 8000C1C0 27380010 */  addiu      $t8, $t9, 0x10
    /* CDC4 8000C1C4 AFB80018 */  sw         $t8, 0x18($sp)
    /* CDC8 8000C1C8 8F2B0014 */  lw         $t3, 0x14($t9)
    /* CDCC 8000C1CC 8F2A0010 */  lw         $t2, 0x10($t9)
    /* CDD0 8000C1D0 016D082B */  sltu       $at, $t3, $t5
    /* CDD4 8000C1D4 014C4023 */  subu       $t0, $t2, $t4
    /* CDD8 8000C1D8 01014023 */  subu       $t0, $t0, $at
    /* CDDC 8000C1DC 016D4823 */  subu       $t1, $t3, $t5
    /* CDE0 8000C1E0 AF290014 */  sw         $t1, 0x14($t9)
    /* CDE4 8000C1E4 AF280010 */  sw         $t0, 0x10($t9)
    /* CDE8 8000C1E8 8FAE0024 */  lw         $t6, 0x24($sp)
    /* CDEC 8000C1EC 8DC40010 */  lw         $a0, 0x10($t6)
    /* CDF0 8000C1F0 0C0030A5 */  jal        func_8000C294
    /* CDF4 8000C1F4 8DC50014 */   lw        $a1, 0x14($t6)
    /* CDF8 8000C1F8 10000022 */  b          .L8000C284
    /* CDFC 8000C1FC 00000000 */   nop
  .L8000C200:
    /* CE00 8000C200 8FAF0024 */  lw         $t7, 0x24($sp)
    /* CE04 8000C204 8DF80000 */  lw         $t8, 0x0($t7)
    /* CE08 8000C208 8DEA0004 */  lw         $t2, 0x4($t7)
    /* CE0C 8000C20C AD580000 */  sw         $t8, 0x0($t2)
    /* CE10 8000C210 8FAB0024 */  lw         $t3, 0x24($sp)
    /* CE14 8000C214 8D6C0004 */  lw         $t4, 0x4($t3)
    /* CE18 8000C218 8D6D0000 */  lw         $t5, 0x0($t3)
    /* CE1C 8000C21C ADAC0004 */  sw         $t4, 0x4($t5)
    /* CE20 8000C220 8FA80024 */  lw         $t0, 0x24($sp)
    /* CE24 8000C224 AD000000 */  sw         $zero, 0x0($t0)
    /* CE28 8000C228 8FA90024 */  lw         $t1, 0x24($sp)
    /* CE2C 8000C22C AD200004 */  sw         $zero, 0x4($t1)
    /* CE30 8000C230 8FB90024 */  lw         $t9, 0x24($sp)
    /* CE34 8000C234 8F2E0018 */  lw         $t6, 0x18($t9)
    /* CE38 8000C238 11C00005 */  beqz       $t6, .L8000C250
    /* CE3C 8000C23C 00000000 */   nop
    /* CE40 8000C240 01C02025 */  or         $a0, $t6, $zero
    /* CE44 8000C244 8F25001C */  lw         $a1, 0x1C($t9)
    /* CE48 8000C248 0C001D78 */  jal        func_800075E0
    /* CE4C 8000C24C 00003025 */   or        $a2, $zero, $zero
  .L8000C250:
    /* CE50 8000C250 8FAF0024 */  lw         $t7, 0x24($sp)
    /* CE54 8000C254 8DF80008 */  lw         $t8, 0x8($t7)
    /* CE58 8000C258 8DF9000C */  lw         $t9, 0xC($t7)
    /* CE5C 8000C25C 17000003 */  bnez       $t8, .L8000C26C
    /* CE60 8000C260 00000000 */   nop
    /* CE64 8000C264 1320FFB4 */  beqz       $t9, .L8000C138
    /* CE68 8000C268 00000000 */   nop
  .L8000C26C:
    /* CE6C 8000C26C ADF80010 */  sw         $t8, 0x10($t7)
    /* CE70 8000C270 ADF90014 */  sw         $t9, 0x14($t7)
    /* CE74 8000C274 0C0030C2 */  jal        func_8000C308
    /* CE78 8000C278 8FA40024 */   lw        $a0, 0x24($sp)
    /* CE7C 8000C27C 1000FFAE */  b          .L8000C138
    /* CE80 8000C280 00000000 */   nop
  .L8000C284:
    /* CE84 8000C284 8FBF0014 */  lw         $ra, 0x14($sp)
    /* CE88 8000C288 27BD0028 */  addiu      $sp, $sp, 0x28
    /* CE8C 8000C28C 03E00008 */  jr         $ra
    /* CE90 8000C290 00000000 */   nop
endlabel func_8000C11C

nonmatching func_8000C294, 0x74

glabel func_8000C294
    /* CE94 8000C294 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* CE98 8000C298 AFBF0014 */  sw         $ra, 0x14($sp)
    /* CE9C 8000C29C AFA40028 */  sw         $a0, 0x28($sp)
    /* CEA0 8000C2A0 0C00312C */  jal        func_8000C4B0
    /* CEA4 8000C2A4 AFA5002C */   sw        $a1, 0x2C($sp)
    /* CEA8 8000C2A8 0C00325C */  jal        func_8000C970
    /* CEAC 8000C2AC AFA2001C */   sw        $v0, 0x1C($sp)
    /* CEB0 8000C2B0 3C018003 */  lui        $at, %hi(D_80037C60)
    /* CEB4 8000C2B4 AC227C60 */  sw         $v0, %lo(D_80037C60)($at)
    /* CEB8 8000C2B8 3C0E8003 */  lui        $t6, %hi(D_80037C60)
    /* CEBC 8000C2BC 8DCE7C60 */  lw         $t6, %lo(D_80037C60)($t6)
    /* CEC0 8000C2C0 8FA9002C */  lw         $t1, 0x2C($sp)
    /* CEC4 8000C2C4 8FA80028 */  lw         $t0, 0x28($sp)
    /* CEC8 8000C2C8 01C0C825 */  or         $t9, $t6, $zero
    /* CECC 8000C2CC 03295821 */  addu       $t3, $t9, $t1
    /* CED0 8000C2D0 24180000 */  addiu      $t8, $zero, 0x0
    /* CED4 8000C2D4 0169082B */  sltu       $at, $t3, $t1
    /* CED8 8000C2D8 00385021 */  addu       $t2, $at, $t8
    /* CEDC 8000C2DC 01485021 */  addu       $t2, $t2, $t0
    /* CEE0 8000C2E0 AFAA0020 */  sw         $t2, 0x20($sp)
    /* CEE4 8000C2E4 AFAB0024 */  sw         $t3, 0x24($sp)
    /* CEE8 8000C2E8 0C003EE4 */  jal        func_8000FB90
    /* CEEC 8000C2EC 01602025 */   or        $a0, $t3, $zero
    /* CEF0 8000C2F0 0C003148 */  jal        func_8000C520
    /* CEF4 8000C2F4 8FA4001C */   lw        $a0, 0x1C($sp)
    /* CEF8 8000C2F8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* CEFC 8000C2FC 27BD0028 */  addiu      $sp, $sp, 0x28
    /* CF00 8000C300 03E00008 */  jr         $ra
    /* CF04 8000C304 00000000 */   nop
endlabel func_8000C294

nonmatching func_8000C308, 0x188

glabel func_8000C308
    /* CF08 8000C308 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* CF0C 8000C30C AFBF0014 */  sw         $ra, 0x14($sp)
    /* CF10 8000C310 0C00312C */  jal        func_8000C4B0
    /* CF14 8000C314 AFA40038 */   sw        $a0, 0x38($sp)
    /* CF18 8000C318 3C0E8003 */  lui        $t6, %hi(D_8002C3F0)
    /* CF1C 8000C31C 8DCEC3F0 */  lw         $t6, %lo(D_8002C3F0)($t6)
    /* CF20 8000C320 AFA20024 */  sw         $v0, 0x24($sp)
    /* CF24 8000C324 8FB80038 */  lw         $t8, 0x38($sp)
    /* CF28 8000C328 8DCF0000 */  lw         $t7, 0x0($t6)
    /* CF2C 8000C32C AFAF0034 */  sw         $t7, 0x34($sp)
    /* CF30 8000C330 8F090014 */  lw         $t1, 0x14($t8)
    /* CF34 8000C334 8F080010 */  lw         $t0, 0x10($t8)
    /* CF38 8000C338 AFA9002C */  sw         $t1, 0x2C($sp)
    /* CF3C 8000C33C 11EE0029 */  beq        $t7, $t6, .L8000C3E4
    /* CF40 8000C340 AFA80028 */   sw        $t0, 0x28($sp)
    /* CF44 8000C344 8DEA0010 */  lw         $t2, 0x10($t7)
    /* CF48 8000C348 8DEB0014 */  lw         $t3, 0x14($t7)
    /* CF4C 8000C34C 010A082B */  sltu       $at, $t0, $t2
    /* CF50 8000C350 14200024 */  bnez       $at, .L8000C3E4
    /* CF54 8000C354 0148082B */   sltu      $at, $t2, $t0
    /* CF58 8000C358 14200003 */  bnez       $at, .L8000C368
    /* CF5C 8000C35C 0169082B */   sltu      $at, $t3, $t1
    /* CF60 8000C360 10200020 */  beqz       $at, .L8000C3E4
    /* CF64 8000C364 00000000 */   nop
  .L8000C368:
    /* CF68 8000C368 27B90028 */  addiu      $t9, $sp, 0x28
    /* CF6C 8000C36C 8FB80034 */  lw         $t8, 0x34($sp)
    /* CF70 8000C370 AFB90020 */  sw         $t9, 0x20($sp)
    /* CF74 8000C374 8F2D0004 */  lw         $t5, 0x4($t9)
    /* CF78 8000C378 8F2C0000 */  lw         $t4, 0x0($t9)
    /* CF7C 8000C37C 8F0F0014 */  lw         $t7, 0x14($t8)
    /* CF80 8000C380 8F0E0010 */  lw         $t6, 0x10($t8)
    /* CF84 8000C384 3C188003 */  lui        $t8, %hi(D_8002C3F0)
    /* CF88 8000C388 01AF082B */  sltu       $at, $t5, $t7
    /* CF8C 8000C38C 018E4023 */  subu       $t0, $t4, $t6
    /* CF90 8000C390 01014023 */  subu       $t0, $t0, $at
    /* CF94 8000C394 01AF4823 */  subu       $t1, $t5, $t7
    /* CF98 8000C398 AF290004 */  sw         $t1, 0x4($t9)
    /* CF9C 8000C39C AF280000 */  sw         $t0, 0x0($t9)
    /* CFA0 8000C3A0 8FAA0034 */  lw         $t2, 0x34($sp)
    /* CFA4 8000C3A4 8F18C3F0 */  lw         $t8, %lo(D_8002C3F0)($t8)
    /* CFA8 8000C3A8 8D4B0000 */  lw         $t3, 0x0($t2)
    /* CFAC 8000C3AC 1178000D */  beq        $t3, $t8, .L8000C3E4
    /* CFB0 8000C3B0 AFAB0034 */   sw        $t3, 0x34($sp)
    /* CFB4 8000C3B4 8FAC0028 */  lw         $t4, 0x28($sp)
    /* CFB8 8000C3B8 8D6E0010 */  lw         $t6, 0x10($t3)
    /* CFBC 8000C3BC 8FAD002C */  lw         $t5, 0x2C($sp)
    /* CFC0 8000C3C0 8D6F0014 */  lw         $t7, 0x14($t3)
    /* CFC4 8000C3C4 01CC082B */  sltu       $at, $t6, $t4
    /* CFC8 8000C3C8 1420FFE7 */  bnez       $at, .L8000C368
    /* CFCC 8000C3CC 00000000 */   nop
    /* CFD0 8000C3D0 018E082B */  sltu       $at, $t4, $t6
    /* CFD4 8000C3D4 14200003 */  bnez       $at, .L8000C3E4
    /* CFD8 8000C3D8 01ED082B */   sltu      $at, $t7, $t5
    /* CFDC 8000C3DC 1420FFE2 */  bnez       $at, .L8000C368
    /* CFE0 8000C3E0 00000000 */   nop
  .L8000C3E4:
    /* CFE4 8000C3E4 8FB90038 */  lw         $t9, 0x38($sp)
    /* CFE8 8000C3E8 8FA80028 */  lw         $t0, 0x28($sp)
    /* CFEC 8000C3EC 8FA9002C */  lw         $t1, 0x2C($sp)
    /* CFF0 8000C3F0 3C188003 */  lui        $t8, %hi(D_8002C3F0)
    /* CFF4 8000C3F4 AF280010 */  sw         $t0, 0x10($t9)
    /* CFF8 8000C3F8 AF290014 */  sw         $t1, 0x14($t9)
    /* CFFC 8000C3FC 8F18C3F0 */  lw         $t8, %lo(D_8002C3F0)($t8)
    /* D000 8000C400 8FAA0034 */  lw         $t2, 0x34($sp)
    /* D004 8000C404 1158000D */  beq        $t2, $t8, .L8000C43C
    /* D008 8000C408 00000000 */   nop
    /* D00C 8000C40C 254B0010 */  addiu      $t3, $t2, 0x10
    /* D010 8000C410 AFAB001C */  sw         $t3, 0x1C($sp)
    /* D014 8000C414 8D4D0014 */  lw         $t5, 0x14($t2)
    /* D018 8000C418 8D4C0010 */  lw         $t4, 0x10($t2)
    /* D01C 8000C41C 8FAE0028 */  lw         $t6, 0x28($sp)
    /* D020 8000C420 8FAF002C */  lw         $t7, 0x2C($sp)
    /* D024 8000C424 018E4023 */  subu       $t0, $t4, $t6
    /* D028 8000C428 01AF082B */  sltu       $at, $t5, $t7
    /* D02C 8000C42C 01014023 */  subu       $t0, $t0, $at
    /* D030 8000C430 01AF4823 */  subu       $t1, $t5, $t7
    /* D034 8000C434 AD490014 */  sw         $t1, 0x14($t2)
    /* D038 8000C438 AD480010 */  sw         $t0, 0x10($t2)
  .L8000C43C:
    /* D03C 8000C43C 8FB90034 */  lw         $t9, 0x34($sp)
    /* D040 8000C440 8FB80038 */  lw         $t8, 0x38($sp)
    /* D044 8000C444 AF190000 */  sw         $t9, 0x0($t8)
    /* D048 8000C448 8FAB0034 */  lw         $t3, 0x34($sp)
    /* D04C 8000C44C 8FAD0038 */  lw         $t5, 0x38($sp)
    /* D050 8000C450 8D6C0004 */  lw         $t4, 0x4($t3)
    /* D054 8000C454 ADAC0004 */  sw         $t4, 0x4($t5)
    /* D058 8000C458 8FAF0034 */  lw         $t7, 0x34($sp)
    /* D05C 8000C45C 8FAE0038 */  lw         $t6, 0x38($sp)
    /* D060 8000C460 8DE80004 */  lw         $t0, 0x4($t7)
    /* D064 8000C464 AD0E0000 */  sw         $t6, 0x0($t0)
    /* D068 8000C468 8FAA0034 */  lw         $t2, 0x34($sp)
    /* D06C 8000C46C 8FA90038 */  lw         $t1, 0x38($sp)
    /* D070 8000C470 AD490004 */  sw         $t1, 0x4($t2)
    /* D074 8000C474 0C003148 */  jal        func_8000C520
    /* D078 8000C478 8FA40024 */   lw        $a0, 0x24($sp)
    /* D07C 8000C47C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* D080 8000C480 8FA20028 */  lw         $v0, 0x28($sp)
    /* D084 8000C484 8FA3002C */  lw         $v1, 0x2C($sp)
    /* D088 8000C488 03E00008 */  jr         $ra
    /* D08C 8000C48C 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_8000C308

nonmatching func_8000C490, 0x18

glabel func_8000C490
    /* D090 8000C490 14800003 */  bnez       $a0, .L8000C4A0
    /* D094 8000C494 00000000 */   nop
    /* D098 8000C498 3C048003 */  lui        $a0, %hi(D_8002C3E0)
    /* D09C 8000C49C 8C84C3E0 */  lw         $a0, %lo(D_8002C3E0)($a0)
  .L8000C4A0:
    /* D0A0 8000C4A0 03E00008 */  jr         $ra
    /* D0A4 8000C4A4 8C820004 */   lw        $v0, 0x4($a0)
endlabel func_8000C490
    /* D0A8 8000C4A8 00000000 */  nop
    /* D0AC 8000C4AC 00000000 */  nop
