.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000C660, 0xC

glabel func_8000C660
    /* D260 8000C660 3C028003 */  lui        $v0, %hi(D_8002C460)
    /* D264 8000C664 03E00008 */  jr         $ra
    /* D268 8000C668 8C42C460 */   lw        $v0, %lo(D_8002C460)($v0)
endlabel func_8000C660
    /* D26C 8000C66C 00000000 */  nop
