.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000C670, 0x2F8

glabel func_8000C670
    /* D270 8000C670 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* D274 8000C674 AFB00018 */  sw         $s0, 0x18($sp)
    /* D278 8000C678 AFBF001C */  sw         $ra, 0x1C($sp)
    /* D27C 8000C67C 3C108003 */  lui        $s0, %hi(D_8002C464)
    /* D280 8000C680 3C0EA440 */  lui        $t6, %hi(VI_CURRENT_REG)
    /* D284 8000C684 8E10C464 */  lw         $s0, %lo(D_8002C464)($s0)
    /* D288 8000C688 8DCF0010 */  lw         $t7, %lo(VI_CURRENT_REG)($t6)
    /* D28C 8000C68C 8E050008 */  lw         $a1, 0x8($s0)
    /* D290 8000C690 31F80001 */  andi       $t8, $t7, 0x1
    /* D294 8000C694 AFB8002C */  sw         $t8, 0x2C($sp)
    /* D298 8000C698 8E040004 */  lw         $a0, 0x4($s0)
    /* D29C 8000C69C 0C003570 */  jal        func_8000D5C0
    /* D2A0 8000C6A0 AFA50044 */   sw        $a1, 0x44($sp)
    /* D2A4 8000C6A4 8FB9002C */  lw         $t9, 0x2C($sp)
    /* D2A8 8000C6A8 8FA50044 */  lw         $a1, 0x44($sp)
    /* D2AC 8000C6AC 960A0000 */  lhu        $t2, 0x0($s0)
    /* D2B0 8000C6B0 00194080 */  sll        $t0, $t9, 2
    /* D2B4 8000C6B4 01194021 */  addu       $t0, $t0, $t9
    /* D2B8 8000C6B8 00084080 */  sll        $t0, $t0, 2
    /* D2BC 8000C6BC 00A83021 */  addu       $a2, $a1, $t0
    /* D2C0 8000C6C0 8CC90028 */  lw         $t1, 0x28($a2)
    /* D2C4 8000C6C4 314B0002 */  andi       $t3, $t2, 0x2
    /* D2C8 8000C6C8 11600008 */  beqz       $t3, .L8000C6EC
    /* D2CC 8000C6CC 01222021 */   addu      $a0, $t1, $v0
    /* D2D0 8000C6D0 8CAD0020 */  lw         $t5, 0x20($a1)
    /* D2D4 8000C6D4 8E0C0020 */  lw         $t4, 0x20($s0)
    /* D2D8 8000C6D8 2401F000 */  addiu      $at, $zero, -0x1000
    /* D2DC 8000C6DC 01A17024 */  and        $t6, $t5, $at
    /* D2E0 8000C6E0 018E7825 */  or         $t7, $t4, $t6
    /* D2E4 8000C6E4 10000003 */  b          .L8000C6F4
    /* D2E8 8000C6E8 AE0F0020 */   sw        $t7, 0x20($s0)
  .L8000C6EC:
    /* D2EC 8000C6EC 8CB80020 */  lw         $t8, 0x20($a1)
    /* D2F0 8000C6F0 AE180020 */  sw         $t8, 0x20($s0)
  .L8000C6F4:
    /* D2F4 8000C6F4 96190000 */  lhu        $t9, 0x0($s0)
    /* D2F8 8000C6F8 33280004 */  andi       $t0, $t9, 0x4
    /* D2FC 8000C6FC 51000035 */  beql       $t0, $zero, .L8000C7D4
    /* D300 8000C700 8CCE002C */   lw        $t6, 0x2C($a2)
    /* D304 8000C704 8CC3002C */  lw         $v1, 0x2C($a2)
    /* D308 8000C708 C6040024 */  lwc1       $ft0, 0x24($s0)
    /* D30C 8000C70C 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* D310 8000C710 30690FFF */  andi       $t1, $v1, 0xFFF
    /* D314 8000C714 44893000 */  mtc1       $t1, $ft1
    /* D318 8000C718 05210004 */  bgez       $t1, .L8000C72C
    /* D31C 8000C71C 46803220 */   cvt.s.w   $ft2, $ft1
    /* D320 8000C720 44815000 */  mtc1       $at, $ft3
    /* D324 8000C724 00000000 */  nop
    /* D328 8000C728 460A4200 */  add.s      $ft2, $ft2, $ft3
  .L8000C72C:
    /* D32C 8000C72C 46082402 */  mul.s      $ft4, $ft0, $ft2
    /* D330 8000C730 24020001 */  addiu      $v0, $zero, 0x1
    /* D334 8000C734 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* D338 8000C738 444AF800 */  cfc1       $t2, $31
    /* D33C 8000C73C 44C2F800 */  ctc1       $v0, $31
    /* D340 8000C740 00000000 */  nop
    /* D344 8000C744 460084A4 */  cvt.w.s    $ft5, $ft4
    /* D348 8000C748 4442F800 */  cfc1       $v0, $31
    /* D34C 8000C74C 00000000 */  nop
    /* D350 8000C750 30420078 */  andi       $v0, $v0, 0x78
    /* D354 8000C754 50400013 */  beql       $v0, $zero, .L8000C7A4
    /* D358 8000C758 44029000 */   mfc1      $v0, $ft5
    /* D35C 8000C75C 44819000 */  mtc1       $at, $ft5
    /* D360 8000C760 24020001 */  addiu      $v0, $zero, 0x1
    /* D364 8000C764 46128481 */  sub.s      $ft5, $ft4, $ft5
    /* D368 8000C768 44C2F800 */  ctc1       $v0, $31
    /* D36C 8000C76C 00000000 */  nop
    /* D370 8000C770 460094A4 */  cvt.w.s    $ft5, $ft5
    /* D374 8000C774 4442F800 */  cfc1       $v0, $31
    /* D378 8000C778 00000000 */  nop
    /* D37C 8000C77C 30420078 */  andi       $v0, $v0, 0x78
    /* D380 8000C780 14400005 */  bnez       $v0, .L8000C798
    /* D384 8000C784 00000000 */   nop
    /* D388 8000C788 44029000 */  mfc1       $v0, $ft5
    /* D38C 8000C78C 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* D390 8000C790 10000007 */  b          .L8000C7B0
    /* D394 8000C794 00411025 */   or        $v0, $v0, $at
  .L8000C798:
    /* D398 8000C798 10000005 */  b          .L8000C7B0
    /* D39C 8000C79C 2402FFFF */   addiu     $v0, $zero, -0x1
    /* D3A0 8000C7A0 44029000 */  mfc1       $v0, $ft5
  .L8000C7A4:
    /* D3A4 8000C7A4 00000000 */  nop
    /* D3A8 8000C7A8 0440FFFB */  bltz       $v0, .L8000C798
    /* D3AC 8000C7AC 00000000 */   nop
  .L8000C7B0:
    /* D3B0 8000C7B0 AE02002C */  sw         $v0, 0x2C($s0)
    /* D3B4 8000C7B4 8CCB002C */  lw         $t3, 0x2C($a2)
    /* D3B8 8000C7B8 2401F000 */  addiu      $at, $zero, -0x1000
    /* D3BC 8000C7BC 44CAF800 */  ctc1       $t2, $31
    /* D3C0 8000C7C0 01616824 */  and        $t5, $t3, $at
    /* D3C4 8000C7C4 004D6025 */  or         $t4, $v0, $t5
    /* D3C8 8000C7C8 10000003 */  b          .L8000C7D8
    /* D3CC 8000C7CC AE0C002C */   sw        $t4, 0x2C($s0)
    /* D3D0 8000C7D0 8CCE002C */  lw         $t6, 0x2C($a2)
  .L8000C7D4:
    /* D3D4 8000C7D4 AE0E002C */  sw         $t6, 0x2C($s0)
  .L8000C7D8:
    /* D3D8 8000C7D8 3C028003 */  lui        $v0, %hi(D_8002C34C)
    /* D3DC 8000C7DC 8C42C34C */  lw         $v0, %lo(D_8002C34C)($v0)
    /* D3E0 8000C7E0 8CCF0030 */  lw         $t7, 0x30($a2)
    /* D3E4 8000C7E4 0002C400 */  sll        $t8, $v0, 16
    /* D3E8 8000C7E8 01F8C823 */  subu       $t9, $t7, $t8
    /* D3EC 8000C7EC 03224021 */  addu       $t0, $t9, $v0
    /* D3F0 8000C7F0 AFA80034 */  sw         $t0, 0x34($sp)
    /* D3F4 8000C7F4 96030000 */  lhu        $v1, 0x0($s0)
    /* D3F8 8000C7F8 8CA7001C */  lw         $a3, 0x1C($a1)
    /* D3FC 8000C7FC 30690020 */  andi       $t1, $v1, 0x20
    /* D400 8000C800 11200002 */  beqz       $t1, .L8000C80C
    /* D404 8000C804 306A0040 */   andi      $t2, $v1, 0x40
    /* D408 8000C808 00003825 */  or         $a3, $zero, $zero
  .L8000C80C:
    /* D40C 8000C80C 5140000D */  beql       $t2, $zero, .L8000C844
    /* D410 8000C810 306B0080 */   andi      $t3, $v1, 0x80
    /* D414 8000C814 AE00002C */  sw         $zero, 0x2C($s0)
    /* D418 8000C818 8E040004 */  lw         $a0, 0x4($s0)
    /* D41C 8000C81C AFA70038 */  sw         $a3, 0x38($sp)
    /* D420 8000C820 AFA60024 */  sw         $a2, 0x24($sp)
    /* D424 8000C824 0C003570 */  jal        func_8000D5C0
    /* D428 8000C828 AFA50044 */   sw        $a1, 0x44($sp)
    /* D42C 8000C82C 8FA50044 */  lw         $a1, 0x44($sp)
    /* D430 8000C830 8FA60024 */  lw         $a2, 0x24($sp)
    /* D434 8000C834 8FA70038 */  lw         $a3, 0x38($sp)
    /* D438 8000C838 00402025 */  or         $a0, $v0, $zero
    /* D43C 8000C83C 96030000 */  lhu        $v1, 0x0($s0)
    /* D440 8000C840 306B0080 */  andi       $t3, $v1, 0x80
  .L8000C844:
    /* D444 8000C844 51600010 */  beql       $t3, $zero, .L8000C888
    /* D448 8000C848 3C0FA440 */   lui       $t7, %hi(VI_DRAM_ADDR_REG)
    /* D44C 8000C84C 960D0028 */  lhu        $t5, 0x28($s0)
    /* D450 8000C850 3C0103FF */  lui        $at, (0x3FF0000 >> 16)
    /* D454 8000C854 8E040004 */  lw         $a0, 0x4($s0)
    /* D458 8000C858 000D6400 */  sll        $t4, $t5, 16
    /* D45C 8000C85C 01817024 */  and        $t6, $t4, $at
    /* D460 8000C860 AE0E002C */  sw         $t6, 0x2C($s0)
    /* D464 8000C864 AFA70038 */  sw         $a3, 0x38($sp)
    /* D468 8000C868 AFA60024 */  sw         $a2, 0x24($sp)
    /* D46C 8000C86C 0C003570 */  jal        func_8000D5C0
    /* D470 8000C870 AFA50044 */   sw        $a1, 0x44($sp)
    /* D474 8000C874 8FA50044 */  lw         $a1, 0x44($sp)
    /* D478 8000C878 8FA60024 */  lw         $a2, 0x24($sp)
    /* D47C 8000C87C 8FA70038 */  lw         $a3, 0x38($sp)
    /* D480 8000C880 00402025 */  or         $a0, $v0, $zero
    /* D484 8000C884 3C0FA440 */  lui        $t7, %hi(VI_DRAM_ADDR_REG)
  .L8000C888:
    /* D488 8000C888 ADE40004 */  sw         $a0, %lo(VI_DRAM_ADDR_REG)($t7)
    /* D48C 8000C88C 8CB80008 */  lw         $t8, 0x8($a1)
    /* D490 8000C890 3C19A440 */  lui        $t9, %hi(VI_WIDTH_REG)
    /* D494 8000C894 3C09A440 */  lui        $t1, %hi(VI_BURST_REG)
    /* D498 8000C898 AF380008 */  sw         $t8, %lo(VI_WIDTH_REG)($t9)
    /* D49C 8000C89C 8CA8000C */  lw         $t0, 0xC($a1)
    /* D4A0 8000C8A0 3C0BA440 */  lui        $t3, %hi(VI_V_SYNC_REG)
    /* D4A4 8000C8A4 3C0CA440 */  lui        $t4, %hi(VI_H_SYNC_REG)
    /* D4A8 8000C8A8 AD280014 */  sw         $t0, %lo(VI_BURST_REG)($t1)
    /* D4AC 8000C8AC 8CAA0010 */  lw         $t2, 0x10($a1)
    /* D4B0 8000C8B0 3C18A440 */  lui        $t8, %hi(VI_H_START_REG)
    /* D4B4 8000C8B4 3C08A440 */  lui        $t0, %hi(VI_V_START_REG)
    /* D4B8 8000C8B8 AD6A0018 */  sw         $t2, %lo(VI_V_SYNC_REG)($t3)
    /* D4BC 8000C8BC 8CAD0014 */  lw         $t5, 0x14($a1)
    /* D4C0 8000C8C0 3C0AA440 */  lui        $t2, %hi(VI_V_BURST_REG)
    /* D4C4 8000C8C4 3C028003 */  lui        $v0, %hi(D_8002C460)
    /* D4C8 8000C8C8 AD8D001C */  sw         $t5, %lo(VI_H_SYNC_REG)($t4)
    /* D4CC 8000C8CC 8CAE0018 */  lw         $t6, 0x18($a1)
    /* D4D0 8000C8D0 3C0DA440 */  lui        $t5, %hi(VI_INTR_REG)
    /* D4D4 8000C8D4 2442C460 */  addiu      $v0, $v0, %lo(D_8002C460)
    /* D4D8 8000C8D8 ADEE0020 */  sw         $t6, %lo(VI_LEAP_REG)($t7)
    /* D4DC 8000C8DC AF070024 */  sw         $a3, %lo(VI_H_START_REG)($t8)
    /* D4E0 8000C8E0 8FB90034 */  lw         $t9, 0x34($sp)
    /* D4E4 8000C8E4 3C0EA440 */  lui        $t6, %hi(VI_X_SCALE_REG)
    /* D4E8 8000C8E8 3C038003 */  lui        $v1, %hi(D_8002C464)
    /* D4EC 8000C8EC AD190028 */  sw         $t9, %lo(VI_V_START_REG)($t0)
    /* D4F0 8000C8F0 8CC90034 */  lw         $t1, 0x34($a2)
    /* D4F4 8000C8F4 2463C464 */  addiu      $v1, $v1, %lo(D_8002C464)
    /* D4F8 8000C8F8 AD49002C */  sw         $t1, %lo(VI_V_BURST_REG)($t2)
    /* D4FC 8000C8FC 8CCB0038 */  lw         $t3, 0x38($a2)
    /* D500 8000C900 ADAB000C */  sw         $t3, %lo(VI_INTR_REG)($t5)
    /* D504 8000C904 8E0C0020 */  lw         $t4, 0x20($s0)
    /* D508 8000C908 02005825 */  or         $t3, $s0, $zero
    /* D50C 8000C90C ADCC0030 */  sw         $t4, %lo(VI_X_SCALE_REG)($t6)
    /* D510 8000C910 8E0F002C */  lw         $t7, 0x2C($s0)
    /* D514 8000C914 260C0030 */  addiu      $t4, $s0, 0x30
    /* D518 8000C918 AF0F0034 */  sw         $t7, %lo(VI_Y_SCALE_REG)($t8)
    /* D51C 8000C91C 8E19000C */  lw         $t9, 0xC($s0)
    /* D520 8000C920 AD190000 */  sw         $t9, %lo(VI_STATUS_REG)($t0)
    /* D524 8000C924 8C4A0000 */  lw         $t2, 0x0($v0)
    /* D528 8000C928 AC500000 */  sw         $s0, 0x0($v0)
    /* D52C 8000C92C AC6A0000 */  sw         $t2, 0x0($v1)
  .L8000C930:
    /* D530 8000C930 8D610000 */  lw         $at, 0x0($t3)
    /* D534 8000C934 256B000C */  addiu      $t3, $t3, 0xC
    /* D538 8000C938 254A000C */  addiu      $t2, $t2, 0xC
    /* D53C 8000C93C AD41FFF4 */  sw         $at, -0xC($t2)
    /* D540 8000C940 8D61FFF8 */  lw         $at, -0x8($t3)
    /* D544 8000C944 AD41FFF8 */  sw         $at, -0x8($t2)
    /* D548 8000C948 8D61FFFC */  lw         $at, -0x4($t3)
    /* D54C 8000C94C 156CFFF8 */  bne        $t3, $t4, .L8000C930
    /* D550 8000C950 AD41FFFC */   sw        $at, -0x4($t2)
    /* D554 8000C954 8FBF001C */  lw         $ra, 0x1C($sp)
    /* D558 8000C958 8FB00018 */  lw         $s0, 0x18($sp)
    /* D55C 8000C95C 27BD0048 */  addiu      $sp, $sp, 0x48
    /* D560 8000C960 03E00008 */  jr         $ra
    /* D564 8000C964 00000000 */   nop
endlabel func_8000C670
    /* D568 8000C968 00000000 */  nop
    /* D56C 8000C96C 00000000 */  nop
