.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching func_8000C970, 0xC

glabel func_8000C970
    /* D570 8000C970 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* D574 8000C974 03E00008 */  jr         $ra
    /* D578 8000C978 00000000 */   nop
endlabel func_8000C970
    /* D57C 8000C97C 00000000 */  nop
