.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000D5C0, 0x7C

glabel func_8000D5C0
    /* E1C0 8000D5C0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E1C4 8000D5C4 AFA40018 */  sw         $a0, 0x18($sp)
    /* E1C8 8000D5C8 8FAE0018 */  lw         $t6, 0x18($sp)
    /* E1CC 8000D5CC 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* E1D0 8000D5D0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E1D4 8000D5D4 01C1082B */  sltu       $at, $t6, $at
    /* E1D8 8000D5D8 14200007 */  bnez       $at, .L8000D5F8
    /* E1DC 8000D5DC 3C01A000 */   lui       $at, (0xA0000000 >> 16)
    /* E1E0 8000D5E0 01C1082B */  sltu       $at, $t6, $at
    /* E1E4 8000D5E4 10200004 */  beqz       $at, .L8000D5F8
    /* E1E8 8000D5E8 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
    /* E1EC 8000D5EC 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* E1F0 8000D5F0 1000000E */  b          .L8000D62C
    /* E1F4 8000D5F4 01C11024 */   and       $v0, $t6, $at
  .L8000D5F8:
    /* E1F8 8000D5F8 8FAF0018 */  lw         $t7, 0x18($sp)
    /* E1FC 8000D5FC 3C01A000 */  lui        $at, (0xA0000000 >> 16)
    /* E200 8000D600 01E1082B */  sltu       $at, $t7, $at
    /* E204 8000D604 14200007 */  bnez       $at, .L8000D624
    /* E208 8000D608 3C01C000 */   lui       $at, (0xC0000000 >> 16)
    /* E20C 8000D60C 01E1082B */  sltu       $at, $t7, $at
    /* E210 8000D610 10200004 */  beqz       $at, .L8000D624
    /* E214 8000D614 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
    /* E218 8000D618 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* E21C 8000D61C 10000003 */  b          .L8000D62C
    /* E220 8000D620 01E11024 */   and       $v0, $t7, $at
  .L8000D624:
    /* E224 8000D624 0C003F2C */  jal        func_8000FCB0
    /* E228 8000D628 8FA40018 */   lw        $a0, 0x18($sp)
  .L8000D62C:
    /* E22C 8000D62C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E230 8000D630 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E234 8000D634 03E00008 */  jr         $ra
    /* E238 8000D638 00000000 */   nop
endlabel func_8000D5C0
    /* E23C 8000D63C 00000000 */  nop
