.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching __osSetSR, 0x10

glabel __osSetSR
    /* E370 8000D770 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* E374 8000D774 00000000 */  nop
    /* E378 8000D778 03E00008 */  jr         $ra
    /* E37C 8000D77C 00000000 */   nop
endlabel __osSetSR

/* Handwritten function */
nonmatching __osGetSR, 0xC

glabel __osGetSR
    /* E380 8000D780 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* E384 8000D784 03E00008 */  jr         $ra
    /* E388 8000D788 00000000 */   nop
endlabel __osGetSR
    /* E38C 8000D78C 00000000 */  nop
