.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000D7F0, 0x48

glabel func_8000D7F0
    /* E3F0 8000D7F0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E3F4 8000D7F4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E3F8 8000D7F8 AFA40018 */  sw         $a0, 0x18($sp)
    /* E3FC 8000D7FC 0C003F5C */  jal        func_8000FD70
    /* E400 8000D800 AFA5001C */   sw        $a1, 0x1C($sp)
    /* E404 8000D804 10400003 */  beqz       $v0, .L8000D814
    /* E408 8000D808 8FAE001C */   lw        $t6, 0x1C($sp)
    /* E40C 8000D80C 10000006 */  b          .L8000D828
    /* E410 8000D810 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8000D814:
    /* E414 8000D814 8FAF0018 */  lw         $t7, 0x18($sp)
    /* E418 8000D818 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* E41C 8000D81C 00001025 */  or         $v0, $zero, $zero
    /* E420 8000D820 01E1C025 */  or         $t8, $t7, $at
    /* E424 8000D824 AF0E0000 */  sw         $t6, %lo(D_A0000000)($t8)
  .L8000D828:
    /* E428 8000D828 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E42C 8000D82C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E430 8000D830 03E00008 */  jr         $ra
    /* E434 8000D834 00000000 */   nop
endlabel func_8000D7F0
    /* E438 8000D838 00000000 */  nop
    /* E43C 8000D83C 00000000 */  nop
