.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching func_8000D890, 0x58

glabel func_8000D890
    /* E490 8000D890 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* E494 8000D894 2409001F */  addiu      $t1, $zero, 0x1F
    /* E498 8000D898 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* E49C 8000D89C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* E4A0 8000D8A0 240A0017 */  addiu      $t2, $zero, 0x17
    /* E4A4 8000D8A4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* E4A8 8000D8A8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* E4AC 8000D8AC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* E4B0 8000D8B0 00095982 */  srl        $t3, $t1, 6
    /* E4B4 8000D8B4 016A5825 */  or         $t3, $t3, $t2
    /* E4B8 8000D8B8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* E4BC 8000D8BC 24090001 */  addiu      $t1, $zero, 0x1
    /* E4C0 8000D8C0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* E4C4 8000D8C4 00000000 */  nop
    /* E4C8 8000D8C8 42000002 */  tlbwi /* handwritten instruction */
    /* E4CC 8000D8CC 00000000 */  nop
    /* E4D0 8000D8D0 00000000 */  nop
    /* E4D4 8000D8D4 00000000 */  nop
    /* E4D8 8000D8D8 00000000 */  nop
    /* E4DC 8000D8DC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* E4E0 8000D8E0 03E00008 */  jr         $ra
    /* E4E4 8000D8E4 00000000 */   nop
endlabel func_8000D890
    /* E4E8 8000D8E8 00000000 */  nop
    /* E4EC 8000D8EC 00000000 */  nop
