.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000D8F0, 0x2C

glabel func_8000D8F0
    /* E4F0 8000D8F0 AFA40000 */  sw         $a0, 0x0($sp)
    /* E4F4 8000D8F4 AFA50004 */  sw         $a1, 0x4($sp)
    /* E4F8 8000D8F8 AFA60008 */  sw         $a2, 0x8($sp)
    /* E4FC 8000D8FC AFA7000C */  sw         $a3, 0xC($sp)
    /* E500 8000D900 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E504 8000D904 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E508 8000D908 01EE1016 */  dsrlv      $v0, $t6, $t7
    /* E50C 8000D90C 0002183C */  dsll32     $v1, $v0, 0
    /* E510 8000D910 0003183F */  dsra32     $v1, $v1, 0
    /* E514 8000D914 03E00008 */  jr         $ra
    /* E518 8000D918 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D8F0

nonmatching func_8000D91C, 0x3C

glabel func_8000D91C
    /* E51C 8000D91C AFA40000 */  sw         $a0, 0x0($sp)
    /* E520 8000D920 AFA50004 */  sw         $a1, 0x4($sp)
    /* E524 8000D924 AFA60008 */  sw         $a2, 0x8($sp)
    /* E528 8000D928 AFA7000C */  sw         $a3, 0xC($sp)
    /* E52C 8000D92C DFAF0008 */  ld         $t7, 0x8($sp)
    /* E530 8000D930 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E534 8000D934 01CF001F */  ddivu      $zero, $t6, $t7
    /* E538 8000D938 15E00002 */  bnez       $t7, .L8000D944
    /* E53C 8000D93C 00000000 */   nop
    /* E540 8000D940 0007000D */  break      7
  .L8000D944:
    /* E544 8000D944 00001010 */  mfhi       $v0
    /* E548 8000D948 0002183C */  dsll32     $v1, $v0, 0
    /* E54C 8000D94C 0003183F */  dsra32     $v1, $v1, 0
    /* E550 8000D950 03E00008 */  jr         $ra
    /* E554 8000D954 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D91C

nonmatching func_8000D958, 0x3C

glabel func_8000D958
    /* E558 8000D958 AFA40000 */  sw         $a0, 0x0($sp)
    /* E55C 8000D95C AFA50004 */  sw         $a1, 0x4($sp)
    /* E560 8000D960 AFA60008 */  sw         $a2, 0x8($sp)
    /* E564 8000D964 AFA7000C */  sw         $a3, 0xC($sp)
    /* E568 8000D968 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E56C 8000D96C DFAE0000 */  ld         $t6, 0x0($sp)
    /* E570 8000D970 01CF001F */  ddivu      $zero, $t6, $t7
    /* E574 8000D974 15E00002 */  bnez       $t7, .L8000D980
    /* E578 8000D978 00000000 */   nop
    /* E57C 8000D97C 0007000D */  break      7
  .L8000D980:
    /* E580 8000D980 00001012 */  mflo       $v0
    /* E584 8000D984 0002183C */  dsll32     $v1, $v0, 0
    /* E588 8000D988 0003183F */  dsra32     $v1, $v1, 0
    /* E58C 8000D98C 03E00008 */  jr         $ra
    /* E590 8000D990 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D958

nonmatching func_8000D994, 0x2C

glabel func_8000D994
    /* E594 8000D994 AFA40000 */  sw         $a0, 0x0($sp)
    /* E598 8000D998 AFA50004 */  sw         $a1, 0x4($sp)
    /* E59C 8000D99C AFA60008 */  sw         $a2, 0x8($sp)
    /* E5A0 8000D9A0 AFA7000C */  sw         $a3, 0xC($sp)
    /* E5A4 8000D9A4 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E5A8 8000D9A8 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E5AC 8000D9AC 01EE1014 */  dsllv      $v0, $t6, $t7
    /* E5B0 8000D9B0 0002183C */  dsll32     $v1, $v0, 0
    /* E5B4 8000D9B4 0003183F */  dsra32     $v1, $v1, 0
    /* E5B8 8000D9B8 03E00008 */  jr         $ra
    /* E5BC 8000D9BC 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D994

nonmatching func_8000D9C0, 0x3C

glabel func_8000D9C0
    /* E5C0 8000D9C0 AFA40000 */  sw         $a0, 0x0($sp)
    /* E5C4 8000D9C4 AFA50004 */  sw         $a1, 0x4($sp)
    /* E5C8 8000D9C8 AFA60008 */  sw         $a2, 0x8($sp)
    /* E5CC 8000D9CC AFA7000C */  sw         $a3, 0xC($sp)
    /* E5D0 8000D9D0 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E5D4 8000D9D4 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E5D8 8000D9D8 01CF001F */  ddivu      $zero, $t6, $t7
    /* E5DC 8000D9DC 15E00002 */  bnez       $t7, .L8000D9E8
    /* E5E0 8000D9E0 00000000 */   nop
    /* E5E4 8000D9E4 0007000D */  break      7
  .L8000D9E8:
    /* E5E8 8000D9E8 00001010 */  mfhi       $v0
    /* E5EC 8000D9EC 0002183C */  dsll32     $v1, $v0, 0
    /* E5F0 8000D9F0 0003183F */  dsra32     $v1, $v1, 0
    /* E5F4 8000D9F4 03E00008 */  jr         $ra
    /* E5F8 8000D9F8 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D9C0

nonmatching func_8000D9FC, 0x5C

glabel func_8000D9FC
    /* E5FC 8000D9FC AFA40000 */  sw         $a0, 0x0($sp)
    /* E600 8000DA00 AFA50004 */  sw         $a1, 0x4($sp)
    /* E604 8000DA04 AFA60008 */  sw         $a2, 0x8($sp)
    /* E608 8000DA08 AFA7000C */  sw         $a3, 0xC($sp)
    /* E60C 8000DA0C DFAF0008 */  ld         $t7, 0x8($sp)
    /* E610 8000DA10 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E614 8000DA14 01CF001E */  ddiv       $zero, $t6, $t7
    /* E618 8000DA18 00000000 */  nop
    /* E61C 8000DA1C 15E00002 */  bnez       $t7, .L8000DA28
    /* E620 8000DA20 00000000 */   nop
    /* E624 8000DA24 0007000D */  break      7
  .L8000DA28:
    /* E628 8000DA28 6401FFFF */  daddiu     $at, $zero, -0x1
    /* E62C 8000DA2C 15E10005 */  bne        $t7, $at, .L8000DA44
    /* E630 8000DA30 64010001 */   daddiu    $at, $zero, 0x1
    /* E634 8000DA34 00010FFC */  dsll32     $at, $at, 31
    /* E638 8000DA38 15C10002 */  bne        $t6, $at, .L8000DA44
    /* E63C 8000DA3C 00000000 */   nop
    /* E640 8000DA40 0006000D */  break      6
  .L8000DA44:
    /* E644 8000DA44 00001012 */  mflo       $v0
    /* E648 8000DA48 0002183C */  dsll32     $v1, $v0, 0
    /* E64C 8000DA4C 0003183F */  dsra32     $v1, $v1, 0
    /* E650 8000DA50 03E00008 */  jr         $ra
    /* E654 8000DA54 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000D9FC

nonmatching func_8000DA58, 0x30

glabel func_8000DA58
    /* E658 8000DA58 AFA40000 */  sw         $a0, 0x0($sp)
    /* E65C 8000DA5C AFA50004 */  sw         $a1, 0x4($sp)
    /* E660 8000DA60 AFA60008 */  sw         $a2, 0x8($sp)
    /* E664 8000DA64 AFA7000C */  sw         $a3, 0xC($sp)
    /* E668 8000DA68 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E66C 8000DA6C DFAE0000 */  ld         $t6, 0x0($sp)
    /* E670 8000DA70 01CF001D */  dmultu     $t6, $t7
    /* E674 8000DA74 00001012 */  mflo       $v0
    /* E678 8000DA78 0002183C */  dsll32     $v1, $v0, 0
    /* E67C 8000DA7C 0003183F */  dsra32     $v1, $v1, 0
    /* E680 8000DA80 03E00008 */  jr         $ra
    /* E684 8000DA84 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000DA58

nonmatching func_8000DA88, 0x60

glabel func_8000DA88
    /* E688 8000DA88 87AF0012 */  lh         $t7, 0x12($sp)
    /* E68C 8000DA8C AFA60008 */  sw         $a2, 0x8($sp)
    /* E690 8000DA90 AFA7000C */  sw         $a3, 0xC($sp)
    /* E694 8000DA94 DFAE0008 */  ld         $t6, 0x8($sp)
    /* E698 8000DA98 01E0C025 */  or         $t8, $t7, $zero
    /* E69C 8000DA9C 0300C825 */  or         $t9, $t8, $zero
    /* E6A0 8000DAA0 01D9001F */  ddivu      $zero, $t6, $t9
    /* E6A4 8000DAA4 17200002 */  bnez       $t9, .L8000DAB0
    /* E6A8 8000DAA8 00000000 */   nop
    /* E6AC 8000DAAC 0007000D */  break      7
  .L8000DAB0:
    /* E6B0 8000DAB0 00004012 */  mflo       $t0
    /* E6B4 8000DAB4 FC880000 */  sd         $t0, 0x0($a0)
    /* E6B8 8000DAB8 87AA0012 */  lh         $t2, 0x12($sp)
    /* E6BC 8000DABC DFA90008 */  ld         $t1, 0x8($sp)
    /* E6C0 8000DAC0 01405825 */  or         $t3, $t2, $zero
    /* E6C4 8000DAC4 01606025 */  or         $t4, $t3, $zero
    /* E6C8 8000DAC8 012C001F */  ddivu      $zero, $t1, $t4
    /* E6CC 8000DACC 15800002 */  bnez       $t4, .L8000DAD8
    /* E6D0 8000DAD0 00000000 */   nop
    /* E6D4 8000DAD4 0007000D */  break      7
  .L8000DAD8:
    /* E6D8 8000DAD8 00006810 */  mfhi       $t5
    /* E6DC 8000DADC FCAD0000 */  sd         $t5, 0x0($a1)
    /* E6E0 8000DAE0 03E00008 */  jr         $ra
    /* E6E4 8000DAE4 00000000 */   nop
endlabel func_8000DA88

nonmatching func_8000DAE8, 0x9C

glabel func_8000DAE8
    /* E6E8 8000DAE8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* E6EC 8000DAEC AFA40008 */  sw         $a0, 0x8($sp)
    /* E6F0 8000DAF0 AFA5000C */  sw         $a1, 0xC($sp)
    /* E6F4 8000DAF4 AFA60010 */  sw         $a2, 0x10($sp)
    /* E6F8 8000DAF8 AFA70014 */  sw         $a3, 0x14($sp)
    /* E6FC 8000DAFC DFAF0010 */  ld         $t7, 0x10($sp)
    /* E700 8000DB00 DFAE0008 */  ld         $t6, 0x8($sp)
    /* E704 8000DB04 01CF001E */  ddiv       $zero, $t6, $t7
    /* E708 8000DB08 00000000 */  nop
    /* E70C 8000DB0C 15E00002 */  bnez       $t7, .L8000DB18
    /* E710 8000DB10 00000000 */   nop
    /* E714 8000DB14 0007000D */  break      7
  .L8000DB18:
    /* E718 8000DB18 6401FFFF */  daddiu     $at, $zero, -0x1
    /* E71C 8000DB1C 15E10005 */  bne        $t7, $at, .L8000DB34
    /* E720 8000DB20 64010001 */   daddiu    $at, $zero, 0x1
    /* E724 8000DB24 00010FFC */  dsll32     $at, $at, 31
    /* E728 8000DB28 15C10002 */  bne        $t6, $at, .L8000DB34
    /* E72C 8000DB2C 00000000 */   nop
    /* E730 8000DB30 0006000D */  break      6
  .L8000DB34:
    /* E734 8000DB34 0000C010 */  mfhi       $t8
    /* E738 8000DB38 FFB80000 */  sd         $t8, 0x0($sp)
    /* E73C 8000DB3C 07010003 */  bgez       $t8, .L8000DB4C
    /* E740 8000DB40 00000000 */   nop
    /* E744 8000DB44 1DE00007 */  bgtz       $t7, .L8000DB64
    /* E748 8000DB48 00000000 */   nop
  .L8000DB4C:
    /* E74C 8000DB4C DFB90000 */  ld         $t9, 0x0($sp)
    /* E750 8000DB50 1B200008 */  blez       $t9, .L8000DB74
    /* E754 8000DB54 00000000 */   nop
    /* E758 8000DB58 DFA80010 */  ld         $t0, 0x10($sp)
    /* E75C 8000DB5C 05010005 */  bgez       $t0, .L8000DB74
    /* E760 8000DB60 00000000 */   nop
  .L8000DB64:
    /* E764 8000DB64 DFA90000 */  ld         $t1, 0x0($sp)
    /* E768 8000DB68 DFAA0010 */  ld         $t2, 0x10($sp)
    /* E76C 8000DB6C 012A582D */  daddu      $t3, $t1, $t2
    /* E770 8000DB70 FFAB0000 */  sd         $t3, 0x0($sp)
  .L8000DB74:
    /* E774 8000DB74 8FA20000 */  lw         $v0, 0x0($sp)
    /* E778 8000DB78 8FA30004 */  lw         $v1, 0x4($sp)
    /* E77C 8000DB7C 03E00008 */  jr         $ra
    /* E780 8000DB80 27BD0008 */   addiu     $sp, $sp, 0x8
endlabel func_8000DAE8

nonmatching func_8000DB84, 0x2C

glabel func_8000DB84
    /* E784 8000DB84 AFA40000 */  sw         $a0, 0x0($sp)
    /* E788 8000DB88 AFA50004 */  sw         $a1, 0x4($sp)
    /* E78C 8000DB8C AFA60008 */  sw         $a2, 0x8($sp)
    /* E790 8000DB90 AFA7000C */  sw         $a3, 0xC($sp)
    /* E794 8000DB94 DFAF0008 */  ld         $t7, 0x8($sp)
    /* E798 8000DB98 DFAE0000 */  ld         $t6, 0x0($sp)
    /* E79C 8000DB9C 01EE1017 */  dsrav      $v0, $t6, $t7
    /* E7A0 8000DBA0 0002183C */  dsll32     $v1, $v0, 0
    /* E7A4 8000DBA4 0003183F */  dsra32     $v1, $v1, 0
    /* E7A8 8000DBA8 03E00008 */  jr         $ra
    /* E7AC 8000DBAC 0002103F */   dsra32    $v0, $v0, 0
endlabel func_8000DB84

/* Handwritten function */
nonmatching func_8000DBB0, 0xC

glabel func_8000DBB0
    /* E7B0 8000DBB0 40026800 */  mfc0       $v0, $13 /* handwritten instruction */
    /* E7B4 8000DBB4 03E00008 */  jr         $ra
    /* E7B8 8000DBB8 00000000 */   nop
endlabel func_8000DBB0
    /* E7BC 8000DBBC 00000000 */  nop
