.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000DBC0, 0x50

glabel func_8000DBC0
    /* E7C0 8000DBC0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E7C4 8000DBC4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E7C8 8000DBC8 240E0001 */  addiu      $t6, $zero, 0x1
    /* E7CC 8000DBCC 3C018003 */  lui        $at, %hi(D_8002C4A0)
    /* E7D0 8000DBD0 3C048003 */  lui        $a0, %hi(D_80037C78)
    /* E7D4 8000DBD4 3C058003 */  lui        $a1, %hi(D_80037C70)
    /* E7D8 8000DBD8 AC2EC4A0 */  sw         $t6, %lo(D_8002C4A0)($at)
    /* E7DC 8000DBDC 24A57C70 */  addiu      $a1, $a1, %lo(D_80037C70)
    /* E7E0 8000DBE0 24847C78 */  addiu      $a0, $a0, %lo(D_80037C78)
    /* E7E4 8000DBE4 0C001A80 */  jal        func_80006A00
    /* E7E8 8000DBE8 24060001 */   addiu     $a2, $zero, 0x1
    /* E7EC 8000DBEC 3C048003 */  lui        $a0, %hi(D_80037C78)
    /* E7F0 8000DBF0 24847C78 */  addiu      $a0, $a0, %lo(D_80037C78)
    /* E7F4 8000DBF4 00002825 */  or         $a1, $zero, $zero
    /* E7F8 8000DBF8 0C001D78 */  jal        func_800075E0
    /* E7FC 8000DBFC 00003025 */   or        $a2, $zero, $zero
    /* E800 8000DC00 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E804 8000DC04 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E808 8000DC08 03E00008 */  jr         $ra
    /* E80C 8000DC0C 00000000 */   nop
endlabel func_8000DBC0

nonmatching func_8000DC10, 0x44

glabel func_8000DC10
    /* E810 8000DC10 3C0E8003 */  lui        $t6, %hi(D_8002C4A0)
    /* E814 8000DC14 8DCEC4A0 */  lw         $t6, %lo(D_8002C4A0)($t6)
    /* E818 8000DC18 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* E81C 8000DC1C AFBF0014 */  sw         $ra, 0x14($sp)
    /* E820 8000DC20 15C00003 */  bnez       $t6, .L8000DC30
    /* E824 8000DC24 00000000 */   nop
    /* E828 8000DC28 0C0036F0 */  jal        func_8000DBC0
    /* E82C 8000DC2C 00000000 */   nop
  .L8000DC30:
    /* E830 8000DC30 3C048003 */  lui        $a0, %hi(D_80037C78)
    /* E834 8000DC34 24847C78 */  addiu      $a0, $a0, %lo(D_80037C78)
    /* E838 8000DC38 27A5001C */  addiu      $a1, $sp, 0x1C
    /* E83C 8000DC3C 0C001C9C */  jal        func_80007270
    /* E840 8000DC40 24060001 */   addiu     $a2, $zero, 0x1
    /* E844 8000DC44 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E848 8000DC48 27BD0020 */  addiu      $sp, $sp, 0x20
    /* E84C 8000DC4C 03E00008 */  jr         $ra
    /* E850 8000DC50 00000000 */   nop
endlabel func_8000DC10

nonmatching func_8000DC54, 0x2C

glabel func_8000DC54
    /* E854 8000DC54 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E858 8000DC58 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E85C 8000DC5C 3C048003 */  lui        $a0, %hi(D_80037C78)
    /* E860 8000DC60 24847C78 */  addiu      $a0, $a0, %lo(D_80037C78)
    /* E864 8000DC64 00002825 */  or         $a1, $zero, $zero
    /* E868 8000DC68 0C001D78 */  jal        func_800075E0
    /* E86C 8000DC6C 00003025 */   or        $a2, $zero, $zero
    /* E870 8000DC70 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E874 8000DC74 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E878 8000DC78 03E00008 */  jr         $ra
    /* E87C 8000DC7C 00000000 */   nop
endlabel func_8000DC54

nonmatching func_8000DC80, 0x4C

glabel func_8000DC80
    /* E880 8000DC80 3C03A460 */  lui        $v1, %hi(PI_STATUS_REG)
    /* E884 8000DC84 34630010 */  ori        $v1, $v1, %lo(PI_STATUS_REG)
    /* E888 8000DC88 8C620000 */  lw         $v0, 0x0($v1)
    /* E88C 8000DC8C 3C188000 */  lui        $t8, %hi(osRomBase)
    /* E890 8000DC90 304E0003 */  andi       $t6, $v0, 0x3
    /* E894 8000DC94 11C00005 */  beqz       $t6, .L8000DCAC
    /* E898 8000DC98 00000000 */   nop
    /* E89C 8000DC9C 8C620000 */  lw         $v0, 0x0($v1)
  .L8000DCA0:
    /* E8A0 8000DCA0 304F0003 */  andi       $t7, $v0, 0x3
    /* E8A4 8000DCA4 55E0FFFE */  bnel       $t7, $zero, .L8000DCA0
    /* E8A8 8000DCA8 8C620000 */   lw        $v0, 0x0($v1)
  .L8000DCAC:
    /* E8AC 8000DCAC 8F180308 */  lw         $t8, %lo(osRomBase)($t8)
    /* E8B0 8000DCB0 3C01A000 */  lui        $at, (0xA0000000 >> 16)
    /* E8B4 8000DCB4 00001025 */  or         $v0, $zero, $zero
    /* E8B8 8000DCB8 0304C825 */  or         $t9, $t8, $a0
    /* E8BC 8000DCBC 03214025 */  or         $t0, $t9, $at
    /* E8C0 8000DCC0 8D090000 */  lw         $t1, 0x0($t0)
    /* E8C4 8000DCC4 03E00008 */  jr         $ra
    /* E8C8 8000DCC8 ACA90000 */   sw        $t1, 0x0($a1)
endlabel func_8000DC80
    /* E8CC 8000DCCC 00000000 */  nop
