.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000E3C0, 0x8

glabel func_8000E3C0
    /* EFC0 8000E3C0 03E00008 */  jr         $ra
    /* EFC4 8000E3C4 46006004 */   sqrt.s    $fv0, $fa0
endlabel func_8000E3C0
    /* EFC8 8000E3C8 00000000 */  nop
    /* EFCC 8000E3CC 00000000 */  nop
