.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000E560, 0x50

glabel func_8000E560
    /* F160 8000E560 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F164 8000E564 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F168 8000E568 240E0001 */  addiu      $t6, $zero, 0x1
    /* F16C 8000E56C 3C018003 */  lui        $at, %hi(D_8002C4B0)
    /* F170 8000E570 3C048003 */  lui        $a0, %hi(D_80037C98)
    /* F174 8000E574 3C058003 */  lui        $a1, %hi(D_80037C90)
    /* F178 8000E578 AC2EC4B0 */  sw         $t6, %lo(D_8002C4B0)($at)
    /* F17C 8000E57C 24A57C90 */  addiu      $a1, $a1, %lo(D_80037C90)
    /* F180 8000E580 24847C98 */  addiu      $a0, $a0, %lo(D_80037C98)
    /* F184 8000E584 0C001A80 */  jal        func_80006A00
    /* F188 8000E588 24060001 */   addiu     $a2, $zero, 0x1
    /* F18C 8000E58C 3C048003 */  lui        $a0, %hi(D_80037C98)
    /* F190 8000E590 24847C98 */  addiu      $a0, $a0, %lo(D_80037C98)
    /* F194 8000E594 00002825 */  or         $a1, $zero, $zero
    /* F198 8000E598 0C001D78 */  jal        func_800075E0
    /* F19C 8000E59C 00003025 */   or        $a2, $zero, $zero
    /* F1A0 8000E5A0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F1A4 8000E5A4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F1A8 8000E5A8 03E00008 */  jr         $ra
    /* F1AC 8000E5AC 00000000 */   nop
endlabel func_8000E560

nonmatching func_8000E5B0, 0x44

glabel func_8000E5B0
    /* F1B0 8000E5B0 3C0E8003 */  lui        $t6, %hi(D_8002C4B0)
    /* F1B4 8000E5B4 8DCEC4B0 */  lw         $t6, %lo(D_8002C4B0)($t6)
    /* F1B8 8000E5B8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* F1BC 8000E5BC AFBF0014 */  sw         $ra, 0x14($sp)
    /* F1C0 8000E5C0 15C00003 */  bnez       $t6, .L8000E5D0
    /* F1C4 8000E5C4 00000000 */   nop
    /* F1C8 8000E5C8 0C003958 */  jal        func_8000E560
    /* F1CC 8000E5CC 00000000 */   nop
  .L8000E5D0:
    /* F1D0 8000E5D0 3C048003 */  lui        $a0, %hi(D_80037C98)
    /* F1D4 8000E5D4 24847C98 */  addiu      $a0, $a0, %lo(D_80037C98)
    /* F1D8 8000E5D8 27A5001C */  addiu      $a1, $sp, 0x1C
    /* F1DC 8000E5DC 0C001C9C */  jal        func_80007270
    /* F1E0 8000E5E0 24060001 */   addiu     $a2, $zero, 0x1
    /* F1E4 8000E5E4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F1E8 8000E5E8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* F1EC 8000E5EC 03E00008 */  jr         $ra
    /* F1F0 8000E5F0 00000000 */   nop
endlabel func_8000E5B0

nonmatching func_8000E5F4, 0x2C

glabel func_8000E5F4
    /* F1F4 8000E5F4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F1F8 8000E5F8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F1FC 8000E5FC 3C048003 */  lui        $a0, %hi(D_80037C98)
    /* F200 8000E600 24847C98 */  addiu      $a0, $a0, %lo(D_80037C98)
    /* F204 8000E604 00002825 */  or         $a1, $zero, $zero
    /* F208 8000E608 0C001D78 */  jal        func_800075E0
    /* F20C 8000E60C 00003025 */   or        $a2, $zero, $zero
    /* F210 8000E610 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F214 8000E614 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F218 8000E618 03E00008 */  jr         $ra
    /* F21C 8000E61C 00000000 */   nop
endlabel func_8000E5F4

nonmatching func_8000E620, 0xD0

glabel func_8000E620
    /* F220 8000E620 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* F224 8000E624 AFA40030 */  sw         $a0, 0x30($sp)
    /* F228 8000E628 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F22C 8000E62C AFA50034 */  sw         $a1, 0x34($sp)
    /* F230 8000E630 240E00FA */  addiu      $t6, $zero, 0xFA
    /* F234 8000E634 3C018003 */  lui        $at, %hi(D_8002C4D4)
    /* F238 8000E638 00A02025 */  or         $a0, $a1, $zero
    /* F23C 8000E63C A02EC4D4 */  sb         $t6, %lo(D_8002C4D4)($at)
    /* F240 8000E640 0C0039BC */  jal        func_8000E6F0
    /* F244 8000E644 00002825 */   or        $a1, $zero, $zero
    /* F248 8000E648 3C058003 */  lui        $a1, %hi(D_80037F60)
    /* F24C 8000E64C 24A57F60 */  addiu      $a1, $a1, %lo(D_80037F60)
    /* F250 8000E650 0C00392C */  jal        func_8000E4B0
    /* F254 8000E654 24040001 */   addiu     $a0, $zero, 0x1
    /* F258 8000E658 8FA40030 */  lw         $a0, 0x30($sp)
    /* F25C 8000E65C 27A50028 */  addiu      $a1, $sp, 0x28
    /* F260 8000E660 0C001C9C */  jal        func_80007270
    /* F264 8000E664 24060001 */   addiu     $a2, $zero, 0x1
    /* F268 8000E668 3C058003 */  lui        $a1, %hi(D_80037F60)
    /* F26C 8000E66C 24A57F60 */  addiu      $a1, $a1, %lo(D_80037F60)
    /* F270 8000E670 0C00392C */  jal        func_8000E4B0
    /* F274 8000E674 00002025 */   or        $a0, $zero, $zero
    /* F278 8000E678 AFA2002C */  sw         $v0, 0x2C($sp)
    /* F27C 8000E67C 8FA40030 */  lw         $a0, 0x30($sp)
    /* F280 8000E680 27A50028 */  addiu      $a1, $sp, 0x28
    /* F284 8000E684 0C001C9C */  jal        func_80007270
    /* F288 8000E688 24060001 */   addiu     $a2, $zero, 0x1
    /* F28C 8000E68C 8FA40034 */  lw         $a0, 0x34($sp)
    /* F290 8000E690 0C0039ED */  jal        func_8000E7B4
    /* F294 8000E694 27A50024 */   addiu     $a1, $sp, 0x24
    /* F298 8000E698 93A20026 */  lbu        $v0, 0x26($sp)
    /* F29C 8000E69C 93B80027 */  lbu        $t8, 0x27($sp)
    /* F2A0 8000E6A0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F2A4 8000E6A4 30430001 */  andi       $v1, $v0, 0x1
    /* F2A8 8000E6A8 10600005 */  beqz       $v1, .L8000E6C0
    /* F2AC 8000E6AC 304F0002 */   andi      $t7, $v0, 0x2
    /* F2B0 8000E6B0 11E00003 */  beqz       $t7, .L8000E6C0
    /* F2B4 8000E6B4 00000000 */   nop
    /* F2B8 8000E6B8 1000000B */  b          .L8000E6E8
    /* F2BC 8000E6BC 24020002 */   addiu     $v0, $zero, 0x2
  .L8000E6C0:
    /* F2C0 8000E6C0 17000003 */  bnez       $t8, .L8000E6D0
    /* F2C4 8000E6C4 00000000 */   nop
    /* F2C8 8000E6C8 14600003 */  bnez       $v1, .L8000E6D8
    /* F2CC 8000E6CC 30590004 */   andi      $t9, $v0, 0x4
  .L8000E6D0:
    /* F2D0 8000E6D0 10000005 */  b          .L8000E6E8
    /* F2D4 8000E6D4 24020001 */   addiu     $v0, $zero, 0x1
  .L8000E6D8:
    /* F2D8 8000E6D8 13200003 */  beqz       $t9, .L8000E6E8
    /* F2DC 8000E6DC 8FA2002C */   lw        $v0, 0x2C($sp)
    /* F2E0 8000E6E0 10000001 */  b          .L8000E6E8
    /* F2E4 8000E6E4 24020004 */   addiu     $v0, $zero, 0x4
  .L8000E6E8:
    /* F2E8 8000E6E8 03E00008 */  jr         $ra
    /* F2EC 8000E6EC 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_8000E620

nonmatching func_8000E6F0, 0xC4

glabel func_8000E6F0
    /* F2F0 8000E6F0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F2F4 8000E6F4 3C068003 */  lui        $a2, %hi(D_80037F60)
    /* F2F8 8000E6F8 240700FE */  addiu      $a3, $zero, 0xFE
    /* F2FC 8000E6FC 3C018003 */  lui        $at, %hi(D_80037AE0)
    /* F300 8000E700 24C27F60 */  addiu      $v0, $a2, %lo(D_80037F60)
    /* F304 8000E704 AFA5001C */  sw         $a1, 0x1C($sp)
    /* F308 8000E708 A0277AE0 */  sb         $a3, %lo(D_80037AE0)($at)
    /* F30C 8000E70C 240F0001 */  addiu      $t7, $zero, 0x1
    /* F310 8000E710 AC4F003C */  sw         $t7, 0x3C($v0)
    /* F314 8000E714 24180001 */  addiu      $t8, $zero, 0x1
    /* F318 8000E718 24190003 */  addiu      $t9, $zero, 0x3
    /* F31C 8000E71C 240800FF */  addiu      $t0, $zero, 0xFF
    /* F320 8000E720 240900FF */  addiu      $t1, $zero, 0xFF
    /* F324 8000E724 240A00FF */  addiu      $t2, $zero, 0xFF
    /* F328 8000E728 A3B8000C */  sb         $t8, 0xC($sp)
    /* F32C 8000E72C A3B9000D */  sb         $t9, 0xD($sp)
    /* F330 8000E730 A3A5000E */  sb         $a1, 0xE($sp)
    /* F334 8000E734 A3A8000F */  sb         $t0, 0xF($sp)
    /* F338 8000E738 A3A90010 */  sb         $t1, 0x10($sp)
    /* F33C 8000E73C A3AA0011 */  sb         $t2, 0x11($sp)
    /* F340 8000E740 18800010 */  blez       $a0, .L8000E784
    /* F344 8000E744 00001825 */   or        $v1, $zero, $zero
    /* F348 8000E748 30860003 */  andi       $a2, $a0, 0x3
    /* F34C 8000E74C 10C00006 */  beqz       $a2, .L8000E768
    /* F350 8000E750 00C02825 */   or        $a1, $a2, $zero
  .L8000E754:
    /* F354 8000E754 24630001 */  addiu      $v1, $v1, 0x1
    /* F358 8000E758 A0400000 */  sb         $zero, 0x0($v0)
    /* F35C 8000E75C 14A3FFFD */  bne        $a1, $v1, .L8000E754
    /* F360 8000E760 24420001 */   addiu     $v0, $v0, 0x1
    /* F364 8000E764 10640007 */  beq        $v1, $a0, .L8000E784
  .L8000E768:
    /* F368 8000E768 24630004 */   addiu     $v1, $v1, 0x4
    /* F36C 8000E76C A0400001 */  sb         $zero, 0x1($v0)
    /* F370 8000E770 A0400002 */  sb         $zero, 0x2($v0)
    /* F374 8000E774 A0400003 */  sb         $zero, 0x3($v0)
    /* F378 8000E778 24420004 */  addiu      $v0, $v0, 0x4
    /* F37C 8000E77C 1464FFFA */  bne        $v1, $a0, .L8000E768
    /* F380 8000E780 A040FFFC */   sb        $zero, -0x4($v0)
  .L8000E784:
    /* F384 8000E784 27AB000C */  addiu      $t3, $sp, 0xC
    /* F388 8000E788 8D610000 */  lw         $at, 0x0($t3)
    /* F38C 8000E78C 24420006 */  addiu      $v0, $v0, 0x6
    /* F390 8000E790 A841FFFA */  swl        $at, -0x6($v0)
    /* F394 8000E794 B841FFFD */  swr        $at, -0x3($v0)
    /* F398 8000E798 91610004 */  lbu        $at, 0x4($t3)
    /* F39C 8000E79C A041FFFE */  sb         $at, -0x2($v0)
    /* F3A0 8000E7A0 916D0005 */  lbu        $t5, 0x5($t3)
    /* F3A4 8000E7A4 A0470000 */  sb         $a3, 0x0($v0)
    /* F3A8 8000E7A8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F3AC 8000E7AC 03E00008 */  jr         $ra
    /* F3B0 8000E7B0 A04DFFFF */   sb        $t5, -0x1($v0)
endlabel func_8000E6F0

nonmatching func_8000E7B4, 0x98

glabel func_8000E7B4
    /* F3B4 8000E7B4 3C028003 */  lui        $v0, %hi(D_80037F60)
    /* F3B8 8000E7B8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F3BC 8000E7BC 24427F60 */  addiu      $v0, $v0, %lo(D_80037F60)
    /* F3C0 8000E7C0 1880000B */  blez       $a0, .L8000E7F0
    /* F3C4 8000E7C4 00001825 */   or        $v1, $zero, $zero
    /* F3C8 8000E7C8 30870003 */  andi       $a3, $a0, 0x3
    /* F3CC 8000E7CC 10E00005 */  beqz       $a3, .L8000E7E4
    /* F3D0 8000E7D0 00E03025 */   or        $a2, $a3, $zero
  .L8000E7D4:
    /* F3D4 8000E7D4 24630001 */  addiu      $v1, $v1, 0x1
    /* F3D8 8000E7D8 14C3FFFE */  bne        $a2, $v1, .L8000E7D4
    /* F3DC 8000E7DC 24420001 */   addiu     $v0, $v0, 0x1
    /* F3E0 8000E7E0 10640003 */  beq        $v1, $a0, .L8000E7F0
  .L8000E7E4:
    /* F3E4 8000E7E4 24630004 */   addiu     $v1, $v1, 0x4
    /* F3E8 8000E7E8 1464FFFE */  bne        $v1, $a0, .L8000E7E4
    /* F3EC 8000E7EC 24420004 */   addiu     $v0, $v0, 0x4
  .L8000E7F0:
    /* F3F0 8000E7F0 88410000 */  lwl        $at, 0x0($v0)
    /* F3F4 8000E7F4 98410003 */  lwr        $at, 0x3($v0)
    /* F3F8 8000E7F8 27AE000C */  addiu      $t6, $sp, 0xC
    /* F3FC 8000E7FC ADC10000 */  sw         $at, 0x0($t6)
    /* F400 8000E800 90410004 */  lbu        $at, 0x4($v0)
    /* F404 8000E804 A1C10004 */  sb         $at, 0x4($t6)
    /* F408 8000E808 90580005 */  lbu        $t8, 0x5($v0)
    /* F40C 8000E80C A1D80005 */  sb         $t8, 0x5($t6)
    /* F410 8000E810 93B9000D */  lbu        $t9, 0xD($sp)
    /* F414 8000E814 332800C0 */  andi       $t0, $t9, 0xC0
    /* F418 8000E818 00084903 */  sra        $t1, $t0, 4
    /* F41C 8000E81C 312A00FF */  andi       $t2, $t1, 0xFF
    /* F420 8000E820 15400008 */  bnez       $t2, .L8000E844
    /* F424 8000E824 A0A90003 */   sb        $t1, 0x3($a1)
    /* F428 8000E828 93AB0010 */  lbu        $t3, 0x10($sp)
    /* F42C 8000E82C 93AD000F */  lbu        $t5, 0xF($sp)
    /* F430 8000E830 000B6200 */  sll        $t4, $t3, 8
    /* F434 8000E834 018D7825 */  or         $t7, $t4, $t5
    /* F438 8000E838 A4AF0000 */  sh         $t7, 0x0($a1)
    /* F43C 8000E83C 93AE0011 */  lbu        $t6, 0x11($sp)
    /* F440 8000E840 A0AE0002 */  sb         $t6, 0x2($a1)
  .L8000E844:
    /* F444 8000E844 03E00008 */  jr         $ra
    /* F448 8000E848 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_8000E7B4
    /* F44C 8000E84C 00000000 */  nop
