.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching func_8000EB00, 0x74

glabel func_8000EB00
    /* F700 8000EB00 00001825 */  or         $v1, $zero, $zero
    /* F704 8000EB04 00801025 */  or         $v0, $a0, $zero
    /* F708 8000EB08 18A00016 */  blez       $a1, .L8000EB64
    /* F70C 8000EB0C 00003025 */   or        $a2, $zero, $zero
    /* F710 8000EB10 30A70003 */  andi       $a3, $a1, 0x3
    /* F714 8000EB14 10E00008 */  beqz       $a3, .L8000EB38
    /* F718 8000EB18 00E02025 */   or        $a0, $a3, $zero
  .L8000EB1C:
    /* F71C 8000EB1C 904E0000 */  lbu        $t6, 0x0($v0)
    /* F720 8000EB20 24C60001 */  addiu      $a2, $a2, 0x1
    /* F724 8000EB24 24420001 */  addiu      $v0, $v0, 0x1
    /* F728 8000EB28 1486FFFC */  bne        $a0, $a2, .L8000EB1C
    /* F72C 8000EB2C 006E1821 */   addu      $v1, $v1, $t6
    /* F730 8000EB30 50C5000D */  beql       $a2, $a1, .L8000EB68
    /* F734 8000EB34 00601025 */   or        $v0, $v1, $zero
  .L8000EB38:
    /* F738 8000EB38 904F0000 */  lbu        $t7, 0x0($v0)
    /* F73C 8000EB3C 90580001 */  lbu        $t8, 0x1($v0)
    /* F740 8000EB40 90590002 */  lbu        $t9, 0x2($v0)
    /* F744 8000EB44 006F1821 */  addu       $v1, $v1, $t7
    /* F748 8000EB48 90480003 */  lbu        $t0, 0x3($v0)
    /* F74C 8000EB4C 00781821 */  addu       $v1, $v1, $t8
    /* F750 8000EB50 24C60004 */  addiu      $a2, $a2, 0x4
    /* F754 8000EB54 00791821 */  addu       $v1, $v1, $t9
    /* F758 8000EB58 24420004 */  addiu      $v0, $v0, 0x4
    /* F75C 8000EB5C 14C5FFF6 */  bne        $a2, $a1, .L8000EB38
    /* F760 8000EB60 00681821 */   addu      $v1, $v1, $t0
  .L8000EB64:
    /* F764 8000EB64 00601025 */  or         $v0, $v1, $zero
  .L8000EB68:
    /* F768 8000EB68 3049FFFF */  andi       $t1, $v0, 0xFFFF
    /* F76C 8000EB6C 03E00008 */  jr         $ra
    /* F770 8000EB70 01201025 */   or        $v0, $t1, $zero
endlabel func_8000EB00

nonmatching func_8000EB74, 0xFC

glabel func_8000EB74
    /* F774 8000EB74 A4C00000 */  sh         $zero, 0x0($a2)
    /* F778 8000EB78 A4A00000 */  sh         $zero, 0x0($a1)
    /* F77C 8000EB7C 94820000 */  lhu        $v0, 0x0($a0)
    /* F780 8000EB80 24870004 */  addiu      $a3, $a0, 0x4
    /* F784 8000EB84 24E90002 */  addiu      $t1, $a3, 0x2
    /* F788 8000EB88 0002C021 */  addu       $t8, $zero, $v0
    /* F78C 8000EB8C A4B80000 */  sh         $t8, 0x0($a1)
    /* F790 8000EB90 94D90000 */  lhu        $t9, 0x0($a2)
    /* F794 8000EB94 00406827 */  not        $t5, $v0
    /* F798 8000EB98 24EA0004 */  addiu      $t2, $a3, 0x4
    /* F79C 8000EB9C 032D7021 */  addu       $t6, $t9, $t5
    /* F7A0 8000EBA0 A4CE0000 */  sh         $t6, 0x0($a2)
    /* F7A4 8000EBA4 94AF0000 */  lhu        $t7, 0x0($a1)
    /* F7A8 8000EBA8 94820002 */  lhu        $v0, 0x2($a0)
    /* F7AC 8000EBAC 2404001C */  addiu      $a0, $zero, 0x1C
    /* F7B0 8000EBB0 24EB0006 */  addiu      $t3, $a3, 0x6
    /* F7B4 8000EBB4 01E2C021 */  addu       $t8, $t7, $v0
    /* F7B8 8000EBB8 A4B80000 */  sh         $t8, 0x0($a1)
    /* F7BC 8000EBBC 94D90000 */  lhu        $t9, 0x0($a2)
    /* F7C0 8000EBC0 00406827 */  not        $t5, $v0
    /* F7C4 8000EBC4 24030004 */  addiu      $v1, $zero, 0x4
    /* F7C8 8000EBC8 032D7021 */  addu       $t6, $t9, $t5
    /* F7CC 8000EBCC A4CE0000 */  sh         $t6, 0x0($a2)
  .L8000EBD0:
    /* F7D0 8000EBD0 94E20000 */  lhu        $v0, 0x0($a3)
    /* F7D4 8000EBD4 94AF0000 */  lhu        $t7, 0x0($a1)
    /* F7D8 8000EBD8 24630008 */  addiu      $v1, $v1, 0x8
    /* F7DC 8000EBDC 00406827 */  not        $t5, $v0
    /* F7E0 8000EBE0 01E2C021 */  addu       $t8, $t7, $v0
    /* F7E4 8000EBE4 A4B80000 */  sh         $t8, 0x0($a1)
    /* F7E8 8000EBE8 94D90000 */  lhu        $t9, 0x0($a2)
    /* F7EC 8000EBEC 24E70008 */  addiu      $a3, $a3, 0x8
    /* F7F0 8000EBF0 25290008 */  addiu      $t1, $t1, 0x8
    /* F7F4 8000EBF4 032D7021 */  addu       $t6, $t9, $t5
    /* F7F8 8000EBF8 A4CE0000 */  sh         $t6, 0x0($a2)
    /* F7FC 8000EBFC 94AF0000 */  lhu        $t7, 0x0($a1)
    /* F800 8000EC00 9522FFF8 */  lhu        $v0, -0x8($t1)
    /* F804 8000EC04 254A0008 */  addiu      $t2, $t2, 0x8
    /* F808 8000EC08 256B0008 */  addiu      $t3, $t3, 0x8
    /* F80C 8000EC0C 01E2C021 */  addu       $t8, $t7, $v0
    /* F810 8000EC10 A4B80000 */  sh         $t8, 0x0($a1)
    /* F814 8000EC14 94D90000 */  lhu        $t9, 0x0($a2)
    /* F818 8000EC18 00406827 */  not        $t5, $v0
    /* F81C 8000EC1C 032D7021 */  addu       $t6, $t9, $t5
    /* F820 8000EC20 A4CE0000 */  sh         $t6, 0x0($a2)
    /* F824 8000EC24 94AF0000 */  lhu        $t7, 0x0($a1)
    /* F828 8000EC28 9542FFF8 */  lhu        $v0, -0x8($t2)
    /* F82C 8000EC2C 01E2C021 */  addu       $t8, $t7, $v0
    /* F830 8000EC30 A4B80000 */  sh         $t8, 0x0($a1)
    /* F834 8000EC34 94D90000 */  lhu        $t9, 0x0($a2)
    /* F838 8000EC38 00406827 */  not        $t5, $v0
    /* F83C 8000EC3C 032D7021 */  addu       $t6, $t9, $t5
    /* F840 8000EC40 A4CE0000 */  sh         $t6, 0x0($a2)
    /* F844 8000EC44 94AF0000 */  lhu        $t7, 0x0($a1)
    /* F848 8000EC48 9562FFF8 */  lhu        $v0, -0x8($t3)
    /* F84C 8000EC4C 01E2C021 */  addu       $t8, $t7, $v0
    /* F850 8000EC50 A4B80000 */  sh         $t8, 0x0($a1)
    /* F854 8000EC54 94D90000 */  lhu        $t9, 0x0($a2)
    /* F858 8000EC58 00406827 */  not        $t5, $v0
    /* F85C 8000EC5C 032D7021 */  addu       $t6, $t9, $t5
    /* F860 8000EC60 1464FFDB */  bne        $v1, $a0, .L8000EBD0
    /* F864 8000EC64 A4CE0000 */   sh        $t6, 0x0($a2)
    /* F868 8000EC68 03E00008 */  jr         $ra
    /* F86C 8000EC6C 00001025 */   or        $v0, $zero, $zero
endlabel func_8000EB74

nonmatching func_8000EC70, 0x350

glabel func_8000EC70
    /* F870 8000EC70 27BDFF60 */  addiu      $sp, $sp, -0xA0
    /* F874 8000EC74 AFBF003C */  sw         $ra, 0x3C($sp)
    /* F878 8000EC78 AFB60038 */  sw         $s6, 0x38($sp)
    /* F87C 8000EC7C AFB50034 */  sw         $s5, 0x34($sp)
    /* F880 8000EC80 AFB40030 */  sw         $s4, 0x30($sp)
    /* F884 8000EC84 AFB3002C */  sw         $s3, 0x2C($sp)
    /* F888 8000EC88 AFB20028 */  sw         $s2, 0x28($sp)
    /* F88C 8000EC8C AFB10024 */  sw         $s1, 0x24($sp)
    /* F890 8000EC90 AFB00020 */  sw         $s0, 0x20($sp)
    /* F894 8000EC94 240EFFFF */  addiu      $t6, $zero, -0x1
    /* F898 8000EC98 00809025 */  or         $s2, $a0, $zero
    /* F89C 8000EC9C 00C0A025 */  or         $s4, $a2, $zero
    /* F8A0 8000ECA0 00A0B025 */  or         $s6, $a1, $zero
    /* F8A4 8000ECA4 00009825 */  or         $s3, $zero, $zero
    /* F8A8 8000ECA8 0C00325C */  jal        func_8000C970
    /* F8AC 8000ECAC ACCE0000 */   sw        $t6, 0x0($a2)
    /* F8B0 8000ECB0 AE820004 */  sw         $v0, 0x4($s4)
    /* F8B4 8000ECB4 8ED9000C */  lw         $t9, 0xC($s6)
    /* F8B8 8000ECB8 8ED80008 */  lw         $t8, 0x8($s6)
    /* F8BC 8000ECBC 02402025 */  or         $a0, $s2, $zero
    /* F8C0 8000ECC0 AE99000C */  sw         $t9, 0xC($s4)
    /* F8C4 8000ECC4 AE980008 */  sw         $t8, 0x8($s4)
    /* F8C8 8000ECC8 8EC90014 */  lw         $t1, 0x14($s6)
    /* F8CC 8000ECCC 8EC80010 */  lw         $t0, 0x10($s6)
    /* F8D0 8000ECD0 AE890014 */  sw         $t1, 0x14($s4)
    /* F8D4 8000ECD4 AE880010 */  sw         $t0, 0x10($s4)
    /* F8D8 8000ECD8 924F0065 */  lbu        $t7, 0x65($s2)
    /* F8DC 8000ECDC 51E00008 */  beql       $t7, $zero, .L8000ED00
    /* F8E0 8000ECE0 27B1007C */   addiu     $s1, $sp, 0x7C
    /* F8E4 8000ECE4 0C003A14 */  jal        func_8000E850
    /* F8E8 8000ECE8 00002825 */   or        $a1, $zero, $zero
    /* F8EC 8000ECEC 50400004 */  beql       $v0, $zero, .L8000ED00
    /* F8F0 8000ECF0 27B1007C */   addiu     $s1, $sp, 0x7C
    /* F8F4 8000ECF4 100000A9 */  b          .L8000EF9C
    /* F8F8 8000ECF8 8FBF003C */   lw        $ra, 0x3C($sp)
    /* F8FC 8000ECFC 27B1007C */  addiu      $s1, $sp, 0x7C
  .L8000ED00:
    /* F900 8000ED00 0220A825 */  or         $s5, $s1, $zero
    /* F904 8000ED04 27B0009C */  addiu      $s0, $sp, 0x9C
    /* F908 8000ED08 02402025 */  or         $a0, $s2, $zero
  .L8000ED0C:
    /* F90C 8000ED0C 0C003A14 */  jal        func_8000E850
    /* F910 8000ED10 326500FF */   andi      $a1, $s3, 0xFF
    /* F914 8000ED14 10400003 */  beqz       $v0, .L8000ED24
    /* F918 8000ED18 00003025 */   or        $a2, $zero, $zero
    /* F91C 8000ED1C 1000009F */  b          .L8000EF9C
    /* F920 8000ED20 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000ED24:
    /* F924 8000ED24 8E440004 */  lw         $a0, 0x4($s2)
    /* F928 8000ED28 8E450008 */  lw         $a1, 0x8($s2)
    /* F92C 8000ED2C 0C003A34 */  jal        func_8000E8D0
    /* F930 8000ED30 02A03825 */   or        $a3, $s5, $zero
    /* F934 8000ED34 10400003 */  beqz       $v0, .L8000ED44
    /* F938 8000ED38 366B0080 */   ori       $t3, $s3, 0x80
    /* F93C 8000ED3C 10000097 */  b          .L8000EF9C
    /* F940 8000ED40 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000ED44:
    /* F944 8000ED44 A3AB007C */  sb         $t3, 0x7C($sp)
    /* F948 8000ED48 27A2007D */  addiu      $v0, $sp, 0x7D
  .L8000ED4C:
    /* F94C 8000ED4C 904C0000 */  lbu        $t4, 0x0($v0)
    /* F950 8000ED50 24420001 */  addiu      $v0, $v0, 0x1
    /* F954 8000ED54 0050082B */  sltu       $at, $v0, $s0
    /* F958 8000ED58 01806827 */  not        $t5, $t4
    /* F95C 8000ED5C 1420FFFB */  bnez       $at, .L8000ED4C
    /* F960 8000ED60 A04DFFFF */   sb        $t5, -0x1($v0)
    /* F964 8000ED64 8E440004 */  lw         $a0, 0x4($s2)
    /* F968 8000ED68 8E450008 */  lw         $a1, 0x8($s2)
    /* F96C 8000ED6C AFA00010 */  sw         $zero, 0x10($sp)
    /* F970 8000ED70 00003025 */  or         $a2, $zero, $zero
    /* F974 8000ED74 0C003DA0 */  jal        func_8000F680
    /* F978 8000ED78 02A03825 */   or        $a3, $s5, $zero
    /* F97C 8000ED7C 10400003 */  beqz       $v0, .L8000ED8C
    /* F980 8000ED80 00003025 */   or        $a2, $zero, $zero
    /* F984 8000ED84 10000085 */  b          .L8000EF9C
    /* F988 8000ED88 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000ED8C:
    /* F98C 8000ED8C 8E440004 */  lw         $a0, 0x4($s2)
    /* F990 8000ED90 8E450008 */  lw         $a1, 0x8($s2)
    /* F994 8000ED94 0C003A34 */  jal        func_8000E8D0
    /* F998 8000ED98 27A7005C */   addiu     $a3, $sp, 0x5C
    /* F99C 8000ED9C 10400003 */  beqz       $v0, .L8000EDAC
    /* F9A0 8000EDA0 27A3005C */   addiu     $v1, $sp, 0x5C
    /* F9A4 8000EDA4 1000007D */  b          .L8000EF9C
    /* F9A8 8000EDA8 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EDAC:
    /* F9AC 8000EDAC 27A2007C */  addiu      $v0, $sp, 0x7C
  .L8000EDB0:
    /* F9B0 8000EDB0 906E0000 */  lbu        $t6, 0x0($v1)
    /* F9B4 8000EDB4 90580000 */  lbu        $t8, 0x0($v0)
    /* F9B8 8000EDB8 55D80006 */  bnel       $t6, $t8, .L8000EDD4
    /* F9BC 8000EDBC 27B9007C */   addiu     $t9, $sp, 0x7C
    /* F9C0 8000EDC0 24630001 */  addiu      $v1, $v1, 0x1
    /* F9C4 8000EDC4 0071082B */  sltu       $at, $v1, $s1
    /* F9C8 8000EDC8 1420FFF9 */  bnez       $at, .L8000EDB0
    /* F9CC 8000EDCC 24420001 */   addiu     $v0, $v0, 0x1
    /* F9D0 8000EDD0 27B9007C */  addiu      $t9, $sp, 0x7C
  .L8000EDD4:
    /* F9D4 8000EDD4 14790018 */  bne        $v1, $t9, .L8000EE38
    /* F9D8 8000EDD8 02402025 */   or        $a0, $s2, $zero
    /* F9DC 8000EDDC 5A600013 */  blezl      $s3, .L8000EE2C
    /* F9E0 8000EDE0 26730001 */   addiu     $s3, $s3, 0x1
    /* F9E4 8000EDE4 0C003A14 */  jal        func_8000E850
    /* F9E8 8000EDE8 00002825 */   or        $a1, $zero, $zero
    /* F9EC 8000EDEC 10400003 */  beqz       $v0, .L8000EDFC
    /* F9F0 8000EDF0 00003025 */   or        $a2, $zero, $zero
    /* F9F4 8000EDF4 10000069 */  b          .L8000EF9C
    /* F9F8 8000EDF8 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EDFC:
    /* F9FC 8000EDFC 8E440004 */  lw         $a0, 0x4($s2)
    /* FA00 8000EE00 8E450008 */  lw         $a1, 0x8($s2)
    /* FA04 8000EE04 0C003A34 */  jal        func_8000E8D0
    /* FA08 8000EE08 02A03825 */   or        $a3, $s5, $zero
    /* FA0C 8000EE0C 10400003 */  beqz       $v0, .L8000EE1C
    /* FA10 8000EE10 93A8007C */   lbu       $t0, 0x7C($sp)
    /* FA14 8000EE14 10000061 */  b          .L8000EF9C
    /* FA18 8000EE18 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EE1C:
    /* FA1C 8000EE1C 24010080 */  addiu      $at, $zero, 0x80
    /* FA20 8000EE20 55010006 */  bnel       $t0, $at, .L8000EE3C
    /* FA24 8000EE24 92490065 */   lbu       $t1, 0x65($s2)
    /* FA28 8000EE28 26730001 */  addiu      $s3, $s3, 0x1
  .L8000EE2C:
    /* FA2C 8000EE2C 2A61003E */  slti       $at, $s3, 0x3E
    /* FA30 8000EE30 5420FFB6 */  bnel       $at, $zero, .L8000ED0C
    /* FA34 8000EE34 02402025 */   or        $a0, $s2, $zero
  .L8000EE38:
    /* FA38 8000EE38 92490065 */  lbu        $t1, 0x65($s2)
  .L8000EE3C:
    /* FA3C 8000EE3C 02402025 */  or         $a0, $s2, $zero
    /* FA40 8000EE40 11200007 */  beqz       $t1, .L8000EE60
    /* FA44 8000EE44 00000000 */   nop
    /* FA48 8000EE48 0C003A14 */  jal        func_8000E850
    /* FA4C 8000EE4C 00002825 */   or        $a1, $zero, $zero
    /* FA50 8000EE50 10400003 */  beqz       $v0, .L8000EE60
    /* FA54 8000EE54 00000000 */   nop
    /* FA58 8000EE58 10000050 */  b          .L8000EF9C
    /* FA5C 8000EE5C 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EE60:
    /* FA60 8000EE60 1A600003 */  blez       $s3, .L8000EE70
    /* FA64 8000EE64 02802025 */   or        $a0, $s4, $zero
    /* FA68 8000EE68 10000002 */  b          .L8000EE74
    /* FA6C 8000EE6C 24020001 */   addiu     $v0, $zero, 0x1
  .L8000EE70:
    /* FA70 8000EE70 00001025 */  or         $v0, $zero, $zero
  .L8000EE74:
    /* FA74 8000EE74 96CF0018 */  lhu        $t7, 0x18($s6)
    /* FA78 8000EE78 A293001A */  sb         $s3, 0x1A($s4)
    /* FA7C 8000EE7C 2685001C */  addiu      $a1, $s4, 0x1C
    /* FA80 8000EE80 31EAFFFE */  andi       $t2, $t7, 0xFFFE
    /* FA84 8000EE84 01425825 */  or         $t3, $t2, $v0
    /* FA88 8000EE88 A68B0018 */  sh         $t3, 0x18($s4)
    /* FA8C 8000EE8C 92CC001B */  lbu        $t4, 0x1B($s6)
    /* FA90 8000EE90 2686001E */  addiu      $a2, $s4, 0x1E
    /* FA94 8000EE94 0C003ADD */  jal        func_8000EB74
    /* FA98 8000EE98 A28C001B */   sb        $t4, 0x1B($s4)
    /* FA9C 8000EE9C 240D0001 */  addiu      $t5, $zero, 0x1
    /* FAA0 8000EEA0 240E0003 */  addiu      $t6, $zero, 0x3
    /* FAA4 8000EEA4 24180004 */  addiu      $t8, $zero, 0x4
    /* FAA8 8000EEA8 24190006 */  addiu      $t9, $zero, 0x6
    /* FAAC 8000EEAC A7AD0048 */  sh         $t5, 0x48($sp)
    /* FAB0 8000EEB0 A7AE004A */  sh         $t6, 0x4A($sp)
    /* FAB4 8000EEB4 A7B8004C */  sh         $t8, 0x4C($sp)
    /* FAB8 8000EEB8 A7B9004E */  sh         $t9, 0x4E($sp)
    /* FABC 8000EEBC 27B00048 */  addiu      $s0, $sp, 0x48
    /* FAC0 8000EEC0 27B10050 */  addiu      $s1, $sp, 0x50
    /* FAC4 8000EEC4 8E440004 */  lw         $a0, 0x4($s2)
  .L8000EEC8:
    /* FAC8 8000EEC8 8E450008 */  lw         $a1, 0x8($s2)
    /* FACC 8000EECC 96060000 */  lhu        $a2, 0x0($s0)
    /* FAD0 8000EED0 24080001 */  addiu      $t0, $zero, 0x1
    /* FAD4 8000EED4 AFA80010 */  sw         $t0, 0x10($sp)
    /* FAD8 8000EED8 0C003DA0 */  jal        func_8000F680
    /* FADC 8000EEDC 02803825 */   or        $a3, $s4, $zero
    /* FAE0 8000EEE0 10400003 */  beqz       $v0, .L8000EEF0
    /* FAE4 8000EEE4 26100002 */   addiu     $s0, $s0, 0x2
    /* FAE8 8000EEE8 1000002C */  b          .L8000EF9C
    /* FAEC 8000EEEC 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EEF0:
    /* FAF0 8000EEF0 0211082B */  sltu       $at, $s0, $s1
    /* FAF4 8000EEF4 5420FFF4 */  bnel       $at, $zero, .L8000EEC8
    /* FAF8 8000EEF8 8E440004 */   lw        $a0, 0x4($s2)
    /* FAFC 8000EEFC 8E440004 */  lw         $a0, 0x4($s2)
    /* FB00 8000EF00 8E450008 */  lw         $a1, 0x8($s2)
    /* FB04 8000EF04 24060001 */  addiu      $a2, $zero, 0x1
    /* FB08 8000EF08 0C003A34 */  jal        func_8000E8D0
    /* FB0C 8000EF0C 02A03825 */   or        $a3, $s5, $zero
    /* FB10 8000EF10 10400003 */  beqz       $v0, .L8000EF20
    /* FB14 8000EF14 02801825 */   or        $v1, $s4, $zero
    /* FB18 8000EF18 10000020 */  b          .L8000EF9C
    /* FB1C 8000EF1C 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000EF20:
    /* FB20 8000EF20 27A2007C */  addiu      $v0, $sp, 0x7C
    /* FB24 8000EF24 27A4009C */  addiu      $a0, $sp, 0x9C
  .L8000EF28:
    /* FB28 8000EF28 90490000 */  lbu        $t1, 0x0($v0)
    /* FB2C 8000EF2C 906F0000 */  lbu        $t7, 0x0($v1)
    /* FB30 8000EF30 512F0004 */  beql       $t1, $t7, .L8000EF44
    /* FB34 8000EF34 904A0001 */   lbu       $t2, 0x1($v0)
    /* FB38 8000EF38 10000017 */  b          .L8000EF98
    /* FB3C 8000EF3C 2402000B */   addiu     $v0, $zero, 0xB
    /* FB40 8000EF40 904A0001 */  lbu        $t2, 0x1($v0)
  .L8000EF44:
    /* FB44 8000EF44 906B0001 */  lbu        $t3, 0x1($v1)
    /* FB48 8000EF48 514B0004 */  beql       $t2, $t3, .L8000EF5C
    /* FB4C 8000EF4C 904C0002 */   lbu       $t4, 0x2($v0)
    /* FB50 8000EF50 10000011 */  b          .L8000EF98
    /* FB54 8000EF54 2402000B */   addiu     $v0, $zero, 0xB
    /* FB58 8000EF58 904C0002 */  lbu        $t4, 0x2($v0)
  .L8000EF5C:
    /* FB5C 8000EF5C 906D0002 */  lbu        $t5, 0x2($v1)
    /* FB60 8000EF60 518D0004 */  beql       $t4, $t5, .L8000EF74
    /* FB64 8000EF64 904E0003 */   lbu       $t6, 0x3($v0)
    /* FB68 8000EF68 1000000B */  b          .L8000EF98
    /* FB6C 8000EF6C 2402000B */   addiu     $v0, $zero, 0xB
    /* FB70 8000EF70 904E0003 */  lbu        $t6, 0x3($v0)
  .L8000EF74:
    /* FB74 8000EF74 90780003 */  lbu        $t8, 0x3($v1)
    /* FB78 8000EF78 24420004 */  addiu      $v0, $v0, 0x4
    /* FB7C 8000EF7C 11D80003 */  beq        $t6, $t8, .L8000EF8C
    /* FB80 8000EF80 00000000 */   nop
    /* FB84 8000EF84 10000004 */  b          .L8000EF98
    /* FB88 8000EF88 2402000B */   addiu     $v0, $zero, 0xB
  .L8000EF8C:
    /* FB8C 8000EF8C 1444FFE6 */  bne        $v0, $a0, .L8000EF28
    /* FB90 8000EF90 24630004 */   addiu     $v1, $v1, 0x4
    /* FB94 8000EF94 00001025 */  or         $v0, $zero, $zero
  .L8000EF98:
    /* FB98 8000EF98 8FBF003C */  lw         $ra, 0x3C($sp)
  .L8000EF9C:
    /* FB9C 8000EF9C 8FB00020 */  lw         $s0, 0x20($sp)
    /* FBA0 8000EFA0 8FB10024 */  lw         $s1, 0x24($sp)
    /* FBA4 8000EFA4 8FB20028 */  lw         $s2, 0x28($sp)
    /* FBA8 8000EFA8 8FB3002C */  lw         $s3, 0x2C($sp)
    /* FBAC 8000EFAC 8FB40030 */  lw         $s4, 0x30($sp)
    /* FBB0 8000EFB0 8FB50034 */  lw         $s5, 0x34($sp)
    /* FBB4 8000EFB4 8FB60038 */  lw         $s6, 0x38($sp)
    /* FBB8 8000EFB8 03E00008 */  jr         $ra
    /* FBBC 8000EFBC 27BD00A0 */   addiu     $sp, $sp, 0xA0
endlabel func_8000EC70

nonmatching func_8000EFC0, 0x164

glabel func_8000EFC0
    /* FBC0 8000EFC0 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* FBC4 8000EFC4 AFBF003C */  sw         $ra, 0x3C($sp)
    /* FBC8 8000EFC8 AFB60038 */  sw         $s6, 0x38($sp)
    /* FBCC 8000EFCC AFB50034 */  sw         $s5, 0x34($sp)
    /* FBD0 8000EFD0 AFB40030 */  sw         $s4, 0x30($sp)
    /* FBD4 8000EFD4 AFB3002C */  sw         $s3, 0x2C($sp)
    /* FBD8 8000EFD8 AFB20028 */  sw         $s2, 0x28($sp)
    /* FBDC 8000EFDC AFB10024 */  sw         $s1, 0x24($sp)
    /* FBE0 8000EFE0 AFB00020 */  sw         $s0, 0x20($sp)
    /* FBE4 8000EFE4 908E0065 */  lbu        $t6, 0x65($a0)
    /* FBE8 8000EFE8 00A09025 */  or         $s2, $a1, $zero
    /* FBEC 8000EFEC 00809825 */  or         $s3, $a0, $zero
    /* FBF0 8000EFF0 51C00008 */  beql       $t6, $zero, .L8000F014
    /* FBF4 8000EFF4 240F0001 */   addiu     $t7, $zero, 0x1
    /* FBF8 8000EFF8 0C003A14 */  jal        func_8000E850
    /* FBFC 8000EFFC 00002825 */   or        $a1, $zero, $zero
    /* FC00 8000F000 50400004 */  beql       $v0, $zero, .L8000F014
    /* FC04 8000F004 240F0001 */   addiu     $t7, $zero, 0x1
    /* FC08 8000F008 1000003D */  b          .L8000F100
    /* FC0C 8000F00C 8FBF003C */   lw        $ra, 0x3C($sp)
    /* FC10 8000F010 240F0001 */  addiu      $t7, $zero, 0x1
  .L8000F014:
    /* FC14 8000F014 24180003 */  addiu      $t8, $zero, 0x3
    /* FC18 8000F018 24190004 */  addiu      $t9, $zero, 0x4
    /* FC1C 8000F01C 24080006 */  addiu      $t0, $zero, 0x6
    /* FC20 8000F020 A7AF0058 */  sh         $t7, 0x58($sp)
    /* FC24 8000F024 A7B8005A */  sh         $t8, 0x5A($sp)
    /* FC28 8000F028 A7B9005C */  sh         $t9, 0x5C($sp)
    /* FC2C 8000F02C A7A8005E */  sh         $t0, 0x5E($sp)
    /* FC30 8000F030 24110001 */  addiu      $s1, $zero, 0x1
    /* FC34 8000F034 27B0005A */  addiu      $s0, $sp, 0x5A
    /* FC38 8000F038 27B60050 */  addiu      $s6, $sp, 0x50
    /* FC3C 8000F03C 24150004 */  addiu      $s5, $zero, 0x4
    /* FC40 8000F040 27B40052 */  addiu      $s4, $sp, 0x52
  .L8000F044:
    /* FC44 8000F044 8E640004 */  lw         $a0, 0x4($s3)
    /* FC48 8000F048 8E650008 */  lw         $a1, 0x8($s3)
    /* FC4C 8000F04C 96060000 */  lhu        $a2, 0x0($s0)
    /* FC50 8000F050 0C003A34 */  jal        func_8000E8D0
    /* FC54 8000F054 02403825 */   or        $a3, $s2, $zero
    /* FC58 8000F058 10400003 */  beqz       $v0, .L8000F068
    /* FC5C 8000F05C 02402025 */   or        $a0, $s2, $zero
    /* FC60 8000F060 10000027 */  b          .L8000F100
    /* FC64 8000F064 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000F068:
    /* FC68 8000F068 02802825 */  or         $a1, $s4, $zero
    /* FC6C 8000F06C 0C003ADD */  jal        func_8000EB74
    /* FC70 8000F070 02C03025 */   or        $a2, $s6, $zero
    /* FC74 8000F074 97A90052 */  lhu        $t1, 0x52($sp)
    /* FC78 8000F078 964A001C */  lhu        $t2, 0x1C($s2)
    /* FC7C 8000F07C 97AB0050 */  lhu        $t3, 0x50($sp)
    /* FC80 8000F080 552A0005 */  bnel       $t1, $t2, .L8000F098
    /* FC84 8000F084 26310001 */   addiu     $s1, $s1, 0x1
    /* FC88 8000F088 964C001E */  lhu        $t4, 0x1E($s2)
    /* FC8C 8000F08C 116C0004 */  beq        $t3, $t4, .L8000F0A0
    /* FC90 8000F090 00000000 */   nop
    /* FC94 8000F094 26310001 */  addiu      $s1, $s1, 0x1
  .L8000F098:
    /* FC98 8000F098 1635FFEA */  bne        $s1, $s5, .L8000F044
    /* FC9C 8000F09C 26100002 */   addiu     $s0, $s0, 0x2
  .L8000F0A0:
    /* FCA0 8000F0A0 16350003 */  bne        $s1, $s5, .L8000F0B0
    /* FCA4 8000F0A4 00008025 */   or        $s0, $zero, $zero
    /* FCA8 8000F0A8 10000014 */  b          .L8000F0FC
    /* FCAC 8000F0AC 2402000A */   addiu     $v0, $zero, 0xA
  .L8000F0B0:
    /* FCB0 8000F0B0 27B40058 */  addiu      $s4, $sp, 0x58
  .L8000F0B4:
    /* FCB4 8000F0B4 1211000D */  beq        $s0, $s1, .L8000F0EC
    /* FCB8 8000F0B8 00106840 */   sll       $t5, $s0, 1
    /* FCBC 8000F0BC 028D7021 */  addu       $t6, $s4, $t5
    /* FCC0 8000F0C0 95C60000 */  lhu        $a2, 0x0($t6)
    /* FCC4 8000F0C4 8E640004 */  lw         $a0, 0x4($s3)
    /* FCC8 8000F0C8 8E650008 */  lw         $a1, 0x8($s3)
    /* FCCC 8000F0CC 240F0001 */  addiu      $t7, $zero, 0x1
    /* FCD0 8000F0D0 AFAF0010 */  sw         $t7, 0x10($sp)
    /* FCD4 8000F0D4 0C003DA0 */  jal        func_8000F680
    /* FCD8 8000F0D8 02403825 */   or        $a3, $s2, $zero
    /* FCDC 8000F0DC 50400004 */  beql       $v0, $zero, .L8000F0F0
    /* FCE0 8000F0E0 26100001 */   addiu     $s0, $s0, 0x1
    /* FCE4 8000F0E4 10000006 */  b          .L8000F100
    /* FCE8 8000F0E8 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8000F0EC:
    /* FCEC 8000F0EC 26100001 */  addiu      $s0, $s0, 0x1
  .L8000F0F0:
    /* FCF0 8000F0F0 1615FFF0 */  bne        $s0, $s5, .L8000F0B4
    /* FCF4 8000F0F4 00000000 */   nop
    /* FCF8 8000F0F8 00001025 */  or         $v0, $zero, $zero
  .L8000F0FC:
    /* FCFC 8000F0FC 8FBF003C */  lw         $ra, 0x3C($sp)
  .L8000F100:
    /* FD00 8000F100 8FB00020 */  lw         $s0, 0x20($sp)
    /* FD04 8000F104 8FB10024 */  lw         $s1, 0x24($sp)
    /* FD08 8000F108 8FB20028 */  lw         $s2, 0x28($sp)
    /* FD0C 8000F10C 8FB3002C */  lw         $s3, 0x2C($sp)
    /* FD10 8000F110 8FB40030 */  lw         $s4, 0x30($sp)
    /* FD14 8000F114 8FB50034 */  lw         $s5, 0x34($sp)
    /* FD18 8000F118 8FB60038 */  lw         $s6, 0x38($sp)
    /* FD1C 8000F11C 03E00008 */  jr         $ra
    /* FD20 8000F120 27BD0060 */   addiu     $sp, $sp, 0x60
endlabel func_8000EFC0

nonmatching func_8000F124, 0x1AC

glabel func_8000F124
    /* FD24 8000F124 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* FD28 8000F128 AFBF001C */  sw         $ra, 0x1C($sp)
    /* FD2C 8000F12C AFB10018 */  sw         $s1, 0x18($sp)
    /* FD30 8000F130 AFB00014 */  sw         $s0, 0x14($sp)
    /* FD34 8000F134 908E0065 */  lbu        $t6, 0x65($a0)
    /* FD38 8000F138 00808025 */  or         $s0, $a0, $zero
    /* FD3C 8000F13C 51C00008 */  beql       $t6, $zero, .L8000F160
    /* FD40 8000F140 8E040004 */   lw        $a0, 0x4($s0)
    /* FD44 8000F144 0C003A14 */  jal        func_8000E850
    /* FD48 8000F148 00002825 */   or        $a1, $zero, $zero
    /* FD4C 8000F14C 50400004 */  beql       $v0, $zero, .L8000F160
    /* FD50 8000F150 8E040004 */   lw        $a0, 0x4($s0)
    /* FD54 8000F154 1000005A */  b          .L8000F2C0
    /* FD58 8000F158 8FBF001C */   lw        $ra, 0x1C($sp)
    /* FD5C 8000F15C 8E040004 */  lw         $a0, 0x4($s0)
  .L8000F160:
    /* FD60 8000F160 8E050008 */  lw         $a1, 0x8($s0)
    /* FD64 8000F164 24060001 */  addiu      $a2, $zero, 0x1
    /* FD68 8000F168 0C003A34 */  jal        func_8000E8D0
    /* FD6C 8000F16C 27A7004C */   addiu     $a3, $sp, 0x4C
    /* FD70 8000F170 10400003 */  beqz       $v0, .L8000F180
    /* FD74 8000F174 27A4004C */   addiu     $a0, $sp, 0x4C
    /* FD78 8000F178 10000051 */  b          .L8000F2C0
    /* FD7C 8000F17C 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8000F180:
    /* FD80 8000F180 27A5006E */  addiu      $a1, $sp, 0x6E
    /* FD84 8000F184 0C003ADD */  jal        func_8000EB74
    /* FD88 8000F188 27A6006C */   addiu     $a2, $sp, 0x6C
    /* FD8C 8000F18C 97AF006E */  lhu        $t7, 0x6E($sp)
    /* FD90 8000F190 97B80068 */  lhu        $t8, 0x68($sp)
    /* FD94 8000F194 27A5004C */  addiu      $a1, $sp, 0x4C
    /* FD98 8000F198 00A08825 */  or         $s1, $a1, $zero
    /* FD9C 8000F19C 15F80004 */  bne        $t7, $t8, .L8000F1B0
    /* FDA0 8000F1A0 97B9006C */   lhu       $t9, 0x6C($sp)
    /* FDA4 8000F1A4 97A9006A */  lhu        $t1, 0x6A($sp)
    /* FDA8 8000F1A8 53290015 */  beql       $t9, $t1, .L8000F200
    /* FDAC 8000F1AC 962A0018 */   lhu       $t2, 0x18($s1)
  .L8000F1B0:
    /* FDB0 8000F1B0 0C003BF0 */  jal        func_8000EFC0
    /* FDB4 8000F1B4 02002025 */   or        $a0, $s0, $zero
    /* FDB8 8000F1B8 2401000A */  addiu      $at, $zero, 0xA
    /* FDBC 8000F1BC 1441000B */  bne        $v0, $at, .L8000F1EC
    /* FDC0 8000F1C0 00401825 */   or        $v1, $v0, $zero
    /* FDC4 8000F1C4 02002025 */  or         $a0, $s0, $zero
    /* FDC8 8000F1C8 27A5004C */  addiu      $a1, $sp, 0x4C
    /* FDCC 8000F1CC 0C003B1C */  jal        func_8000EC70
    /* FDD0 8000F1D0 27A60028 */   addiu     $a2, $sp, 0x28
    /* FDD4 8000F1D4 10400003 */  beqz       $v0, .L8000F1E4
    /* FDD8 8000F1D8 00000000 */   nop
    /* FDDC 8000F1DC 10000038 */  b          .L8000F2C0
    /* FDE0 8000F1E0 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8000F1E4:
    /* FDE4 8000F1E4 10000005 */  b          .L8000F1FC
    /* FDE8 8000F1E8 27B10028 */   addiu     $s1, $sp, 0x28
  .L8000F1EC:
    /* FDEC 8000F1EC 50400004 */  beql       $v0, $zero, .L8000F200
    /* FDF0 8000F1F0 962A0018 */   lhu       $t2, 0x18($s1)
    /* FDF4 8000F1F4 10000031 */  b          .L8000F2BC
    /* FDF8 8000F1F8 00601025 */   or        $v0, $v1, $zero
  .L8000F1FC:
    /* FDFC 8000F1FC 962A0018 */  lhu        $t2, 0x18($s1)
  .L8000F200:
    /* FE00 8000F200 02002025 */  or         $a0, $s0, $zero
    /* FE04 8000F204 02202825 */  or         $a1, $s1, $zero
    /* FE08 8000F208 314B0001 */  andi       $t3, $t2, 0x1
    /* FE0C 8000F20C 5560000D */  bnel       $t3, $zero, .L8000F244
    /* FE10 8000F210 02202025 */   or        $a0, $s1, $zero
    /* FE14 8000F214 0C003B1C */  jal        func_8000EC70
    /* FE18 8000F218 27A60028 */   addiu     $a2, $sp, 0x28
    /* FE1C 8000F21C 10400003 */  beqz       $v0, .L8000F22C
    /* FE20 8000F220 97AC0040 */   lhu       $t4, 0x40($sp)
    /* FE24 8000F224 10000026 */  b          .L8000F2C0
    /* FE28 8000F228 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8000F22C:
    /* FE2C 8000F22C 318D0001 */  andi       $t5, $t4, 0x1
    /* FE30 8000F230 15A00003 */  bnez       $t5, .L8000F240
    /* FE34 8000F234 27B10028 */   addiu     $s1, $sp, 0x28
    /* FE38 8000F238 10000020 */  b          .L8000F2BC
    /* FE3C 8000F23C 2402000B */   addiu     $v0, $zero, 0xB
  .L8000F240:
    /* FE40 8000F240 02202025 */  or         $a0, $s1, $zero
  .L8000F244:
    /* FE44 8000F244 2605000C */  addiu      $a1, $s0, 0xC
    /* FE48 8000F248 0C0034AC */  jal        func_8000D2B0
    /* FE4C 8000F24C 24060020 */   addiu     $a2, $zero, 0x20
    /* FE50 8000F250 922E001B */  lbu        $t6, 0x1B($s1)
    /* FE54 8000F254 24090010 */  addiu      $t1, $zero, 0x10
    /* FE58 8000F258 240A0008 */  addiu      $t2, $zero, 0x8
    /* FE5C 8000F25C AE0E004C */  sw         $t6, 0x4C($s0)
    /* FE60 8000F260 922F001A */  lbu        $t7, 0x1A($s1)
    /* FE64 8000F264 AE090050 */  sw         $t1, 0x50($s0)
    /* FE68 8000F268 AE0A0054 */  sw         $t2, 0x54($s0)
    /* FE6C 8000F26C 31E200FF */  andi       $v0, $t7, 0xFF
    /* FE70 8000F270 000218C0 */  sll        $v1, $v0, 3
    /* FE74 8000F274 0002C040 */  sll        $t8, $v0, 1
    /* FE78 8000F278 24680008 */  addiu      $t0, $v1, 0x8
    /* FE7C 8000F27C 27190003 */  addiu      $t9, $t8, 0x3
    /* FE80 8000F280 01035821 */  addu       $t3, $t0, $v1
    /* FE84 8000F284 AE190060 */  sw         $t9, 0x60($s0)
    /* FE88 8000F288 AE080058 */  sw         $t0, 0x58($s0)
    /* FE8C 8000F28C AE0B005C */  sw         $t3, 0x5C($s0)
    /* FE90 8000F290 8E040004 */  lw         $a0, 0x4($s0)
    /* FE94 8000F294 8E050008 */  lw         $a1, 0x8($s0)
    /* FE98 8000F298 24060007 */  addiu      $a2, $zero, 0x7
    /* FE9C 8000F29C 2607002C */  addiu      $a3, $s0, 0x2C
    /* FEA0 8000F2A0 0C003A34 */  jal        func_8000E8D0
    /* FEA4 8000F2A4 A20F0064 */   sb        $t7, 0x64($s0)
    /* FEA8 8000F2A8 50400004 */  beql       $v0, $zero, .L8000F2BC
    /* FEAC 8000F2AC 00001025 */   or        $v0, $zero, $zero
    /* FEB0 8000F2B0 10000003 */  b          .L8000F2C0
    /* FEB4 8000F2B4 8FBF001C */   lw        $ra, 0x1C($sp)
    /* FEB8 8000F2B8 00001025 */  or         $v0, $zero, $zero
  .L8000F2BC:
    /* FEBC 8000F2BC 8FBF001C */  lw         $ra, 0x1C($sp)
  .L8000F2C0:
    /* FEC0 8000F2C0 8FB00014 */  lw         $s0, 0x14($sp)
    /* FEC4 8000F2C4 8FB10018 */  lw         $s1, 0x18($sp)
    /* FEC8 8000F2C8 03E00008 */  jr         $ra
    /* FECC 8000F2CC 27BD0070 */   addiu     $sp, $sp, 0x70
endlabel func_8000F124

nonmatching func_8000F2D0, 0xD4

glabel func_8000F2D0
    /* FED0 8000F2D0 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* FED4 8000F2D4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* FED8 8000F2D8 AFB00018 */  sw         $s0, 0x18($sp)
    /* FEDC 8000F2DC 908E0065 */  lbu        $t6, 0x65($a0)
    /* FEE0 8000F2E0 00808025 */  or         $s0, $a0, $zero
    /* FEE4 8000F2E4 51C0000F */  beql       $t6, $zero, .L8000F324
    /* FEE8 8000F2E8 8E040004 */   lw        $a0, 0x4($s0)
    /* FEEC 8000F2EC 0C003A14 */  jal        func_8000E850
    /* FEF0 8000F2F0 00002825 */   or        $a1, $zero, $zero
    /* FEF4 8000F2F4 24010002 */  addiu      $at, $zero, 0x2
    /* FEF8 8000F2F8 14410005 */  bne        $v0, $at, .L8000F310
    /* FEFC 8000F2FC 00401825 */   or        $v1, $v0, $zero
    /* FF00 8000F300 02002025 */  or         $a0, $s0, $zero
    /* FF04 8000F304 0C003A14 */  jal        func_8000E850
    /* FF08 8000F308 00002825 */   or        $a1, $zero, $zero
    /* FF0C 8000F30C 00401825 */  or         $v1, $v0, $zero
  .L8000F310:
    /* FF10 8000F310 50400004 */  beql       $v0, $zero, .L8000F324
    /* FF14 8000F314 8E040004 */   lw        $a0, 0x4($s0)
    /* FF18 8000F318 1000001D */  b          .L8000F390
    /* FF1C 8000F31C 00601025 */   or        $v0, $v1, $zero
    /* FF20 8000F320 8E040004 */  lw         $a0, 0x4($s0)
  .L8000F324:
    /* FF24 8000F324 8E050008 */  lw         $a1, 0x8($s0)
    /* FF28 8000F328 24060001 */  addiu      $a2, $zero, 0x1
    /* FF2C 8000F32C 0C003A34 */  jal        func_8000E8D0
    /* FF30 8000F330 27A70028 */   addiu     $a3, $sp, 0x28
    /* FF34 8000F334 1040000D */  beqz       $v0, .L8000F36C
    /* FF38 8000F338 24010002 */   addiu     $at, $zero, 0x2
    /* FF3C 8000F33C 10410003 */  beq        $v0, $at, .L8000F34C
    /* FF40 8000F340 24060001 */   addiu     $a2, $zero, 0x1
    /* FF44 8000F344 10000013 */  b          .L8000F394
    /* FF48 8000F348 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8000F34C:
    /* FF4C 8000F34C 8E040004 */  lw         $a0, 0x4($s0)
    /* FF50 8000F350 8E050008 */  lw         $a1, 0x8($s0)
    /* FF54 8000F354 0C003A34 */  jal        func_8000E8D0
    /* FF58 8000F358 27A70028 */   addiu     $a3, $sp, 0x28
    /* FF5C 8000F35C 50400004 */  beql       $v0, $zero, .L8000F370
    /* FF60 8000F360 2604000C */   addiu     $a0, $s0, 0xC
    /* FF64 8000F364 1000000B */  b          .L8000F394
    /* FF68 8000F368 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8000F36C:
    /* FF6C 8000F36C 2604000C */  addiu      $a0, $s0, 0xC
  .L8000F370:
    /* FF70 8000F370 27A50028 */  addiu      $a1, $sp, 0x28
    /* FF74 8000F374 0C003E34 */  jal        func_8000F8D0
    /* FF78 8000F378 24060020 */   addiu     $a2, $zero, 0x20
    /* FF7C 8000F37C 50400004 */  beql       $v0, $zero, .L8000F390
    /* FF80 8000F380 00001025 */   or        $v0, $zero, $zero
    /* FF84 8000F384 10000002 */  b          .L8000F390
    /* FF88 8000F388 24020002 */   addiu     $v0, $zero, 0x2
    /* FF8C 8000F38C 00001025 */  or         $v0, $zero, $zero
  .L8000F390:
    /* FF90 8000F390 8FBF001C */  lw         $ra, 0x1C($sp)
  .L8000F394:
    /* FF94 8000F394 8FB00018 */  lw         $s0, 0x18($sp)
    /* FF98 8000F398 27BD0048 */  addiu      $sp, $sp, 0x48
    /* FF9C 8000F39C 03E00008 */  jr         $ra
    /* FFA0 8000F3A0 00000000 */   nop
endlabel func_8000F2D0

nonmatching func_8000F3A4, 0x5C

glabel func_8000F3A4
    /* FFA4 8000F3A4 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* FFA8 8000F3A8 AFB40030 */  sw         $s4, 0x30($sp)
    /* FFAC 8000F3AC 30D400FF */  andi       $s4, $a2, 0xFF
    /* FFB0 8000F3B0 AFB20028 */  sw         $s2, 0x28($sp)
    /* FFB4 8000F3B4 00809025 */  or         $s2, $a0, $zero
    /* FFB8 8000F3B8 AFBF0034 */  sw         $ra, 0x34($sp)
    /* FFBC 8000F3BC AFB3002C */  sw         $s3, 0x2C($sp)
    /* FFC0 8000F3C0 AFB10024 */  sw         $s1, 0x24($sp)
    /* FFC4 8000F3C4 AFB00020 */  sw         $s0, 0x20($sp)
    /* FFC8 8000F3C8 AFA5005C */  sw         $a1, 0x5C($sp)
    /* FFCC 8000F3CC AFA60060 */  sw         $a2, 0x60($sp)
    /* FFD0 8000F3D0 16800011 */  bnez       $s4, . + 4 + (0x11 << 2)
    /* FFD4 8000F3D4 AFA70064 */   sw        $a3, 0x64($sp)
    /* FFD8 8000F3D8 3C0F8003 */  lui        $t7, %hi(__osSiChannelMask)
    /* FFDC 8000F3DC 91EFC4D4 */  lbu        $t7, %lo(__osSiChannelMask)($t7)
    /* FFE0 8000F3E0 93B80067 */  lbu        $t8, 0x67($sp)
    /* FFE4 8000F3E4 3C198003 */  lui        $t9, %hi(__osSiLastChannel)
    /* FFE8 8000F3E8 55F8000C */  bnel       $t7, $t8, . + 4 + (0xC << 2)
    /* FFEC 8000F3EC 92490065 */   lbu       $t1, 0x65($s2)
    /* FFF0 8000F3F0 8F39C4D0 */  lw         $t9, %lo(__osSiLastChannel)($t9)
    /* FFF4 8000F3F4 8C880008 */  lw         $t0, 0x8($a0)
    /* FFF8 8000F3F8 3C048003 */  lui        $a0, %hi(__osContPifInode)
    /* FFFC 8000F3FC 24847CB0 */  addiu      $a0, $a0, %lo(__osContPifInode)
endlabel func_8000F3A4
